<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5a2m5qCh5Yqo5oCB');
$cfg_Cs[2]=array(0,1,1,'5YWz5LqO576k5Li9');
$cfg_Cs[3]=array(0,17,1,'5LiT5Lia6K++56iL');
$cfg_Cs[4]=array(0,1,1,'5biI6LWE5Zui6Zif');
$cfg_Cs[14]=array(0,1,1,'5a2m5ZGY5Yqo5oCB');
$cfg_Cs[6]=array(0,1,1,'5byA54+t5L+h5oGv');
$cfg_Cs[7]=array(0,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[8]=array(3,17,1,'5b2p5aaG6K++56iL');
$cfg_Cs[9]=array(3,17,1,'576O55Sy6K++56iL');
$cfg_Cs[10]=array(3,17,1,'5pGE5b2x6K++56iL');
$cfg_Cs[11]=array(3,17,1,'57q557uj6K++56iL');
$cfg_Cs[12]=array(3,17,1,'57u85ZCI6K++56iL');
$cfg_Cs[13]=array(3,17,1,'576O5a656K++56iL');
?>