<div class="list_zykcsz">
            <div class="list_zykcl">
                <a href="[field:arcurl/]">
                    <img src="[field:picname/]" alt="">
                    <p>[field:title/]</p>
                </a>
            </div>
            <div class="list_zykcr">
                <h2>[field:title/]</h2>
                <!-- <p><b>[field:description function='cn_substr(@me,120)'/]</b></p> -->
                <p class="xue"><b>学期：</b>[field:xuexi/]</p>
                <p class="xue"><b>学费：</b><span>[field:yxuefei/]RMB</span>（优惠价[field:youhui/]RMB）</p>
                <p class="xue"><b>班级人数：</b>[field:renshu/]</p>
                <p class="xue"><b>上课时间：</b>[field:sksj/]</p>
                <p class="xue"><b>上午上课时间：</b>[field:am/]</p>
                <p class="xue"><b>下午上课时间：</b>[field:pm/]</p>
            </div>
        </div>