<?php
$z[0]=Array("arcurl","",88,103);
$z[1]=Array("picname","",136,152);
$z[2]=Array("title","",185,199);
$z[3]=Array("title","",301,315);
$z[4]=Array("description","",348,398);
$z[4][4]['function']="cn_substr(@me,120)";
$z[5]=Array("xuexi","",458,472);
$z[6]=Array("yxuefei","",530,546);
$z[7]=Array("youhui","",568,583);
$z[8]=Array("renshu","",647,662);
$z[9]=Array("sksj","",720,733);
$z[10]=Array("am","",797,808);
$z[11]=Array("pm","",872,883);

?>