<div class="list_zykcsz">
            <div class="list_zykcl">
                <a href="[field:arcurl/]"><img src="[field:picname/]" alt=""></a>
                <a href="[field:arcurl/]" class="listtitle">[field:title/]</a>
            </div>
            <div class="list_zykcr">
                <h2>高级韩式半永久化妆师专业</h2>
                <p><b>课程介绍：</b>掌握半永久化妆技能，高级眉眼唇的艺术是基本的要求，同时培养具有专业知识全面以及</p>
                <p>学期：35-45天</p>
                <p>学费：8980RMB（优惠价5980RMB）</p>
            </div>
        </div>