<div class="list_zykcsz">
            <div class="list_zykcl">
                <a href="[field:arcurl/]"><img src="[field:picname/]" alt=""></a>
                <a href="[field:arcurl/]" class="listtitle">[field:title/]</a>
            </div>
            <div class="list_zykcr">
                <h2>[field:zylx/]</h2>
                <p><b>课程介绍：[field:body function='cn_substr(@me,70)'/]</b></p>
                <p class="xue"><b>学期：</b>[field:xuexi/]</p>
                <p class="xue"><b>学费：</b><span>[field:zylx/]RMB</span>（优惠价[field:zylx/]RMB）</p>
            </div>
        </div>