<field:kcbjt itemname="课程背景图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:kcbjt>
<field:xuexi itemname="学期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xuexi>
<field:renshu itemname="班级人数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:renshu>
<field:zylx itemname="专业类型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zylx>
<field:yxuefei itemname="学费(原价)" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:yxuefei>
<field:youhui itemname="优惠价" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:youhui>
<field:sksj itemname="上课时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sksj>
<field:am itemname="上午上课时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:am>
<field:pm itemname="下午上课时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pm>
<field:body itemname="课程介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:body>
<field:dyktp itemname="第一课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dyktp>
<field:dyknr itemname="第一课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dyknr>
<field:dektp itemname="第二课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dektp>
<field:deknr itemname="第二课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:deknr>
<field:dsktp itemname="第三课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsktp>
<field:dsknr itemname="第三课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsknr>
<field:dsiktp itemname="第四课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsiktp>
<field:dsiknr itemname="第四课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsiknr>
<field:dwuktp itemname="第五课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dwuktp>
<field:dwuknr itemname="第五课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dwuknr>
<field:dliuktp itemname="第六课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dliuktp>
<field:dliuknr itemname="第六课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dliuknr>
<field:dqiktp itemname="第七课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dqiktp>
<field:dqiknr itemname="第七课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dqiknr>
<field:dbaktp itemname="第八课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dbaktp>
<field:dbaknr itemname="第八课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dbaknr>
<field:djiuktp itemname="第九课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:djiuktp>
<field:djiuknr itemname="第九课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:djiuknr>
<field:dshiktp itemname="第十课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dshiktp>

<field:dshiknr itemname="第十课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dshiknr>

<field:dshiyiktp itemname="第十一课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dshiyiktp>

<field:dshiyiknr itemname="第十一课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dshiyiknr>

<field:dshierktp itemname="第十二课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dshierktp>

<field:dshierknr itemname="第十二课内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dshierknr>

<field:dshisanktp itemname="第十三课图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dshisanktp>
