<?php
$z[0]=Array("field","",209,228);
$z[0][4]['name']="title";
$z[1]=Array("global","",229,255);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",283,312);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",350,409);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",557,595);
$z[4][4]['filename']="header.htm";
$z[5]=Array("include","",596,634);
$z[5][4]['filename']="banner.htm";
$z[6]=Array("field","",656,685);
$z[6][4]['name']="position";
$z[7]=Array("channelartlist","\n        <div class=\"list_zykc\">\n            <a href=\"{dede:field name='typeurl'/}\"><img src=\"{dede:field name='typeimg'/}\" alt=\"\"></a>\n            <a href=\"{dede:field name='typeurl'/}\" class=\"listtitle\">{dede:field name='typename'/}{dede:field name='seotitle'/}</a>\n        </div>\n        ",729,1063);
$z[8]=Array("include","",1079,1117);
$z[8][4]['filename']="footer.htm";

?>