{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}怎样做DIY美甲？成都美甲学校{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352962622P-29A2.jpg" style="width: 521px; height: 128px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　<a href="http://www.ql-school.com">成都美甲学校</a>给大家整理了几款简单的，不用去美甲室，可以自己在家做的美甲</p>
<p>
	　　第一种</p>
<p>
	　　step1</p>
<p>
	　　准备一瓶红色指甲油和几根牙签，还需要在涂指甲油前涂一层护甲油然后用牙签蘸取适量的指甲油。</p>
<p>
	　　step2</p>
<p>
	　　随意的像流水状的涂在指甲前端</p>
<p>
	　　step3</p>
<p>
	　　然后就可以出来流水状的美甲造型，非常简单也会很显白的美甲</p>
<p>
	　　第二种</p>
<p>
	　　step1</p>
<p>
	　　先在每个手指上涂抹白色的甲油，做底部美甲</p>
<p>
	　　step2</p>
<p>
	　　先涂上护甲油，趁护甲油没干前，快速的涂蓝色的甲油，用干净的刷子轻轻把甲油晕开</p>
<p>
	　　step3</p>
<p>
	　　用同样的方法，再快速涂粉色的甲油</p>
<p>
	　　step4</p>
<p>
	　　然后每个手指都做出晕染的效果</p>
<p>
	　　step5</p>
<p>
	　　在指甲油都干了后，再次涂抹护甲水就完成了</p>
<p>
	　　第三种</p>
<p>
	　　step1</p>
<p>
	　　先用白色的甲油做手指打底</p>
<p>
	　　step2</p>
<p>
	　　用银色的甲油在二拇指和小拇指半圆状的涂在指甲前半段</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352962S0Z-34352.jpg" style="width: 604px; height: 369px;" /></p>
<p>
	　　step3</p>
<p>
	　　用粉色，绿色，褐色和洗的美甲刷，在中指和四拇指，勾勒出苹果状的造型</p>
<p>
	　　step4</p>
<p>
	　　最后等甲油都干了后，涂上一层护甲油</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352963034Z-454U.jpg" style="width: 532px; height: 302px;" /></p>
<p>
	&nbsp;</p>
<p>
	　　step5</p>
<p>
	　　就出来了适合夏天的嫩嫩的水果美甲</p>
<p>
	　　今天他尚先生给大家带来了超全的美甲篇，</p>
<p>
	　　希望可以帮到你们</p>
<p>
	　　选择一款美美的美甲!</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352962622P-29A2_lit.jpg{/dede:field}
