<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","精心挑选的美甲款式 打造你的漂亮指尖",368,458);
$z[2][4]['name']="title";
$z[3]=Array("field","",460,499);
$z[3][4]['name']="writer";
$z[4]=Array("field","",501,540);
$z[4][4]['name']="source";
$z[5]=Array("field","",542,582);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　欣赏<a href=\"http://www.ql-school.com\">成都美甲学校</a>精心选择的美甲样式，感受瞬间很多啦!</p>\r\n<p>\r\n	　　粉色是公主的颜色，没有女性能反抗的颜色，更是抓获男神心扉的法宝。淡淡的粉色与冬季是绝配，香甜心爱，让冬季不再单调。果冻色的淡粉更是受万千女性的追捧，心爱漂亮，一见难忘。<br />\r\n	<img alt=\"成都美甲学校培训作品\" src=\"/uploads/allimg/c180619/1529352cD9110-106401.jpg\" style=\"width: 600px; height: 600px;\" /><br />\r\n	　　黑白<br />\r\n	&nbsp; &nbsp; &nbsp; &nbsp; 永久的是非经典，尽显时髦!<br />\r\n	<img alt=\"成都美甲学校培训作品\" src=\"/uploads/allimg/c180619/1529352cH2920-11Z23.jpg\" style=\"width: 600px; height: 600px;\" /></p>\r\n<p>\r\n	　　蓝色、绿色</p>\r\n<p>\r\n	　　显手白?你能够试试高雅的薄荷绿或许蓝色系~<br />\r\n	<img alt=\"成都美甲学校培训作品\" src=\"/uploads/allimg/c180619/1529352cK55P-121X9.jpg\" style=\"width: 600px; height: 450px;\" /></p>\r\n<p>\r\n	　　红色</p>\r\n<p>\r\n	　　红色是中国人新年与新年的主色调，当然也要引荐了，花式美甲、酒赤色或许单单的大赤色都美极了!<br />\r\n	<img alt=\"成都美甲学校培训作品\" src=\"/uploads/allimg/c180619/1529352cN5260-132V1.jpg\" style=\"width: 600px; height: 577px;\" /><br />\r\n	&nbsp;</p>\r\n</p>",584,2002);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/1529352cD9110-106401_lit.jpg",2004,2095);
$z[7][4]['name']="litpic";

?>