{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}穿凉鞋涂什么色的指甲油？看完你就懂了{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　夏天穿凉鞋露脚趾的同时也要考虑着给脚趾甲涂上指甲油了!可是到底涂什么颜色的指甲油才配上美美哒凉鞋才最好看呢?</p>
<p>
	　　大家也都知道，有这么一个词&mdash;&mdash;&ldquo;色彩搭配&rdquo;。色儿搭配对了，才能凸显出气质来。可是道理都懂问题是&hellip;&hellip;不懂色彩!不会搭啊!</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352bR4120-64X9.jpg" style="width: 618px; height: 450px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　没关系，<a href="http://www.ql-school.com">成都美甲学校</a>小编接下来就仔细讲一讲选指甲油的门道!</p>
<p>
	　　经典白灰黑</p>
<p>
	　　白色凉鞋很百搭，不论是暖色系亦或是冷色系的指甲油，搭配在一起都还不错，只要别涂抹白色的指甲油就可以了。</p>
<p>
	　　黑色和红色的指甲油组合是最经典的，脚上也不例外。看看黑色配黑色，恐怖的无法想象啊!</p>
<p>
	　　黄色系</p>
<p>
	　　嫩黄色的鞋子搭配粉红色的指甲油，会穿出少女感、萝莉范;搭配绿色或者蓝色的指甲油能够起到显白的效果，但是同样的，别搭配同色系的指甲油哈。黄色凉鞋的禁忌是和大红色的搭配，显得特艳俗!墨绿色才是其最好的选择。</p>
<p>
	　　如暖阳的橘红色配宝蓝色的指甲油是最好的，如果是黑色的指甲油就很糟糕了</p>
<p>
	　　红色系</p>
<p>
	　　枚红色凉鞋的搭配要注意的是不要用反差太大的甲油颜色，否则很突兀，红色凉鞋切不可搭配红色甲油，不然最风尘气的那个人就是你~</p>
<p>
	　　冷色系</p>
<p>
	　　颜色鲜艳的绿色不可配对比最强的红色!原来绿色这样鲜艳的颜色要和同色系才显得好看，如果配紫色会显脚黑呢!</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352bR4120-64X9_lit.jpg{/dede:field}
