<field:btime itemname="活动价格" autofield="1" notsend="0" type="datetime" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:btime>

<field:cnt itemname="开班人数" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cnt>
<field:syrs itemname="剩余名额" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:syrs>
<field:price itemname="费用" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:price>
<field:pic2 itemname="缩略图2（鼠标悬浮时）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic2>
<field:xx itemname="详细" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xx>
