<li><a href="[field:arcurl/]" title="[field:title/]">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]</a></li>
                <div>
                    <h3 class="hot"><span>开班最新动态</span></h3>
                    <p>
                        文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代
                        文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代
                        文案暂代文案暂代文案暂代文案暂代文案暂代文案暂代
                    </p>
                </div>
                <div style="padding-left:40px;width: 430px">
                    <h3><span>专业课程详询热线</span></h3>
                    <p>
                        <span  style="color:#e74159">028-86661825</span>
                        <span  style="color:#e74159">028-86661640</span>
                    </p>
                </div>