{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}群丽学校，又有一批毕业学员成功就业了!{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　群丽学校，又有一批毕业学员成功就业了!兼职的兼职;就业的就业，开店的开店</p>
<p>
	　　相信只要有了过硬技术，不再是：&ldquo;你来找工作!而是工作来找你!&rdquo;在我们没有背景，没有颜值;没有很高的学历&hellip;&hellip;想要有一个好的人生，除了靠别人(别人是靠不住的)更多的还是要自己独立，选一个真心做教育的学校才能教会你好的技能!你才能拥有好的人生!所以同学们在择校时一定要考虑清楚，因为&ldquo;选择比努力更重要&rdquo;!成都群丽化妆美甲培训学校，<a href="http://www.ql-school.com">成都美甲学校</a>！</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529291A60-1cW.jpg" style="width: 426px; height: 574px;" /><br />
	<img alt="成都群丽美甲学校" src="/uploads/allimg/c180619/1529352929515Z-2T47.jpg" style="width: 425px; height: 652px;" /><br />
	<img alt="群丽美甲学校" src="/uploads/allimg/c180619/152935292b3T0-35A4.jpg" style="width: 725px; height: 592px;" /><br />
	<img alt="群丽美甲学校" src="/uploads/allimg/c180619/152935293014O0-45Y9.jpg" style="width: 799px; height: 569px;" /><br />
	<img alt="成都群丽美甲学校" src="/uploads/allimg/c180619/152935293044U0-5S94.jpg" style="width: 746px; height: 422px;" /><br />
	<img alt="成都群丽美甲学校" src="/uploads/allimg/c180619/1529352930Q0Z-633Z.jpg" style="width: 684px; height: 572px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935293111220-N923.jpg" style="width: 725px; height: 532px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352931391Z-R624.jpg" style="width: 407px; height: 603px;" /></p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/15293529291A60-1cW_lit.jpg{/dede:field}
