<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","纯色极简风美甲，让气质更出众！",368,451);
$z[2][4]['name']="title";
$z[3]=Array("field","",453,492);
$z[3][4]['name']="writer";
$z[4]=Array("field","",494,533);
$z[4][4]['name']="source";
$z[5]=Array("field","",535,575);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p style=\"text-align: center;\">\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/15293525H3V50-632F.jpg\" style=\"width: 646px; height: 326px;\" /></p>\r\n<p>\r\n	　　纯色系美甲，一直是简约有范的代名词。乍一看，它似乎没什么特别的，但上手的效果却十分出色。</p>\r\n<p>\r\n	　　做多了繁杂的款式，不如试试下面这些耐看的纯色系美甲，偶尔换换口味，说不定会遇到更多惊喜喔~</p>\r\n<p style=\"text-align: center;\">\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/15293525HK330-J635.jpg\" style=\"width: 585px; height: 443px;\" /><br />\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/15293525I13410-V1N.jpg\" style=\"width: 579px; height: 440px;\" /></p>\r\n<p>\r\n	　　更多好看的美甲图，实用的美甲技巧尽在<a href=\"http://www.ql-school.com\">成都美甲学校</a></p>\r\n</p>",577,1506);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/15293525H3V50-632F_lit.jpg",1508,1597);
$z[7][4]['name']="litpic";

?>