{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}如何用书籍帮自己美甲，这个方法女生一定会羡{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　爱美是每个人的天性，除了一身漂漂亮亮的装扮外，如何把自己的指甲弄得有特色的也很重要，一昧的涂得花花绿绿是不行的。今天就来教大家怎么让别人一眼就做的你是个学霸，因为我们用文字来点缀。</p>
<p>
	　　想要把纸上面的文字印在指甲上，就需要灰色指甲油、酒精、报纸以及透明指甲油等等。</p>
<p>
	　　现在指甲上面抹一层灰色的指甲油，然后把指尖泡在酒精里一会。<a href="http://www.ql-school.com">成都美甲学校</a></p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352a634G0-1V94.jpg" style="width: 510px; height: 386px;" /></p>
<p>
	　　接着就撕下一小块的纸张按在上面，掀开的时候你就会发现字母已经留在你指甲上了。</p>
<p>
	　　用棉花签擦拭干净周围多余的痕迹。</p>
<p>
	　　然后抹上一层透明的指甲油，等它干了后就算完成了。不知道大家觉得这个方法怎么样，如果你没时间去找人帮你美甲，不妨试试这个方法，既不困难也不会单调，又显得你是个知性分子，多好。</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352a634G0-1V94_lit.jpg{/dede:field}
