{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}成都化妆学校推荐瘦脸腮红的方法{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　腮红也跟着盛行走!盛行烟熏妆 时淡一点，裸妆 大红就得浓一点&rdquo;DIOR全国彩妆组长暨训育讲师，腮红的画法都跟着彩妆盛行趋势走!就像前两年很盛行的重烟熏，基本上就不太需求画腮红!但这一季的柔软烟熏，腮红是用来描写立体感，不只需瘦脸 ，还要好气色。</p>
<p>
	　　瘦脸腮红的画法：</p>
<p>
	　　STEP1 大眼影刷沾取腮红粉</p>
<p>
	　　用大支的眼影棒直接沾取腮红粉末。既不会像大只的粉底 刷那样沾得到处都是，也蘸取了满意的量。</p>
<p>
	　　STEP2 腮红从基地点起</p>
<p>
	　　找到笑肌的正基地方位，将沾了腮红粉末的眼影棒从最基地开始点起。</p>
<p>
	　　STEP3 用手再推匀</p>
<p>
	　　眼影刷把腮红点上去今后，再用指腹悄悄推开，让腮红更匀透。</p>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
