{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}[DIY美甲] 好看又特别的 一款晕染的时尚美甲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px;">
	指尖上美观的外型会给你增加时髦元素，让你伸出手时都格外的自信。今天<a href="http://www.ql-school.com">成都美甲学校</a>的小编就带来一款晕染的时髦美甲，跟着小编一同DIY，既美观又格外。</p>
<p style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px; text-align: center;">
	<img alt="[DIY美甲] 好看又特别的 一款晕染的时尚美甲" src="/uploads/allimg/c180619/152935295cN0-152533.jpg" style="width: 599px; height: 330px;" /></p>
<p style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px;">
	<br />
	Step1：将指尖修方正，在中指无名指上涂上白色指甲油，在剩下甲面涂上藏蓝色指甲油。<br />
	<br />
	Step2：取一支美甲勾花笔和白纸。在纸上点上少量的藏蓝色指甲油。<br />
	<br />
	Step3：在白色甲面点上几个藏蓝色的椭圆形状。<br />
	&nbsp;</p>
<p p="" style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px;">
	<span style="font-size: 13.3333px;">Step4：将画好的椭圆向四周晕染开，让两种色彩融合，如图所示。</span><br style="font-size: 13.3333px;" />
	<br style="font-size: 13.3333px;" />
	<span style="font-size: 13.3333px;">Step5：等指甲油干透后，在指尖结尾的中心贴上银色小方块。</span></p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935295cN0-152533_lit.jpg{/dede:field}
