<li>
                            <div>
                                <div class="showDetails">
                                    <h4>代理名</h4>
                                    <span>[field:title/] </span>
                                    <p>简介：[field:info/]/p>
                                </div>
                            </div>
                            <a href="">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]</a>
                        </li>