{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}这个夏季，在成都这些美甲可能会比较受欢迎哦{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>这个夏季，在成都这些美甲可能会比较受欢迎哦!<a href="http://www.ql-school.com">成都美甲学校</a>!
<div style="text-align: center;">
	<br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935292234C0-1H551.jpg" style="width: 813px; height: 534px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352922Ja0-1R5E.jpg" style="width: 564px; height: 536px;" /><br />
	<img alt="群丽美甲学校" src="/uploads/allimg/c180619/1529352923040-195457.jpg" style="width: 593px; height: 375px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529233510-20a91.jpg" style="width: 603px; height: 491px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352923CS0-21S07.jpg" style="width: 586px; height: 421px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352924003F-229635.jpg" style="width: 544px; height: 420px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529243FF-231324.jpg" style="width: 537px; height: 493px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352924A120-24G56.jpg" style="width: 570px; height: 552px;" /></div>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935292234C0-1H551_lit.jpg{/dede:field}
