<h3>[field:title/]</h3>
                            <div>
                                <dl>
                                    <dd>开班时间dd：[field:kbsj/]</dd>
                                    <dd>班级人数：[field:quantity/]人</dd>
                                    <dd>剩余人数：名额仅剩 <span>[field:sy/]</span>人</dd>
                                </dl>                       
                            </div>
                            <a href="" class="baoming">马上报名</a>