<li>
                 <img src="[field:litpic/]" alt="[field:title/]"/>
                 <div class="classTxt">
                     <div class="classTxtL">
                         <h2>[field:title/]</h2>
                         <span>[field:shorttitle/]</span>
                     </div>
                     <div class="classTxtR">
                         <p>
                             学期： <span>五个半月</span>        学费：  <span>[field:kbsj/]元</span>
                         </p>
                         <p>
                             限时活动价： <span style="font-size:18px;color:#e74159;font-weight:bold;font-family:'微软雅黑';">[field:price/]元</span>
                         </p>
                     </div>
                 </div>
             </li>