<div class="stRowsFl">
                        <div class="stRowsFlImgBox">
                            <a href="[field:arcurl/]" target="_blank">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]</a>
                        </div>
                        <div>
                            <h5>[field:title/]<span>离校时间：[field:leavetime function="GetDateMK(@me)"/]</span></h5>
                            <p>
                              [field:description/]
                            </p>
                        </div>
                    </div>