{dede:noteinfo notename="新闻" channelid="1" macthtype="string"
refurl="http://www.ql-school.com/index3.html" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.ql-school.com/index3.html"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.ql-school.com/index3.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="t2-2">{/dede:areastart}
    {dede:areaend}</body>{/dede:areaend}
{/dede:listrule}
