{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}11款各式各样的夏日美甲，总有你看了就想去做的{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　手是女人的第二张脸，每日更新最新美甲，希望为每一位爱美女性带来你喜欢的美丽方式，记得要阅读完喔。<a href="http://www.ql-school.com">成都美甲学校</a></p>
<p>
	　　成都群丽美甲学校：夏日小清新美甲图案参考</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aD610-23620.jpg" style="width: 394px; height: 329px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aG5R0-3b51.jpg" style="width: 264px; height: 441px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aI9620-4EX.jpg" style="width: 406px; height: 218px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aL60Z-545B.jpg" style="width: 383px; height: 304px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aO0P-61458.jpg" style="width: 382px; height: 394px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aQ95F-NE4.jpg" style="width: 357px; height: 267px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aU24Z-T2P.jpg" style="width: 391px; height: 267px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aX2950-92b8.jpg" style="width: 384px; height: 293px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352aZ2I0-1059C.jpg" style="width: 432px; height: 340px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352a921I0-1145A.jpg" style="width: 413px; height: 286px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352a9410-12bO.jpg" style="width: 366px; height: 363px;" /></p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352aD610-23620_lit.jpg{/dede:field}
