{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}可以营造专业美甲师的氛围的美甲小工具{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　成都群丽学校和大家介绍几个简单好用的美甲小工具，在家就可以营造专业美甲师的氛围哦~</p>
<p>
	　　一、法式贴</p>
<p>
	　　在做法式甲的时候，总是担心微笑线画不好吗?贴上法式贴，再涂甲油，就能DIY出整齐的边缘线条哦!</p>
<p>
	　　法式贴使用方法：</p>
<p>
	　　先把底色打好，这样会比较饱满，等底色完全干透。(干透标准：不粘就可以了)</p>
<p>
	　　把法式贴纸从纸板上撕下，找到中心点，照图片这个样子贴上</p>
<p>
	　　3.在留出指甲的位置涂上自己喜欢的颜色就可以了。</p>
<p>
	　　4.把纸条撕掉后，再涂一层，就是完美的法式指甲了。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529441C50-15351.jpg" style="width: 623px; height: 266px;" /></p>
<p>
	　　二、美甲贴纸</p>
<p>
	　　喜欢自己捣鼓美甲的菇凉，可以尝试买一些美甲贴纸在家里，不想涂甲油胶的时候，直接贴上一款美甲贴纸哦~简单漂亮快捷哟~</p>
<p>
	　　<a href="http://www.ql-school.com">成都美甲学校</a>小编偷偷告诉大家，想要美甲贴纸更亮更持久建议上涂上封层哦~</p>
<p>
	　　三、美甲线条贴</p>
<p>
	　　画直线总是花很多时间有木有?还老是画不直有木有?其实我们可以借助神奇线条贴来完成直线哦~</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529444940-25Q7.jpg" style="width: 544px; height: 309px;" /></p>
<p>
	&nbsp;</p>
<p>
	　　直线贴使用方法：</p>
<p>
	&nbsp;</p>
<p>
	　　1.涂完底色之后，直接贴到指甲上做线条造型，减去多余的长度即可。</p>
<p>
	　　2.在固定好后，记得涂上一层封层，能起到加固的作用。</p>
<p>
	　　四、美甲贴钻</p>
<p>
	　　涂上纯色美甲太简单?试试用一颗简单闪亮的钻，就能让整双手闪耀起来~</p>
<p>
	　　贴钻使用方法：</p>
<p>
	　　用夹子或其他工具夹起水钻，在要贴钻的甲面上涂上胶水。</p>
<p>
	　　将钻贴在胶水上后，在钻的边缘位置涂上封层就完成啦(注意不要把封层涂在钻的表面哦~不然会影响钻的亮度哦)</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/15293529441C50-15351_lit.jpg{/dede:field}
