{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}离高级化妆师你只差这几点？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><div>
	&nbsp;</div>
<div>
	日妆也称<a href="http://www.ql-school.com/kecheng/caizhuang/list_12_1.html#makeUp">生活妆</a>、淡妆，用于一般的日常生活和工作。日妆常出现在日光环境下，化妆时必须在日光光源下进行。妆色宜清淡典雅，自然协调，尽量不露化妆痕迹。</div>
<div>
	&nbsp;</div>
<div>
	&nbsp; 化日常妆的程序</div>
<div>
	&nbsp;</div>
<div>
	（一） 洁面：首先用洗面奶、清水将面部清除干净洗去多余油脂。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X133G0-294D.jpg" style="width: 500px; height: 278px;" /></div>
<div>
	（二）化妆水、润肤霜：日光下容易脱妆，化妆前必须选用收敛性的化妆水，然后擦上合适的润肤霜。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X15Z30-354X.jpg" style="width: 550px; height: 334px;" /></div>
<div>
	（三）乳液：化日妆宜选用乳液，含油量不宜太大，可选用水溶性乳液。</div>
<div>
	&nbsp;</div>
<div>
	（四）修正液、修正粉底：用于调整皮肤的颜色，适合化日妆使用，方便快捷，肤色黄的人用紫色粉底，可使皮肤显白；对红血丝皮肤用绿色粉底可起掩饰作用。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X1910-44H4.jpg" style="width: 700px; height: 299px;" /></div>
<div>
	（五）粉底液：适用于肤质好的人，也可以局部遮掩，用量宜少、宜薄，有严重斑点的部位和高光部位可多涂抹两次，皮肤较干或有严重斑点的皮肤应使用粉底霜。</div>
<div>
	&nbsp;</div>
<div>
	（六）定妆：用粉刷蘸取少量散粉或用粉饼在全脸薄薄定妆，尤其是脸颊和眼部。散粉宜少、宜薄。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X2230Z-5c49.jpg" style="width: 734px; height: 437px;" /></div>
<div>
	（七）眼影：眼部结构好的人可用单色眼影晕染。用眼影刷蘸取少量眼影色，从上眼睑外眼角向内眼角轻轻晕染，然后用干净大眼影刷晕染，位置为眼球的边缘线上。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X254H0-ET0.jpg" style="width: 573px; height: 433px;" /></div>
<div>
	（八）眼线：睫毛浓密的人可不画眼线，睫毛条件差的人可选合适的眼线笔，画上下眼线，然后用眉刷蘸深色眼影作晕染。使眼线产生睫毛的浓密感和朦胧感。</div>
<div>
	<img alt="化妆培训" src="/uploads/allimg/c180619/1529352X2VL0-N104.jpg" style="width: 300px; height: 350px;" /></div>
<div>
	（九）眉毛：眉毛条件好的人，只需用眉刷蘸取少量深色眼影刷顺眉毛，眉毛条件差者，用深色眼影轻刷一遍，缺少的眉毛要用眉笔一根一根的按眉毛生长的方向画上。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X31120-W409.jpg" style="width: 477px; height: 338px;" /></div>
<div>
	（十）口红：日妆的口红颜色不宜鲜艳，尽量接近唇色，可选用粉质无光的口红，画出唇形后，用唇刷蘸单色口红晕染，或涂上少量浅色唇油。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X330310-93S6.jpg" style="width: 484px; height: 300px;" /></div>
<div>
	（十一）睫毛：睫毛条件好的人，可用无色睫毛膏刷一遍；睫毛条件差的人，先要把睫毛夹弯上翘，然后刷2~3遍增长睫毛膏，使睫毛向上弯曲，可增强眼睛的立体感和魅力。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X361C0-105W9.jpg" style="width: 512px; height: 330px;" /></div>
<div>
	（十二）胭脂：脸形和肤色好的人可以不刷胭脂，需要刷时用胭脂刷，选择浅红色胭脂，用量宜少不宜多，非常自然、似有似无的感觉。</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X3ZJ0-1121U.jpg" style="width: 660px; height: 330px;" /><br />
	想学化妆来<a href="http://www.ql-school.com">成都群丽化妆学校</a>资深的教学教学经历,联系电话028-85831188</div>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352X133G0-294D_lit.jpg{/dede:field}
