<?php
$z[0]=Array("sppage","",0,73);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.ql-school.com/news/xinwen/1423.html",75,156);
$z[2]=Array("keywordtrim","",158,195);
$z[3]=Array("descriptiontrim","",197,242);
$z[4]=Array("item","\n   {dede:match}<h1>[内容]</h1>{/dede:match}\n   \n   {dede:function}{/dede:function}\n",244,396);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\n   {dede:match}{/dede:match}\n   \n   {dede:function}{/dede:function}\n",398,534);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\n   {dede:match}{/dede:match}\n   \n   {dede:function}{/dede:function}\n",536,672);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\n   {dede:match}{/dede:match}\n   \n   {dede:function}@me=GetMkTime(@me);{/dede:function}\n",674,830);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\n   {dede:match}<span>摘要：</span>\r\n                </div>[内容]<!--<p class=\"note\">{/dede:match}\n   \n   {dede:function}{/dede:function}\n",832,1042);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>