<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","清凉又可口的美甲，来一波！",368,445);
$z[2][4]['name']="title";
$z[3]=Array("field","",447,486);
$z[3][4]['name']="writer";
$z[4]=Array("field","",488,527);
$z[4][4]['name']="source";
$z[5]=Array("field","",529,569);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　清凉又可口的美甲</p>\r\n<p>\r\n	　　让你不得不爱-<a href=\"http://www.ql-school.com\">成都美甲学校</a></p>\r\n<p style=\"text-align: center;\">\r\n	<a href=\"http://www.ql-school.com\"><img alt=\"成都美甲学校\" src=\"/uploads/allimg/170615/1-1F615142400Q4.jpg\" style=\"width: 498px; height: 480px;\" /></a></p>\r\n<p>\r\n	　　爱吃的女孩，运气都不会太差!爱各种食物美甲的女孩，让人倍感可爱呢!</p>\r\n<p>\r\n	　　冰淇淋美甲</p>\r\n<p>\r\n	　　越来越能感受到夏日的热辣气息，除了衣服，指甲也要清凉起来，这个时候涂个冰淇淋美甲，真是自带清凉感呢!夏天最爱的冰淇淋也能跃然指尖了!</p>\r\n<p>\r\n	　　果冻美甲</p>\r\n<p>\r\n	　　当Q弹轻盈的果冻变成美甲的元素，真是少女心爆棚!每一款都想吃!!通透感十足清新迷人，让人无法抗拒!</p>\r\n<p>\r\n	　　西瓜美甲</p>\r\n<p>\r\n	　　西瓜是不是你夏天最爱的解暑水果呢，清爽的感觉，也可以从一款西瓜美甲做起啊，红红的指尖，带点点西瓜仁，十分的可爱。</p>\r\n<p>\r\n	　　柠檬美甲</p>\r\n<p>\r\n	　　柠檬指甲，仿佛连指尖都感受到了酸酸甜甜的味道，亮眼的柠檬黄也十分适合闪耀的夏日哦!</p>\r\n</p>",571,1876);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/1529352ab2420-13N06_lit.jpg",1878,1968);
$z[7][4]['name']="litpic";

?>