{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}清凉又可口的美甲，来一波！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　清凉又可口的美甲</p>
<p>
	　　让你不得不爱-<a href="http://www.ql-school.com">成都美甲学校</a></p>
<p style="text-align: center;">
	<a href="http://www.ql-school.com"><img alt="成都美甲学校" src="/uploads/allimg/170615/1-1F615142400Q4.jpg" style="width: 498px; height: 480px;" /></a></p>
<p>
	　　爱吃的女孩，运气都不会太差!爱各种食物美甲的女孩，让人倍感可爱呢!</p>
<p>
	　　冰淇淋美甲</p>
<p>
	　　越来越能感受到夏日的热辣气息，除了衣服，指甲也要清凉起来，这个时候涂个冰淇淋美甲，真是自带清凉感呢!夏天最爱的冰淇淋也能跃然指尖了!</p>
<p>
	　　果冻美甲</p>
<p>
	　　当Q弹轻盈的果冻变成美甲的元素，真是少女心爆棚!每一款都想吃!!通透感十足清新迷人，让人无法抗拒!</p>
<p>
	　　西瓜美甲</p>
<p>
	　　西瓜是不是你夏天最爱的解暑水果呢，清爽的感觉，也可以从一款西瓜美甲做起啊，红红的指尖，带点点西瓜仁，十分的可爱。</p>
<p>
	　　柠檬美甲</p>
<p>
	　　柠檬指甲，仿佛连指尖都感受到了酸酸甜甜的味道，亮眼的柠檬黄也十分适合闪耀的夏日哦!</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352ab2420-13N06_lit.jpg{/dede:field}
