<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","蓝色美甲为啥就这么多人喜欢？群丽美甲学校",368,466);
$z[2][4]['name']="title";
$z[3]=Array("field","",468,507);
$z[3][4]['name']="writer";
$z[4]=Array("field","",509,548);
$z[4][4]['name']="source";
$z[5]=Array("field","",550,590);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　浅浅的天蓝</p>\r\n<p>\r\n	　　深邃的湖蓝</p>\r\n<p>\r\n	　　靓丽的宝蓝</p>\r\n<p>\r\n	　　神秘的孔雀蓝</p>\r\n<p>\r\n	　　最流行色彩诠释多面蓝色浪漫风情</p>\r\n<p style=\"text-align: center;\">\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/15293529495L10-143D.jpg\" style=\"width: 478px; height: 448px;\" /><br />\r\n	<img alt=\"成都群丽美甲学校\" src=\"/uploads/allimg/c180619/152935294c4150-240P.jpg\" style=\"width: 513px; height: 381px;\" /><br />\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295024a0-35635.jpg\" style=\"width: 488px; height: 408px;\" /><br />\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295051440-4R20.jpg\" style=\"width: 567px; height: 408px;\" /><br />\r\n	<img alt=\"群丽美甲学校\" src=\"/uploads/allimg/c180619/1529352950U2F-5DA.jpg\" style=\"width: 514px; height: 397px;\" /></p>\r\n<p>\r\n	　　喜欢做美甲的你，快来<a href=\"http://www.ql-school.com\">成都美甲学校</a>!</p>\r\n</p>",592,1637);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/15293529495L10-143D_lit.jpg",1639,1729);
$z[7][4]['name']="litpic";

?>