{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}蓝色美甲为啥就这么多人喜欢？群丽美甲学校{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　浅浅的天蓝</p>
<p>
	　　深邃的湖蓝</p>
<p>
	　　靓丽的宝蓝</p>
<p>
	　　神秘的孔雀蓝</p>
<p>
	　　最流行色彩诠释多面蓝色浪漫风情</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529495L10-143D.jpg" style="width: 478px; height: 448px;" /><br />
	<img alt="成都群丽美甲学校" src="/uploads/allimg/c180619/152935294c4150-240P.jpg" style="width: 513px; height: 381px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935295024a0-35635.jpg" style="width: 488px; height: 408px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935295051440-4R20.jpg" style="width: 567px; height: 408px;" /><br />
	<img alt="群丽美甲学校" src="/uploads/allimg/c180619/1529352950U2F-5DA.jpg" style="width: 514px; height: 397px;" /></p>
<p>
	　　喜欢做美甲的你，快来<a href="http://www.ql-school.com">成都美甲学校</a>!</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/15293529495L10-143D_lit.jpg{/dede:field}
