{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}成都美甲学校：指尖上的条纹与花朵搭配{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	<span style="font-size: 12px;">　　条纹是一个非常时尚的元素，在很多地方都应用得到，美甲也不例外，而小花朵也是一个美丽抢眼的元素，很多人都觉得这两种搭配在一起会显得有点格格不入，其实不然!今天<a href="http://www.ql-school.com">成都美甲学校</a>小编就带来这款惊艳你的美甲，一起随着成都群丽美甲学校小编来看看吧。</span></p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352Zb5310-213M2.jpg" style="width: 476px; height: 422px;" /></p>
<p>
	　　Step1：修剪指尖，涂上透明底油。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935291012020-22S34.jpg" style="width: 470px; height: 385px;" /></p>
<p>
	　　Step2：等底油干透后，涂上白色指甲油，建议涂抹两层。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935291031L0-235534.jpg" style="width: 444px; height: 346px;" /></p>
<p>
	　　Step3：用非常细的美甲勾画笔蘸取黑色指甲油，在指甲表面画间隔相等的斜线，呈现黑白条纹状。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935291054b0-24M12.jpg" style="width: 471px; height: 421px;" /></p>
<p>
	　　Step4：另外的甲面也画好黑白条纹。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352910PN0-25a14.jpg" style="width: 484px; height: 400px;" /></p>
<p>
	　　Step5：在大拇指，食指和小拇指上贴上颜色不同的小花朵，在贴的时候贴在当中的一条黑色斜线上，如图所示。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529110X0-2632P.jpg" style="width: 450px; height: 402px;" /></p>
<p>
	　　Step6：在中指和无名指的中间贴上两朵黑色小花朵，最后涂上亮甲油封层。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935291142J0-2H4U.jpg" style="width: 468px; height: 412px;" /></p>
<p>
	　　画在指尖让人惊艳，原来条纹与花朵搭配在一起是这么的美~</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352Zb5310-213M2_lit.jpg{/dede:field}
