{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}美甲控的9大怪癖！来看看你中了哪一个？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　1 、钟情于显手白，无法自拔</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935300H4P-161392.jpg" style="width: 606px; height: 446px;" /></p>
<p>
	　　2 、刚做完美甲，会一直摸自己滑滑的甲面</p>
<p>
	　　3 、才刚换新美甲没两天，看到好看的又想换了</p>
<p>
	　　4 刚做完美甲，要拍N张不同角度的照片才会满足</p>
<p>
	　　5 、发朋友圈的时候不忘让美甲也出境</p>
<p>
	　　6 、手机里收藏了几百甚至上千张美甲图</p>
<p>
	　　7 、经常向身边的朋友安利和科普美甲</p>
<p>
	　　8 、家里的甲油数不清，但是依然还想继续买买买</p>
<p>
	　　9 、经常偷瞄其他女生的美甲!</p>
<p>
	　　哈哈哈哈哈，妞儿几乎全中</p>
<p>
	　　你呢?</p>
<p>
	　　喜欢做美甲的你，快来<a href="http://www.ql-school.com">成都美甲学校</a>。</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935300H4P-161392_lit.jpg{/dede:field}
