<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","美甲控的9大怪癖！来看看你中了哪一个？",368,461);
$z[2][4]['name']="title";
$z[3]=Array("field","",463,502);
$z[3][4]['name']="writer";
$z[4]=Array("field","",504,543);
$z[4][4]['name']="source";
$z[5]=Array("field","",545,585);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　1 、钟情于显手白，无法自拔</p>\r\n<p style=\"text-align: center;\">\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935300H4P-161392.jpg\" style=\"width: 606px; height: 446px;\" /></p>\r\n<p>\r\n	　　2 、刚做完美甲，会一直摸自己滑滑的甲面</p>\r\n<p>\r\n	　　3 、才刚换新美甲没两天，看到好看的又想换了</p>\r\n<p>\r\n	　　4 刚做完美甲，要拍N张不同角度的照片才会满足</p>\r\n<p>\r\n	　　5 、发朋友圈的时候不忘让美甲也出境</p>\r\n<p>\r\n	　　6 、手机里收藏了几百甚至上千张美甲图</p>\r\n<p>\r\n	　　7 、经常向身边的朋友安利和科普美甲</p>\r\n<p>\r\n	　　8 、家里的甲油数不清，但是依然还想继续买买买</p>\r\n<p>\r\n	　　9 、经常偷瞄其他女生的美甲!</p>\r\n<p>\r\n	　　哈哈哈哈哈，妞儿几乎全中</p>\r\n<p>\r\n	　　你呢?</p>\r\n<p>\r\n	　　喜欢做美甲的你，快来<a href=\"http://www.ql-school.com\">成都美甲学校</a>。</p>\r\n</p>",587,1619);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/152935300H4P-161392_lit.jpg",1621,1711);
$z[7][4]['name']="litpic";

?>