<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","夏日缤纷多彩创意指甲，绚烂夺目！",368,454);
$z[2][4]['name']="title";
$z[3]=Array("field","",456,495);
$z[3][4]['name']="writer";
$z[4]=Array("field","",497,536);
$z[4][4]['name']="source";
$z[5]=Array("field","",538,578);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　手是女人的第二张脸，连手都能照顾好的女生不简单哦。</p>\r\n<p>\r\n	　　在指尖上加上季节的颜色，就感觉特别酷。</p>\r\n<p>\r\n	　　特别是夏日，足部指甲也能绚烂夺目，双倍享受美甲带来的快乐。</p>\r\n<p>\r\n	　　每个女生，指甲上跳动鲜艳的颜色，都会让人振奋精神，心情舒畅。</p>\r\n<p>\r\n	　　首先选好自己喜欢的款式，让指甲变得更加时尚。<a href=\"http://www.ql-school.com\">成都美甲学校</a>!</p>\r\n<p>\r\n	　　指尖闪闪亮~</p>\r\n<p style=\"text-align: center;\">\r\n	　　<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295AT30-D035.jpg\" style=\"width: 600px; height: 357px;\" /></p>\r\n<p>\r\n	　　夏天就要玩转色彩。</p>\r\n<p>\r\n	　　施华洛世奇水晶钻光芒璀璨。</p>\r\n<p>\r\n	　　无需奢华珠宝，就让你光彩照人。</p>\r\n<p>\r\n	　　婚礼聚会都美艳动人。</p>\r\n<p>\r\n	　　足部美甲和凉鞋的完美组合</p>\r\n<p style=\"text-align: center;\">\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295DD20-J326.jpg\" style=\"width: 612px; height: 332px;\" /></p>\r\n<p>\r\n	　　冬眠了的脚趾甲就等着在今天大放光彩。</p>\r\n<p>\r\n	　　美甲颜色可以选择和凉鞋同色系的颜色，简练的线条立马粗现</p>\r\n</p>",580,1949);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/152935295AT30-D035_lit.jpg",1951,2040);
$z[7][4]['name']="litpic";

?>