<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","一款绝对高颜值的美甲，你的心动了么",368,457);
$z[2][4]['name']="title";
$z[3]=Array("field","",459,498);
$z[3][4]['name']="writer";
$z[4]=Array("field","",500,539);
$z[4][4]['name']="source";
$z[5]=Array("field","",541,581);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　<span style=\"font-size: 12px;\">　　美甲病患者看过来，这里有一款绝对高颜值的美甲在召唤你哦!下面成都群丽美甲学校就给大家分享这款美甲的DIY教程，这么让人心水的美甲就等你来宠幸啦~</span></p>\r\n<p>\r\n	　　</p>\r\n<center>\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/1529352YW13Z-2HI.jpg\" style=\"width: 572px; height: 389px;\" /></center>\r\n<p>\r\n	&nbsp;</p>\r\n<p>\r\n	　　Step 1：用偏橘粉色带金色小亮片的指甲油涂在中指和无名指上。</p>\r\n<p>\r\n	　　Step 2：在中指涂上一层透明的指甲油。</p>\r\n<p>\r\n	　　Step 3：趁着透明的指甲油没有干在上面画上白色的细线条，线条不用太规则。</p>\r\n<p>\r\n	　　Step 4：用刷子将白色的指甲油晕染开。</p>\r\n<p>\r\n	　　Step 5：重复步骤3-4。</p>\r\n<p>\r\n	　　Step 6：在中指指根贴上装饰品。</p>\r\n<p>\r\n	　　Step 7：无名指正中间也贴上装饰品。</p>\r\n<p>\r\n	　　Step 8：食指指尖用酒红色指甲油画一个法式美甲，然后在酒红色指甲油的边缘贴上铆钉和水钻。大拇指、小拇指也同食指。</p>\r\n<p style=\"text-align: center;\">\r\n	　　<img alt=\"群丽美甲学校\" src=\"/uploads/allimg/c180619/1529352YZE40-3O61.jpg\" style=\"width: 622px; height: 415px;\" /></p>\r\n<p>\r\n	　　融合了少女和女神的气质，想不喜欢都有点难呐!你心动了么，心动了就来<a href=\"http://www.ql-school.com\">成都美甲学校</a>：群丽，学习吧！</p>\r\n</p>",583,2147);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/1529352YW13Z-2HI_lit.jpg",2149,2236);
$z[7][4]['name']="litpic";

?>