{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}美甲款式参考，每一款都超级耐看{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><span style="color: rgb(68, 68, 68); font-family: Tahoma, &quot;Microsoft Yahei&quot;, Simsun; font-size: 14px;"><a href="http://www.ql-school.com">成都美甲学校</a>为你吐血整理海量人气美甲参考图。</span><br style="word-wrap: break-word; color: rgb(68, 68, 68); font-family: Tahoma, &quot;Microsoft Yahei&quot;, Simsun; font-size: 14px;" />
<span style="color: rgb(68, 68, 68); font-family: Tahoma, &quot;Microsoft Yahei&quot;, Simsun; font-size: 14px;">这么多款式,肯定有你喜欢的!</span><br style="word-wrap: break-word; color: rgb(68, 68, 68); font-family: Tahoma, &quot;Microsoft Yahei&quot;, Simsun; font-size: 14px;" />
<span style="color: rgb(68, 68, 68); font-family: Tahoma, &quot;Microsoft Yahei&quot;, Simsun; font-size: 14px;">趁现在就为自己换上一个迷人的彩甲吧!<br />
<img alt="成都美甲学校学生作品" src="/uploads/allimg/c180619/1529352cTa0-144Z0.jpg" style="width: 434px; height: 299px;" /><br />
<img alt="成都美甲学校学生作品" src="/uploads/allimg/c180619/1529352cW5V0-151224.jpg" style="width: 429px; height: 282px;" /><br />
<img alt="成都美甲学校学生作品" src="/uploads/allimg/c180619/1529352cYN40-1C0K.jpg" style="width: 437px; height: 314px;" /><br />
<img alt="成都美甲学校学生作品" src="/uploads/allimg/c180619/1529352c925160-1O333.jpg" style="width: 441px; height: 307px;" /></span><br />
<br />
<br />
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352cTa0-144Z0_lit.jpg{/dede:field}
