{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}化妆工具？新手化妆要准备那些东西{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>现在有些朋友因为工作忙而没有时间化妆，还有些朋友之前就没自己化过妆，他们对化妆的知识基本就是完全不懂，那么画个淡妆的话一般需要哪些化妆品呢？成都<a href="http://www.ql-school.com">群丽化妆学校</a>跟大家谈谈这些化妆的基础问题<br />
<div>
	一、工具/原料</div>
<div>
	&nbsp;隔离霜、bb霜、遮瑕膏、蜜粉、眉粉、眼影、睫毛膏、腮红、唇彩等化妆品；</div>
<div>
	二、方法/步骤</div>
<div>
	<br />
	1、首先在脸上大面积的点涂隔离霜，然后用掌心按压全脸使其被吸收；</div>
<div>
	<br />
	2、然后在粉刷上挤出适量的bb霜，让其在脸颊由内往外的蔓延开；</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352X643A0-1XQ0.jpg" style="width: 660px; height: 330px;" /><br />
	3、用眼部专业遮瑕膏在眼睛下方轻轻地点上，然后轻轻拍打使其遮瑕膏到无痕；</div>
<div>
	<br />
	4、为了让妆容的持久度更高，在全脸薄刷一层粉蜜能更好定妆；</div>
<div>
	<br />
	5、用横刷在蘸取棕色眉粉后，把多余的粉末在纸上扫去，然后从眉头开始描画眉毛；</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352XCXF-1cQ1.jpg" style="width: 477px; height: 338px;" /><br />
	6、在眼头和眼尾的地方用白色眼影刷出半圆形状，然后沿着上睫毛根部刷一层淡蓝色眼影，在下眼睑的尾部用粉色眼影清扫一层；</div>
<div>
	<br />
	7、紧接着选择防水型眼线笔从眼珠上方开始勾勒眼线，注意要两头细中间粗是原则；</div>
<div>
	<br />
	8、用睫毛夹将自己的睫毛夹至卷翘后，上一层睫毛膏，如果不够纤长可重复刷一次；</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352XF1340-209591.jpg" style="width: 495px; height: 246px;" /><br />
	9、使用纤长的假睫毛分别在上下睫毛根部粘贴好，一定要沿着自己的眼型粘贴才能自然；</div>
<div>
	<br />
	10、用白色的眼线笔在眼角的三角区域轻轻画一下，让眼睛瞬间有提亮的感觉；</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352XH5c0-219260.jpg" style="width: 500px; height: 324px;" /><br />
	11、眼妆完成后，就轮到腮红部分了；</div>
<div>
	<img alt="化妆知识" src="/uploads/allimg/c180619/1529352XK2C0-22XH.jpg" style="width: 376px; height: 345px;" /><br />
	12、最后，选择果冻色的啫喱或唇彩沿着唇部上一层薄薄的唇妆即可。</div>
<div>
	<br />
	注意，选择眼线产品时应根据自己眼睛的出油状况来选择最佳的。想了解更多化妆技巧和知识请联系02885831188;或输入网址www.ql-school.com</div>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352X643A0-1XQ0_lit.jpg{/dede:field}
