<dd><a href=""></a><em>[field:pubdate function="GetDateTimeMK(@me)"/]</em></dd>
                        <li><a href="[field:arcurl/]">
                        [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]
                            <img src="{dede:global.cfg_templets_skin/}/images/newShow1.png" alt="[field:title/]"/>
                        </a></li>