<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","星星美甲教程：俏皮清新的美甲和夏季更搭",368,463);
$z[2][4]['name']="title";
$z[3]=Array("field","",465,504);
$z[3][4]['name']="writer";
$z[4]=Array("field","",506,545);
$z[4][4]['name']="source";
$z[5]=Array("field","",547,587);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	<span style=\"font-size: 12px;\">　　<strong><a href=\"http://www.ql-school.com\">成都美甲学校</a></strong>今天为大家带来一款星星美甲教程，俏皮不失清新的美甲和这个夏季更搭哦。</span></p>\r\n<p>\r\n	　　星星美甲教程</p>\r\n<p style=\"text-align: center;\">\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/1529352Z0FC0-K2Y.jpg\" style=\"width: 457px; height: 337px;\" /></p>\r\n<p>\r\n	　　星星亮片甲油搭配紫色的，略带俏皮不失清新甜美的一款美甲!</p>\r\n<p>\r\n	　　星星美甲具体步骤</p>\r\n<p>\r\n	　　第一步：准备好所需的甲油和工具，刷上底油，照灯60秒。在无名指后缘黏上微笑贴纸，再在前缘刷上紫色甲油，照灯60秒。</p>\r\n<p>\r\n	　　第二步：按同样的方法在大拇指前缘刷出反法式，待干后刷上星星亮片甲油，照灯60秒。</p>\r\n<p>\r\n	　　第三步：无名指前缘也刷上星星亮片甲油，待干。分别用粉色甲油和白色甲油在其它几枚指甲前缘刷出反法式，照灯60秒。</p>\r\n<p>\r\n	　　第四步：用点钻笔分别蘸白色和紫色甲油在其它几枚指甲法式后缘相见着点出圆点，照灯60秒。最后全部指甲彻底干透后，刷上亮油待干就完成啦。</p>\r\n</p>",589,1909);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/1529352Z0FC0-K2Y_lit.jpg",1911,1998);
$z[7][4]['name']="litpic";

?>