{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}成都美甲学校：时尚又漂亮的美甲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	<span style="font-size: 12px;">　　复古茶色</span></p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935291910010-HO3.jpg" style="width: 540px; height: 427px;" /></p>
<p>
	　　个性晕染</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935291946230-V021.jpg" style="width: 505px; height: 416px;" /></center>
<p>
	　　象牙塔</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935291a94F-9CN.jpg" style="width: 531px; height: 443px;" /></p>
<p>
	　　摩登贵妇</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529200B50-10L91.jpg" style="width: 528px; height: 424px;" /></p>
<p>
	　　气质白领</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935292034M0-115R7.jpg" style="width: 523px; height: 478px;" /></p>
<p>
	　　阿尔卑斯</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352920D5P-1235S.jpg" style="width: 504px; height: 468px;" /></p>
<p>
	　　都市丽人</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352920ca0-139191.jpg" style="width: 513px; height: 454px;" /></p>
<p>
	　　摩登少女</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935292130A0-145140.jpg" style="width: 535px; height: 425px;" /></p>
<p>
	　　水晶之恋</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935292155920-15D13.jpg" style="width: 495px; height: 448px;" /></p>
<p>
	　　芭比粉</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352921W060-1615N.jpg" style="width: 503px; height: 465px;" /></p>
<p>
	妹子们有没有看的心动了，如果有想发哪就来<a href="http://www.ql-school.com">成都美甲学校</a>，到<strong>成都群丽美甲学校</strong>进行了解吧！</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935291910010-HO3_lit.jpg{/dede:field}
