{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}好看的美甲，每天都要不重样！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　<a href="http://www.ql-school.com">成都美甲学校</a>-群丽学员作品</p>
<center>
	<br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352bXA10-I411.jpg" style="width: 467px; height: 417px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　显白又气质的裸色，小仙女的最爱 ~</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352b913930-UD3.jpg" style="width: 434px; height: 378px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　蓝绿色，超级春天的颜色 ~</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352b933050-93Q6.jpg" style="width: 423px; height: 403px;" /></p>
<p>
	　　香芋紫色也太美了吧!</p>
<p>
	　　</p>
<center>
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352b9591P-10FL.jpg" style="width: 430px; height: 425px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　浅紫色和浅粉色的搭配，实在是心旷神怡 ~</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352bb21P-11G24.jpg" style="width: 446px; height: 383px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　芥末绿色超级气质的 ~ 喜欢 ~</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352c003a0-122G4.jpg" style="width: 413px; height: 366px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　豆沙色和酒红色碰撞出别样的火花，好看 ~</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352c02340-135212.jpg" style="width: 442px; height: 371px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　春意满满的绿色，显白没商量 ~</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352bXA10-I411_lit.jpg{/dede:field}
