<li>
                                <div>
                                    <div class="showDetails">
                                        <span>[field:title/] </span>
                                        <p>简介：[field:info/]</p>
                                    </div>
                                </div>
                                <a href="[field:arcurl/]" target="_blank"><img src='[field:leavetime/]'/></a></li>