{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}4款百搭平法式美甲，哪款是你的菜？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　说起法式美甲，很多人都会想到传统法式。</p>
<p>
	　　比起传统法式，平法式更加时髦简约。</p>
<p>
	　　百搭的平法式，到底有多少种玩法呢?</p>
<p>
	　　</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935262c3W0-10c11.jpg" style="width: 343px; height: 297px;" /></p>
<p>
	　　闪耀金银线</p>
<p>
	　　巧妙运用粗细不同的金银线，也会让平法式有不同的感觉，细线更加精致，而粗线则更有金属感。</p>
<p>
	&nbsp;</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935263019560-116004.jpg" style="width: 564px; height: 297px;" /></center>
<p>
	　　活泼多色系</p>
<p>
	　　看腻了单色的平法式，可以试试用两种颜色拼接，如时尚的绿色、显白的宝蓝色，会有不一样的时尚感哦~</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293526303Y50-12OE.jpg" style="width: 495px; height: 292px;" /></p>
<p>
	　　简约几何风</p>
<p>
	　　几何元素依旧是今年的潮流元素，将几何跟平法式结合起来，让本来就简单的平法式更添了一份利落感。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352630E550-134629.jpg" style="width: 511px; height: 299px;" /></p>
<p>
	　　优雅钻饰款</p>
<p>
	　　自带奢华感的钻饰，用到平法式上不会显得累赘，反而有种低调的优雅感。</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935263094B0-143W6.jpg" style="width: 291px; height: 272px;" /></p>
<p>
	　　　　除了<a href="http://www.ql-school.com">成都美甲学校</a>介绍的四种平法式玩法之外，你还见过平法式有哪些玩法呢?</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935262c3W0-10c11_lit.jpg{/dede:field}
