<li>
                         <a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
                         <dl>
                         {dede:channel type='son' noself='yes'}
                          <dd><a href="[field:typelink/]">[field:typename/]</a></d>                         
                          {/dede:channel}    
                         </dl>
                     </li>