{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}群丽叶老师作为人力资源部和劳动局特邀讲师{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　群丽学校实习季，群丽叶老师作为人力资源部和劳动局特邀讲师，再次为各级领导老师上课，谢谢各级领导的信任，群丽学生受成都西南脑科研究中心和艺术小学，化妆造型受到各级单位的认同，<span style="font-stretch: normal; font-size: 15px; line-height: 19px; font-family: punctuation, PingFangSC-Regular, 'Microsoft Yahei', sans-serif; color: rgb(49, 51, 46);">真的很棒！成都群丽化妆美甲学校，<a href="http://www.ql-school.com">成都美甲学校</a></span></p>
<p style="text-align: center;">
	<span style="font-stretch: normal; font-size: 15px; line-height: 19px; font-family: punctuation, PingFangSC-Regular, 'Microsoft Yahei', sans-serif; color: rgb(49, 51, 46);"><img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352934X020-1J0V.jpg" style="width: 454px; height: 588px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935293521110-1Y1I.jpg" style="width: 687px; height: 506px;" /><br />
	<img alt="成都群丽美甲学校" src="/uploads/allimg/c180619/152935293552050-196494.jpg" style="width: 389px; height: 493px;" /><br />
	<img alt="成都群丽美甲学校" src="/uploads/allimg/c180619/1529352935T440-2031J.jpg" style="width: 451px; height: 501px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529361E20-212T7.jpg" style="width: 444px; height: 499px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352936494Z-22TQ.jpg" style="width: 424px; height: 516px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935293D3260-232507.jpg" style="width: 417px; height: 533px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935293G04Z-245449.jpg" style="width: 809px; height: 603px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935293K4940-251435.jpg" style="width: 436px; height: 558px;" /></span></p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352934X020-1J0V_lit.jpg{/dede:field}
