<li class="infoImg1">
                            <h3></h3>
                            <div>
                                <dl>
                                    <dd>开班时间：[field:btime function='strftime("%b %d, %Y",@me)/]  [field:btime function="GetDateTimeMK(@me)"/]</dd>
                                    <dd>班级人数：[field:cnt/]人</dd>
                                    <dd>剩余人数：名额仅剩 <span>[field:syrs/]</span>人</dd>
                                </dl>
                            </div>
                            <a href="" class="baoming">马上报名</a>
                        </li>