{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}快让自己的脚打扮的美美的，露脚趾的季节已到{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　夏天当然要换上美美的凉鞋，显露美美的脚趾，当然要做个足部美甲啦!</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935295I4130-U0a.jpg" style="width: 619px; height: 575px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935295MK30-96246.jpg" style="width: 534px; height: 470px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935295PQ0-10W43.jpg" style="width: 495px; height: 352px;" /></p>
<p>
	　　做好美丽的美甲，<a href="http://www.ql-school.com">成都美甲学校</a>小编帮你们选择的几款鞋子，一定要记住搭对鞋子哦~</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935295SG20-1145Q.jpg" style="width: 497px; height: 425px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935295VH30-124E8.jpg" style="width: 487px; height: 499px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935295I4130-U0a_lit.jpg{/dede:field}
