<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","快让自己的脚打扮的美美的，露脚趾的季节已到",368,469);
$z[2][4]['name']="title";
$z[3]=Array("field","",471,510);
$z[3][4]['name']="writer";
$z[4]=Array("field","",512,551);
$z[4][4]['name']="source";
$z[5]=Array("field","",553,593);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　夏天当然要换上美美的凉鞋，显露美美的脚趾，当然要做个足部美甲啦!</p>\r\n<p style=\"text-align: center;\">\r\n	　　<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295I4130-U0a.jpg\" style=\"width: 619px; height: 575px;\" /><br />\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295MK30-96246.jpg\" style=\"width: 534px; height: 470px;\" /><br />\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295PQ0-10W43.jpg\" style=\"width: 495px; height: 352px;\" /></p>\r\n<p>\r\n	　　做好美丽的美甲，<a href=\"http://www.ql-school.com\">成都美甲学校</a>小编帮你们选择的几款鞋子，一定要记住搭对鞋子哦~</p>\r\n<p>\r\n	　　</p>\r\n<center>\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295SG20-1145Q.jpg\" style=\"width: 497px; height: 425px;\" /><br />\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935295VH30-124E8.jpg\" style=\"width: 487px; height: 499px;\" /></center>\r\n<p>\r\n	&nbsp;</p>\r\n<p>\r\n	　　</p>\r\n</p>",595,1682);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/152935295I4130-U0a_lit.jpg",1684,1773);
$z[7][4]['name']="litpic";

?>