{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}拒绝撞“甲”，打造属于你的个性美甲{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　无论是在工作还是生活中，细致润滑的双手都代表着你的生活品质，举手投足间尽显女性之美。一切美丽的事物都能让内心愉悦，心情不好的时候不妨伸开双手，欣赏自己精心挑选的美甲款式，感觉瞬间好多啦!&rdquo;<a href="http://www.ql-school.com">成都美甲学校</a></p>
<p>
	　　粉色</p>
<p>
	　　粉红色是公主的颜色，没有女生能抗拒的颜色，更是俘获男神心扉的法宝。淡淡的粉色与冬天是绝配，甜美可爱，让冬天不再单调。果冻色的淡粉更是受万千女生的追捧，可爱俏丽，一见难忘。</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529353005D520-11Ib.jpg" style="width: 578px; height: 564px;" /></p>
<p>
	　　黑白</p>
<p>
	　　永远的黑白经典，尽显时尚!</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529353005bZ-121533.jpg" style="width: 439px; height: 467px;" /></p>
<p>
	　　蓝色、绿色</p>
<p>
	　　显手白?你可以试试优雅的薄荷绿或者蓝色系~</p>
<p style="text-align: center;">
	　<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293530062C20-13I53.jpg" style="width: 568px; height: 554px;" /></p>
<p>
	　　红色</p>
<p>
	　　红色是中国人新年与春节的主色调，当然也要推荐了，花式美甲、酒红色或者单单的大红色都美极了!</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529353006495P-14LI.jpg" style="width: 520px; height: 406px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935300C2350-154P5.jpg" style="width: 535px; height: 570px;" /></p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529353005D520-11Ib_lit.jpg{/dede:field}
