<li ><a  href="[field:arcurl/]" >
                        [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]
                        </a></li>    
                         <h1><a href=""><img src="{dede:global.cfg_templets_skin/}/images/vedioCenter.png" alt=""/></a></h1>
                         <h5><span>[field:title/]</span><a>[field:pubdate function="GetDateTimeMK(@me)"/]</a></h5>
                         <p>[field:description/]</p>