<?php
$z[0]=Array("field","",67,95);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",97,126);
$z[1][4]['name']="typename";
$z[2]=Array("channel","<a href=\"[field:typeurl/]\">[field:typename/]</a>",156,244);
$z[2][4]['type']="son";
$z[3]=Array("arclist","\n					<p><span class='t5'>发布日期：[field:pubdate function=\"GetDateMK(@me)\" /]</span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></p>\n					",287,473);
$z[3][4]['row']="100";

?>