<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.ql-school.com/news/xinwen/1423.html",61,142);
$z[2]=Array("keywordtrim","",144,181);
$z[3]=Array("descriptiontrim","",183,228);
$z[4]=Array("item","\n   {dede:match}<h1>[内容]</h1>{/dede:match}\n   \n   {dede:function}{/dede:function}\n",230,382);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\n   {dede:match}{/dede:match}\n   \n   {dede:function}{/dede:function}\n",382,518);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\n   {dede:match}{/dede:match}\n   \n   {dede:function}{/dede:function}\n",518,654);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\n   {dede:match}{/dede:match}\n   \n   {dede:function}{/dede:function}\n",654,791);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\n   {dede:match}<span>摘要：</span>\r\n                </div>[内容]<!--<p class=\"note\">{/dede:match}\n   \n   {dede:function}{/dede:function}\n",791,1001);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>