<dd><a href="[field:arcurl/]">[field:title/]</a><em>[field:pubdate function="GetDateTimeMK(@me)"/]</em></dd>
                        {/dede:arclist }
                    </dl>
                    <a href="">VIEW MORE</a>
                </div>
                <div style="margin-left:50px;">
                    <dl>
                        <dt>新闻动态 <span>LATEST NEWS</span></dt>
                        <dd><a href="">新闻标题新闻标题新闻新闻标题新闻标题新闻新闻新闻新闻新闻新闻标题</a><em>2014.12.1</em></dd>
                        <dd><a href="">新闻标题新闻题新闻标题新闻标题新闻标题</a><em>2014.12.1</em></dd>
                        <dd><a href="">新闻标题新闻标题新闻标题新闻标新闻标题新闻标题</a><em>2014.12.1</em></dd>
                        <dd><a href="">新闻标题新闻题新闻标题新闻标题</a><em>2014.12.1</em></dd>
                        <dd><a href="">新闻标题新闻标题新闻标标题新闻标题新闻标题新闻标题</a><em>2014.12.1</em></dd>

                    </dl>
                    <a href="">VIEW MORE</a>
                </div>
                <h6 style="clear: both"></h6>
            </div>
        </div>
        <!--群丽活动-->
        <div class="students qunliActive">
            <h1><a href=""><img src="{dede:global.cfg_templets_skin