{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}美甲小教程 自己DIY的美甲方式{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	<span style="font-size: 12px;">　　很多小伙伴已经越来越习惯于自己DIY的美甲方式了，可以随意风格造型，可以做各式自己喜欢的图案，今天<a href="http://www.ql-school.com">成都美甲学校</a>继续带大家美甲DIY。</span></p>
<p style="text-align: center;">
	<span style="font-size: 12px;"><img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352Z022040-612P.jpg" style="width: 431px; height: 260px;" /></span></p>
<p>
	　　第一步：准备甲油，点钻笔，还有金箔小方片。</p>
<p>
	　　第二步：修剪打磨指甲，给指甲上一层底油，起到保护指甲的作用。</p>
<p>
	　　第三步：给指甲上底色，我们选择黑色甲油，涂的时候要均匀。</p>
<p>
	　　第四步：滴一滴透明甲油在纸上，有条件的mm也可以使用专业的胶水，不过小编觉得甲油其实就足够了，金箔方片不像立体的钻，不容易掉。用甲油来黏也更好操作。</p>
<p>
	　　第五步：把小金片分开平铺若干在纸上，不要重叠哦，要分开放哦!</p>
<p>
	　　第六步：用点钻笔蘸取透明甲油，然后黏上来一个方片。</p>
<p>
	　　第七步：把方片按在黑色指甲上，调整好位置。</p>
<p>
	　　第八步：大概隔开一个方片的位置再放一个，要注意不要贴歪了哦，否则整体效果就不好看了哦!</p>
<p>
	　　第九步：把整个甲面都铺满，做出格子的效果。</p>
<p>
	　　第十步：这时候用小剪刀或者指甲钳把边边多余的部分剪掉。</p>
<p>
	　　最后，给指甲涂一层亮油就完成了。</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352Z022040-612P_lit.jpg{/dede:field}
