{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}当甜美遇到小可爱后的美甲，一定让你惊喜！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　甜美与可爱似乎是一对形影不离的好姐妹，她们总是如影随形，时刻扮靓着女孩们的生活，看看当甜美遇到小可爱之后会有什么样令人惊喜的化学反应呢?<a href="http://www.ql-school.com">成都美甲学校</a></p>
<p>
	&nbsp;</p>
<p>
	　　STEP 1：将十指的指甲修剪成自己喜欢的模样，指尖尽量方一些，然后均匀涂抹上打底油，为指甲提供保护。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935261T5540-53192.jpg" style="width: 477px; height: 180px;" /></p>
<p>
	　　STEP 2：等护甲油干透之后，选择咖啡色的指甲油涂抹在指甲上，涂抹指甲油的时候尽量三笔成型，让指甲油尽可能的均匀。</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935261Vc30-EV2.jpg" style="width: 482px; height: 294px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　STEP 3：咖啡色指甲油干透之后，用细刷头蘸取粉色的指甲油有间隔的在指甲的前半段画竖条纹。然后再香芋色的指甲油涂抹在粉色中间的空白位置。</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935261Y33Z-G642.jpg" style="width: 482px; height: 298px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　STEP 4：等粉色香芋色的指甲油干透之后，用极细的笔刷蘸取大红色的指甲油在指甲前半段的中间画一条横线。在横线以下画两个椭圆型，在椭圆形的对立面画两条粗粗的缎带，蝴蝶结的形状就基本完成了。</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352619191Z-X5C.jpg" style="width: 473px; height: 206px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　STEP 5：所有的指甲油都干透之后再指甲上涂抹一层亮油。在亮油未干之前，用镊子将小水钻贴在蝴蝶结的中间压平，等亮油干以后水钻就粘在指甲上了。</p>
<p>
	　　</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352619415F-91458.jpg" style="width: 481px; height: 272px;" /></center>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935261T5540-53192_lit.jpg{/dede:field}
