{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}[DIY美甲] 小碎花美甲，将一道超美的风景线画在{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px;">
	虽然已进入夏日，可是鲜艳的花朵还在开放，想要时间欣赏到这种漂亮的景色，就来看看今日<a href="http://www.ql-school.com">成都美甲学校</a>带来的小碎花美甲，将这道超美的景色线画在指尖，留住这份美。</p>
<p style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px; text-align: center;">
	<img alt="[DIY美甲] 小碎花美甲，将一道超美的风景线画在指尖" src="/uploads/allimg/c180619/15293529513H20-A1Y.jpg" style="width: 499px; height: 328px;" /></p>
<p style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px;">
	<br />
	Step1：修剪指甲，涂上一层透明护甲油。<br />
	<br />
	Step2：在食指和小拇指的甲面涂上赤色指甲油，要涂抹两层，使色泽更丰满。<br />
	<br />
	Step3：先在大拇指涂上淡淡的一层粉色指甲油，之后用勾花笔蘸取赤色指甲油，在甲面画赤色小花朵和绿色的树枝，完成小碎花的造型。<br />
	<br />
	Step4：中指和无名指的甲面也先用粉色指甲油打底，再仔细的画上赤色小碎花。</p>
<p style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px;">
	<br />
	Step5：用绿色树枝树叶来装点，让全体更形象传神。<br />
	​<br />
	Step6：最后涂上一层亮甲油，将漂亮封层在指尖。</p>
<p style="word-wrap: break-word; margin: 5px 0px; color: rgb(0, 0, 0); font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 13.3333px;">
	&nbsp;</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/15293529513H20-A1Y_lit.jpg{/dede:field}
