<?php
$z[0]=Array("field","",69,97);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",99,128);
$z[1][4]['name']="typename";
$z[2]=Array("channel","<a href=\"[field:typeurl/]\">[field:typename/]</a>",159,247);
$z[2][4]['type']="son";
$z[3]=Array("arclist","\r\n					<p><span class='t5'>发布日期：[field:pubdate function=\"GetDateMK(@me)\" /]</span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></p>\r\n					",293,481);
$z[3][4]['row']="100";

?>