{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}4种新款碎玻璃美甲，好看又时尚！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　碎玻璃美甲&mdash;&mdash;夏日百搭之选</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352594114F-101630.jpg" style="width: 565px; height: 527px;" /></p>
<p>
	　　炎炎夏日，就该来点酷酷的款式~</p>
<p>
	　　今天，<a href="http://www.ql-school.com">成都美甲学校</a>为大家推荐新款碎玻璃美甲</p>
<p>
	　　既显白又时尚，</p>
<p>
	　　喜欢的宝宝记得收藏起来哦~</p>
<p>
	　　经典碎玻璃</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293525944TZ-1134F.jpg" style="width: 541px; height: 492px;" /></p>
<center>
	&nbsp;</center>
<div align="left">
	渐变碎玻璃</div>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352594913P-124224.jpg" style="width: 601px; height: 379px;" /></p>
<p>
	　　显手白碎玻璃</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352595121P-139457.jpg" style="width: 621px; height: 316px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935259543060-149B6.jpg" style="width: 465px; height: 347px;" /></p>
<p>
	　　喜欢今天推荐的碎玻璃美甲吗?</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352594114F-101630_lit.jpg{/dede:field}
