<li><a href="[field:arcurl/]" title="[field:title/]">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]</a></li>
                <div>
                    {dede:arclist typeid="23"  titlelen='200' orderby='pubdate' } 
                    <li><a href="[field:arcurl/]" title="[field:title/]">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]</a></li>