<?php
$z[0]=Array("arcurl","",13,28);
$z[1]=Array("title","",37,51);
$z[2]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}'/>\"); ",53,161);
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",312,327);
$z[4]=Array("title","",336,350);
$z[5]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}'/>\"); ",352,460);
$z[5][4]['runphp']="yes";

?>