<li>
                                    <a href="">[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]</a>
                                    <div>
                                        <h3>[field:title/]</h3>
                                        <span>
                                            [field:info/]
                                        </span>
                                    </div>
                                </li>