{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}简单大方美甲,今天为大家带来6款17年新款简单美{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　清新的糖果色配色，搭配呆萌的小表情甚是讨人喜欢。这款美甲简单易做，很适合自己在家DIY哦~<a href="http://www.ql-school.com">成都美甲学校</a>!</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/152935300M9410-1L508.jpg" style="width: 426px; height: 300px;" /></p>
<p>
	　　黑色大眼猫搭配法式的款式画在指甲上，搭配碎玻璃纸，整款美甲显得简单又不失大方。</p>
<p>
	　　想要一款简单大方的美甲，美甲师一定会推荐酒红色纯色美甲。颜色显白，即使是单色也很好看的一款美甲!</p>
<p style="text-align: center;">
	　　<img alt="群丽美甲学校" src="/uploads/allimg/c180619/152935300PO30-1S129.jpg" style="width: 434px; height: 329px;" /></p>
<p>
	　　人鱼姬作为彩妆界近期流行色，当然美甲也不能放过!显白又显嫩，非常适合春季的颜色~</p>
<p style="text-align: center;">
	　　<img alt="成都群丽美甲学校" src="/uploads/allimg/c180619/152935300SB10-194110.jpg" style="width: 470px; height: 281px;" /></p>
<p>
	　　姜黄色美甲搭配波点美甲，虽然是酒红色美甲但一点都不会觉得颜色过重，和姜黄色很和谐的搭配。</p>
<p>
	　　这款几何撞色美甲虽然略微复杂一些，但因为法式美甲的原因，而款款大方，很百搭。</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935300M9410-1L508_lit.jpg{/dede:field}
