<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","简单大方美甲,今天为大家带来6款17年新款简单美",368,470);
$z[2][4]['name']="title";
$z[3]=Array("field","",472,511);
$z[3][4]['name']="writer";
$z[4]=Array("field","",513,552);
$z[4][4]['name']="source";
$z[5]=Array("field","",554,594);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　清新的糖果色配色，搭配呆萌的小表情甚是讨人喜欢。这款美甲简单易做，很适合自己在家DIY哦~<a href=\"http://www.ql-school.com\">成都美甲学校</a>!</p>\r\n<p style=\"text-align: center;\">\r\n	　　<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/152935300M9410-1L508.jpg\" style=\"width: 426px; height: 300px;\" /></p>\r\n<p>\r\n	　　黑色大眼猫搭配法式的款式画在指甲上，搭配碎玻璃纸，整款美甲显得简单又不失大方。</p>\r\n<p>\r\n	　　想要一款简单大方的美甲，美甲师一定会推荐酒红色纯色美甲。颜色显白，即使是单色也很好看的一款美甲!</p>\r\n<p style=\"text-align: center;\">\r\n	　　<img alt=\"群丽美甲学校\" src=\"/uploads/allimg/c180619/152935300PO30-1S129.jpg\" style=\"width: 434px; height: 329px;\" /></p>\r\n<p>\r\n	　　人鱼姬作为彩妆界近期流行色，当然美甲也不能放过!显白又显嫩，非常适合春季的颜色~</p>\r\n<p style=\"text-align: center;\">\r\n	　　<img alt=\"成都群丽美甲学校\" src=\"/uploads/allimg/c180619/152935300SB10-194110.jpg\" style=\"width: 470px; height: 281px;\" /></p>\r\n<p>\r\n	　　姜黄色美甲搭配波点美甲，虽然是酒红色美甲但一点都不会觉得颜色过重，和姜黄色很和谐的搭配。</p>\r\n<p>\r\n	　　这款几何撞色美甲虽然略微复杂一些，但因为法式美甲的原因，而款款大方，很百搭。</p>\r\n</p>",596,2069);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/152935300M9410-1L508_lit.jpg",2071,2162);
$z[7][4]['name']="litpic";

?>