{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}创意美甲-简约风脚甲，耐看又百搭！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　夏天最适合做的就是脚甲啦~~</p>
<p>
	　　虽然复杂的款式不是所有人都能驾驭，</p>
<p>
	　　也有可能和你的穿搭不符，</p>
<p>
	　　但想要耐看又百搭，就一起看看<a href="http://www.ql-school.com">成都美甲学校</a>小编推荐的</p>
<p style="text-align: center;">
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529C49140-1b357.jpg" style="width: 539px; height: 379px;" /><br />
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/15293529CV240-204940.jpg" style="width: 520px; height: 290px;" /></p>
<p>
	　　简约风脚甲吧~</p>
<p>
	　　你们喜欢今天的款式吗?</p>
<p>
	　　快来夸夸<strong>成都美甲学校</strong>的小编吧~</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/15293529C49140-1b357_lit.jpg{/dede:field}
