<?php
$z[0]=Array("field","成都学化妆,成都化妆,成都",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","创意美甲-简约风脚甲，耐看又百搭！",368,455);
$z[2][4]['name']="title";
$z[3]=Array("field","",457,496);
$z[3][4]['name']="writer";
$z[4]=Array("field","",498,537);
$z[4][4]['name']="source";
$z[5]=Array("field","",539,579);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p><p>\r\n	　　夏天最适合做的就是脚甲啦~~</p>\r\n<p>\r\n	　　虽然复杂的款式不是所有人都能驾驭，</p>\r\n<p>\r\n	　　也有可能和你的穿搭不符，</p>\r\n<p>\r\n	　　但想要耐看又百搭，就一起看看<a href=\"http://www.ql-school.com\">成都美甲学校</a>小编推荐的</p>\r\n<p style=\"text-align: center;\">\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/15293529C49140-1b357.jpg\" style=\"width: 539px; height: 379px;\" /><br />\r\n	<img alt=\"成都美甲学校\" src=\"/uploads/allimg/c180619/15293529CV240-204940.jpg\" style=\"width: 520px; height: 290px;\" /></p>\r\n<p>\r\n	　　简约风脚甲吧~</p>\r\n<p>\r\n	　　你们喜欢今天的款式吗?</p>\r\n<p>\r\n	　　快来夸夸<strong>成都美甲学校</strong>的小编吧~</p>\r\n</p>",581,1397);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c180619/15293529C49140-1b357_lit.jpg",1399,1490);
$z[7][4]['name']="litpic";

?>