<li class="infoImg2">
                            <h1></h1>
                            <div>
                                <dl>
                                    <dd>活动价格：￥[field:kbsj/]</dd>
                                    <dd>班级人数：[field:quantity/]人</dd>
                                    <dd>剩余人数：名额仅剩 <span>[field:sy/]</span>人</dd>
                                </dl>
                            </div>
                            <a href="tencent://message/?uin=4000111803" class="baoming">马上报名</a></li>