<li>
                        <div>
                            <a href="[field:arcurl/]"><img src="[field:leavetime/]" alt="[field:title/]"/></a>
                        </div>
                        <div>
                            <p>
                                <span>[field:title/]</span>
                            </p>
                            <p>
                                [field:info/]
                            </p>
                        </div>
                    </li>