<field:leavetime itemname="离校时间（仅添加学员时填写）" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:leavetime>
<field:pic2 itemname="缩略图2（鼠标悬浮时）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic2>
<field:xxxx itemname="详细信息" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xxxx>
