{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}过气潮人是你？美容学校纠正你的NG观点{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p style="color: rgb(0, 0, 0);">
	　　你还在引以为傲地化着不变的妆容吗?你还以为某些看起来很out的妆容和发型是不值一提的么?当心哦，或许你的观念需求update下了，要不变成过气潮人也不自知呢?下面就让<a href="http://www.ql-school.com">成都美甲学校</a>讲解下，哪些彩妆和发型趋向需与时俱进呢?</p>
<p style="color: rgb(0, 0, 0); text-align: center;">
	<img alt="过气潮人是你？美容学校纠正你的NG观点" src="/uploads/allimg/c180619/152935256112F-34W9.jpg" style="width: 354px; height: 437px;" /><br />
	&nbsp;</p>
<p style="color: rgb(0, 0, 0);">
	　　过时观念1：蓝色眼影看起来很cheap，很难hold得住。</p>
<p style="color: rgb(0, 0, 0); text-align: center;">
	<img alt="过气潮人是你？美容学校纠正你的NG观点" src="/uploads/allimg/c180619/152935256149440-454X.jpg" style="width: 498px; height: 443px;" /></p>
<p style="color: rgb(0, 0, 0);">
	　　正解：错!蓝色眼影可以让眼睛看起来更有穿透力。但需留意的是巧妙的选择蓝色。今夏十分盛行马卡龙颜色的眼妆，蓝色也是主流之一，选择粉嫩的蓝色能带来清爽的觉得。一款耀眼并带些微闪光的蓝色眼影则能让你在派对上带来新颖感，T台上也十分喜欢以蓝色眼影作大面积的晕染哦。</p>
<p style="color: rgb(0, 0, 0);">
	　　T台妆容示范：伦敦时装周上Jean-Pierre Braganza的2013春夏成衣秀场的妆容可谓最为吸睛。高光大面积地打亮眼窝，魅惑的蓝色画出眼妆中最重要的局部，蓝色的眼线不断延伸到鼻梁局部，眼角前方的精致勾勒好像蓝色的翅膀，中间的空隙用雪白色的眼影填满，似乎海洋般神秘。</p>
<p style="color: rgb(0, 0, 0);">
	　　过时观念2：法式美甲曾经是前几年的事了，如今早不盛行了。</p>
<p style="color: rgb(0, 0, 0); text-align: center;">
	<img alt="过气潮人是你？美容学校纠正你的NG观点" src="/uploads/allimg/c180619/1529352561RJ0-55561.jpg" style="width: 492px; height: 427px;" /></p>
<p style="color: rgb(0, 0, 0);">
	　　正解：错!两种颜色混搭的美甲又开端盛行了，但前提是需选对颜色。</p>
<p style="color: rgb(0, 0, 0);">
	　　T台妆容示范：</p>
<p style="color: rgb(0, 0, 0);">
	　　Threeasfour，三段式甲油，指尖是银色，中段是灰湖绿色，后段是透明色。</p>
<p style="color: rgb(0, 0, 0);">
	　　Alexis Mabille，模特手涂黑金、红金搭配的法式美甲，在不谐和中寻觅分歧，接着又突破调和的来了一支突兀的红。</p>
<p style="color: rgb(0, 0, 0);">
	　　Titania Inglis，指尖金色的甲油和十指的金属配饰融为了一体!</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/152935256112F-34W9_lit.jpg{/dede:field}
