<dd><a href="[field:arcurl/]"></a><em>[field:pubdate function="GetDateTimeMK(@me)"/]</em></dd>
                        <li>
                            <div>
                                <div class="showDetails">
                                    <h4>代理名</h4>
                                    <span>[field:title/] </span>
                                    <p>简介：[field:info/]/p>
                                </div>
                            </div>
                            <a href=""><img src="{dede:global.cfg_templets_skin/}/images/fantacy1.png" alt=""/></a>
                        </li>