<?php
$z[0]=Array("arcurl","",13,28);
$z[1]=Array("title","",37,51);
$z[2]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}'/>\"); ",53,161);
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",309,324);
$z[4]=Array("title","",333,347);
$z[5]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<img src='{@me['litpic']}'/>\"); ",349,457);
$z[5][4]['runphp']="yes";

?>