<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:kbsj itemname="活动价格" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:kbsj>


<field:quantity itemname="班级人数" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:quantity>

<field:sy itemname="剩余名额" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sy>

<field:price itemname="课程学费" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:price>
