{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}美甲容易致癌？还能继续做美甲了吗？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><p>
	　　<a href="http://www.ql-school.com">成都美甲学校</a>小编收到美眉们来的疑问，那现在给姐妹们聊聊美甲后指甲无法呼吸，容易致癌?指甲上的月牙越多越健康?美甲灯会把手照黑吗?</p>
<p>
	　　美甲后指甲会变得又薄又软吗?</p>
<p>
	　　1、为什么金属饰品会变黑?1美甲后指甲无法呼吸，容易致癌?NO!指甲是不需要呼吸的。指甲跟我们的头发一样，表面没有气孔，不需要呼吸新鲜空气来维持生存。所以，指甲并不需要呼吸，更不会吸收，致癌的说法是错误的。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352a2NW0-61011.jpg" style="width: 615px; height: 504px;" /></p>
<p>
	　　2、指甲上的月牙越多越健康?指甲上的「月牙」确实可以反映健康状况。不过，不是看数量，而是看与之前相比，它最近的变化是不是很大。一般来说，「月牙」的变化可以反映人体的代谢情况，如果与之前自己的月牙相比&mdash;&mdash; 变大、变多：身体代谢加快，要注意甲亢等; 变小、消失：身体代谢变慢，要注意甲减等。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352a311B0-H919.jpg" style="width: 389px; height: 282px;" /></p>
<p>
	　　3、美甲灯会把手照黑吗?</p>
<p>
	　　1，长时间使用UV灯的确会让手变黑美甲灯是使凝胶固化的重要工具。目前常用的美甲灯有UV灯，CCFL灯以及LED灯。UV灯是紫外线灯管的简称。美甲常用的UV灯属于热阴极荧光灯，发出的正是UVA(长波紫外线)，长波紫外线是可以达到真皮深处的，并引起皮肤黑色素沉着，使皮肤变黑变干燥!</p>
<p>
	　　2，手部过于干燥，视觉效果上显黑如果使用的不是UV灯还显手黑的话，那就要看看是不是手部护理方面做得不足了。一般情况下，如果手部太干燥，在照灯后会在视觉上让人感觉又皱又黑。</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352a33D20-X356.jpg" style="width: 555px; height: 518px;" /></p>
<p>
	　　4、美甲后指甲会变得又薄又软吗?NO!指甲薄软分先天和后天。有的人天生就是指甲薄软型，或者工作中常碰水使得指甲变软，对于这些人来说，美甲可以让指甲增强硬度，不容易从边缘裂开。但是，美甲时如果过度不正确地打磨，就很容易导致指甲越磨越薄。总的来说，指甲薄软的问题不能完全归结于美甲.</p>
<center>
	<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352a3D120-c119.jpg" style="width: 545px; height: 444px;" /></center>
<p>
	&nbsp;</p>
<p>
	　　5、为什么金属饰品会变黑呢?原因主要有两个，第一是饰品经过长期摩擦导致变色，第二是饰品被氧化了，封层也是会氧化的哦。不过，正常情况下，如果2天左右饰品就变黑，那就是饰品质量问题了!</p>
<p style="text-align: center;">
	　　<img alt="成都美甲学校" src="/uploads/allimg/c180619/1529352a3a140-10W44.jpg" style="width: 616px; height: 456px;" /></p>
<p>
	　　大家有关于美甲的任何问题都可以咨询我们学校老师哦，喜欢做美甲的你，快来成都群丽美甲学校吧</p>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352a2NW0-61011_lit.jpg{/dede:field}
