{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}如何画好生活妆,让你看起来更显年轻_成都群丽化{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><div>
	&nbsp; &nbsp; &nbsp; &nbsp;在如今化妆最流行的年代各种妆型缤纷呈现在我们的视野中,但是<a href="http://www.ql-school.com/news/xinwen/list_18_1.html#news">生活妆</a>是生活中应用最广泛也最流行的一种妆型。适用于各种年龄、类型的各种人。这种进行局部修饰的淡妆更为真实自然。在化妆的过程中对五官的特点扬长避短，这样化妆既节省时间又使人神采奕奕。下面<a href="http://www.ql-school.com">成都化妆学校</a>对生活妆的简单介绍.</div>
<div>
	&nbsp;一、生活妆的妆面特点</div>
<div>
	&nbsp;1,生活妆用色简洁，在接近原有肤色的基础上，用淡雅自然柔和的色彩适当美化。</div>
<div>
	&nbsp;2,在遵循原有的容貌的基础上，适当修饰、掩盖一些瑕疵，对轮廓、五官、立体感的修饰不能太过于夸张，以清晰、自然为佳。</div>
<div>
	&nbsp;3,化妆程序可根据需要灵活多变。</div>
<div>
	&nbsp;4,应用于自然光线下，手法简洁。</div>
<div>
	&nbsp;二、生化妆的简单步骤</div>
<div>
	&nbsp;1,上粉底：</div>
<div>
	&nbsp; &nbsp; &nbsp; &nbsp;生活化妆中，上粉底用粉底液就可以了，可根据面部的情况选择含油或不含油的。有些MM脸上有痘痘，觉得粉底打厚点可以遮住，如果只是平常的痘印，建议使用遮盖力强的粉底液就可以遮住。但是在涂抹时要注意面部与颈部颜色的统一。</div>
<div>
	&nbsp;2,画眉毛：</div>
<div>
	&nbsp; &nbsp; &nbsp; 在日常妆，我们化妆中用眉刷来修饰眼眉。但是要注意在化妆过程中要使用比眉色浅一号的眉粉，利用眉刷从眉头至眉尾顺向刷过，眉毛的颜色可以与发色协调一致，这样看起来更清新自然。</div>
<div>
	&nbsp;3,画眼线和上眼影:</div>
<div>
	&nbsp; &nbsp; &nbsp; <a href="http://www.ql-school.com/news/xinwen/list_18_1.html#news">生活妆</a>眼部化妆特别强调眼影和眼线的化妆方法。用毛刷清扫眼影粉，使不同颜色的眼影粉刷得更加均匀。然后，在眼险内侧涂上较深的眼影，以衬托出鼻子的线条，这是我们东方人脸型常用的一种化妆技巧。画眼线用黑色眼线笔描画，采用上眼线后2/3，下眼线后1/3的画法，然后用棉花棒或细小的眼影刷轻轻晕开，看起来化妆效果更加自然。</div>
<div>
	&nbsp;4,睫毛的修饰:</div>
<div>
	&nbsp; &nbsp; &nbsp; 生活淡妆清亮的眼神需要纤长的睫毛陪衬想让眼睛看起来更迷人，因此生活淡妆化妆中睫毛膏是必须的。另外化妆时要准备大小不一的两支睫毛夹，先用大号的睫毛夹夹卷整个睫毛，再用小号的睫毛夹将眼角不易夹到的睫毛夹翘。</div>
<div>
	&nbsp;5,涂抹腮红</div>
<div>
	&nbsp; &nbsp; &nbsp; 常妆化妆时涂抹腮红是最后一步最重要的化妆步骤。在脸部涂抹腮红，能使整个脸部显得柔美自然，也能使颧骨显得突出。化妆完成后再用同色腮红轻扫太阳穴部位，便可使面部色彩显得浓淡和谐。涂腮红时腮红色要浅淡，唇色与妆色一致，唇膏涂完后用纸巾吸去嘴唇上的油脂．使唇色自然、伏贴。</div>
<div>
	&nbsp;以上就是我们<a href="http://www.ql-school.com">成都化妆学校</a>对生活妆的简单的介绍,好的生活妆不仅让人看起来神采奕奕看起来更显年轻</div>
</p>{/dede:field}
{dede:field name='litpic'}{/dede:field}
