{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}成都化妆培训,快速掌握化妆技巧{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><div>
	&nbsp;</div>
<div>
	&nbsp; 化妆，是人体装饰艺术的组成部分，也是日常生活、交际礼仪中不可缺少的条件。仪容化妆应包括头发的保养护理与修饰，皮肤的保养护理与化妆等内容，<a href="http://www.ql-school.com">成都群丽化妆学校</a>和你介绍女士面部化妆的基本知识。 &nbsp; &nbsp;化妆是生活中的一门艺术，适度而得体的化妆，可以体现女性端庄、温柔、美丽、大方的独特气质，达到巧夺天工的效果。化妆是用化妆品及艺术描绘手法来达到装扮美化自己的目的。化妆一定适当，要恰如其分，也就是说懂得化妆才能很好地掩盖人的缺点，甚至缺陷，更好地体现人的五官的优点，让人更美，充满信心，充满魅力。社交场合，得体适度的化妆，既是自尊自信的表现，又体现了对他人的尊重。 &nbsp;</div>
<div style="text-align: center;">
	<img alt="化妆培训" src="/uploads/allimg/c180619/1529352X442550-125H6.jpg" style="width: 500px; height: 284px;" /></div>
<div>
	&nbsp;</div>
<div>
	一、基本化妆的工具及其作用&nbsp;</div>
<div>
	&nbsp;⑴眉刀--修眉毛的工具之一，用于刮除多余的眉毛。 &nbsp;</div>
<div>
	&nbsp;<br />
	⑵眉剪--修眉毛的工具之一，用于修剪过长的眉毛。 &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	⑶眉梳--状如精细的小梳，用于梳理杂乱的眉毛，也可以用于梳睫毛。 &nbsp; &nbsp;</div>
<div>
	&nbsp;<br />
	⑷眉刷--刷毛坚硬，扁平排列，用于刷眉粉等。 &nbsp; &nbsp;</div>
<div>
	&nbsp;<br />
	⑸睫毛夹--用于夹睫毛，使睫毛弯曲。 &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	⑹眼线刷笔--尖头笔刷，形如毛笔，笔尖细而硬，用于粘取油彩或眼线液描画眼线。 &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	⑺眼影刷笔--扁平小笔刷，用于刷影粉，另有一种海绵棒式，用于化妆眼部细微结构上的眼影。 &nbsp; &nbsp;</div>
<div>
	<br />
	⑻鼻影刷笔--刷笔略粗，用于刷鼻影色。 &nbsp; &nbsp;</div>
<div>
	<br />
	⑼腮红刷笔--刷笔毛比较软而且厚，用于刷腮红。 &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	⑽散粉刷笔--扁平或圆形大刷笔，用于刷散粉定妆。 &nbsp;&nbsp;</div>
<div>
	<br />
	&nbsp;⑾粉扑--由海绵或绒布制成，用于扑打粉底或粉饼。 &nbsp;&nbsp;</div>
<div style="text-align: center;">
	<img alt="化妆培训" src="/uploads/allimg/c180619/1529352X4LT0-13MF.jpg" style="width: 376px; height: 345px;" /></div>
<div>
	二、 化妆的基本步骤是： &nbsp;&nbsp;</div>
<div>
	&nbsp; 1、洗面; &nbsp; &nbsp;</div>
<div>
	&nbsp;<br />
	2、拍收缩水(化妆水); &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	3、搽营养霜; &nbsp; &nbsp;</div>
<div>
	&nbsp;<br />
	4、底妆 ①上粉底 ②上粉饼 &nbsp; &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	5、第一次定妆(涂干粉); &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	6、修眉; &nbsp;&nbsp;</div>
<div>
	<br />
	7、眼部化妆 ①眉 ②眼影 ③眼线 ④睫毛膏 &nbsp; &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	8、鼻侧影; &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	10、涂腮红; &nbsp; &nbsp;</div>
<div>
	<br />
	11、化眼睫毛; &nbsp;&nbsp;</div>
<div>
	&nbsp;<br />
	12、嘴部化妆 ①唇线 ②唇膏&nbsp;</div>
<div>
	&nbsp;<br />
	13、定妆 &nbsp; &nbsp;&nbsp;<br />
	想快速掌握化妆技巧就来<a href="http://www.ql-school.com">成都群丽化妆学校</a>联系热线028-85831188</div>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352X442550-125H6_lit.jpg{/dede:field}
