{dede:field name='keywords'}成都学化妆,成都化妆,成都{/dede:field}
{dede:field name='description'}成都锦江区群丽化妆培训学校13年学校提倡良心教学。学校以整体形象设计、化妆培训、美甲培训、彩妆培训为主要.小班教学,一对一指导,价格合适,地铁旁边.拥有众多资深化妆师、美容{/dede:field}
{dede:field name='title'}新娘妆基础，你掌握多少呢？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><div>
	　　结婚对很多人来说是人生中的一件大事，在精致婚纱礼服下的新娘就成为了整个婚礼中最受瞩目的焦点。所以，新娘化妆就区别去一般普通化妆，更显得格外慎重。不仅要注重脸型、肤色的修饰，还要注重化妆的整体表现尤其要自然、高雅和喜气，而且更要使妆效能持久、不脱落。总之整体而言，新娘的妆扮，特别注重整体美感的呈现。下面成都化妆学校就简单详解一下新娘妆的画法。</div>
<div>
	　　一、要准备的原料及工具</div>
<div>
	　　唇膏</div>
<div>
	　　唇刷</div>
<div>
	　　大号粉刷</div>
<div>
	　　假睫毛</div>
<div>
	　　眉粉</div>
<div>
	　　膏状腮红</div>
<div>
	　　二、简单步骤及方法</div>
<div>
	　　1</div>
<div>
	　　粉底</div>
<div>
	　　打粉底时要注意发际、唇部、鼻角、嘴角、脖子等处要均匀的擦拭。选取粉底颜色时可比肤色稍微浅一点，切记颜色不可太白，以粉红色为最佳，这样可以营造出一种喜气</div>
<div style="text-align: center;">
	<img alt="新娘妆知识" src="/uploads/allimg/c180619/1529352GZ5430-L2F.jpg" style="width: 486px; height: 326px;" /></div>
<div>
	　　2</div>
<div>
	　　蜜粉</div>
<div>
	　　我们先以粉饼薄薄施一层，再以透明蜜粉轻轻擦上一层，注意都要涂抹均匀，使粉底更固定。蜜粉可选择透明感较好的，使脸部看起来更亮，但不要涂抹过多。</div>
<div>
	　　3</div>
<div>
	　　瑕疵修饰</div>
<div>
	　　用浅色的粉底擦拭于黑眼圈及额头处可以加深脸部的明亮度，这样可以使五官更立体。对于斑点、疤痕、鼻梁阴影处，都要细心修饰。想要遮盖黑眼圈或黑斑时，我们先用盖斑膏轻轻点在欲遮盖的地方，再用粉扑涂抹匀即可。</div>
<div>
	　　4</div>
<div>
	　　腮红</div>
<div>
	　　刷上少许腮红，并以余粉修饰脸型，使的新娘妆更柔和且喜气。腮红要沿着颧骨往下画，脸型长者，可以往鼻中方向画；脸型短者，可以往嘴角方向画。</div>
<div style="text-align: center;">
	<img alt="新娘妆基础" src="/uploads/allimg/c180619/1529352G95S40-XA8.jpg" style="width: 760px; height: 476px;" /></div>
<div>
	　　5</div>
<div>
	　　眉毛</div>
<div>
	　　划出柔和自然的眉型，再以眉刷刷匀，亦可以刷上少许与发色相近的眼影粉。</div>
<div>
	　　6</div>
<div>
	　　眼影</div>
<div>
	　　均匀刷上带有喜气之色眼影，要表现柔美及立体感。眼影可选择较喜气的粉红、紫色、蓝色等色系，皮肤较黑的新娘用橘红、金色、咖啡色系可使五官看起来更柔和。</div>
<div>
	　　7</div>
<div>
	　　眼线</div>
<div>
	　　描绘出眼线，再以用眼线液强调眼神。新娘在画眼影时候，可以先用眼线笔描完后，为了使眼影不易脱妆并更具立体感，可以用眼线液再描一次。</div>
<div>
	　　8</div>
<div>
	　　唇部</div>
<div>
	　　依据新娘的肤色，唇型而设定，皮肤白者，可选用鲜红、玫瑰红。肤色黑者或嘴型大者，则不宜浅色唇膏，先用唇线笔描出唇型，再涂上唇膏，最后在上一层亮光唇油，可使嘴唇看起来娇艳欲滴。</div>
<div style="text-align: center;">
	<img alt="新娘妆基础" src="/uploads/allimg/c180619/1529352Gc1K0-b260.jpg" style="width: 652px; height: 429px;" /></div>
<div>
	　　通过以上新娘妆的画法，可以打造出迷人的妆容。但是还有一些我们化妆师需要注意的一些地方，如果你对这一方面比较喜爱但不知如何入手可以来成都群丽化妆学校了解更多，或者拨打热线028-85831188</div>
</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180619/1529352GZ5430-L2F_lit.jpg{/dede:field}
