<?php
$z[0]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Profile</a></li>\n        ",738,866);
$z[0][4]['typeid']="8";
$z[1]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Culture</a></li>\n        ",928,1056);
$z[1][4]['typeid']="9";
$z[2]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Environment</a></li>\n        ",1091,1224);
$z[2][4]['typeid']="10";
$z[3]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Honor</a></li>\n        ",1236,1363);
$z[3][4]['typeid']="11";
$z[4]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Professional Makeup</a></li>\n        ",1451,1585);
$z[4][4]['typeid']="12";
$z[5]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] •  Beauty Professional</a></li>\n        ",1647,1782);
$z[5][4]['typeid']="13";
$z[6]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Nail Professional</a></li>\n        ",1817,1949);
$z[6][4]['typeid']="14";
$z[7]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Training</a></li>\n        ",1961,2084);
$z[7][4]['typeid']="15";
$z[8]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Openning Information</a></li>\n        ",2210,2345);
$z[8][4]['typeid']="16";
$z[9]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] •  Latest News</a></li>\n        ",2407,2534);
$z[9][4]['typeid']="17";
$z[10]=Array("type","\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School News</a></li>\n        ",2569,2695);
$z[10][4]['typeid']="18";

?>