<?php
$z[0]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Profile</a></li>\r\n        ",759,889);
$z[0][4]['typeid']="8";
$z[1]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Culture</a></li>\r\n        ",952,1082);
$z[1][4]['typeid']="9";
$z[2]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Environment</a></li>\r\n        ",1118,1253);
$z[2][4]['typeid']="10";
$z[3]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Honor</a></li>\r\n        ",1266,1395);
$z[3][4]['typeid']="11";
$z[4]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Professional Makeup</a></li>\r\n        ",1489,1625);
$z[4][4]['typeid']="12";
$z[5]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] •  Beauty Professional</a></li>\r\n        ",1688,1825);
$z[5][4]['typeid']="13";
$z[6]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Nail Professional</a></li>\r\n        ",1861,1995);
$z[6][4]['typeid']="14";
$z[7]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Training</a></li>\r\n        ",2008,2133);
$z[7][4]['typeid']="15";
$z[8]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Openning Information</a></li>\r\n        ",2265,2402);
$z[8][4]['typeid']="16";
$z[9]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] •  Latest News</a></li>\r\n        ",2465,2594);
$z[9][4]['typeid']="17";
$z[10]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School News</a></li>\r\n        ",2630,2758);
$z[10][4]['typeid']="18";

?>