<?php
$z[0]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Profile</a></li>                             \r\n                    ",1028,1215);
$z[0][4]['typeid']="8";
$z[1]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Culture</a></li>                       \r\n                    ",1290,1471);
$z[1][4]['typeid']="9";
$z[2]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Environment</a></li>                       \r\n                    ",1519,1705);
$z[2][4]['typeid']="10";
$z[3]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Honor</a></li>                       \r\n                    ",1730,1910);
$z[3][4]['typeid']="11";
$z[4]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • Professional Makeup</a></li>                             \r\n                    ",2114,2307);
$z[4][4]['typeid']="12";
$z[5]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] •  Beauty Professional</a></li>                       \r\n                    ",2382,2570);
$z[5][4]['typeid']="13";
$z[6]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • Nail Professional</a></li>                       \r\n                    ",2618,2803);
$z[6][4]['typeid']="14";
$z[7]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • Training</a></li>                       \r\n                    ",2828,3004);
$z[7][4]['typeid']="15";
$z[8]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • Openning Information</a></li>                             \r\n                    ",3234,3428);
$z[8][4]['typeid']="16";
$z[9]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] •  Latest News</a></li>                       \r\n                    ",3503,3683);
$z[9][4]['typeid']="17";
$z[10]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • School News</a></li>                       \r\n                    ",3731,3910);
$z[10][4]['typeid']="18";
$z[11]=Array("type","\r\n                        <li><a href=\"[field:typeurl/]\">[field:typename/] • Employment Information</a></li>                       \r\n                    ",3935,4125);
$z[11][4]['typeid']="19";

?>