<?php
$z[0]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Profile</a></li>\r\n        ",760,890);
$z[0][4]['typeid']="8";
$z[1]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Culture</a></li>\r\n        ",953,1083);
$z[1][4]['typeid']="9";
$z[2]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Environment</a></li>\r\n        ",1119,1254);
$z[2][4]['typeid']="10";
$z[3]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School Honor</a></li>\r\n        ",1267,1396);
$z[3][4]['typeid']="11";
$z[4]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Professional Makeup</a></li>\r\n        ",1490,1626);
$z[4][4]['typeid']="12";
$z[5]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] •  Beauty Professional</a></li>\r\n        ",1689,1826);
$z[5][4]['typeid']="13";
$z[6]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Nail Professional</a></li>\r\n        ",1862,1996);
$z[6][4]['typeid']="14";
$z[7]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Training</a></li>\r\n        ",2009,2134);
$z[7][4]['typeid']="15";
$z[8]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • Openning Information</a></li>\r\n        ",2266,2403);
$z[8][4]['typeid']="16";
$z[9]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] •  Latest News</a></li>\r\n        ",2466,2595);
$z[9][4]['typeid']="17";
$z[10]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/] • School News</a></li>\r\n        ",2631,2759);
$z[10][4]['typeid']="18";

?>