<?php
$z[0]=Array("global","",265,297);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",469,501);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",808,840);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",907,939);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1006,1038);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1105,1137);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1204,1236);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1368,1400);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("channelartlist","\r\n                     <li>\r\n                         <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                         <dl>\r\n                          {dede:channel type='son' noself='yes'}\r\n                          <dd><a href=\"[field:typelink/]\">[field:typename/]</a></d>                         \r\n                          {/dede:channel}                         \r\n                         <!-- {dede:sql sql='Select * from dede_arctype where reid=~id~ and isHidden=0 ORDER BY id limit 0,7'}\r\n                             <dd><a href=\"[field:typedir/]\">[field:typename/]</a></dd>\r\n                         {/dede:sql} -->\r\n                         </dl>\r\n                     </li>                \r\n                ",1580,2398);
$z[8][4]['typeid']="top";
$z[8][4]['row']="8";

?>