<?php
$z[0]=Array("global","",267,299);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",471,503);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",876,908);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channelartlist","\r\n                     <li>\r\n                         <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                         <dl>\r\n                         {dede:channel type='son' noself='yes'}\r\n                          <dd><a href=\"[field:typelink/]\">[field:typename/]</a></d>                         \r\n                          {/dede:channel}    \r\n                         </dl>\r\n                     </li>                \r\n                ",1092,1630);
$z[3][4]['typeid']="top";
$z[3][4]['row']="8";

?>