<?php
$z[0]=Array("arclist","\n                    <li>\n                        <div>\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:leavetime/]\" alt=\"[field:title/]\"/></a>\n                        </div>\n                        <div>\n                            <p>\n                                <span>[field:title/]</span>\n                            </p>\n                            <p>\n                                [field:info/]\n                            </p>\n                        </div>\n                    </li>\n                    ",10838,11455);
$z[0][4]['addfields']="leavetime";
$z[0][4]['channelid']="18";
$z[0][4]['row']="100";

?>