<?php
$z[0]=Array("global","",233,268);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",280,313);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",348,380);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channelartlist","\n		<div class=\"t2\">\n			<div class=\"t2-1\">\n				<h2 class=\"t3\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></h2>\n				<div class=\"t4\">{dede:channel type=\"son\"}<a href=\"[field:typeurl/]\">[field:typename/]</a>{/dede:channel}</div>\n			</div>\n			<div class=\"t2-2\">\n				{dede:arclist row=100}\n					<p><span class='t5'>发布日期：[field:pubdate function=\"GetDateMK(@me)\" /]</span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></p>\n					{/dede:arclist}\n			</div>\n		</div>\n		",892,1444);
$z[3][4]['type']="top";

?>