<?php
$z[0]=Array("global","",236,271);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",284,317);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",354,386);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channelartlist","\r\n		<div class=\"t2\">\r\n			<div class=\"t2-1\">\r\n				<h2 class=\"t3\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></h2>\r\n				<div class=\"t4\">{dede:channel type=\"son\"}<a href=\"[field:typeurl/]\">[field:typename/]</a>{/dede:channel}</div>\r\n			</div>\r\n			<div class=\"t2-2\">\r\n				{dede:arclist row=100}\r\n					<p><span class='t5'>发布日期：[field:pubdate function=\"GetDateMK(@me)\" /]</span><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></p>\r\n					{/dede:arclist}\r\n			</div>\r\n		</div>\r\n		",914,1478);
$z[3][4]['type']="top";

?>