/**
 * Created with JetBrains PhpStorm.
 * User: xuheng
 * Date: 12-8-8
 * Time: 下午2:00
 * To change this template use File | Settings | File Templates.
 */
var templates = [
    {
        "pre":"pre0.png",
        'title':lang.blank,
        'preHtml':'<section style=\"margin-top:2em;text-align:center;padding:0;border:medium none;line-height:1.4;box-sizing:border-box;margin-bottom:1em\"><hr style=\"border-top-width:0;border-style:none;height:1px;background-color:#DD8B00;color:#d5d5d5;margin:-.7em 0\"><span style=\"font-size:14px\"><strong><span class=\"yead1\" style=\"background-color:#DD8B00;border-color:#548dd4;color:#fff;font-family:inherit;font-weight:inherit;padding:8px 23px;text-decoration:inherit\">请输入你的文字<\/span><\/strong><\/span><\/section>\n',
        "html":'<section style=\"margin-top:2em;text-align:center;padding:0;border:medium none;line-height:1.4;box-sizing:border-box;margin-bottom:1em\"><hr style=\"border-top-width:0;border-style:none;height:1px;background-color:#DD8B00;color:#d5d5d5;margin:-.7em 0\"><span style=\"font-size:14px\"><strong><span class=\"yead1\" style=\"background-color:#DD8B00;border-color:#548dd4;color:#fff;font-family:inherit;font-weight:inherit;padding:8px 23px;text-decoration:inherit\">请输入你的文字<\/span><\/strong><\/span><\/section>\n'

    },
    {
        "pre":"pre2.png",
        'title':lang.resume,
        'preHtml':'<section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"position:static;box-sizing:border-box\"><section style=\"margin-top:10px;margin-bottom:10px;position:static;box-sizing:border-box\"><section style=\"padding-left:1em;padding-right:1em;display:inline-block;text-align:center;box-sizing:border-box\"><p style=\"margin:0;padding:0;box-sizing:border-box\"><span style=\"display:inline-block;padding:.3em .5em;border-radius:.5em;background-color:#af0000;font-size:14px;color:#fff;box-sizing:border-box\"><strong style=\"box-sizing:border-box\">标题：<\/strong><\/span><\/p><\/section><section style=\"border:1px solid #c0c8d1;margin-top:-1em;padding:20px 10px 10px;background-color:#efefef;text-align:center;box-sizing:border-box\"><section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"box-sizing:border-box\"><section style=\"position:static;box-sizing:border-box\"><section style=\"text-align:left;font-size:14px;box-sizing:border-box\"><p style=\"margin:0;padding:0;box-sizing:border-box\">&nbsp; &nbsp; &nbsp; &nbsp;内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容<\/p><\/section><\/section><\/section><\/section><\/section><\/section>\n',
        "html":'<section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"position:static;box-sizing:border-box\"><section style=\"margin-top:10px;margin-bottom:10px;position:static;box-sizing:border-box\"><section style=\"padding-left:1em;padding-right:1em;display:inline-block;text-align:center;box-sizing:border-box\"><p style=\"margin:0;padding:0;box-sizing:border-box\"><span style=\"display:inline-block;padding:.3em .5em;border-radius:.5em;background-color:#af0000;font-size:14px;color:#fff;box-sizing:border-box\"><strong style=\"box-sizing:border-box\">标题：<\/strong><\/span><\/p><\/section><section style=\"border:1px solid #c0c8d1;margin-top:-1em;padding:20px 10px 10px;background-color:#efefef;text-align:center;box-sizing:border-box\"><section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"box-sizing:border-box\"><section style=\"position:static;box-sizing:border-box\"><section style=\"text-align:left;font-size:14px;box-sizing:border-box\"><p style=\"margin:0;padding:0;box-sizing:border-box\">&nbsp; &nbsp; &nbsp; &nbsp;内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容<\/p><\/section><\/section><\/section><\/section><\/section><\/section>\n'

    },
    {
        "pre":"pre3.png",
        'title':lang.richText,
        'preHtml':'<section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"position:static;box-sizing:border-box\"><section style=\"margin:.5em 0;position:static;box-sizing:border-box\"><section style=\"border-radius:.5em .5em 0 0;background-color:#af0000;box-sizing:border-box\"><section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"box-sizing:border-box\"><section style=\"position:static;box-sizing:border-box\"><section style=\"font-size:14px;padding:5px 10px;text-align:center;color:#fff;box-sizing:border-box\"><p style=\"margin:0;padding:0;box-sizing:border-box\"><strong style=\"box-sizing:border-box\">温馨提示<\/strong><\/p><\/section><\/section><\/section><\/section><section style=\"border-radius:0 0 .5em .5em;border-right:1px solid #c0c8d1;border-bottom:1px solid #c0c8d1;border-left:1px solid #c0c8d1;border-image:initial;border-top:none #c0c8d1;box-sizing:border-box\"><section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"box-sizing:border-box\"><section style=\"position:static;box-sizing:border-box\"><section style=\"text-align:center;padding:5px 10px;font-size:14px;box-sizing:border-box\"><p style=\"text-align:left;margin:0;padding:0;box-sizing:border-box\"><span style=\"text-shadow:#fff 2px 0 2px;box-sizing:border-box\">&nbsp; &nbsp; &nbsp; &nbsp;内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容<\/span><\/p><\/section><\/section><\/section><\/section><\/section><\/section>\n',
        "html":'<section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"position:static;box-sizing:border-box\"><section style=\"margin:.5em 0;position:static;box-sizing:border-box\"><section style=\"border-radius:.5em .5em 0 0;background-color:#af0000;box-sizing:border-box\"><section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"box-sizing:border-box\"><section style=\"position:static;box-sizing:border-box\"><section style=\"font-size:14px;padding:5px 10px;text-align:center;color:#fff;box-sizing:border-box\"><p style=\"margin:0;padding:0;box-sizing:border-box\"><strong style=\"box-sizing:border-box\">温馨提示<\/strong><\/p><\/section><\/section><\/section><\/section><section style=\"border-radius:0 0 .5em .5em;border-right:1px solid #c0c8d1;border-bottom:1px solid #c0c8d1;border-left:1px solid #c0c8d1;border-image:initial;border-top:none #c0c8d1;box-sizing:border-box\"><section class=\"Powered-by-XIUMI V5\" powered-by=\"xiumi.us\" style=\"box-sizing:border-box\"><section style=\"position:static;box-sizing:border-box\"><section style=\"text-align:center;padding:5px 10px;font-size:14px;box-sizing:border-box\"><p style=\"text-align:left;margin:0;padding:0;box-sizing:border-box\"><span style=\"text-shadow:#fff 2px 0 2px;box-sizing:border-box\">&nbsp; &nbsp; &nbsp; &nbsp;内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容内容<\/span><\/p><\/section><\/section><\/section><\/section><\/section><\/section>\n'
    },
    {
        "pre":"pre4.png",
        'title':lang.sciPapers,
        'preHtml':'<section class="aeditorg" style="position:static;box-sizing:border-box;border:0 none;padding:0"><section class="aeditorh" style="text-align:right"><section class="aeditori" style="display:inline-block;width:65%;margin-top:.7em;padding:1em;border-top-left-radius:1em;border-top-right-radius:1em;border-bottom-right-radius:1em;border-bottom-left-radius:1em;text-align:left;font-size:1em;color:#fff;margin-right:-.4em;background-color:#17afb0;border-color:#fff"><div class="aeditorj" style="color:inherit"><a href="javascript:void(0);return false;" onclick="return openZoosUrl(),!1" target="_blank"><span class="aeditork">请输入文字？</span></a></div></section><section class="aeditorl" style="display:inline-block;margin-top:1.2em;vertical-align:top;width:20px;padding-top:10px;padding-bottom:10px;color:inherit"><section class="aeditorm" style="margin:0;padding:0;border-left-width:20px;border-right-width:0;border-left-style:solid;border-left-color:#17afb0;border-right-color:#17afb0;display:inline-block;height:1px;width:10px;vertical-align:top;float:left;color:inherit;border-bottom-width:12px!important;border-top-style:solid!important;border-bottom-style:solid!important;border-top-color:transparent!important;border-bottom-color:transparent!important">&nbsp;</section></section><section class="aeditorn" style="display:inline-block;line-height:20px;vertical-align:top;margin-top:.5em;text-align:center;color:inherit"><div><a href="javascript:void(0);return false;" onclick="return openZoosUrl(),!1" target="_blank"><img class="aeditoro" style="vertical-align:top;width:40px!important;height:auto!important" src="/images/yishengico.png"></a></div><div><a href="javascript:void(0);return false;" onclick="return openZoosUrl(),!1" target="_blank"><span class="aeditorp" style="font-size:12px;color:#000">点击咨询</span></a></div></section></section></section>',
        'html':'<section class="aeditorg" style="position:static;box-sizing:border-box;border:0 none;padding:0"><section class="aeditorh" style="text-align:right"><section class="aeditori" style="display:inline-block;width:65%;margin-top:.7em;padding:1em;border-top-left-radius:1em;border-top-right-radius:1em;border-bottom-right-radius:1em;border-bottom-left-radius:1em;text-align:left;font-size:1em;color:#fff;margin-right:-.4em;background-color:#17afb0;border-color:#fff"><div class="aeditorj" style="color:inherit"><a href="javascript:void(0);return false;" onclick="return openZoosUrl(),!1" target="_blank"><span class="aeditork">请输入文字？</span></a></div></section><section class="aeditorl" style="display:inline-block;margin-top:1.2em;vertical-align:top;width:20px;padding-top:10px;padding-bottom:10px;color:inherit"><section class="aeditorm" style="margin:0;padding:0;border-left-width:20px;border-right-width:0;border-left-style:solid;border-left-color:#17afb0;border-right-color:#17afb0;display:inline-block;height:1px;width:10px;vertical-align:top;float:left;color:inherit;border-bottom-width:12px!important;border-top-style:solid!important;border-bottom-style:solid!important;border-top-color:transparent!important;border-bottom-color:transparent!important">&nbsp;</section></section><section class="aeditorn" style="display:inline-block;line-height:20px;vertical-align:top;margin-top:.5em;text-align:center;color:inherit"><div><a href="javascript:void(0);return false;" onclick="return openZoosUrl(),!1" target="_blank"><img class="aeditoro" style="vertical-align:top;width:40px!important;height:auto!important" src="/images/yishengico.png"></a></div><div><a href="javascript:void(0);return false;" onclick="return openZoosUrl(),!1" target="_blank"><span class="aeditorp" style="font-size:12px;color:#000">点击咨询</span></a></div></section></section></section>'
    },
    {
        "pre":"pre5.png",
        'title':lang.sciPapers,
        'preHtml':'<section class="abrushi" style="position:static;box-sizing:border-box;border:0 none;padding:8px 0"><h2 class="abrushj" style="margin:8px 0 0;padding:0;font-weight:700;font-size:16px;line-height:28px;max-width:100%;color:#59c3f9;min-height:32px;border-bottom-width:1.5px;border-bottom-style:solid;border-color:#59c3f9;text-align:justify"><span class="abrushk" style="background-color:#59C3F9;color:#FFF;display:block;float:left;line-height:20px;margin:0 8px 0 0;max-width:100%;padding:4px 10px;word-wrap:break-word!important">1</span><strong class="abrushl" style="border-color:#59c3f9;color:inherit;font-size:.6rem">请输入你文字<></h2><ction>',
        'html':'<section class="abrushi" style="position:static;box-sizing:border-box;border:0 none;padding:8px 0"><h2 class="abrushj" style="margin:8px 0 0;padding:0;font-weight:700;font-size:16px;line-height:28px;max-width:100%;color:#59c3f9;min-height:32px;border-bottom-width:1.5px;border-bottom-style:solid;border-color:#59c3f9;text-align:justify"><span class="abrushk" style="background-color:#59C3F9;color:#FFF;display:block;float:left;line-height:20px;margin:0 8px 0 0;max-width:100%;padding:4px 10px;word-wrap:break-word!important">1</span><strong class="abrushl" style="border-color:#59c3f9;color:inherit;font-size:.6rem">请输入你文字<></h2><ction>'
    }
];