document.writeln("<script src=\"/laydate/laydate.js\"></script>");
var cdzzz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:频繁眨眼" id="diagnose_0"> <a>频繁眨眼</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:皱鼻噘嘴" id="diagnose_1"> <a>皱鼻噘嘴</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:摇头耸肩" id="diagnose_2"> <a>摇头耸肩</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:清嗓子" id="diagnose_3"> <a>清嗓子</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:吐口水" id="diagnose_4"> <a>吐口水</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:甩手踢腿" id="diagnose_4"> <a>甩手踢腿</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*抽动症*/
var dxzz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:四肢抽搐" id="diagnose_0"> <a>四肢抽搐</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:口吐白沫" id="diagnose_1"> <a>口吐白沫</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:面色青紫" id="diagnose_2"> <a>面色青紫</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:翻白眼" id="diagnose_2"> <a>翻白眼</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:意识障碍" id="diagnose_2"> <a>意识障碍</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*癫痫*/
var ddzzz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:多动" id="diagnose_0"> <a>多动</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:学习困难" id="diagnose_1"> <a>学习困难</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:注意力不集中" id="diagnose_2"> <a>注意力不集中</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:脾气暴躁" id="diagnose_2"> <a>脾气暴躁</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:不听管教" id="diagnose_2"> <a>不听管教</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:无危险意识" id="diagnose_2"> <a>无危险意识</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*多动症 注意力不集中 学习困难*/
var zylbjzz = '<div class="nr_n1"><p>1、孩子出现状况的主要原因？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子出现状况的主要原因:生理原因" id="diagnose_0"> <a>生理原因</a></label><label><input type="checkbox" name="zyzz" value="孩子出现状况的主要原因:病理原因" id="diagnose_1"> <a>病理原因</a></label><label><input type="checkbox" name="zyzz" value="孩子出现状况的主要原因:环境原因" id="diagnose_2"> <a>环境原因</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*注意力不集中*/
var xxkn = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:多动" id="diagnose_0"> <a>多动</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:学习困难" id="diagnose_1"> <a>学习困难</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:注意力不集中" id="diagnose_2"> <a>注意力不集中</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:脾气暴躁" id="diagnose_2"> <a>脾气暴躁</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:不听管教" id="diagnose_2"> <a>不听管教</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:无危险意识" id="diagnose_2"> <a>无危险意识</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/* 学习困难*/
var gtst = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:前庭平衡功能失常" id="diagnose_0"> <a>前庭平衡功能失常</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:视觉感不良" id="diagnose_1"> <a>视觉感不良</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:触觉过分敏感" id="diagnose_2"> <a>触觉过分敏感</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:听觉感不良" id="diagnose_2"> <a>听觉感不良</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:本体感失调" id="diagnose_2"> <a>本体感失调</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:动作协调不良" id="diagnose_2"> <a>动作协调不良</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/* 感统失调*/
var fychzz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:运动发育落后" id="diagnose_0"> <a>运动发育落后</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:语言发育迟缓" id="diagnose_1"> <a>语言发育迟缓</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:智力发育落后" id="diagnose_2"> <a>智力发育落后</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*发育迟缓*/
var ntzz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:进食困难" id="diagnose_0"> <a>进食困难</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:拇指内收" id="diagnose_1"> <a>拇指内收</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:姿势异常" id="diagnose_2"> <a>姿势异常</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:肌张力异常" id="diagnose_2"> <a>肌张力异常</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:脚尖着地" id="diagnose_2"> <a>脚尖着地</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*脑瘫*/
var xzszz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><div class="xingbie"><p>女孩：</p><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:女：乳房发育/硬结" id="diagnose_0"> <a>乳房发育/硬结</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:女：毛发生长" id="diagnose_1"> <a>毛发生长</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:女：月经提前" id="diagnose_2"> <a>月经提前</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:女：骨龄偏大" id="diagnose_3"> <a>骨龄偏大</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:女：其他" id="diagnose_4"> <a>其他</a></label></p></div><div class="cl"></div><div class="xingbie"><p class="nanhai">男孩：</p><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:男孩：喉结变大" id="diagnose_0"> <a>喉结变大</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:男孩：胡须生长" id="diagnose_1"> <a>胡须生长</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:男孩：声音变粗" id="diagnose_2"> <a>声音变粗</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:男孩：睾丸增大" id="diagnose_3"> <a>睾丸增大</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:男孩：其他" id="diagnose_4"> <a>其他</a></label></p></div></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1个月以内" id="diagnose_0"> <a>1个月以内</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*性早熟*/
var axzz = '<div class="nr_n1"><p>1、运动状况</p><div class="nr_n1_dx"><p><label><input type="radio" name="zyzz" value="运动状况:偶尔" id="diagnose_0"> <a>偶尔</a></label><label><input type="radio" name="zyzz" value="运动状况:经常" id="diagnose_1"> <a>经常</a></label><label><input type="radio" name="zyzz" value="运动状况:从不" id="diagnose_2"> <a>从不</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、睡眠情况？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="睡眠情况：5小时以内" id="diagnose_0"> <a>5小时以内</a></label><label><input type="radio" name="duojiu" value="睡眠情况： 6到8小时" id="diagnose_1"> <a>6到8小时</a></label><label><input type="radio" name="duojiu" value="睡眠情况：8小时以上" id="diagnose_2"> <a>8小时以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、饮食情况？</p><div class="nr_n1_dx"><p><label><input type="radio" name="ks" value="饮食情况:荤素平衡" id="diagnose_0"> <a>荤素平衡</a></label><label><input type="radio" name="ks" value="饮食情况：偏食" id="diagnose_1"> <a>偏食</a></label><label><input type="radio" name="ks" value="饮食情况：随便吃" id="diagnose_2"> <a>随便吃</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、目前采用过哪些增高方法</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前采用过哪些增高方法：饮食营养" id="diagnose_0"> <a>饮食营养</a></label><label><input type="checkbox" name="ks" value="目前采用过哪些增高方法：运动锻炼" id="diagnose_1"> <a>运动锻炼</a></label><label><input type="checkbox" name="ks" value="目前采用过哪些增高方法：增高药" id="diagnose_2"> <a>增高药</a></label><label><input type="checkbox" name="ks" value="目前采用过哪些增高方法： 注射生长激素" id="diagnose_3"> <a>注射生长激素</a></label><label><input type="checkbox" name="ks" value="目前采用过哪些增高方法：中药" id="diagnose_4"> <a>中药</a></label><label><input type="checkbox" name="ks" value="目前采用过哪些增高方法：未采用增高方法" id="diagnose_4"> <a>未采用增高方法</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>5、您想了解的是</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您想了解的是:身高预测" id="diagnose_0"> <a>身高预测</a></label><label><input type="checkbox" name="ks" value="您想了解的是:长高方法" id="diagnose_1"> <a>长高方法</a></label><label><input type="checkbox" name="ks" value="目前采用过哪些增高方法：增高药" id="diagnose_2"> <a>增高费用</a></label><label><input type="checkbox" name="ks" value="您想了解的是:增高效果" id="diagnose_3"> <a>增高效果</a></label><label><input type="checkbox" name="ks" value="您想了解的是:其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*矮小症*/
var ynzzz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:晚上尿床" id="diagnose_0"> <a>晚上尿床</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:白天尿裤子" id="diagnose_1"> <a>白天尿裤子</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:尿味大" id="diagnose_2"> <a>尿味大</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:免疫力低" id="diagnose_3"> <a>免疫力低</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:睡眠昏沉" id="diagnose_4"> <a>睡眠昏沉</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:受天气影响尿床" id="diagnose_4"> <a>受天气影响尿床</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"> <a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"> <a>3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"> <a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"> <a>1年以上</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"> <a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"> <a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"> <a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"> <a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"> <a>未接受过治疗</a></label></p></div></div><div style="clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"> <a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"> <a>治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"> <a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"> <a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"> <a>其他事宜</a></label></p></div></div>';
/*遗尿症*/
var zbzzz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:不爱说话" id="diagnose_0"><a>不爱说话</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:孤独离群" id="diagnose_1"><a>孤独离群</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:重复语言" id="diagnose_2"><a>重复语言</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:表情淡漠" id="diagnose_3"><a>表情淡漠</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:行为刻板" id="diagnose_4"><a>行为刻板</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"><a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"><a> 3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"><a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"><a>1年以上</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"><a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"><a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"><a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"><a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"><a>未接受过治疗</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"><a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"><a> 治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"><a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"><a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"><a>其他事宜</a></label></p></div></div>';
/*自闭症*/
var zldxzz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:反应迟钝" id="diagnose_0"><a>反应迟钝</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:理解能力差" id="diagnose_1"><a> 理解能力差</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:运动落后" id="diagnose_2"><a>运动落后</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:表情呆滞" id="diagnose_3"><a>表情呆滞</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:说话晚" id="diagnose_3"><a>说话晚</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"><a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"><a> 3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"><a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"><a>1年以上</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"><a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"><a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"><a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"><a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"><a>未接受过治疗</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"><a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"><a> 治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"><a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"><a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"><a>其他事宜</a></label></p></div></div>';
/*智力低下*/
var yyzazz = '<div class="nr_n1"><p>1、孩子现在主要有什么症状？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:说话晚" id="diagnose_0"><a>说话晚</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:不会说话" id="diagnose_1"><a> 不会说话</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:吐词不清" id="diagnose_2"><a>吐词不清</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:交流困难" id="diagnose_3"><a>交流困难</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:不理人" id="diagnose_3"><a>不理人</a></label><label><input type="checkbox" name="zyzz" value="孩子现在主要有什么症状:脾气暴躁" id="diagnose_3"><a>脾气暴躁</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>2、孩子出现以上症状多久了？</p><div class="nr_n1_dx"><p><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1~3个月" id="diagnose_0"><a>1~3个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了： 3~6个月" id="diagnose_1"><a> 3~6个月</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：6个月~1年" id="diagnose_2"><a>6个月~1年</a></label><label><input type="radio" name="duojiu" value="孩子出现以上症状多久了：1年以上" id="diagnose_3"><a>1年以上</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>3、目前接受过哪些治疗？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:西药" id="diagnose_0"><a>西药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:中成药" id="diagnose_1"><a>中成药</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:偏方" id="diagnose_2"><a>偏方</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:行为训练" id="diagnose_3"><a>行为训练</a></label><label><input type="checkbox" name="ks" value="目前接受过哪些治疗:未接受过治疗" id="diagnose_4"><a>未接受过治疗</a></label></p></div></div><div style=" clear:both"></div><div class="nr_n1"><p>4、您更想了解的是？</p><div class="nr_n1_dx"><p><label><input type="checkbox" name="ks" value="您更想了解的是：病情咨询" id="diagnose_0"><a>病情咨询</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗方法" id="diagnose_1"><a> 治疗方法</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗费用" id="diagnose_2"><a>治疗费用</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：治疗周期" id="diagnose_3"><a>治疗周期</a></label><label><input type="checkbox" name="ks" value="您更想了解的是：其他事宜" id="diagnose_4"><a>其他事宜</a></label></p></div></div>';
/*语言障碍*/
var liuyan114 = '<form method="post" name="form1" id="gh_form" target="frameNo" class="form1" style="background: #EEEEEE"><div class="nrjjsb"><div class="titlecw"><span>网络联合初诊表</span><samp>Associates diagnosed table</samp><div class="titlecw-img1"><img src="/images/header_bgimg_03.jpg" alt=""></div><div class="titlecw-img2"><img src="/images/header_bgimg_03.jpg" alt=""></div></div><div class="jiange"></div>';
/*留言前*/

var liuyan114d = '<ul class="guahao-ul"><li><div class="beijing"><label>姓名：</label><input name="name" id="name" type="text" class="text"></div></li><li><div class="beijing"><label>性别：</label><select id="sex" name="sex" class="text"><option value="男">男</option><option value="女">女</option></select></div></li><li><div class="beijing"><label>年龄：</label><input name="age" id="age" type="number" class="text"></div></li><li><div class="beijing"><label>电话：</label><input name="tel" id="tel" type="text" class="text"></div></li><li><div class="beijing beijing2"><label class="gh_o">症状描述：</label><textarea form="form1" name="zzms" placeholder="请填写孩子目前大概情况..." cols="100%"></textarea></div></li></ul><div class="wxts"><p style="text-align:center;margin-top:-10px;color:#bf4426"><strong>立即申请检查减半优惠或治疗援助</strong></p></div><div class="anniu1"><input type="button" name="submit" class="act-submit" id="submit" onclick="yuyue(\'gh_form\',\'3\',\'3\',\'name\',\'tel\')" value="提交问题"> <input type="reset" class="act-submit1 act-submit2" onclick="" value="重新填写"></div><div class="wxts"><p><strong>温馨提示：</strong>您所填的信息我们将及时反馈给医生进行诊断，对于您的个人信息我们承诺保密！请您放心</p></div></div></form>';


function art_liuyan() {
    var pat = document.URL;
    if (pat.indexOf("/ddz/") > 0 ) {
        document.writeln(ddzzz);
    } else if (pat.indexOf("/cdz/") > 0) {
        document.writeln(cdzzz);
    } else if (pat.indexOf("/zbz/") > 0) {
        document.writeln(zbzzz);
    } else if (pat.indexOf("/ynz/") > 0) {
        document.writeln(ynzzz);
    } else if (pat.indexOf("/yyza/") > 0) {
        document.writeln(yyzazz);
    } else if(pat.indexOf("/axz/") > 0){
        document.writeln(axzz);
    }else if(pat.indexOf("/fych/")> 0){
        document.writeln(fychzz);
    }else if(pat.indexOf("/zldx/")> 0){
        document.writeln(zldxzz);
    }else if(pat.indexOf("/xzs/")> 0){
        document.writeln(xzszz);
    }else if(pat.indexOf("/xuexikunnan/")> 0){
        document.writeln(xxkn);
    }else if(pat.indexOf("/gantongshidiao/")> 0){
        document.writeln(gtst);
    }else if(pat.indexOf("/zylbjz/")> 0){
        document.writeln(zylbjzz);
    }
}

function art_ly() {
    document.writeln(liuyan114);
    art_liuyan();
    document.writeln(liuyan114d);
}
art_ly();

$(document).ready(function() {
    laydate.render({
        elem: '#hdtime',
        type: 'datetime',
        min: 0,
        max: 3
    });
    laydate.render({
        elem: '#hdstime',
        type: 'datetime',
    });
});