<div class="ykzs_list">
                        <div class="list_left">
                            <span><img src="/images/icon_list.png"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></span>
                            <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[field:description function="cn_substr(@me,500)"/]</span>
                            <span><a href="[field:arcurl/]" target="_blank">[阅读全文]</a></span>
                        </div>
                        <div class="list_right">
                            <span class="right_time">发布日期：[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                            <div class="right_a">
                                <a href="javascript:openZoosUrl('chatwin','&e=在线咨询')"><span>在线咨询</span></a>
                                <a href="javascript:openZoosUrl('chatwin','&e=在线预约')"><span>在线预约</span></a>
                            </div>
                        </div>
                    </div>