{dede:field name='keywords'}烤瓷牙,种类{/dede:field}
{dede:field name='description'}烤瓷牙作为一种较为理想的修复体逐渐被越来越多的人所接受。其美观和舒适的特点是其他种类的口腔修复技术所不能比拟的，因此很多人在选{/dede:field}
{dede:field name='title'}烤瓷牙的种类具体有哪些{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p>　　烤瓷牙作为一种较为理想的修复体逐渐被越来越多的人所接受。其美观和舒适的特点是其他种类的口腔修复技术所不能比拟的，因此很多人在选择修复时间会偏向于烤瓷牙修复。牙齿美学修复烤瓷牙主要有哪些种类的划分，<strong>北京维尔口腔医生在线为您详细的介绍</strong>。</p>
<p style="text-align: center; font-stretch: normal;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427061523381.jpg" style="width: 300px; height: 185px;" /></a></p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-stretch: normal; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192);"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">1</span><strong>烤瓷牙的种类具体划分为以下三点，</strong></h2>
<p>　　一、<strong>全瓷牙</strong></p>
<p>　　全瓷牙： 即无金属烤瓷牙，是烤瓷牙中至高级的修复材料。其透光性好、色泽高贵典雅、坚固耐磨、相容性极佳，在欧美发达国家普遍使用。</p>
<p>　　全瓷瓷牙全瓷冠突破传统美牙的各种弊端，运用仿生材料，对畸形牙、色素牙的临床冠部分施以专业技术，整个美牙过程轻松完成，不伤害原本真牙，少拔牙微痛苦。矫治整个过程只需7天，美牙不出现黑线，具有持久的亮白效果。同时，无需配戴牙套，是一项具备技术和艺术的 专业医生操作的美牙技术。美牙当天即可改善唇形、脸形和咬颌关系，并将越来越完美，成为各国明星和上层人士的美牙 。</p>
<p>　　二、<strong>贵金属烤瓷牙</strong></p>
<p>　　贵金属烤瓷牙：贵金属类烤瓷牙是在治疗的牙根或牙冠上用高强度合金做成金属帽，在其表面烤上一层与天然牙色泽相近的瓷粉，至后将由金属与瓷粉高温铸烤而成的复合体粘结在基牙上，形成形象逼真类似于真牙的牙齿。以钴铬、黄金烤瓷牙为代表的贵金属，颜色及形态与真牙一样，相容性好，能保护牙体组织，属于中高档的烤瓷牙。</p>
<p>　　三、<strong>非贵金属烤瓷牙</strong></p>
<p>　　非金属烤瓷牙：非贵金属烤瓷所使用的金属是钴铬合金。它属于一种成熟的修复技术，在临床应用时间较长，其修复效果已经被广大医生及求美者所认同并接受。主要以钴铬合金、钛合金烤瓷牙为代表的非贵金属，生物相容性一般，是烤瓷牙家族中至普通的一种烤瓷牙。</p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-stretch: normal; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192);"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">2</span><strong>维尔口腔烤瓷修复&mdash;&mdash;任蕾美学修复主任推荐</strong></h2>
<div style="text-align: center; padding: 0px; margin: 0px; font-stretch: normal; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0);"><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427070305545.jpg" style="width: 450px; height: 280px;" /></a></div>
<div style="font-stretch: normal;">&nbsp;</div>
<div style="font-stretch: normal;">
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">3</span><strong>维尔口腔</strong><strong>任蕾美学修复主任</strong><strong>&mdash;&mdash;烤瓷牙修复真实案例</strong></h2>
<br />
<div style="TEXT-ALIGN: center"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0428/20170428060405884.jpg" style="width: 300px; height: 195px;" /></a><br />
<span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px"><span style="COLOR: rgb(0,0,0)"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">王女士 年龄：33 门牙烤瓷牙</a></span></span><br />
<u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="COLOR: rgb(0,128,128)"><span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px">烤瓷牙的寿命多长？击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-stretch: normal; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192);"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">4</span><strong>维尔口腔&mdash;&mdash;北京专业美学修复中心</strong></h2>
<div style="padding: 0px; margin: 0px; font-stretch: normal; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0);">
<p>　　维尔口腔是北京较早开展美学修复项目的医疗机构之一。引进的仿生美容冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。由维尔美齿导师刘志杰院长制定出的3-3-4-4美齿黄金法则， 被众多美齿机构广泛借鉴及沿用。</p>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">安全材质</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　具有高度生物兼容性，对口腔无害，并加速种牙冠与口内组织的紧密结合性。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; PADDING-TOP: 5px"><font color="#e36c09"><span style="FONT-SIZE: 14px">专业团队</span></font></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　由院长刘志杰、美学修复主任任蕾等经验丰富的美学修复医生，亲自临床，提高修复安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">科学流程</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。</p>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解烤瓷牙，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
</div>
</div>
<br />{/dede:field}
{dede:field name='body'}<p>　　烤瓷牙作为一种较为理想的修复体逐渐被越来越多的人所接受。其美观和舒适的特点是其他种类的口腔修复技术所不能比拟的，因此很多人在选择修复时间会偏向于烤瓷牙修复。牙齿美学修复烤瓷牙主要有哪些种类的划分，<strong>北京维尔口腔医生在线为您详细的介绍</strong>。</p>
<p style="text-align: center; font-stretch: normal;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D6124353F-24521.jpg" style="width: 300px; height: 185px;" /></a></p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-stretch: normal; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192);"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">1</span><strong>烤瓷牙的种类具体划分为以下三点，</strong></h2>
<p>　　一、<strong>全瓷牙</strong></p>
<p>　　全瓷牙： 即无金属烤瓷牙，是烤瓷牙中至高级的修复材料。其透光性好、色泽高贵典雅、坚固耐磨、相容性极佳，在欧美发达国家普遍使用。</p>
<p>　　全瓷瓷牙全瓷冠突破传统美牙的各种弊端，运用仿生材料，对畸形牙、色素牙的临床冠部分施以专业技术，整个美牙过程轻松完成，不伤害原本真牙，少拔牙微痛苦。矫治整个过程只需7天，美牙不出现黑线，具有持久的亮白效果。同时，无需配戴牙套，是一项具备技术和艺术的 专业医生操作的美牙技术。美牙当天即可改善唇形、脸形和咬颌关系，并将越来越完美，成为各国明星和上层人士的美牙 。</p>
<p>　　二、<strong>贵金属烤瓷牙</strong></p>
<p>　　贵金属烤瓷牙：贵金属类烤瓷牙是在治疗的牙根或牙冠上用高强度合金做成金属帽，在其表面烤上一层与天然牙色泽相近的瓷粉，至后将由金属与瓷粉高温铸烤而成的复合体粘结在基牙上，形成形象逼真类似于真牙的牙齿。以钴铬、黄金烤瓷牙为代表的贵金属，颜色及形态与真牙一样，相容性好，能保护牙体组织，属于中高档的烤瓷牙。</p>
<p>　　三、<strong>非贵金属烤瓷牙</strong></p>
<p>　　非金属烤瓷牙：非贵金属烤瓷所使用的金属是钴铬合金。它属于一种成熟的修复技术，在临床应用时间较长，其修复效果已经被广大医生及求美者所认同并接受。主要以钴铬合金、钛合金烤瓷牙为代表的非贵金属，生物相容性一般，是烤瓷牙家族中至普通的一种烤瓷牙。</p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-stretch: normal; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192);"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">2</span><strong>维尔口腔烤瓷修复&mdash;&mdash;任蕾美学修复主任推荐</strong></h2>
<div style="text-align: center; padding: 0px; margin: 0px; font-stretch: normal; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0);"><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D6124Q220-3B43.jpg" style="width: 450px; height: 280px;" /></a></div>
<div style="font-stretch: normal;">&nbsp;</div>
<div style="font-stretch: normal;">
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">3</span><strong>维尔口腔</strong><strong>任蕾美学修复主任</strong><strong>&mdash;&mdash;烤瓷牙修复真实案例</strong></h2>
<br />
<div style="TEXT-ALIGN: center"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D61253RZ-4G08.jpg" style="width: 300px; height: 195px;" /></a><br />
<span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px"><span style="COLOR: rgb(0,0,0)"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">王女士 年龄：33 门牙烤瓷牙</a></span></span><br />
<u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="COLOR: rgb(0,128,128)"><span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px">烤瓷牙的寿命多长？击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-stretch: normal; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192);"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">4</span><strong>维尔口腔&mdash;&mdash;北京专业美学修复中心</strong></h2>
<div style="padding: 0px; margin: 0px; font-stretch: normal; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0);">
<p>　　维尔口腔是北京较早开展美学修复项目的医疗机构之一。引进的仿生美容冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。由维尔美齿导师刘志杰院长制定出的3-3-4-4美齿黄金法则， 被众多美齿机构广泛借鉴及沿用。</p>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">安全材质</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　具有高度生物兼容性，对口腔无害，并加速种牙冠与口内组织的紧密结合性。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; PADDING-TOP: 5px"><font color="#e36c09"><span style="FONT-SIZE: 14px">专业团队</span></font></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　由院长刘志杰、美学修复主任任蕾等经验丰富的美学修复医生，亲自临床，提高修复安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">科学流程</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。</p>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解烤瓷牙，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
</div>
</div>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D6124353F-24521_lit.jpg{/dede:field}
