{dede:field name='keywords'}后牙,怎么办{/dede:field}
{dede:field name='description'}患者提问：前段时间拔了颗阻生智齿，到今天为止已经快三周了。但拔牙的那侧还是无法使劲咬东西，遇冷热刺激也会疼。我该怎么办?本人26{/dede:field}
{dede:field name='title'}拔牙后牙疼怎么办?{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p><span style="font-size:16px;">　　患者提问：前段时间拔了颗阻生智齿，到今天为止已经快三周了。但拔牙的那侧还是无法使劲咬东西，遇冷热刺激也会疼。我该怎么办?本人26岁。</span></p>
<p><span style="font-size:16px;">　　医生解答：如果是拔牙当天出现疼痛，那属于正常范畴。如果疼痛持续很长时间，就要去找拔牙的医生进行详细的检查。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/1017/20171017102104510.jpg" style="width: 390px; height: 257px;" /></a></span></p>
<p><strong><span style="font-size:16px;">　　维尔口腔的医生介绍：拔牙后出现长时间疼痛，可能是由以下两个原因导致的：</span></strong></p>
<p><span style="font-size:16px;">　　一、拔牙技术不当。技术不当的话，这主要就可能是因为医生的操作过程不小心引起的拔牙后牙齿疼痛。在很多情况下，医生技术不过硬或者经验匮乏，就可能在拔牙的时候伤到患者的口腔其它组织。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">推荐阅读：拔牙的注意事项有哪些</span></a></span></p>
<p><span style="font-size:16px;">　　二、细菌感染。口腔内的死角容易藏匿细菌，拔牙前没有做好灭菌处理，细菌就会侵蚀伤口产生疼痛。</span></p>
<p><strong><span style="font-size:16px;">　　那作为患者，拔牙后出现疼痛症状，该如何处理?</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔的医生介绍：患者如果能够及时到正规的口腔医院接受专业的治疗，那就可以将危害减轻到较小，这也是保护患者自身安全的一种措施。不仅能够避免拔牙引发的危险，也能较大程度减轻疼痛。此外还应该选择正规的医院进行拔牙，从源头上杜绝可能出现的伤害。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><span style="color:#ff0000;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0203/20180203112323171.jpg" style="width: 550px; height: 130px;" /></a></span></span></p>
<p><span style="font-size:16px;">　　经过多年的发展，维尔口腔已经成为百姓选择的口腔专业医院，究其原因，认真负责的态度、精益求精的技术、临床经验丰富的医生、高端先进的设备、舒适卫生的环境等，都是维尔被喜欢的理由。虽然拔牙是非常小的小手术，但是维尔依然非常认真的对待，保证过程中安全卫生微痛，拔牙后无感染恢复快。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); font-size: 16px;">推荐阅读：北京拔牙多少钱</span></a></p>{/dede:field}
{dede:field name='body'}<p><span style="font-size:16px;">　　患者提问：前段时间拔了颗阻生智齿，到今天为止已经快三周了。但拔牙的那侧还是无法使劲咬东西，遇冷热刺激也会疼。我该怎么办?本人26岁。</span></p>
<p><span style="font-size:16px;">　　医生解答：如果是拔牙当天出现疼痛，那属于正常范畴。如果疼痛持续很长时间，就要去找拔牙的医生进行详细的检查。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/1017/20171017102104510.jpg" style="width: 390px; height: 257px;" /></a></span></p>
<p><strong><span style="font-size:16px;">　　维尔口腔的医生介绍：拔牙后出现长时间疼痛，可能是由以下两个原因导致的：</span></strong></p>
<p><span style="font-size:16px;">　　一、拔牙技术不当。技术不当的话，这主要就可能是因为医生的操作过程不小心引起的拔牙后牙齿疼痛。在很多情况下，医生技术不过硬或者经验匮乏，就可能在拔牙的时候伤到患者的口腔其它组织。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">推荐阅读：拔牙的注意事项有哪些</span></a></span></p>
<p><span style="font-size:16px;">　　二、细菌感染。口腔内的死角容易藏匿细菌，拔牙前没有做好灭菌处理，细菌就会侵蚀伤口产生疼痛。</span></p>
<p><strong><span style="font-size:16px;">　　那作为患者，拔牙后出现疼痛症状，该如何处理?</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔的医生介绍：患者如果能够及时到正规的口腔医院接受专业的治疗，那就可以将危害减轻到较小，这也是保护患者自身安全的一种措施。不仅能够避免拔牙引发的危险，也能较大程度减轻疼痛。此外还应该选择正规的医院进行拔牙，从源头上杜绝可能出现的伤害。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><span style="color:#ff0000;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0203/20180203112323171.jpg" style="width: 550px; height: 130px;" /></a></span></span></p>
<p><span style="font-size:16px;">　　经过多年的发展，维尔口腔已经成为百姓选择的口腔专业医院，究其原因，认真负责的态度、精益求精的技术、临床经验丰富的医生、高端先进的设备、舒适卫生的环境等，都是维尔被喜欢的理由。虽然拔牙是非常小的小手术，但是维尔依然非常认真的对待，保证过程中安全卫生微痛，拔牙后无感染恢复快。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); font-size: 16px;">推荐阅读：北京拔牙多少钱</span></a></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DUQ53F-MX4_lit.jpg{/dede:field}
