<?php
$z[0]=Array("noteinfo","",0,170);
$z[0][4]['notename']="烤瓷牙种类";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://beij.weierkq.com/kcyzlq/2.html\r\nhttp://beij.weierkq.com/kcyzlq/{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"left_center auto\">{/dede:areastart}\r\n    {dede:areaend}<div id=\"pages\" class=\"text-c auto\">{/dede:areaend}\r\n",172,703);
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://";
$z[1][4]['startid']="1";
$z[1][4]['endid']="";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="http://beij.weierkq.com/kcyzlq/";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>