{dede:field name='keywords'}龋齿,症状,儿童{/dede:field}
{dede:field name='description'}龋齿虽然是一种比较常见的牙齿疾病，我们应当做到早发现、早治疗，以防患牙丧失牙齿。平时生活中还有很多人对龋齿的认识不够，那么，儿童{/dede:field}
{dede:field name='title'}儿童龋齿主要的症状有哪些{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;"><b>&nbsp; &nbsp;&nbsp;</b>龋齿虽然是一种比较常见的牙齿疾病，我们应当做到早发现、早治疗，以防患牙丧失牙齿。平时生活中还有很多人对龋齿的认识不够，那么，<strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">儿童龋齿主要的症状有哪些?</span></a></strong></span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="儿童龋齿主要的症状有哪些?" src="/uploadfile/2017/0920/20170920044212678.jpg" style="cursor: pointer; border-width: 0px; border-style: solid; width: 300px; height: 200px;" /></a></span></div>
<p><span style="color:#ff0000;"><span style="font-size:16px;"><strong>儿童龋齿主要的症状有哪些</strong></span></span></p>
<p><span style="font-size:16px;">　　<strong><span style="color:#ff0000;">1、轻度龋齿(浅龋)：</span></strong>龋蚀破坏只在釉质内，初期表现为釉质出现褐色或黑褐色斑点或斑块，表面粗糙。继而形成表面破坏。邻面龋开始发生在接触面下方，窝沟龋则多开始在沟内，早期都不容易看到。只有发生在窝沟口时才可以看到，但儿童牙齿窝沟口处又容易有食物的色素沉着，医师检查不仔细也会误诊或漏诊。浅龋没有自觉症状。</span></p>
<p><span style="font-size:16px;">　　<strong><span style="color:#ff0000;">2、中度龋齿：</span></strong>龋蚀已达到牙本质，形成牙本质浅层龋洞。患者对冷、甜、酸等刺激性食物会感到牙齿酸痛，但刺激去掉以后，症状立即消失。这是因为牙本质对刺激感觉过敏的缘故。中龋及时得到治疗效果良好。</span></p>
<p><span style="font-size:16px;">　<span style="color:#ff0000;"><strong>　3、深度龋齿：</strong></span>龋蚀已达到牙本质深层，接近牙髓，或已影响牙髓。患儿对冷、热、酸、甜都有痛感，特别对热敏感，一败涂地去掉以后，疼痛仍持续一定时间才逐渐消失。这时多数需要作牙髓治疗以保存牙齿。深龋未经治疗，则牙髓继发感染或牙髓坏死。细菌可以通过牙根达到根尖孔外，引起根尖周围炎。牙冠若大部破坏或只留残根时，应将彻底拔除。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询在线医生</strong></span></a></span></p>
<div><span style="color:#ff0000;"><strong><span style="font-size:16px;">维尔口腔医院，专业塑造品牌!</span></strong></span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　1、专业团队 放心诊疗</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　国内知名口腔教授刘志杰领衔的口腔医师团队，让您轻松拥有自然、美观、精细、逼真的牙齿。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　2、即刻手术 节约时长</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔引进先进技术，手术过程仅需5-10分钟，短暂的手术时间降低了手术风险;仅需一次手术，恒久支撑牙冠，咀嚼更给力。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　3、品牌优势 个性修复</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔安全放心，材质安全无害，经久耐用，治疗时会根据顾客牙齿的颜色与形状等实际情况来综合考量，力求整体协调和美观的效果。</span><br />
&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0920/20170920044351521.jpg" style="width: 450px; height: 280px;" /></a></div>
<p><span style="font-size:16px;">　<strong><span style="color: rgb(255, 0, 0);">　</span></strong>维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;"><b>&nbsp; &nbsp;&nbsp;</b>龋齿虽然是一种比较常见的牙齿疾病，我们应当做到早发现、早治疗，以防患牙丧失牙齿。平时生活中还有很多人对龋齿的认识不够，那么，<strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">儿童龋齿主要的症状有哪些?</span></a></strong></span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="儿童龋齿主要的症状有哪些?" src="/uploadfile/2017/0920/20170920044212678.jpg" style="cursor: pointer; border-width: 0px; border-style: solid; width: 300px; height: 200px;" /></a></span></div>
<p><span style="color:#ff0000;"><span style="font-size:16px;"><strong>儿童龋齿主要的症状有哪些</strong></span></span></p>
<p><span style="font-size:16px;">　　<strong><span style="color:#ff0000;">1、轻度龋齿(浅龋)：</span></strong>龋蚀破坏只在釉质内，初期表现为釉质出现褐色或黑褐色斑点或斑块，表面粗糙。继而形成表面破坏。邻面龋开始发生在接触面下方，窝沟龋则多开始在沟内，早期都不容易看到。只有发生在窝沟口时才可以看到，但儿童牙齿窝沟口处又容易有食物的色素沉着，医师检查不仔细也会误诊或漏诊。浅龋没有自觉症状。</span></p>
<p><span style="font-size:16px;">　　<strong><span style="color:#ff0000;">2、中度龋齿：</span></strong>龋蚀已达到牙本质，形成牙本质浅层龋洞。患者对冷、甜、酸等刺激性食物会感到牙齿酸痛，但刺激去掉以后，症状立即消失。这是因为牙本质对刺激感觉过敏的缘故。中龋及时得到治疗效果良好。</span></p>
<p><span style="font-size:16px;">　<span style="color:#ff0000;"><strong>　3、深度龋齿：</strong></span>龋蚀已达到牙本质深层，接近牙髓，或已影响牙髓。患儿对冷、热、酸、甜都有痛感，特别对热敏感，一败涂地去掉以后，疼痛仍持续一定时间才逐渐消失。这时多数需要作牙髓治疗以保存牙齿。深龋未经治疗，则牙髓继发感染或牙髓坏死。细菌可以通过牙根达到根尖孔外，引起根尖周围炎。牙冠若大部破坏或只留残根时，应将彻底拔除。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询在线医生</strong></span></a></span></p>
<div><span style="color:#ff0000;"><strong><span style="font-size:16px;">维尔口腔医院，专业塑造品牌!</span></strong></span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　1、专业团队 放心诊疗</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　国内知名口腔教授刘志杰领衔的口腔医师团队，让您轻松拥有自然、美观、精细、逼真的牙齿。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　2、即刻手术 节约时长</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔引进先进技术，手术过程仅需5-10分钟，短暂的手术时间降低了手术风险;仅需一次手术，恒久支撑牙冠，咀嚼更给力。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　3、品牌优势 个性修复</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔安全放心，材质安全无害，经久耐用，治疗时会根据顾客牙齿的颜色与形状等实际情况来综合考量，力求整体协调和美观的效果。</span><br />
&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0920/20170920044351521.jpg" style="width: 450px; height: 280px;" /></a></div>
<p><span style="font-size:16px;">　<strong><span style="color: rgb(255, 0, 0);">　</span></strong>维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D9A15220-592F_lit.jpg{/dede:field}
