{dede:field name='keywords'}龋齿,怎么办,儿童{/dede:field}
{dede:field name='description'}小孩蛀牙痛怎么办?这是家长很关心的事情，当牙痛的时候大人都受不了，更何况是孩子，因为牙痛使得孩子经常性的吵闹严重影响着孩子和全家人{/dede:field}
{dede:field name='title'}儿童龋齿怎么办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}&nbsp; &nbsp;&nbsp;<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>小孩蛀牙痛怎么办?</strong></span></a>这是家长很关心的事情，当牙痛的时候大人都受不了，更何况是孩子，因为牙痛使得孩子经常性的吵闹严重影响着孩子和全家人的生活。所以当遇到孩子因为蛀牙牙齿痛怎么办?那就让维尔口腔的医师介绍一下吧。
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="龋齿示意图" src="http://beij.wekq.net/uploadfile/2017/0607/20170607035450332.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 216px;" /></a></div>
<p>&nbsp; &nbsp;找家正规的医院或者牙科诊所，检查下牙齿，需要填的治疗的抓紧时间处理，有的牙齿要用好多年，尤其是后牙，健康的牙齿对小孩的发育很重要。并且出现牙痛的症状说明已经伤到牙神经了，一定要抓紧时间进行治疗。</p>
<p>&nbsp; &nbsp; 对于已经形成的蛀牙,一定要立刻去牙医处就诊,让牙医及时采取措施,填补龋洞,防止其继续恶化。切记不能有等一等,算了吧的观念。&ldquo;牙疼不是病&rdquo;的观点不仅是错误的,而且会耽误治疗,造成蛀牙恶化,牙齿坏死,而且还有可能导致更多的蛀牙产生。真要是到了疼得实在受不了的阶段,有时就连牙医也帮不上你,那真是小洞不补,大洞吃苦。</p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0203/20180203035443628.jpg" style="width: 550px; height: 130px;" /></a></p>
<p><span style="color: rgb(255, 0, 0);"><strong>&nbsp; &nbsp; 快速治疗牙痛的方法就是根据病因针对性的治疗：</strong></span></p>
<p>&nbsp; &nbsp; ①龋齿：初龋一般,如龋洞变大而深时,可出现进食时牙痛,吃甜食或过冷,过热的食物时疼痛加重。这时可先用防酸止痛牙膏,温水刷牙,必要时用民间验方止痛,但有效的治疗方法应是填补龋洞。</p>
<p>&nbsp; &nbsp; ②牙髓炎：多是由于深龋未补致牙髓感染,或化学药物或温度刺激引起,其疼痛为自发性,阵发性剧痛,可有冷,热刺激痛和叩痛。这种牙痛的应急处理止痛,或用民间验方止痛。治疗的方法是在局麻下用牙砧磨开牙髓腔作牙髓治疗。</p>
<p>&nbsp; &nbsp; ③牙根尖周炎：多由牙髓炎扩散到根管口,致根尖周围组织发炎。表现为持续性牙痛。患牙有伸长感,触,压痛明显,不能咬食物。这时可服消炎止痛药,并吃软食。待消炎后再作根管治疗。</p>
<div><span style="color: rgb(255, 0, 0);"><strong>【维尔在奔跑，只为帮助更多人重绽笑容】</strong></span><br />
&nbsp;</div>
<div>　 &nbsp; 维尔口腔医院作是一所集医疗、教学、科研、治疗、修复、美容、预防为一体的技术力量雄厚、医疗前沿的现代化大型北京口腔医院。<br />
&nbsp;</div>
<div><strong>　人文服务</strong><br />
&nbsp;</div>
<div>　 &nbsp; &nbsp;视患者为亲人，营造高品位的人文关怀，从患者舒心、方便、安全、满意的角度出发，倡导&ldquo;一患、一医、一护&rdquo;的绿色专业护理，创建&ldquo;无烟输液室&rdquo;，同时开设24小时专家咨询热线，定期为患者健康回访等一系列绿色人文医疗制度。<br />
&nbsp;</div>
<div><strong>　绿色医疗</strong><br />
&nbsp;</div>
<div>　 &nbsp; 为患者就诊提供大方便，实行&ldquo;无节假日医院&rdquo;，建立以病人为中心的科学布局和便捷就医的合理流程，科学规范的医疗操作，严格的消毒措施，避免了其它疾病的交叉感染，让患者更放心安全的就医，实现全程导医服务的绿色通道，全力营造舒适、温馨的绿色医疗花园，建立诚信、理解、和谐的医疗环境。<br />
&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0607/20170607035519575.jpg" style="width: 450px; height: 280px;" /></a></div>
<div><br />
&nbsp; &nbsp; 小孩蛀牙牙痛怎么办?赶快来维尔口腔看一看，了解具体情况才能找出相应的治疗方案，如果还是有许多的疑问，可与我们的在线咨询进行免费的咨询。咨询电话：<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>400-6655-111</strong></span></a>.</div>{/dede:field}
{dede:field name='body'}&nbsp; &nbsp;&nbsp;<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>小孩蛀牙痛怎么办?</strong></span></a>这是家长很关心的事情，当牙痛的时候大人都受不了，更何况是孩子，因为牙痛使得孩子经常性的吵闹严重影响着孩子和全家人的生活。所以当遇到孩子因为蛀牙牙齿痛怎么办?那就让维尔口腔的医师介绍一下吧。
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="龋齿示意图" src="/uploads/allimg/c180322/1521D9631W910-62600.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 216px;" /></a></div>
<p>&nbsp; &nbsp;找家正规的医院或者牙科诊所，检查下牙齿，需要填的治疗的抓紧时间处理，有的牙齿要用好多年，尤其是后牙，健康的牙齿对小孩的发育很重要。并且出现牙痛的症状说明已经伤到牙神经了，一定要抓紧时间进行治疗。</p>
<p>&nbsp; &nbsp; 对于已经形成的蛀牙,一定要立刻去牙医处就诊,让牙医及时采取措施,填补龋洞,防止其继续恶化。切记不能有等一等,算了吧的观念。&ldquo;牙疼不是病&rdquo;的观点不仅是错误的,而且会耽误治疗,造成蛀牙恶化,牙齿坏死,而且还有可能导致更多的蛀牙产生。真要是到了疼得实在受不了的阶段,有时就连牙医也帮不上你,那真是小洞不补,大洞吃苦。</p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0203/20180203035443628.jpg" style="width: 550px; height: 130px;" /></a></p>
<p><span style="color: rgb(255, 0, 0);"><strong>&nbsp; &nbsp; 快速治疗牙痛的方法就是根据病因针对性的治疗：</strong></span></p>
<p>&nbsp; &nbsp; ①龋齿：初龋一般,如龋洞变大而深时,可出现进食时牙痛,吃甜食或过冷,过热的食物时疼痛加重。这时可先用防酸止痛牙膏,温水刷牙,必要时用民间验方止痛,但有效的治疗方法应是填补龋洞。</p>
<p>&nbsp; &nbsp; ②牙髓炎：多是由于深龋未补致牙髓感染,或化学药物或温度刺激引起,其疼痛为自发性,阵发性剧痛,可有冷,热刺激痛和叩痛。这种牙痛的应急处理止痛,或用民间验方止痛。治疗的方法是在局麻下用牙砧磨开牙髓腔作牙髓治疗。</p>
<p>&nbsp; &nbsp; ③牙根尖周炎：多由牙髓炎扩散到根管口,致根尖周围组织发炎。表现为持续性牙痛。患牙有伸长感,触,压痛明显,不能咬食物。这时可服消炎止痛药,并吃软食。待消炎后再作根管治疗。</p>
<div><span style="color: rgb(255, 0, 0);"><strong>【维尔在奔跑，只为帮助更多人重绽笑容】</strong></span><br />
&nbsp;</div>
<div>　 &nbsp; 维尔口腔医院作是一所集医疗、教学、科研、治疗、修复、美容、预防为一体的技术力量雄厚、医疗前沿的现代化大型北京口腔医院。<br />
&nbsp;</div>
<div><strong>　人文服务</strong><br />
&nbsp;</div>
<div>　 &nbsp; &nbsp;视患者为亲人，营造高品位的人文关怀，从患者舒心、方便、安全、满意的角度出发，倡导&ldquo;一患、一医、一护&rdquo;的绿色专业护理，创建&ldquo;无烟输液室&rdquo;，同时开设24小时专家咨询热线，定期为患者健康回访等一系列绿色人文医疗制度。<br />
&nbsp;</div>
<div><strong>　绿色医疗</strong><br />
&nbsp;</div>
<div>　 &nbsp; 为患者就诊提供大方便，实行&ldquo;无节假日医院&rdquo;，建立以病人为中心的科学布局和便捷就医的合理流程，科学规范的医疗操作，严格的消毒措施，避免了其它疾病的交叉感染，让患者更放心安全的就医，实现全程导医服务的绿色通道，全力营造舒适、温馨的绿色医疗花园，建立诚信、理解、和谐的医疗环境。<br />
&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D9632952Z-Q437.jpg" style="width: 450px; height: 280px;" /></a></div>
<div><br />
&nbsp; &nbsp; 小孩蛀牙牙痛怎么办?赶快来维尔口腔看一看，了解具体情况才能找出相应的治疗方案，如果还是有许多的疑问，可与我们的在线咨询进行免费的咨询。咨询电话：<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>400-6655-111</strong></span></a>.</div>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D9631W910-62600_lit.jpg{/dede:field}
