<?php
$z[0]=Array("addurls","http://beij.weierkq.com/wgfbC/5.html\r\nhttp://beij.weierkq.com/wgfbC/4.html\r\nhttp://beij.weierkq.com/wgfbC/3.html\r\nhttp://beij.weierkq.com/wgfbC/2.html\r\nhttp://beij.weierkq.com/wgfbC/",6,217);
$z[1]=Array("batchrule","",223,256);
$z[2]=Array("regxrule","",262,293);
$z[3]=Array("areastart","<div class=\"left_center auto\">",299,362);
$z[4]=Array("areaend","<div id=\"pages\" class=\"text-c auto\">",368,433);

?>