{dede:noteinfo notename="窝沟封闭" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area" musthas="http://beij.weierkq.com/wgfbC/"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://beij.weierkq.com/wgfbC/5.html
http://beij.weierkq.com/wgfbC/4.html
http://beij.weierkq.com/wgfbC/3.html
http://beij.weierkq.com/wgfbC/2.html
http://beij.weierkq.com/wgfbC/{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="left_center auto">{/dede:areastart}
    {dede:areaend}<div id="pages" class="text-c auto">{/dede:areaend}
{/dede:listrule}
