{dede:field name='keywords'}步骤{/dede:field}
{dede:field name='description'}根管治疗是针对牙齿、牙髓、根尖病变的一个治疗过程。根管治疗术是通过清除根管内的坏死物质，进行适当的消毒，充填根管，以去除根管内{/dede:field}
{dede:field name='title'}根管治疗的步骤有哪些{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p><span style="font-size:16px;">　　根管治疗是针对牙齿、牙髓、根尖病变的一个治疗过程。根管治疗术是通过清除根管内的坏死物质，进行适当的消毒，充填根管，以去除根管内容物对根尖周围组织的不良刺激，防止发生根尖周病变或促进根尖周病变愈合的一种治疗方法，那么，根管治疗的步骤有哪些?</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://baidu.weierkouqiang.com/uploadfile/2016/0128/20160128025117516.jpg" style="width: 670px; height: 165px;" /></a><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;点击咨询在线专家&lt;&lt;&lt;</span></a></span></p>
<p><span style="font-size:16px;">　<strong>　北京维尔口腔医生介绍，根管治疗步骤主要包括：</strong></span></p>
<p><span style="font-size:16px;">　　1 术前拍摄X线片评估牙齿冠、根情况以及牙槽骨情况，在根管治疗过程中，医生常常要求患牙在根管治疗术前，术中和术后分别拍X线片，以帮助诊断，了解髓室的位置和根管数目及形态，测量根管工作长度及日后随访和评价疗效提供对比的依据。</span></p>
<p><span style="font-size:16px;">　　2 揭开髓腔，去净腐质和原有充填物、揭净随顶，看到整个髓底解剖结构、髓壁与根管壁连续流畅、没有牙颈部台阶，没有过度切割髓壁和髓底以便后续治疗顺利进行。</span></p>
<p><span style="font-size:16px;">　　3 确定根管工作长度，应用平行投照X线方法、根管长度测量仪确定根管度度。办法是：技术+经验+根管长度测量仪+ X线。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;根管治疗多少钱？</span></a></span></p>
<p><span style="font-size:16px;">　　4 根管预备，根管清理成形的目的是去净根管壁上的感染物，通过根管器械的切削作用去除感染的牙本质并清理根管壁细菌以利于根管充填。</span></p>
<p><span style="font-size:16px;">　　5 根管冲洗，根管冲洗的目的是清除微生物、冲掉残渣，润滑根管器械和溶解有机残渣。</span></p>
<p><span style="font-size:16px;">　　6 根管消毒，目前用于根管消毒的封药有：氢氧化钙制剂、碘仿、抗生素类、洗必泰类等等，也可用丁香油、甲醛甲酚、樟脑酚等制剂。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;点击咨询根管治疗的适应症</span></a></span></p>
<p><span style="font-size:16px;">　　7 根管充填，治疗后牙齿无自觉症状、叩诊时无明显疼痛、根管内无异味、无渗出液、无急性尖周炎症状即可充填，有时候不必等到所有症状完全消失，也不一定要等到瘘管完全愈合，反复的封药有时容易对牙齿根尖周造成更大的刺激反应。</span></p>
<p><span style="font-size:16px;">　　8 治疗后的牙冠修复，牙齿根管治疗后由于牙体缺乏营养供应，脆性变大行嵌体或牙冠修复，以预防牙齿折裂。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><img alt="" src="/uploadfile/2017/1013/20171013050156776.jpg" style="width: 450px; height: 280px;" /><br />
有问题？点击咨询在线专家</span></a></span></p>
<p><span style="font-size:16px;">　<strong>　维尔口腔显微镜(热牙胶)根管治疗优势</strong></span></p>
<p><span style="font-size:16px;">　　一：细径光纤牙髓根管显微内窥镜仪器，探头尺寸仅1mm，小至0.06 mm的病灶都能发现。</span></p>
<p><span style="font-size:16px;">　　二：高清的放大功能，显著的3D立体效果，超大的景深，便于医生确切临床诊断，彻底清除病灶，术后舒适，限度延长牙齿寿命。</span></p>
<p><span style="font-size:16px;">　　三：软组织创伤少，减少肿胀情况，恢复更快</span></p>
<p><span style="font-size:16px;">　　四：整个设备的表面具有特殊的 性的纳米抗菌涂层保护，杜绝交叉感染</span></p>
<p><span style="font-size:16px;">　　五：实时的超精细图像监控，治疗成功率高达99.5%，若传统技术出现断针，超显微根管微创技术可以取出断针。</span></p>
<p><span style="font-size:16px;">　　<strong>友情提示：</strong>维尔口腔会对每位网上预约前来就诊的顾客提供免费口腔检查，同时由专家根据顾客自身的情况和需求，制定完美的解决方案，在顾客详细了解治疗的过程和费用并确认同意之后才开始进行，杜绝了隐性消费的因素。如果您还有什么疑问<strong>，</strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;点击在线咨询服务&lt;&lt;&lt;</span></a>，或拨打<span style="color:#ff0000;">维尔口腔咨询电话：400-6655111</span>,维尔口腔口腔专家将用丰富的知识为您解答。</span></p>{/dede:field}
{dede:field name='body'}<p><span style="font-size:16px;">　　根管治疗是针对牙齿、牙髓、根尖病变的一个治疗过程。根管治疗术是通过清除根管内的坏死物质，进行适当的消毒，充填根管，以去除根管内容物对根尖周围组织的不良刺激，防止发生根尖周病变或促进根尖周病变愈合的一种治疗方法，那么，根管治疗的步骤有哪些?</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DV62JE0-11a44.jpg" style="width: 670px; height: 165px;" /></a><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;点击咨询在线专家&lt;&lt;&lt;</span></a></span></p>
<p><span style="font-size:16px;">　<strong>　北京维尔口腔医生介绍，根管治疗步骤主要包括：</strong></span></p>
<p><span style="font-size:16px;">　　1 术前拍摄X线片评估牙齿冠、根情况以及牙槽骨情况，在根管治疗过程中，医生常常要求患牙在根管治疗术前，术中和术后分别拍X线片，以帮助诊断，了解髓室的位置和根管数目及形态，测量根管工作长度及日后随访和评价疗效提供对比的依据。</span></p>
<p><span style="font-size:16px;">　　2 揭开髓腔，去净腐质和原有充填物、揭净随顶，看到整个髓底解剖结构、髓壁与根管壁连续流畅、没有牙颈部台阶，没有过度切割髓壁和髓底以便后续治疗顺利进行。</span></p>
<p><span style="font-size:16px;">　　3 确定根管工作长度，应用平行投照X线方法、根管长度测量仪确定根管度度。办法是：技术+经验+根管长度测量仪+ X线。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;根管治疗多少钱？</span></a></span></p>
<p><span style="font-size:16px;">　　4 根管预备，根管清理成形的目的是去净根管壁上的感染物，通过根管器械的切削作用去除感染的牙本质并清理根管壁细菌以利于根管充填。</span></p>
<p><span style="font-size:16px;">　　5 根管冲洗，根管冲洗的目的是清除微生物、冲掉残渣，润滑根管器械和溶解有机残渣。</span></p>
<p><span style="font-size:16px;">　　6 根管消毒，目前用于根管消毒的封药有：氢氧化钙制剂、碘仿、抗生素类、洗必泰类等等，也可用丁香油、甲醛甲酚、樟脑酚等制剂。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;点击咨询根管治疗的适应症</span></a></span></p>
<p><span style="font-size:16px;">　　7 根管充填，治疗后牙齿无自觉症状、叩诊时无明显疼痛、根管内无异味、无渗出液、无急性尖周炎症状即可充填，有时候不必等到所有症状完全消失，也不一定要等到瘘管完全愈合，反复的封药有时容易对牙齿根尖周造成更大的刺激反应。</span></p>
<p><span style="font-size:16px;">　　8 治疗后的牙冠修复，牙齿根管治疗后由于牙体缺乏营养供应，脆性变大行嵌体或牙冠修复，以预防牙齿折裂。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><img alt="" src="/uploadfile/2017/1013/20171013050156776.jpg" style="width: 450px; height: 280px;" /><br />
有问题？点击咨询在线专家</span></a></span></p>
<p><span style="font-size:16px;">　<strong>　维尔口腔显微镜(热牙胶)根管治疗优势</strong></span></p>
<p><span style="font-size:16px;">　　一：细径光纤牙髓根管显微内窥镜仪器，探头尺寸仅1mm，小至0.06 mm的病灶都能发现。</span></p>
<p><span style="font-size:16px;">　　二：高清的放大功能，显著的3D立体效果，超大的景深，便于医生确切临床诊断，彻底清除病灶，术后舒适，限度延长牙齿寿命。</span></p>
<p><span style="font-size:16px;">　　三：软组织创伤少，减少肿胀情况，恢复更快</span></p>
<p><span style="font-size:16px;">　　四：整个设备的表面具有特殊的 性的纳米抗菌涂层保护，杜绝交叉感染</span></p>
<p><span style="font-size:16px;">　　五：实时的超精细图像监控，治疗成功率高达99.5%，若传统技术出现断针，超显微根管微创技术可以取出断针。</span></p>
<p><span style="font-size:16px;">　　<strong>友情提示：</strong>维尔口腔会对每位网上预约前来就诊的顾客提供免费口腔检查，同时由专家根据顾客自身的情况和需求，制定完美的解决方案，在顾客详细了解治疗的过程和费用并确认同意之后才开始进行，杜绝了隐性消费的因素。如果您还有什么疑问<strong>，</strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;点击在线咨询服务&lt;&lt;&lt;</span></a>，或拨打<span style="color:#ff0000;">维尔口腔咨询电话：400-6655111</span>,维尔口腔口腔专家将用丰富的知识为您解答。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DV62JE0-11a44_lit.jpg{/dede:field}
