{dede:field name='keywords'}烤瓷牙,价格{/dede:field}
{dede:field name='description'}烤瓷牙的适应症较广，严重的口腔牙列不齐、牙缝、四环素牙、氟牙症、畸形牙以及各种不能充填的牙根都可以通过烤瓷牙来修复。有数据显示{/dede:field}
{dede:field name='title'}烤瓷牙的价格{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">　　烤瓷牙的适应症较广，严重的口腔牙列不齐、牙缝、四环素牙、氟牙症、畸形牙以及各种不能充填的牙根都可以通过烤瓷牙来修复。有数据显示，在目前做烤瓷牙的病人中，有60%-70%都是年轻人。除了效果外，很多人也在纠结烤瓷牙的价格问题，下面就一起来了解下烤瓷牙的价格表。</span>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0518/20170518052344757.jpg" style="width: 300px; height: 185px;" /></span></a></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　&gt;&gt;&gt;更多烤瓷牙材料，在线了解&gt;&gt;&gt;</span></span></a></p>
<p><strong><span style="font-size:16px;">　　一、非贵金属烤瓷牙</span></strong></p>
<p><span style="font-size:16px;">　　1、镍铬合金烤瓷牙：以镍和铬为主要成分，在使用中镍离子会缓慢游离出来，并渗透到临近牙龈组织，导致牙龈着色，一般为灰黑色。一般不建议使用，其价格通常为每颗几百元左右。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">【点击咨询】【在线预约】</span></a></span></p>
<p><span style="font-size:16px;">　　2、钴铬合金烤瓷牙：其优点是具有较强的金属稳定性，由于不含镍元素，生物相容性大大提高，造成牙龈变色的概率也降低，一般情况下是不会出现黑色牙龈或者牙龈出血的现象。与贵金属烤瓷牙以及全瓷牙相比，钴铬烤瓷牙的费用明显就低很多，而跟镍铬烤瓷牙相比的话，钴铬烤瓷牙又比较安全。钴铬烤瓷牙价格一般在千元左右。</span></p>
<p><strong><span style="font-size:16px;">　　二、贵金属烤瓷牙</span></strong></p>
<p><span style="font-size:16px;">　　1、合金烤瓷牙：含银量在50%以上的含银内冠烤瓷牙，几近于金内冠烤瓷冠的价格。如钯银合金烤瓷牙在大城市价格约一千多元左右。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size: 16px;">&gt;&gt;&gt;烤瓷牙具体价格是多少?在线咨询&gt;&gt;&gt;</span></span></a></p>
<p><span style="font-size:16px;">　　2、白金烤瓷牙：白金烤瓷牙具有良好的生物相容性，使用非常安全。不会产生龈缘黑线。白金烤瓷牙价格在两千元左右。</span></p>
<p><span style="font-size:16px;">　　3、黄金烤瓷牙： 其内冠含金量在84%以上，价格因金的使用重量而有一定差异，价格一般在两千元以上。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;">　　<img alt="" src="http://beij.wekq.net/uploadfile/2017/0518/20170518052202989.jpg" style="width: 450px; height: 280px;" /></span></a></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;">　　</span><span style="color:#ff0000;"><span style="font-size: 16px;">&ensp;[烤瓷牙多少钱?直接与维尔的在线医生一对一交流]</span></span></a></p>
<p><strong><span style="font-size:16px;">　　三、全瓷烤瓷牙</span></strong></p>
<p><span style="font-size:16px;">　　1、铸瓷牙：分两代，一代以白榴石为内冠，也叫铸造玻璃陶瓷;二代以锂基陶瓷为内冠，大城市地区的收费与全瓷牙相近，但效果却无法相比，铸瓷烤瓷牙价格在几千元不等。</span></p>
<p><span style="font-size:16px;">　　2、全瓷牙：较大特点是没有金属内冠，而采用先用的瓷性材料烧制内冠，内冠材料主要是氧化锆或氧化铝，所以牙齿透明度好，光泽度极佳，更有效避免了金属过敏等问题。根据内冠材料的不同，价格从千元到万元不等。</span></p>
<p><span style="font-size:16px;">　　维尔口腔的医生提示患者：烤瓷牙并非越贵越好，不同的烤瓷牙也有不同的适应症。在维尔，医生会根据您牙齿的状况、您的要求结合医生的专业意见来综合考虑，给出较合适的治疗方案。<span style="color:#ff0000;">&ensp;</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">[您适合哪类烤瓷牙?结合症状咨询维尔的在线客服]</span></a></span></p>
<p><strong><span style="font-size:16px;">　　做烤瓷牙，就到维尔!</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔医院是华东地区数字化口腔医院，该院与德国、美国、法国、日本、瑞士、香港、台湾等国家和地区的口腔医疗单位建立了良好的学术交流与技术合作关系。医院拥有数十位技术超群的口腔医生诊疗团队，他们专注于口腔事业，立足于口腔技术前沿。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); font-size: 16px; text-align: center;">牙齿美容师定制专属美牙方案</span></a></p>
<p><strong><span style="font-size:16px;">　　专业操作+合适的材料=好效果</span></strong></p>
<p><span style="font-size:16px;">　　在烤瓷牙方面，维尔引进的德国3D美牙冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。&ldquo;美牙冠&rdquo;牙齿美容采用3D数码定位技术，对顾客牙齿的自然形态和颜色全面分析，根据牙冠、牙根、牙颈三部分形态，再结合专业牙齿美容医师的检测，制定出较适合你的牙齿美容方案，成形后的牙齿美观大方，拥有明星般的漂亮牙齿不是梦。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;"><img alt="" src="/uploadfile/2018/0202/20180202021348503.jpg" style="width: 550px; height: 130px;" /></span></span></a></p>
<p><span style="font-size:16px;">　　温馨提示：如果您还有什么疑问，可以点击在线咨询，或拨打我们的24小时美牙咨询热线400-6655-111，维尔口腔专业医生将给出专业的意见并提供较优质的咨询服务。同时您也可以通过网络就诊，免挂号费、免排队，优先会诊，为您节省宝贵时间!　<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">　[想做烤瓷牙?立即挂号，到院免排队挂号，优先就诊]</span></a></span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">　　烤瓷牙的适应症较广，严重的口腔牙列不齐、牙缝、四环素牙、氟牙症、畸形牙以及各种不能充填的牙根都可以通过烤瓷牙来修复。有数据显示，在目前做烤瓷牙的病人中，有60%-70%都是年轻人。除了效果外，很多人也在纠结烤瓷牙的价格问题，下面就一起来了解下烤瓷牙的价格表。</span>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploads/allimg/c180322/1521D5Z4602F-31I0.jpg" style="width: 300px; height: 185px;" /></span></a></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　&gt;&gt;&gt;更多烤瓷牙材料，在线了解&gt;&gt;&gt;</span></span></a></p>
<p><strong><span style="font-size:16px;">　　一、非贵金属烤瓷牙</span></strong></p>
<p><span style="font-size:16px;">　　1、镍铬合金烤瓷牙：以镍和铬为主要成分，在使用中镍离子会缓慢游离出来，并渗透到临近牙龈组织，导致牙龈着色，一般为灰黑色。一般不建议使用，其价格通常为每颗几百元左右。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">【点击咨询】【在线预约】</span></a></span></p>
<p><span style="font-size:16px;">　　2、钴铬合金烤瓷牙：其优点是具有较强的金属稳定性，由于不含镍元素，生物相容性大大提高，造成牙龈变色的概率也降低，一般情况下是不会出现黑色牙龈或者牙龈出血的现象。与贵金属烤瓷牙以及全瓷牙相比，钴铬烤瓷牙的费用明显就低很多，而跟镍铬烤瓷牙相比的话，钴铬烤瓷牙又比较安全。钴铬烤瓷牙价格一般在千元左右。</span></p>
<p><strong><span style="font-size:16px;">　　二、贵金属烤瓷牙</span></strong></p>
<p><span style="font-size:16px;">　　1、合金烤瓷牙：含银量在50%以上的含银内冠烤瓷牙，几近于金内冠烤瓷冠的价格。如钯银合金烤瓷牙在大城市价格约一千多元左右。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size: 16px;">&gt;&gt;&gt;烤瓷牙具体价格是多少?在线咨询&gt;&gt;&gt;</span></span></a></p>
<p><span style="font-size:16px;">　　2、白金烤瓷牙：白金烤瓷牙具有良好的生物相容性，使用非常安全。不会产生龈缘黑线。白金烤瓷牙价格在两千元左右。</span></p>
<p><span style="font-size:16px;">　　3、黄金烤瓷牙： 其内冠含金量在84%以上，价格因金的使用重量而有一定差异，价格一般在两千元以上。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;">　　<img alt="" src="/uploads/allimg/c180322/1521D5Z50LZ-41Z1.jpg" style="width: 450px; height: 280px;" /></span></a></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;">　　</span><span style="color:#ff0000;"><span style="font-size: 16px;">&ensp;[烤瓷牙多少钱?直接与维尔的在线医生一对一交流]</span></span></a></p>
<p><strong><span style="font-size:16px;">　　三、全瓷烤瓷牙</span></strong></p>
<p><span style="font-size:16px;">　　1、铸瓷牙：分两代，一代以白榴石为内冠，也叫铸造玻璃陶瓷;二代以锂基陶瓷为内冠，大城市地区的收费与全瓷牙相近，但效果却无法相比，铸瓷烤瓷牙价格在几千元不等。</span></p>
<p><span style="font-size:16px;">　　2、全瓷牙：较大特点是没有金属内冠，而采用先用的瓷性材料烧制内冠，内冠材料主要是氧化锆或氧化铝，所以牙齿透明度好，光泽度极佳，更有效避免了金属过敏等问题。根据内冠材料的不同，价格从千元到万元不等。</span></p>
<p><span style="font-size:16px;">　　维尔口腔的医生提示患者：烤瓷牙并非越贵越好，不同的烤瓷牙也有不同的适应症。在维尔，医生会根据您牙齿的状况、您的要求结合医生的专业意见来综合考虑，给出较合适的治疗方案。<span style="color:#ff0000;">&ensp;</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">[您适合哪类烤瓷牙?结合症状咨询维尔的在线客服]</span></a></span></p>
<p><strong><span style="font-size:16px;">　　做烤瓷牙，就到维尔!</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔医院是华东地区数字化口腔医院，该院与德国、美国、法国、日本、瑞士、香港、台湾等国家和地区的口腔医疗单位建立了良好的学术交流与技术合作关系。医院拥有数十位技术超群的口腔医生诊疗团队，他们专注于口腔事业，立足于口腔技术前沿。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); font-size: 16px; text-align: center;">牙齿美容师定制专属美牙方案</span></a></p>
<p><strong><span style="font-size:16px;">　　专业操作+合适的材料=好效果</span></strong></p>
<p><span style="font-size:16px;">　　在烤瓷牙方面，维尔引进的德国3D美牙冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。&ldquo;美牙冠&rdquo;牙齿美容采用3D数码定位技术，对顾客牙齿的自然形态和颜色全面分析，根据牙冠、牙根、牙颈三部分形态，再结合专业牙齿美容医师的检测，制定出较适合你的牙齿美容方案，成形后的牙齿美观大方，拥有明星般的漂亮牙齿不是梦。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;"><img alt="" src="/uploadfile/2018/0202/20180202021348503.jpg" style="width: 550px; height: 130px;" /></span></span></a></p>
<p><span style="font-size:16px;">　　温馨提示：如果您还有什么疑问，可以点击在线咨询，或拨打我们的24小时美牙咨询热线400-6655-111，维尔口腔专业医生将给出专业的意见并提供较优质的咨询服务。同时您也可以通过网络就诊，免挂号费、免排队，优先会诊，为您节省宝贵时间!　<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">　[想做烤瓷牙?立即挂号，到院免排队挂号，优先就诊]</span></a></span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D5Z4602F-31I0_lit.jpg{/dede:field}
