{dede:field name='keywords'}神经{/dede:field}
{dede:field name='description'}很多人，特别是老一辈的人都会觉得拔牙是一件非常危险的事，会对神经造成伤害。很显然，这种观念只是片面的，那事实是怎么样的? 拔{/dede:field}
{dede:field name='title'}拔牙会不会对神经造成伤害{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p><span style="font-size:16px;">　　很多人，特别是老一辈的人都会觉得拔牙是一件非常危险的事，会对神经造成伤害。很显然，这种观念只是片面的，那事实是怎么样的?</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/1017/20171017102431329.jpg" style="width: 390px; height: 257px;" /></a></span></p>
<p><strong><span style="font-size:16px;">　　拔牙会不会对神经造成伤害?</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔专家表示：人们担心拔牙会影响到神经，通常指的是牙髓神经。其实，牙髓神经是用来感觉较强烈的物理和化学刺激的。在正常情况下，这部分神经不会向大脑传递明显的感觉信号，牙神经的主要作用是向牙齿内的细胞提供养分，维护牙齿健康。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">推荐阅读： 急性智齿冠周炎要不要拔牙</span></a></span></p>
<p><span style="font-size:16px;">　　现在拔牙都讲究微创微痛，对神经的影响很小，可以忽略不计。拔牙所用的局部麻药仅对其注射范围内的痛觉神经纤维起暂时性、可逆性的阻断作用，而非长久性损坏，并且麻药不可能进入大脑，不会对脑神经产生药理作用，因此，也不会影响到大脑神经。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); font-size: 16px;">推荐阅读 北京维尔拔牙多少钱</span></a></p>
<p><span style="font-size:16px;">　　当然，要是拔牙的过程中医师操作水平不够熟练，或医院的消毒系统不够完善等，也是很容易引起伤口感染，伤及神经的。若三叉神经线受到影响，患者或会在嘴唇和舌头的位置感到麻痹，麻痹的程度则要看神经所受创伤的程度了。牙根神经与面部神经相连，拔牙过于剧烈的话也可造成面部肌肉坏死甚至面瘫。因此，拔牙一定要选择有正规资质的医疗机构进行，谨慎就医，避免风险。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0203/20180203112303721.jpg" style="width: 550px; height: 130px;" /></a></span></p>
<p><span style="font-size:16px;">　　温馨提醒：如果拔牙几天后还有持续出血或疼痛，甚至出现明显的头晕心慌等不适症状，请立即到医院复诊，查明原因后及时处理。如果您还有更多疑问，请点击在线咨询，维尔医生给您较满意的解答!</span></p>{/dede:field}
{dede:field name='body'}<p><span style="font-size:16px;">　　很多人，特别是老一辈的人都会觉得拔牙是一件非常危险的事，会对神经造成伤害。很显然，这种观念只是片面的，那事实是怎么样的?</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/1017/20171017102431329.jpg" style="width: 390px; height: 257px;" /></a></span></p>
<p><strong><span style="font-size:16px;">　　拔牙会不会对神经造成伤害?</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔专家表示：人们担心拔牙会影响到神经，通常指的是牙髓神经。其实，牙髓神经是用来感觉较强烈的物理和化学刺激的。在正常情况下，这部分神经不会向大脑传递明显的感觉信号，牙神经的主要作用是向牙齿内的细胞提供养分，维护牙齿健康。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">推荐阅读： 急性智齿冠周炎要不要拔牙</span></a></span></p>
<p><span style="font-size:16px;">　　现在拔牙都讲究微创微痛，对神经的影响很小，可以忽略不计。拔牙所用的局部麻药仅对其注射范围内的痛觉神经纤维起暂时性、可逆性的阻断作用，而非长久性损坏，并且麻药不可能进入大脑，不会对脑神经产生药理作用，因此，也不会影响到大脑神经。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); font-size: 16px;">推荐阅读 北京维尔拔牙多少钱</span></a></p>
<p><span style="font-size:16px;">　　当然，要是拔牙的过程中医师操作水平不够熟练，或医院的消毒系统不够完善等，也是很容易引起伤口感染，伤及神经的。若三叉神经线受到影响，患者或会在嘴唇和舌头的位置感到麻痹，麻痹的程度则要看神经所受创伤的程度了。牙根神经与面部神经相连，拔牙过于剧烈的话也可造成面部肌肉坏死甚至面瘫。因此，拔牙一定要选择有正规资质的医疗机构进行，谨慎就医，避免风险。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0203/20180203112303721.jpg" style="width: 550px; height: 130px;" /></a></span></p>
<p><span style="font-size:16px;">　　温馨提醒：如果拔牙几天后还有持续出血或疼痛，甚至出现明显的头晕心慌等不适症状，请立即到医院复诊，查明原因后及时处理。如果您还有更多疑问，请点击在线咨询，维尔医生给您较满意的解答!</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DUS03510-b147_lit.jpg{/dede:field}
