{dede:field name='keywords'}牙周炎{/dede:field}
{dede:field name='description'}牙周炎的危害是非常大的，属于牙周组织的一种慢性炎症。它的破坏性非常大，会造成牙齿逐渐松动，成为成年人牙齿脱落的主要原因。{/dede:field}
{dede:field name='title'}牙周炎怎么治疗{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}　　牙周炎的危害是非常大的，属于牙周组织的一种慢性炎症。它的破坏性非常大，会造成牙齿逐渐松动，成为成年人牙齿脱落的主要原因。并且还有很多的并发症，如出血、疼痛等，因此，一旦发现自己有牙周炎的症状，一定要及时到医院检查，接受治疗。那么，牙周炎是怎么治疗的呢?许多患者都还不了解，下面我们就让维尔口腔医生给我们介绍一下吧。 <a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;"><strong>&gt;&gt;&gt;点击与维尔客服在线交流&gt;&gt;&gt;</strong></span></a>
<p><span style="color:#008080;">　　<strong>什么是牙周炎?</strong></span></p>
<p>　　牙周炎是侵犯牙龈和牙周组织的慢性炎症，是一种破坏性疾病，其主要特征为牙周袋的形成及袋壁的炎症，牙槽骨吸收和牙齿逐渐松动，它是导致成年人牙齿丧失的主要原因<font color="#0020ff"><font color="#000000">。</font></font><span style="color:#ff8c00;"><strong>&gt;&gt;&gt;我的情况是属于牙周炎吗?点击咨询客服&gt;&gt;&gt;</strong></span></p>
<p><font color="#0020ff"><strong>　　</strong></font></p>
<center>
	<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0428/20170428053921230.png" style="width: 326px; height: 212px;" /></a></center>
<p>&nbsp;</p>
<p><span style="color:#008080;">　　<strong>维尔口腔医生介绍：牙周炎怎么治疗?</strong></span></p>
<p><span style="background-color:#ffffff;">　</span><strong><span style="background-color:#ffffff;">　</span><span style="color:#808080;"><font style="BACKGROUND-COLOR: #ffff00"><span style="background-color:#ffffff;">一、轻度牙周炎 - 牙龈炎</span></font></span></strong></p>
<p>　　牙周炎早期佳的治疗方法就是洗牙，除去口腔内的牙菌斑和牙石。但是传统的洗牙的弊端在于比较痛，会出比较多的血，洗后牙齿表面比较粗糙。维尔超声波洁牙能在瞬间柔和地清除牙垢、牙菌斑,并且在洁治过程中对釉质几乎无损害，消除导致牙周炎症的牙结石。 <a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;"><strong>&gt;&gt;&gt;点击预约洁牙&gt;&gt;&gt;</strong></span></a></p>
<p><span style="color:#808080;">　　<strong>诊疗技术：<font style="BACKGROUND-COLOR: #0020ff"><span style="background-color:#ffffff;">维尔超声波洁牙</span></font></strong></span></p>
<p>　　1、不伤牙：在洁牙过程中震动感更小、更柔和、更舒适，不伤牙齿。</p>
<p>　　2、祛除表面色素：使用特殊喷砂颗粒,清楚牙齿表面，从而达到去除牙齿表面烟斑、茶渍、咖啡渍等色素沉着。</p>
<p>　　3、自然光泽：喷砂提高牙齿的光泽度，使牙齿亮白。</p>
<p>　　4、预防牙龈炎症和出血：有效去除牙结石、牙垢等，预防和延缓食物残渣在牙齿表面聚集，进而预防牙龈发炎、出血和萎缩。</p>
<p>　　</p>
<center>
	<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0428/20170428054204815.jpg" style="width: 300px; height: 180px;" /></a></center>
<p>&nbsp;</p>
<p><span style="background-color:#ffffff;">　　</span><span style="color:#808080;"><font style="BACKGROUND-COLOR: #ffff00"><strong><span style="background-color:#ffffff;">二、牙周炎中期 - 炎症恶化出现牙周脓袋易出血</span></strong></font></span></p>
<p>　　这时候的牙周炎已经发展到很严重的阶段，仅仅定期的洁治(洗牙)已经不能使治疗牙龈出血，只有采取刮治和其它牙周治疗或牙周手术治疗，才能缓解病症。&gt;&gt;&gt;我的情况是不是属于牙周炎中期，点击咨询&gt;&gt;&gt;</p>
<p><strong><span style="color:#808080;"><span style="background-color:#ffffff;">　　诊疗技术：</span><font style="BACKGROUND-COLOR: #0020ff"><span style="background-color:#ffffff;">维尔水激光刮治</span></font></span></strong></p>
<p>　　水光动能现象和一般的牙钻不同之处在于：在作用于硬组织时，它不会出现振动，也不会产生热量，能使患者的神经不会感觉过分敏感而产生疼痛。由于2780nm激光能量直接作用于软组织，并有恰当的吸水率，因此可获得较佳的切割和止血效果，创面不会产生结痂区。&gt;&gt;&gt;点击咨询水激光刮治技术的详细情况&gt;&gt;&gt;</p>
<p>　　</p>
<center>
	<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0428/20170428054204547.jpg" style="width: 300px; height: 180px;" /></a></center>
<p>&nbsp;</p>
<p><span style="color:#808080;"><span style="background-color:#ffffff;">　　</span><strong><font style="BACKGROUND-COLOR: #ffff00"><span style="background-color:#ffffff;">三、牙周病后期 - 牙槽骨与牙周韧带破坏</span></font></strong></span></p>
<p><strong><span style="color:#808080;"><span style="background-color:#ffffff;">　　诊疗技术：</span><font style="BACKGROUND-COLOR: #0020ff"><span style="background-color:#ffffff;">龈下刮治术</span></font></span></strong></p>
<p>　　龈下刮治术，是用比较精细的龈下刮治器刮除位于牙周袋内根面上的牙石和菌斑。而我们一般通过龈下刮治术，也就是通俗所说的&quot;深层洁牙&quot;来去除深在的牙石菌斑。而根面平整术即为龈下洁治术的继续和完善。</p>
<p>　　</p>
<center>
	<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0428/20170428054205206.jpg" style="width: 300px; height: 180px;" /></a></center>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;">　　<strong>&gt;&gt;&gt;我的情况适合哪种治疗方式?点击咨询在线客服&gt;&gt;&gt;</strong></span></a></p>
<p><span style="color:#008080;">　　<strong>治疗牙周炎，维尔值得您信赖</strong></span></p>
<p>　　<span style="color:#808080;"><strong>高效精准：</strong></span>数字化全面检查，准确了解口腔状况，医学组成员亲自操作，快速解决疑难根管问题;</p>
<p>　　<span style="color:#808080;"><strong>舒适：</strong></span>采用先进的根管技术，防止根管壁侧穿、偏移根尖等发生，减少就诊时间，整个过程舒适;</p>
<p>　　<span style="color:#808080;"><strong><span style="background-color:#ffffff;">健康卫生：</span></strong></span>根管治疗材料通过药监部门层层审核，不影响口腔健康，保障口腔健康</p>
<p>　　<span style="color:#808080;"><strong><span style="background-color:#ffffff;">避免感染：</span></strong></span>推行阳光无菌诊疗模式，配备消毒中心，采用十一个无菌诊疗服务，防止交叉感染。 <strong><span style="color:#ff8c00;">&gt;</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;">&gt;&gt;点击此处，预约维尔口腔专业治疗牙周炎</span></a></strong></p>
<p>　　维尔口腔，19多年荣誉铸就，精益求精</p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn">　　<img alt="" src="http://beij.wekq.net/uploadfile/2017/0428/20170428054810877.png" style="width: 400px; height: 250px;" /></a></p>
<center style="text-align: center;">
	&nbsp;</center>
<p style="text-align: center;">&nbsp;</p>
<p>　　北京维尔口腔医院是一所融医疗、教学、科研、急救医学、预防保健为一体的综合性医院，医院医生云集、医术精湛，拥有国内外先进的检验、治疗仪、设施先进、服务温馨，采用标准的&ldquo;一人一医一诊室&rdquo;的个性人性化设置，实施&ldquo;专科、专病、专治&rdquo;的诊疗方针。</p>
<p>　　北京维尔口腔医院主要致力于口腔医疗先进技术的引进、消化和研究。聘请美国、韩国、德国和内地的医生为技术顾问，成立口腔医学医生委员会。形成维尔口腔医院在口腔医疗领域的技术特色和专业保障。卓越的医疗技术、一流的医生资源、国内外先进的医疗设备，为客户提供上佳的医疗体验和保障。<font color="#0020ff"><strong>&nbsp;</strong></font><strong><font color="#0020ff">&nbsp;</font><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;">&gt;&gt;&gt;点击此处，预约维尔口腔专业治疗牙周炎</span></a></strong></p>
<p>　　如果您还有想要了解的情况，可以点击我们的<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#008080;"><strong>【在线咨询】</strong></span></a>，我们的在线客服会给您较专业，较详细的解答，或是拨打我们的24小时美牙咨询热线400/6655111。维尔口腔专业咨询会给您耐心的，详细的解答，并给您一个满意的答复!</p>{/dede:field}
{dede:field name='body'}　　牙周炎的危害是非常大的，属于牙周组织的一种慢性炎症。它的破坏性非常大，会造成牙齿逐渐松动，成为成年人牙齿脱落的主要原因。并且还有很多的并发症，如出血、疼痛等，因此，一旦发现自己有牙周炎的症状，一定要及时到医院检查，接受治疗。那么，牙周炎是怎么治疗的呢?许多患者都还不了解，下面我们就让维尔口腔医生给我们介绍一下吧。 <a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;"><strong>&gt;&gt;&gt;点击与维尔客服在线交流&gt;&gt;&gt;</strong></span></a>
<p><span style="color:#008080;">　　<strong>什么是牙周炎?</strong></span></p>
<p>　　牙周炎是侵犯牙龈和牙周组织的慢性炎症，是一种破坏性疾病，其主要特征为牙周袋的形成及袋壁的炎症，牙槽骨吸收和牙齿逐渐松动，它是导致成年人牙齿丧失的主要原因<font color="#0020ff"><font color="#000000">。</font></font><span style="color:#ff8c00;"><strong>&gt;&gt;&gt;我的情况是属于牙周炎吗?点击咨询客服&gt;&gt;&gt;</strong></span></p>
<p><font color="#0020ff"><strong>　　</strong></font></p>
<center>
	<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><img alt="" src="/uploads/allimg/c180322/1521DZ0002W0-15031.png" style="width: 326px; height: 212px;" /></a></center>
<p>&nbsp;</p>
<p><span style="color:#008080;">　　<strong>维尔口腔医生介绍：牙周炎怎么治疗?</strong></span></p>
<p><span style="background-color:#ffffff;">　</span><strong><span style="background-color:#ffffff;">　</span><span style="color:#808080;"><font style="BACKGROUND-COLOR: #ffff00"><span style="background-color:#ffffff;">一、轻度牙周炎 - 牙龈炎</span></font></span></strong></p>
<p>　　牙周炎早期佳的治疗方法就是洗牙，除去口腔内的牙菌斑和牙石。但是传统的洗牙的弊端在于比较痛，会出比较多的血，洗后牙齿表面比较粗糙。维尔超声波洁牙能在瞬间柔和地清除牙垢、牙菌斑,并且在洁治过程中对釉质几乎无损害，消除导致牙周炎症的牙结石。 <a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;"><strong>&gt;&gt;&gt;点击预约洁牙&gt;&gt;&gt;</strong></span></a></p>
<p><span style="color:#808080;">　　<strong>诊疗技术：<font style="BACKGROUND-COLOR: #0020ff"><span style="background-color:#ffffff;">维尔超声波洁牙</span></font></strong></span></p>
<p>　　1、不伤牙：在洁牙过程中震动感更小、更柔和、更舒适，不伤牙齿。</p>
<p>　　2、祛除表面色素：使用特殊喷砂颗粒,清楚牙齿表面，从而达到去除牙齿表面烟斑、茶渍、咖啡渍等色素沉着。</p>
<p>　　3、自然光泽：喷砂提高牙齿的光泽度，使牙齿亮白。</p>
<p>　　4、预防牙龈炎症和出血：有效去除牙结石、牙垢等，预防和延缓食物残渣在牙齿表面聚集，进而预防牙龈发炎、出血和萎缩。</p>
<p>　　</p>
<center>
	<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><img alt="" src="/uploads/allimg/c180322/1521DZ00a110-22920.jpg" style="width: 300px; height: 180px;" /></a></center>
<p>&nbsp;</p>
<p><span style="background-color:#ffffff;">　　</span><span style="color:#808080;"><font style="BACKGROUND-COLOR: #ffff00"><strong><span style="background-color:#ffffff;">二、牙周炎中期 - 炎症恶化出现牙周脓袋易出血</span></strong></font></span></p>
<p>　　这时候的牙周炎已经发展到很严重的阶段，仅仅定期的洁治(洗牙)已经不能使治疗牙龈出血，只有采取刮治和其它牙周治疗或牙周手术治疗，才能缓解病症。&gt;&gt;&gt;我的情况是不是属于牙周炎中期，点击咨询&gt;&gt;&gt;</p>
<p><strong><span style="color:#808080;"><span style="background-color:#ffffff;">　　诊疗技术：</span><font style="BACKGROUND-COLOR: #0020ff"><span style="background-color:#ffffff;">维尔水激光刮治</span></font></span></strong></p>
<p>　　水光动能现象和一般的牙钻不同之处在于：在作用于硬组织时，它不会出现振动，也不会产生热量，能使患者的神经不会感觉过分敏感而产生疼痛。由于2780nm激光能量直接作用于软组织，并有恰当的吸水率，因此可获得较佳的切割和止血效果，创面不会产生结痂区。&gt;&gt;&gt;点击咨询水激光刮治技术的详细情况&gt;&gt;&gt;</p>
<p>　　</p>
<center>
	<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><img alt="" src="/uploads/allimg/c180322/1521DZ0145A0-3OV.jpg" style="width: 300px; height: 180px;" /></a></center>
<p>&nbsp;</p>
<p><span style="color:#808080;"><span style="background-color:#ffffff;">　　</span><strong><font style="BACKGROUND-COLOR: #ffff00"><span style="background-color:#ffffff;">三、牙周病后期 - 牙槽骨与牙周韧带破坏</span></font></strong></span></p>
<p><strong><span style="color:#808080;"><span style="background-color:#ffffff;">　　诊疗技术：</span><font style="BACKGROUND-COLOR: #0020ff"><span style="background-color:#ffffff;">龈下刮治术</span></font></span></strong></p>
<p>　　龈下刮治术，是用比较精细的龈下刮治器刮除位于牙周袋内根面上的牙石和菌斑。而我们一般通过龈下刮治术，也就是通俗所说的&quot;深层洁牙&quot;来去除深在的牙石菌斑。而根面平整术即为龈下洁治术的继续和完善。</p>
<p>　　</p>
<center>
	<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><img alt="" src="/uploads/allimg/c180322/1521DZ0191260-45U4.jpg" style="width: 300px; height: 180px;" /></a></center>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;">　　<strong>&gt;&gt;&gt;我的情况适合哪种治疗方式?点击咨询在线客服&gt;&gt;&gt;</strong></span></a></p>
<p><span style="color:#008080;">　　<strong>治疗牙周炎，维尔值得您信赖</strong></span></p>
<p>　　<span style="color:#808080;"><strong>高效精准：</strong></span>数字化全面检查，准确了解口腔状况，医学组成员亲自操作，快速解决疑难根管问题;</p>
<p>　　<span style="color:#808080;"><strong>舒适：</strong></span>采用先进的根管技术，防止根管壁侧穿、偏移根尖等发生，减少就诊时间，整个过程舒适;</p>
<p>　　<span style="color:#808080;"><strong><span style="background-color:#ffffff;">健康卫生：</span></strong></span>根管治疗材料通过药监部门层层审核，不影响口腔健康，保障口腔健康</p>
<p>　　<span style="color:#808080;"><strong><span style="background-color:#ffffff;">避免感染：</span></strong></span>推行阳光无菌诊疗模式，配备消毒中心，采用十一个无菌诊疗服务，防止交叉感染。 <strong><span style="color:#ff8c00;">&gt;</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;">&gt;&gt;点击此处，预约维尔口腔专业治疗牙周炎</span></a></strong></p>
<p>　　维尔口腔，19多年荣誉铸就，精益求精</p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn">　　<img alt="" src="/uploads/allimg/c180322/1521DZ02IW0-53626.png" style="width: 400px; height: 250px;" /></a></p>
<center style="text-align: center;">
	&nbsp;</center>
<p style="text-align: center;">&nbsp;</p>
<p>　　北京维尔口腔医院是一所融医疗、教学、科研、急救医学、预防保健为一体的综合性医院，医院医生云集、医术精湛，拥有国内外先进的检验、治疗仪、设施先进、服务温馨，采用标准的&ldquo;一人一医一诊室&rdquo;的个性人性化设置，实施&ldquo;专科、专病、专治&rdquo;的诊疗方针。</p>
<p>　　北京维尔口腔医院主要致力于口腔医疗先进技术的引进、消化和研究。聘请美国、韩国、德国和内地的医生为技术顾问，成立口腔医学医生委员会。形成维尔口腔医院在口腔医疗领域的技术特色和专业保障。卓越的医疗技术、一流的医生资源、国内外先进的医疗设备，为客户提供上佳的医疗体验和保障。<font color="#0020ff"><strong>&nbsp;</strong></font><strong><font color="#0020ff">&nbsp;</font><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#ff8c00;">&gt;&gt;&gt;点击此处，预约维尔口腔专业治疗牙周炎</span></a></strong></p>
<p>　　如果您还有想要了解的情况，可以点击我们的<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn"><span style="color:#008080;"><strong>【在线咨询】</strong></span></a>，我们的在线客服会给您较专业，较详细的解答，或是拨打我们的24小时美牙咨询热线400/6655111。维尔口腔专业咨询会给您耐心的，详细的解答，并给您一个满意的答复!</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DZ0002W0-15031_lit.png{/dede:field}
