{dede:field name='keywords'}种牙疼吗{/dede:field}
{dede:field name='description'}种植牙不算是大手术，只要没有严重的高血压、心脏病、糖尿病等其它的血液疾病，拔牙可以做，那么种植牙就可以做，疼痛的程度比拔牙要好{/dede:field}
{dede:field name='title'}种牙疼吗{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">&nbsp; &nbsp; 种植牙不算是大手术，只要没有严重的高血压、心脏病、糖尿病等其它的血液疾病，拔牙可以做，那么种植牙就可以做，疼痛的程度比拔牙要好一点点，种牙好后两三天内会有胀胀的感觉，但是适应几天就好了。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="种植牙流程" src="/uploads/allimg/c180322/1521D3R04O20-12017.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 165px;" /></a></span></div>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">维尔口腔种植中心简介</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 种植牙是通过外科手术的方式将人工牙根植入牙槽骨内，再在人工牙根上制作烤瓷冠，从而制作出近似真牙的牙齿。很多人对种植牙的寿命、种植牙的价格、种植牙好不好等问题有所疑问,我们维尔口腔医师针对这些疑问指出影响种植牙的寿命和价格的因素! <a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><strong><span style="color:#ff0000;">查询多大年龄可以做种植牙</span></strong></a></span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔全力巨资引进较先进的奥齿泰种植系统，奥齿泰OSSTEM种植牙是口腔种植行业的市场较早品牌。产品先后得相关认证。经过众多临床手术，在临床上得到好的检验。多样化的系列产品选择，根据不同的口腔环境和外壳位置变化，方便植入、高成功率，达到较佳的使用效果。</span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">奥齿泰OSSTEM种植系统特点：</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔采用的 OSSTEM(奥齿泰)种植系统它具有两大特点：一、稳定性好：具有强固位和稳定性，可像接近真牙扎在患者的口腔里;二、不伤真牙：种植中可少磨或不磨自己的真牙，保护原来的牙齿。 OSSTEM(奥齿泰)种植系统应用在口腔手术中，在口腔CT三维重建制作种植导板辅助下于下颌骨模型植入种植体具有较高的精度,对于辅助临床种植体植入具有较高的价值。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询在线医生</strong></span></a></span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">维尔口腔医院，专业塑造品牌！</span></span></h2>
</section>
</div>
</div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　1、专业团队 放心诊疗</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　国内知名口腔教授刘志杰领衔的口腔医师团队，让您轻松拥有自然、美观、精细、逼真的牙齿。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　2、即刻手术 节约时长</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔引进先进技术，手术过程仅需5-10分钟，短暂的手术时间降低了手术风险;仅需一次手术，恒久支撑牙冠，咀嚼更给力。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　3、品牌优势 个性修复</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔安全放心，材质安全无害，经久耐用，治疗时会根据顾客牙齿的颜色与形状等实际情况来综合考量，力求整体协调和美观的效果。</span><br />
&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn"><img alt="" src="/uploads/allimg/c180322/1521D3R22O40-215N.jpg" style="width: 450px; height: 280px;" /></a><br />
&nbsp;</div>
<div><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></div>{/dede:field}
{dede:field name='pubdate'}1521683824{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D3R04O20-12017_lit.jpg{/dede:field}
