<div class="ykzs_title">
                        <div class="title_yxjz">
                            <div class="yxjz_img">
                                <img src="[field:picname/]" width="237" height="169">
                            </div>
                            <div class="yxjz_font">
                                <span>[field:title/]</span>
                                <span>[field:description function="cn_substr(@me,500)"/]</span>
                                <a href="[field:typeurl/]"><span>【查看详情】</span></a>
                            </div>
                            <div style="clear:both"></div>
                        </div>
                    </div>