<?php
$z[0]=Array("field","北京,院长,都市",0,61);
$z[0][4]['name']="keywords";
$z[1]=Array("field","北京维尔口腔全国连锁医院自成立以来秉承服务至上精益求精的理念，特聘各大公立医院口腔博士、专家,拥有数十年丰富的临床经验,让顾客在治疗过程中感觉专业、安全、放心。热线电",63,352);
$z[1][4]['name']="description";
$z[2]=Array("field","北京中科创新院院长称赞维尔技术发展领跑牙科行业",354,461);
$z[2][4]['name']="title";
$z[3]=Array("field","",463,502);
$z[3][4]['name']="writer";
$z[4]=Array("field","",504,543);
$z[4][4]['name']="source";
$z[5]=Array("field","<embed allowscriptaccess=\"always\" bgcolor=\"#000000\" flashvars=\"autoplay=1&amp;skin=http://beij.wekq.net/statics/js/ckeditor/plugins/flashplayer/player/skin.swf&amp;video=http://video.wekq.net/video/MV_1.flv&amp;thumbnail=\" height=\"400px\" hspace=\"40\" id=\"f4Player\" quality=\"high\" src=\"http://beij.wekq.net/statics/js/ckeditor/plugins/flashplayer/player/player.swf\" type=\"application/x-shockwave-flash\" width=\"640px\" wmode=\"transparent\"></embed>",545,1028);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<embed allowscriptaccess=\"always\" bgcolor=\"#000000\" flashvars=\"autoplay=1&amp;skin=http://beij.wekq.net/statics/js/ckeditor/plugins/flashplayer/player/skin.swf&amp;video=http://video.wekq.net/video/MV_1.flv&amp;thumbnail=\" height=\"400px\" hspace=\"40\" id=\"f4Player\" quality=\"high\" src=\"/uploads/allimg/c180407/15230A3212NZ-62303.swf\" type=\"application/x-shockwave-flash\" width=\"640px\" wmode=\"transparent\"></embed>",1030,1478);
$z[6][4]['name']="body";
$z[7]=Array("field","",1480,1519);
$z[7][4]['name']="litpic";

?>