{dede:field name='keywords'}北京,院长,都市{/dede:field}
{dede:field name='description'}北京维尔口腔全国连锁医院自成立以来秉承服务至上精益求精的理念，特聘各大公立医院口腔博士、专家,拥有数十年丰富的临床经验,让顾客在治疗过程中感觉专业、安全、放心。热线电{/dede:field}
{dede:field name='title'}北京中科创新院院长称赞维尔技术发展领跑牙科行业{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<embed allowscriptaccess="always" bgcolor="#000000" flashvars="autoplay=1&amp;skin=http://beij.wekq.net/statics/js/ckeditor/plugins/flashplayer/player/skin.swf&amp;video=http://video.wekq.net/video/MV_1.flv&amp;thumbnail=" height="400px" hspace="40" id="f4Player" quality="high" src="http://beij.wekq.net/statics/js/ckeditor/plugins/flashplayer/player/player.swf" type="application/x-shockwave-flash" width="640px" wmode="transparent"></embed>{/dede:field}
{dede:field name='body'}<embed allowscriptaccess="always" bgcolor="#000000" flashvars="autoplay=1&amp;skin=http://beij.wekq.net/statics/js/ckeditor/plugins/flashplayer/player/skin.swf&amp;video=http://video.wekq.net/video/MV_1.flv&amp;thumbnail=" height="400px" hspace="40" id="f4Player" quality="high" src="/uploads/allimg/c180407/15230A3212NZ-62303.swf" type="application/x-shockwave-flash" width="640px" wmode="transparent"></embed>{/dede:field}
{dede:field name='litpic'}{/dede:field}
