{dede:field name='keywords'}肿痛,智齿,牙龈{/dede:field}
{dede:field name='description'}孕妇长智齿牙龈肿痛怎么办?这是困扰很多人的一个问题，众所周知，孕妇这个特殊群体是不能被当做是普通的智齿去治疗，智齿，学名第三大{/dede:field}
{dede:field name='title'}孕妇长智齿牙龈肿痛怎么办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">&nbsp; &nbsp; 孕妇长智齿牙龈肿痛怎么办?这是困扰很多人的一个问题，众所周知，孕妇这个特殊群体是不能被当做是普通的智齿去治疗，智齿，学名第三大臼齿，俗称智慧齿，是口腔较靠近喉咙的牙齿，如果全部生长出来一共4颗，上下颚各两颗，一般是于16岁或之后才生长出来，一般刚开始长智齿，很多人容易会有牙痛的，严重的还是牙龈肿痛的症状。那么下面就由维尔口腔的医师们就这几个问题给大家做一下简单介绍孕妇长智齿牙龈肿痛怎么办。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="阻生智齿X光片" src="http://beij.wekq.net/uploadfile/2017/0706/20170706020151589.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 216px;" /></a></span></div>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">怀孕期间可以拔牙吗？</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 由于怀孕期间拔牙是有一定风险的，通常医生也会建议生完小孩后再拔牙，同时孕妇对许多止痛药物和抗生素都有很严的禁忌规定的，所以也不能滥用这些止痛药物。</span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 建议可使用一些没有明显问题的口腔护理品，植物成份的口含片直接对肿痛患处起作用不需要经过消化系统，因此不会对孕妇造成不利影响。</span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 如果牙龈肿痛同时出现上呼吸道感染的症状(如舌苔黄、喉痛、淋巴结痛、便秘等)，可咨询妇产科医生，看看能否用些牛黄解毒片来消除控制，牛黄解毒片的副作用肯定没有抗生素来得大。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0706/20170706020537990.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">&nbsp; &nbsp; 孕妇长智齿牙龈肿痛怎么办?这是困扰很多人的一个问题，众所周知，孕妇这个特殊群体是不能被当做是普通的智齿去治疗，智齿，学名第三大臼齿，俗称智慧齿，是口腔较靠近喉咙的牙齿，如果全部生长出来一共4颗，上下颚各两颗，一般是于16岁或之后才生长出来，一般刚开始长智齿，很多人容易会有牙痛的，严重的还是牙龈肿痛的症状。那么下面就由维尔口腔的医师们就这几个问题给大家做一下简单介绍孕妇长智齿牙龈肿痛怎么办。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="阻生智齿X光片" src="/uploads/allimg/c180322/1521DZ1Ha20-194C.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 216px;" /></a></span></div>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">怀孕期间可以拔牙吗？</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 由于怀孕期间拔牙是有一定风险的，通常医生也会建议生完小孩后再拔牙，同时孕妇对许多止痛药物和抗生素都有很严的禁忌规定的，所以也不能滥用这些止痛药物。</span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 建议可使用一些没有明显问题的口腔护理品，植物成份的口含片直接对肿痛患处起作用不需要经过消化系统，因此不会对孕妇造成不利影响。</span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 如果牙龈肿痛同时出现上呼吸道感染的症状(如舌苔黄、喉痛、淋巴结痛、便秘等)，可咨询妇产科医生，看看能否用些牛黄解毒片来消除控制，牛黄解毒片的副作用肯定没有抗生素来得大。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DZ1MQ30-25935.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DZ1Ha20-194C_lit.jpg{/dede:field}
