{dede:field name='keywords'}乳牙{/dede:field}
{dede:field name='description'}乳牙根管治疗。由于孩子孩子没有独立的生活能力以及饮食习惯，因此，孩子中龋齿发病率总是居高不下。有些家长对于龋齿不重视，当孩子牙{/dede:field}
{dede:field name='title'}乳牙需要做根管治疗吗？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size: 16px;">&nbsp; &nbsp; 乳牙根管治疗。由于孩子孩子没有独立的生活能力以及饮食习惯，因此，孩子中龋齿发病率总是居高不下。有些家长对于龋齿不重视，当孩子牙疼的时候才想起来看医生，这时候，龋齿已经很严重，就需要做根管治疗了。那么根管治疗的注意事项有哪些，维尔口腔医师来为我们详细介绍一下。</span><br />
<br />
<div style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="什么是根管治疗" src="http://beij.wekq.net/uploadfile/2017/0709/20170709041735741.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 204px;" /></a></span></div>
<div>&nbsp;</div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">乳牙根管治疗的注意事项：</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">关于乳牙根管治疗的注意事项，维尔口腔医师指出，因为乳牙具有特殊性，因此治疗时应注意：</span></p>
<p><span style="font-size: 16px;">1、术前拍X片，了解根尖周病变和牙根吸收情况。牙根吸收已达1/3以上者，难获良好的疗效。</span></p>
<p><span style="font-size: 16px;">2、预备根管时应测根管长度以防器械超出根尖孔，以免将感染物质推出根尖孔或损伤恒牙胚。</span></p>
<p><span style="font-size: 16px;">3、不用牙胶尖。</span></p>
<p><span style="font-size: 16px;">4、根充剂仅可采用可吸收的糊剂充填，不影响恒牙交替。</span></p>
<p><span style="font-size: 16px;">5、术后应拍X片观察根充情况。</span></p>
<p style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0709/20170709041736430.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size: 16px;">&nbsp; &nbsp; 乳牙根管治疗。由于孩子孩子没有独立的生活能力以及饮食习惯，因此，孩子中龋齿发病率总是居高不下。有些家长对于龋齿不重视，当孩子牙疼的时候才想起来看医生，这时候，龋齿已经很严重，就需要做根管治疗了。那么根管治疗的注意事项有哪些，维尔口腔医师来为我们详细介绍一下。</span><br />
<br />
<div style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="什么是根管治疗" src="/uploads/allimg/c180322/1521D93G22210-V414.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 204px;" /></a></span></div>
<div>&nbsp;</div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">乳牙根管治疗的注意事项：</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">关于乳牙根管治疗的注意事项，维尔口腔医师指出，因为乳牙具有特殊性，因此治疗时应注意：</span></p>
<p><span style="font-size: 16px;">1、术前拍X片，了解根尖周病变和牙根吸收情况。牙根吸收已达1/3以上者，难获良好的疗效。</span></p>
<p><span style="font-size: 16px;">2、预备根管时应测根管长度以防器械超出根尖孔，以免将感染物质推出根尖孔或损伤恒牙胚。</span></p>
<p><span style="font-size: 16px;">3、不用牙胶尖。</span></p>
<p><span style="font-size: 16px;">4、根充剂仅可采用可吸收的糊剂充填，不影响恒牙交替。</span></p>
<p><span style="font-size: 16px;">5、术后应拍X片观察根充情况。</span></p>
<p style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D93GH050-a305.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D93G22210-V414_lit.jpg{/dede:field}
