{dede:field name='keywords'}维尔口腔专家团队赴德进{/dede:field}
{dede:field name='description'}日前，以北京维尔口腔医院医务院长贺彩、北京维尔口腔医院种植院长杨光、上海维尔口腔医院院长汪廷乐、武汉维尔口腔院长李双、北京维尔{/dede:field}
{dede:field name='title'}维尔口腔专家团队赴德进行种植学术交流{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0406/20170406114511925.jpg" style="width: 460px; height: 345px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　日前，以北京维尔口腔医院医务院长贺彩、北京维尔口腔医院种植院长杨光、上海维尔口腔医院院长汪廷乐、武汉维尔口腔院长李双、北京维尔口腔医院修复院长邱星明组成的维尔口腔5人专家团队接受德国法兰克福大学医学院邀请进行种植牙学术交流。</span><br />
&nbsp;</p>
<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0406/20170406114523643.jpg" style="width: 460px; height: 342px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　法兰克福大学是德国享誉 的 国际研究型大学。相比于德国其他历史悠久的名校，建立于1914年的法兰克福大学，于仅百年的发展中迅速繁荣，已有19人获诺贝尔奖(数量全德第5)。作为德国 大学联盟&ldquo;U15大学联盟&rdquo;中的一员，法兰克福大学的排名非常靠前。</span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　在法兰克福大学医学院，维尔口腔的专家团队参观了学院牙科实验教学基地，并通过视频直播的方式观摩德国专家为病人做口腔种植手术的过程。同时，还观看了德国先进的牙科专业手术设备。德国人的严谨、认真的态度，以及先进的专科诊疗设备和细致的服务理念，是有许多值得借鉴的地方。特别是德国牙科医生的匠心精神深得国内同仁的推崇。</span><br />
&nbsp;</p>
<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0406/20170406114531592.jpg" style="width: 460px; height: 345px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　其实，维尔口腔很早就与德国先进的诊疗技术合作。很多年前，维尔口腔就与全球数字化口腔解决方案开拓者德国西诺德公司达成战略合作，斥资数千万引进德国原装进口全套数字口腔诊疗设备，如瓷睿刻(CEREC)椅旁修复系统(3D齿雕技术)，美齿需求可通过计算机三维模拟实现，一次性完成备牙、光学取模、设计、研磨、试戴、安装等全部程序，一小时完成明星美齿&ldquo;定制&rdquo;。打破拔牙、磨牙、取模、刻腊、烧瓷等传统技术的繁琐程序，真正实现烤瓷牙&ldquo;立等可戴&rdquo;。德国3D线体层影像系统(口腔CT)，能直观地发现口腔细微病变，对腔骨组织、下颌关节进行准确诊断，有助于医生更准确地设计治疗方案、评估术后效果。在德国技术支撑的数字化诊疗环境之下，治疗时间有效缩短、患者疼痛明显减轻、交叉感染的可能性也大大降低。</span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　北京维尔口腔医院医务院长贺彩表示，维尔的教学及学术交流不以盈利为目的，而是以振兴中国口腔医疗事业为己任，通过与高等学府的教授、博士学术交流，通过邀请国外专家对中国口腔医生进行教学和培训，以提高国内口腔医生技术水平，技术和潮流接轨，更好地服务于中国口腔患者。同时也为维尔发现人才，留住人才。</span><br />
&nbsp;</p>
<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0406/20170406114539404.jpg" style="width: 460px; height: 345px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　在这次经验交流中，维尔口腔医院的专家还向德国专家介绍了许多国内口腔种植的疑难案例，许多案例甚至让德国专家都叹为观止，特别是维尔口腔使用的中科科技创新发展研究院&ldquo;一日得&rdquo;种植技术，在口腔临床应用方面所取得的成就和经验获得外国同仁的一致赞许。</span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　&ldquo;一日得&rdquo;种植技术是利用四个关键位置的种植体保持牢固半口的所有牙，两颗前牙部位的植体垂直植入牙槽骨，两颗中远部位的植体倾斜角度植入牙槽骨，然后在种植体的基台上安装&ldquo;拱形连桥&rdquo;牙冠，这样整个种植牙的受力就呈现出&ldquo;拱形&rdquo;的特征，受力会均匀地分布到整体，这在建筑学上是更为稳固的形状。这种稳固的结构也使在种牙的当天，就可安装牙冠恢复美观和咀嚼。</span><br />
&nbsp;</p>
<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0406/20170406114550166.jpg" style="width: 460px; height: 343px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　北京维尔口腔医院是一家从事口腔诊疗的专科医院，成立至今已经有19年，在北京、上海、武汉、苏州、沈阳等城市拥有多家直营门诊，汇集了一批国内牙科专家。多年来，维尔口腔多次受邀参加国内外举办的口腔诊疗专业技术的交流活动，学习先进的诊疗技术和先进的服务理念。</span></p>{/dede:field}
{dede:field name='body'}<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="/uploads/allimg/c180407/15230A3OZ430-325T.jpg" style="width: 460px; height: 345px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　日前，以北京维尔口腔医院医务院长贺彩、北京维尔口腔医院种植院长杨光、上海维尔口腔医院院长汪廷乐、武汉维尔口腔院长李双、北京维尔口腔医院修复院长邱星明组成的维尔口腔5人专家团队接受德国法兰克福大学医学院邀请进行种植牙学术交流。</span><br />
&nbsp;</p>
<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="/uploads/allimg/c180407/15230A3P40020-43344.jpg" style="width: 460px; height: 342px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　法兰克福大学是德国享誉 的 国际研究型大学。相比于德国其他历史悠久的名校，建立于1914年的法兰克福大学，于仅百年的发展中迅速繁荣，已有19人获诺贝尔奖(数量全德第5)。作为德国 大学联盟&ldquo;U15大学联盟&rdquo;中的一员，法兰克福大学的排名非常靠前。</span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　在法兰克福大学医学院，维尔口腔的专家团队参观了学院牙科实验教学基地，并通过视频直播的方式观摩德国专家为病人做口腔种植手术的过程。同时，还观看了德国先进的牙科专业手术设备。德国人的严谨、认真的态度，以及先进的专科诊疗设备和细致的服务理念，是有许多值得借鉴的地方。特别是德国牙科医生的匠心精神深得国内同仁的推崇。</span><br />
&nbsp;</p>
<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="/uploads/allimg/c180407/15230A3P94040-52453.jpg" style="width: 460px; height: 345px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　其实，维尔口腔很早就与德国先进的诊疗技术合作。很多年前，维尔口腔就与全球数字化口腔解决方案开拓者德国西诺德公司达成战略合作，斥资数千万引进德国原装进口全套数字口腔诊疗设备，如瓷睿刻(CEREC)椅旁修复系统(3D齿雕技术)，美齿需求可通过计算机三维模拟实现，一次性完成备牙、光学取模、设计、研磨、试戴、安装等全部程序，一小时完成明星美齿&ldquo;定制&rdquo;。打破拔牙、磨牙、取模、刻腊、烧瓷等传统技术的繁琐程序，真正实现烤瓷牙&ldquo;立等可戴&rdquo;。德国3D线体层影像系统(口腔CT)，能直观地发现口腔细微病变，对腔骨组织、下颌关节进行准确诊断，有助于医生更准确地设计治疗方案、评估术后效果。在德国技术支撑的数字化诊疗环境之下，治疗时间有效缩短、患者疼痛明显减轻、交叉感染的可能性也大大降低。</span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　北京维尔口腔医院医务院长贺彩表示，维尔的教学及学术交流不以盈利为目的，而是以振兴中国口腔医疗事业为己任，通过与高等学府的教授、博士学术交流，通过邀请国外专家对中国口腔医生进行教学和培训，以提高国内口腔医生技术水平，技术和潮流接轨，更好地服务于中国口腔患者。同时也为维尔发现人才，留住人才。</span><br />
&nbsp;</p>
<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="/uploads/allimg/c180407/15230A3Q43S0-D931.jpg" style="width: 460px; height: 345px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　在这次经验交流中，维尔口腔医院的专家还向德国专家介绍了许多国内口腔种植的疑难案例，许多案例甚至让德国专家都叹为观止，特别是维尔口腔使用的中科科技创新发展研究院&ldquo;一日得&rdquo;种植技术，在口腔临床应用方面所取得的成就和经验获得外国同仁的一致赞许。</span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　&ldquo;一日得&rdquo;种植技术是利用四个关键位置的种植体保持牢固半口的所有牙，两颗前牙部位的植体垂直植入牙槽骨，两颗中远部位的植体倾斜角度植入牙槽骨，然后在种植体的基台上安装&ldquo;拱形连桥&rdquo;牙冠，这样整个种植牙的受力就呈现出&ldquo;拱形&rdquo;的特征，受力会均匀地分布到整体，这在建筑学上是更为稳固的形状。这种稳固的结构也使在种牙的当天，就可安装牙冠恢复美观和咀嚼。</span><br />
&nbsp;</p>
<p style="text-align: center;"><span style="font-size:16px;"><img alt="" src="/uploads/allimg/c180407/15230A3QT5Z-G310.jpg" style="width: 460px; height: 343px;" /></span><br />
&nbsp;</p>
<p><span style="font-size:16px;">　　北京维尔口腔医院是一家从事口腔诊疗的专科医院，成立至今已经有19年，在北京、上海、武汉、苏州、沈阳等城市拥有多家直营门诊，汇集了一批国内牙科专家。多年来，维尔口腔多次受邀参加国内外举办的口腔诊疗专业技术的交流活动，学习先进的诊疗技术和先进的服务理念。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180407/15230A3OZ430-325T_lit.jpg{/dede:field}
