<?php
$z[0]=Array("addurls","http://beij.weierkq.com/by4/4.html\r\nhttp://beij.weierkq.com/by4/3.html\r\nhttp://beij.weierkq.com/by4/2.html\r\nhttp://beij.weierkq.com/by4/",6,171);
$z[1]=Array("batchrule","",177,210);
$z[2]=Array("regxrule","",216,247);
$z[3]=Array("areastart","<div class=\"left_center auto\">",253,316);
$z[4]=Array("areaend","<div id=\"pages\" class=\"text-c auto\">",322,387);

?>