{dede:noteinfo notename="成人牙齿矫正" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area" musthas="crycjzk"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://beij.weierkq.com/crycjzk/9.html
http://beij.weierkq.com/crycjzk/8.html
http://beij.weierkq.com/crycjzk/7.html
http://beij.weierkq.com/crycjzk/6.html
http://beij.weierkq.com/crycjzk/5.html
http://beij.weierkq.com/crycjzk/4.html
http://beij.weierkq.com/crycjzk/3.html
http://beij.weierkq.com/crycjzk/2.html
http://beij.weierkq.com/crycjzk/{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="left_center auto">{/dede:areastart}
    {dede:areaend}<div id="pages" class="text-c auto">{/dede:areaend}
{/dede:listrule}
