{dede:field name='keywords'}什么是窝沟封闭{/dede:field}
{dede:field name='description'}蛀牙大家都非常熟悉，而说到窝沟封闭很多人还不是很了解，窝沟封闭是蛀牙预防常用的方法，那么具体什么是窝沟封闭呢?什么是窝沟封闭{/dede:field}
{dede:field name='title'}什么是窝沟封闭{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">&nbsp; &nbsp; 蛀牙大家都非常熟悉，而说到窝沟封闭很多人还不是很了解，窝沟封闭是蛀牙预防常用的方法，那么<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>具体什么是窝沟封闭呢?</strong></span></a></span>
<div>&nbsp;</div>
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0929/20170929042801917.jpg" style="width: 300px; height: 216px;" /></a></span></div>
<div><span style="color:#ff0000;"><strong style="font-size: 16px;">什么是窝沟封闭</strong></span></div>
<p><span style="font-size:16px;">　　窝沟封闭是目前拥有蛀牙预防常用的方法，窝沟封闭是指不损伤牙体组织，将窝沟封闭材料涂布于牙冠咬合面、颊舌面的窝沟点隙，当它流入并渗透窝沟后固化变硬，形成一层保护性的屏障，覆盖在窝沟上，能够阻止致龋菌及酸性代谢产物对牙体的侵蚀，以达到预防窝沟龋的方法。窝沟封闭的过程一般如下：</span></p>
<p><span style="font-size:16px;">　　用小毛刷蘸取适量清洁剂于牙面，对牙面和窝沟来回刷洗约1分钟，同时不断滴水保持毛刷湿润。</span></p>
<p><span style="font-size:16px;">　　清洁牙面后需要用棉纱球简易隔湿，用压缩空气将牙面吹干后，再用小棉球或细毛刷蘸取酸蚀剂放在要封闭的牙面上。</span></p>
<p><span style="font-size:16px;">　　酸蚀后用水加压彻底的冲洗牙面10&mdash;15秒，去除牙釉质表面和反应沉淀物。冲洗的同时需使用吸唾器随时吸净口内唾液。</span></p>
<p><span style="font-size:16px;">　　用洗刷笔蘸取适量封闭剂涂布在经酸蚀后的牙面上。注意沿窝沟从远中向近中逐渐涂布，同时细刷笔上下微微抖动，使封闭剂渗入窝沟，排除窝沟内的空气，防止封闭剂下面出现空隙。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询在线医生</strong></span></a></span></p>
<p><span style="font-size:16px;">　　固化封闭剂涂布后，立即用可见光源照射，引发固化。</span></p>
<p><span style="font-size:16px;">　　等封闭剂固化后，用尖锐的探针进行全面检查，观察其固化程度，与牙面的粘接情况，确认有无气泡存在，检查咬合是否过高，如果发现问题及时处理。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0929/20170929043044269.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size:16px;">　　维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">&nbsp; &nbsp; 蛀牙大家都非常熟悉，而说到窝沟封闭很多人还不是很了解，窝沟封闭是蛀牙预防常用的方法，那么<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>具体什么是窝沟封闭呢?</strong></span></a></span>
<div>&nbsp;</div>
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0929/20170929042801917.jpg" style="width: 300px; height: 216px;" /></a></span></div>
<div><span style="color:#ff0000;"><strong style="font-size: 16px;">什么是窝沟封闭</strong></span></div>
<p><span style="font-size:16px;">　　窝沟封闭是目前拥有蛀牙预防常用的方法，窝沟封闭是指不损伤牙体组织，将窝沟封闭材料涂布于牙冠咬合面、颊舌面的窝沟点隙，当它流入并渗透窝沟后固化变硬，形成一层保护性的屏障，覆盖在窝沟上，能够阻止致龋菌及酸性代谢产物对牙体的侵蚀，以达到预防窝沟龋的方法。窝沟封闭的过程一般如下：</span></p>
<p><span style="font-size:16px;">　　用小毛刷蘸取适量清洁剂于牙面，对牙面和窝沟来回刷洗约1分钟，同时不断滴水保持毛刷湿润。</span></p>
<p><span style="font-size:16px;">　　清洁牙面后需要用棉纱球简易隔湿，用压缩空气将牙面吹干后，再用小棉球或细毛刷蘸取酸蚀剂放在要封闭的牙面上。</span></p>
<p><span style="font-size:16px;">　　酸蚀后用水加压彻底的冲洗牙面10&mdash;15秒，去除牙釉质表面和反应沉淀物。冲洗的同时需使用吸唾器随时吸净口内唾液。</span></p>
<p><span style="font-size:16px;">　　用洗刷笔蘸取适量封闭剂涂布在经酸蚀后的牙面上。注意沿窝沟从远中向近中逐渐涂布，同时细刷笔上下微微抖动，使封闭剂渗入窝沟，排除窝沟内的空气，防止封闭剂下面出现空隙。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询在线医生</strong></span></a></span></p>
<p><span style="font-size:16px;">　　固化封闭剂涂布后，立即用可见光源照射，引发固化。</span></p>
<p><span style="font-size:16px;">　　等封闭剂固化后，用尖锐的探针进行全面检查，观察其固化程度，与牙面的粘接情况，确认有无气泡存在，检查咬合是否过高，如果发现问题及时处理。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0929/20170929043044269.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size:16px;">　　维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D924610460-3Ja_lit.jpg{/dede:field}
