{dede:noteinfo notename="植牙案例" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area" musthas="zzal"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}beij.weierkq.com/zzal/{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="al_list">{/dede:areastart}
    {dede:areaend}<div class="zj_fenye">
{/dede:areaend}
{/dede:listrule}
