{dede:field name='keywords'}一般根管治疗多久{/dede:field}
{dede:field name='description'}很多牙痛患者看牙病的时候都会被建议做根管治疗。随着生活节奏加快，很多人工作比较忙，相信对于想做根管治疗的人来说，想知道的莫过于{/dede:field}
{dede:field name='title'}一般根管治疗多久{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}&nbsp; &nbsp; 很多牙痛患者看牙病的时候都会被建议做根管治疗。随着生活节奏加快，很多人工作比较忙，相信对于想做根管治疗的人来说，想知道的莫过于根管治疗需要多长时间。
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0603/20170603045603896.jpg" style="width: 300px; height: 200px;" /></a></p>
<p><span style="color: rgb(255, 0, 0);"><strong>根管治疗要多久?</strong></span></p>
<p>&nbsp; &nbsp; 维尔医师表示，根管治疗一般要经过两大的步骤，一次消炎，第二次根管治疗。相隔时间为一周，顺利的话一周就能完成。有时候根据患者的具体情况或医生的手法会有一点不同，可能间隔3天，也可能时间会更长点。</p>
<p>&nbsp; &nbsp; 在牙齿根管治疗过程中，正常情况下，如果是前牙，每次20分钟左右，如果是后牙，每次40分钟左右。根管治疗手术后一般需要来院复诊3到5次。另外，根管治疗只有选择正规医院才能保证根管治疗的效果。</p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0212/20180212101728928.jpg" style="width: 550px; height: 130px;" /></a></p>
<p><span style="color: rgb(255, 0, 0);"><strong>根管治疗时需要注意以下几方面的事项：</strong></span></p>
<p>1、由于根管治疗术较繁杂，要求医生必须熟悉牙体结构的解剖知识及熟练操作技术，同时需要专用配套的根管治疗器械及设备和材料。因而，根管治疗术较费时且费用相对较高些。</p>
<p>2、根管治疗期间或完成后可能出现短暂不适，通常服用消炎或止痛药可缓解，局部出现肿痛应告知医生处理。</p>
<p>3、牙齿治疗后脆性较大比较好行嵌体或冠修复，防止牙齿折裂，延长牙齿的寿命。</p>
<p><span style="color: rgb(255, 0, 0);"><strong>维尔技术推荐根管治疗</strong></span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0603/20170603045637877.jpg" style="width: 450px; height: 280px;" /></a></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><strong><span style="color: rgb(255, 0, 0);">【在线咨询】【在线预约】</span></strong></a></p>
<p>&nbsp; &nbsp; 根管治疗是牙髓病和根尖周病的国际上常用的有效治疗方法，其原理是通过机械和化学方法去除根管内的大部分感染物，并通 过充填根管、封闭冠部，防止发生根尖周病变或促进已经发生的根尖周病变的愈合。根管治疗的成功率高达90%以上，是目前保存病牙的治疗方法，也是残根、残冠 能选择的治疗方法，可谓是一项&ldquo;救牙工程&rdquo;。</p>
<p><span style="color: rgb(255, 0, 0);"><strong>&nbsp; &nbsp;【温馨提示】</strong></span>为避免后期牙病复发或感染病菌，一定去正规的医院去治疗，先进的技术设备加经验丰富的医师才会让你的治疗效果更快，更持久，维尔口腔秉承患者需要一、规矩行医、人文关怀精神，并引进新的医疗设备和技术，并吸纳来自各国医疗精英加盟，组成国际化口腔医师团队，确保维尔的技术同步国际水平，打造安全、专业、时尚、舒适的诊疗环境，创造高品质就医享受。如果还有其他疑问，可<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><strong><span style="color: rgb(255, 0, 0);">在线咨询</span></strong></a>，与医师一对一交流，或拨打健康热线：<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><font color="#ff0000"><span style="font-size: 14px;"><b>400-6655-111</b></span></font></a>！</p>{/dede:field}
{dede:field name='body'}&nbsp; &nbsp; 很多牙痛患者看牙病的时候都会被建议做根管治疗。随着生活节奏加快，很多人工作比较忙，相信对于想做根管治疗的人来说，想知道的莫过于根管治疗需要多长时间。
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DV5M5P-595O.jpg" style="width: 300px; height: 200px;" /></a></p>
<p><span style="color: rgb(255, 0, 0);"><strong>根管治疗要多久?</strong></span></p>
<p>&nbsp; &nbsp; 维尔医师表示，根管治疗一般要经过两大的步骤，一次消炎，第二次根管治疗。相隔时间为一周，顺利的话一周就能完成。有时候根据患者的具体情况或医生的手法会有一点不同，可能间隔3天，也可能时间会更长点。</p>
<p>&nbsp; &nbsp; 在牙齿根管治疗过程中，正常情况下，如果是前牙，每次20分钟左右，如果是后牙，每次40分钟左右。根管治疗手术后一般需要来院复诊3到5次。另外，根管治疗只有选择正规医院才能保证根管治疗的效果。</p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0212/20180212101728928.jpg" style="width: 550px; height: 130px;" /></a></p>
<p><span style="color: rgb(255, 0, 0);"><strong>根管治疗时需要注意以下几方面的事项：</strong></span></p>
<p>1、由于根管治疗术较繁杂，要求医生必须熟悉牙体结构的解剖知识及熟练操作技术，同时需要专用配套的根管治疗器械及设备和材料。因而，根管治疗术较费时且费用相对较高些。</p>
<p>2、根管治疗期间或完成后可能出现短暂不适，通常服用消炎或止痛药可缓解，局部出现肿痛应告知医生处理。</p>
<p>3、牙齿治疗后脆性较大比较好行嵌体或冠修复，防止牙齿折裂，延长牙齿的寿命。</p>
<p><span style="color: rgb(255, 0, 0);"><strong>维尔技术推荐根管治疗</strong></span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DV5X00Z-MH5.jpg" style="width: 450px; height: 280px;" /></a></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><strong><span style="color: rgb(255, 0, 0);">【在线咨询】【在线预约】</span></strong></a></p>
<p>&nbsp; &nbsp; 根管治疗是牙髓病和根尖周病的国际上常用的有效治疗方法，其原理是通过机械和化学方法去除根管内的大部分感染物，并通 过充填根管、封闭冠部，防止发生根尖周病变或促进已经发生的根尖周病变的愈合。根管治疗的成功率高达90%以上，是目前保存病牙的治疗方法，也是残根、残冠 能选择的治疗方法，可谓是一项&ldquo;救牙工程&rdquo;。</p>
<p><span style="color: rgb(255, 0, 0);"><strong>&nbsp; &nbsp;【温馨提示】</strong></span>为避免后期牙病复发或感染病菌，一定去正规的医院去治疗，先进的技术设备加经验丰富的医师才会让你的治疗效果更快，更持久，维尔口腔秉承患者需要一、规矩行医、人文关怀精神，并引进新的医疗设备和技术，并吸纳来自各国医疗精英加盟，组成国际化口腔医师团队，确保维尔的技术同步国际水平，打造安全、专业、时尚、舒适的诊疗环境，创造高品质就医享受。如果还有其他疑问，可<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><strong><span style="color: rgb(255, 0, 0);">在线咨询</span></strong></a>，与医师一对一交流，或拨打健康热线：<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><font color="#ff0000"><span style="font-size: 14px;"><b>400-6655-111</b></span></font></a>！</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DV5M5P-595O_lit.jpg{/dede:field}
