<?php
$z[0]=Array("type","\r\n        <a href=\"[field:typeurl/]\">\r\n            <li>\r\n                <span class=\"icon_img_2\"></span>\r\n                <span>[field:typename/]</span>\r\n            </li>\r\n        </a>",261,481);
$z[0][4]['typeid']="3";
$z[1]=Array("type","\r\n        <a href=\"[field:typeurl/]\">\r\n            <li>\r\n                <span class=\"icon_img_3\"></span>\r\n                <span>[field:typename/]</span>\r\n            </li>\r\n        </a>",482,702);
$z[1][4]['typeid']="7";
$z[2]=Array("type","\r\n        <a href=\"[field:typeurl/]\">\r\n            <li>\r\n                <span class=\"icon_img_4\"></span>\r\n                <span>[field:typename/]</span>\r\n            </li>\r\n        </a>",703,923);
$z[2][4]['typeid']="3";
$z[3]=Array("type","\r\n        <a href=\"[field:typeurl/]\">\r\n            <li>\r\n                <span class=\"icon_img_5\"></span>\r\n                <span>[field:typename/]</span>\r\n            </li>\r\n        </a>",924,1144);
$z[3][4]['typeid']="1";

?>