{dede:noteinfo notename="牙齿贴面" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://beij.weierkq.com/yctmz/(*).html"
startid="2" endid="3" addv="1" urlrule="area" musthas="http://beij.weierkq.com/yctmz/"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="left_center auto">
{/dede:areastart}
    {dede:areaend}<div id="pages" class="text-c auto">{/dede:areaend}
{/dede:listrule}
