<?php
$z[0]=Array("addurls","http://beij.weierkq.com/ycjzffj/5.html\r\nhttp://beij.weierkq.com/ycjzffj/4.html\r\nhttp://beij.weierkq.com/ycjzffj/3.html\r\nhttp://beij.weierkq.com/ycjzffj/2.html\r\nhttp://beij.weierkq.com/ycjzffj/",6,227);
$z[1]=Array("batchrule","",233,266);
$z[2]=Array("regxrule","",272,303);
$z[3]=Array("areastart","<div class=\"left_center auto\">",309,372);
$z[4]=Array("areaend","<div id=\"pages\" class=\"text-c auto\">",378,443);

?>