{dede:field name='keywords'}时候{/dede:field}
{dede:field name='description'}很多人遇到蛀牙或者牙齿缺失的情况，就会到医院进行补牙，补牙在口腔专业中称作充填术，为很多人解决了牙齿的疾病，现在有一部分人牙齿{/dede:field}
{dede:field name='title'}补牙的时候会疼吗{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">&nbsp; &nbsp; 很多人遇到蛀牙或者牙齿缺失的情况，就会到医院进行补牙，补牙在口腔专业中称作充填术，为很多人解决了牙齿的疾病，现在有一部分人牙齿有问题，而担心补牙会造成疼痛，不愿意去医院补牙，那么补牙的时候会疼吗?下面就来看一下医师对补牙的时候会不会疼是怎么介绍的。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="补牙前后对比" src="/uploadfile/2017/0809/20170809020150339.jpg" style="border-width: 0px; border-style: solid; width: 400px; height: 162px;" /></a></span><br />
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">补牙的时候会疼吗？</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">一、是因为在补牙制备洞形的过程中或消毒药物刺激牙髓所致，可能出现短时的冷热刺激痛，此类情况不需作特殊处理，1-2日后一般可自行恢复。</span></p>
<p><span style="font-size:16px;">二、是龋洞较深，用的衬垫材料太薄，不能隔断银汞合金传导的冷热刺激，而出现冷热刺激痛的症状。这就需要加厚垫底材料后再作充填。</span></p>
<p><span style="font-size:16px;">三、是因治疗需要，对牙髓进行失活(俗称杀神经)，在封失活药后的短时间或次日因为药物作用有可能出现牙痛，但疼痛不会很剧烈并且不会持续很长时间。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="color: rgb(255, 0, 0);">查询银汞材料和树脂材料的详细对比</span></strong></a></span></p>
<p><span style="font-size:16px;">四、补牙后近期出现刺激痛或自发痛的原因可能是充填材料中的某些化学物质刺激牙髓或根尖组织所致;也可能是牙髓失活不全所致。</span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">维尔口腔医院，专业塑造品牌！</span></span></h2>
</section>
</div>
</div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　1、专业团队 放心诊疗</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　国内知名口腔教授刘志杰领衔的口腔医师团队，让您轻松拥有自然、美观、精细、逼真的牙齿。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　2、即刻手术 节约时长</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔引进先进技术，手术过程仅需5-10分钟，短暂的手术时间降低了手术风险;仅需一次手术，恒久支撑牙冠，咀嚼更给力。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　3、品牌优势 个性修复</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔安全放心，材质安全无害，经久耐用，治疗时会根据顾客牙齿的颜色与形状等实际情况来综合考量，力求整体协调和美观的效果。</span></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0809/20170809020418209.jpg" style="width: 450px; height: 280px;" /></span></a></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">&nbsp; &nbsp; 很多人遇到蛀牙或者牙齿缺失的情况，就会到医院进行补牙，补牙在口腔专业中称作充填术，为很多人解决了牙齿的疾病，现在有一部分人牙齿有问题，而担心补牙会造成疼痛，不愿意去医院补牙，那么补牙的时候会疼吗?下面就来看一下医师对补牙的时候会不会疼是怎么介绍的。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="补牙前后对比" src="/uploadfile/2017/0809/20170809020150339.jpg" style="border-width: 0px; border-style: solid; width: 400px; height: 162px;" /></a></span><br />
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">补牙的时候会疼吗？</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">一、是因为在补牙制备洞形的过程中或消毒药物刺激牙髓所致，可能出现短时的冷热刺激痛，此类情况不需作特殊处理，1-2日后一般可自行恢复。</span></p>
<p><span style="font-size:16px;">二、是龋洞较深，用的衬垫材料太薄，不能隔断银汞合金传导的冷热刺激，而出现冷热刺激痛的症状。这就需要加厚垫底材料后再作充填。</span></p>
<p><span style="font-size:16px;">三、是因治疗需要，对牙髓进行失活(俗称杀神经)，在封失活药后的短时间或次日因为药物作用有可能出现牙痛，但疼痛不会很剧烈并且不会持续很长时间。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="color: rgb(255, 0, 0);">查询银汞材料和树脂材料的详细对比</span></strong></a></span></p>
<p><span style="font-size:16px;">四、补牙后近期出现刺激痛或自发痛的原因可能是充填材料中的某些化学物质刺激牙髓或根尖组织所致;也可能是牙髓失活不全所致。</span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">维尔口腔医院，专业塑造品牌！</span></span></h2>
</section>
</div>
</div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　1、专业团队 放心诊疗</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　国内知名口腔教授刘志杰领衔的口腔医师团队，让您轻松拥有自然、美观、精细、逼真的牙齿。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　2、即刻手术 节约时长</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔引进先进技术，手术过程仅需5-10分钟，短暂的手术时间降低了手术风险;仅需一次手术，恒久支撑牙冠，咀嚼更给力。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　3、品牌优势 个性修复</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔安全放心，材质安全无害，经久耐用，治疗时会根据顾客牙齿的颜色与形状等实际情况来综合考量，力求整体协调和美观的效果。</span></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0809/20170809020418209.jpg" style="width: 450px; height: 280px;" /></span></a></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DT2333450-5Q01_lit.jpg{/dede:field}
