{dede:noteinfo notename="种植牙价格" channelid="1" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas="/zzyjgb/" nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://beij.weierkq.com/zzyjgb/2.html
http://beij.weierkq.com/zzyjgb/3.html
http://beij.weierkq.com/zzyjgb/4.html
http://beij.weierkq.com/zzyjgb/5.html
http://beij.weierkq.com/zzyjgb/6.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="left_center auto">{/dede:areastart}
    {dede:areaend}<div id="pages" class="text-c auto">{/dede:areaend}
{/dede:listrule}
