{dede:field name='keywords'}315北京维尔口腔坚守品质{/dede:field}
{dede:field name='description'}为迎接315消费者权益日，3月15日，以 "诚信医疗服务，维护患者权益 "为主题的北京维尔口腔医院315《诚信医疗承诺书》承诺仪式在京举行，这也标志着医院将诚信医疗、规范办院升级到{/dede:field}
{dede:field name='title'}315北京维尔口腔坚守品质 邀监督员来挑刺{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size: 16px;">&nbsp; &nbsp; &nbsp; 为迎接315消费者权益日，3月15日，以&quot;诚信医疗服务，维护患者权益&quot;为主题的北京维尔口腔医院315《诚信医疗承诺书》承诺仪式在京举行，这也标志着医院将诚信医疗、规范办院升级到新的高度。同时北京维尔口腔医院开展了&quot;种植牙品质监督月&quot;活动，邀请百名监督对维尔口腔医疗品质进行挑刺儿，增强市民对种植牙技术的认识和信赖，以进一步提高维尔口腔医疗服务品质。</span><br />
&nbsp;
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size: 16px;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0406/20170406114116620.jpg" style="width: 600px; height: 397px;" /></span></a></p>
<p>&nbsp;</p>
<section class="xmyeditor cur" id="xmy1489549026349" onmouseup="ajh(this.id);" style="">
	<section style="margin: 5px 0px;">
		<section class="wxqq-borderTopColor wxqq-borderBottomColor" id="uuu0" style="border-top-width: 3px; border-top-style: solid; border-top-color: rgb(30, 155, 232); border-bottom-width: 1px; border-bottom-style: dashed; border-bottom-color: rgb(30, 155, 232); padding: 3px 8px; background-color: rgb(245, 245, 245);">
			<p class="wxqq-Color" id="uuu1" style="font-size: 17px; color: rgb(30, 155, 232);"><strong><span style="font-size: 16px;">坚守如一做诚信医疗的自律者</span></strong></p>
		</section>
		<p><span style="font-size:16px;">　<br />
		&nbsp; &nbsp; 　承诺仪式上，北京维尔口腔医院医疗总院长刘志杰、北京维尔口腔医院医务院长贺彩率全体医护人员宣读了维尔口腔诚信医疗服务的十大承诺，同时共同在承诺书上郑重签字。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　&quot;在维尔，诚信，就是对患者的口腔健康心怀敬畏，我们永远把消费者的口腔健康放在首位。&quot;维尔口腔医院医疗总院长刘志杰对诚信医疗这样解读。作为一家全国连锁的口腔医疗机构，维尔口腔自成立之始，便将诚信作为企业经营之道。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　据了解，维尔口腔的 &quot;医患接触零距离，诊疗操作零差错，医患关系零投诉，顾客隐私零暴露&quot;以及&quot;无痛、无菌、无近远期障碍&quot;的四零要求和三无理念正是对诊疗做出的细化要求，医德、医术两驾马车并驾齐驱是对牙齿问题患者做出的承诺。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　在为患者治疗前，维尔口腔医院都会与患者签订诊疗项目知情协议书，让患者明明白白消费，放心、安心治疗。维尔口腔还与中科创新发展研究院在行业内倡议发起&quot;透明行动&quot;。首先，问询透明化，规范问询流程，确保在缺牙者问诊时给予正确、专业的诊断建议，让缺牙者提前了解治疗的全过程。其次，手术过程透明化，手术所用的药品、材料由缺牙者先检查再拆分，确保来源与质量，并让缺牙者全面了解手术过程，清清楚楚、明明白白的消费。然后，植体质保透明化，维尔口腔提出种植体来源透明化，维尔口腔的每颗种植体均统一采购，都有出厂编码可查，让缺牙者选用指定种植体，签署种植牙质保承诺书，让质保透明化。</span><br />
		&nbsp;</p>
		<p style="text-align: center;"><object height="360" width="760"><param name="quality" value="high" /><param name="wmode" value="transparent" /><param name="movie" value="http://www.wekq.net/skin/video/315.swf" /><param name="allowScriptAccess" value="always" /><embed allowscriptaccess="always" height="360" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="http://www.wekq.net/skin/video/315.swf" type="application/x-shockwave-flash" width="760" wmode="transparent"></embed></object><br />
		&nbsp;</p>
		<section class="xmyeditor cur" id="xmy1489549026349" onmouseup="ajh(this.id);" style="">
			<section style="margin: 5px 0px;">
				<section class="wxqq-borderTopColor wxqq-borderBottomColor" id="uuu0" style="border-top-width: 3px; border-top-style: solid; border-top-color: rgb(30, 155, 232); border-bottom-width: 1px; border-bottom-style: dashed; border-bottom-color: rgb(30, 155, 232); padding: 3px 8px; background-color: rgb(245, 245, 245);">
					<p class="wxqq-Color" id="uuu1" style="font-size: 17px; color: rgb(30, 155, 232);"><strong><span style="font-size: 16px;">种植牙品质监督月百名监督员来&quot;挑刺&quot;</span></strong></p>
				</section>
			</section>
		</section>
		<p><span style="font-size:16px;">　　<br />
		&nbsp; &nbsp; &nbsp; &nbsp; &quot;不可否认，口腔行业内存在一些急功近利、医生与顾客之间彼此不信任等现象。&quot; 北京维尔口腔医院医疗总院长刘志杰介绍。这种现象的背后是患者与医生之间沟通的欠缺，患者对医疗质量的不满。&quot;因此，在维尔，我们将医疗品质视为 的生命线。&quot;</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　自本月初，维尔口腔医院就发布消息，面向全社会征募评选了100名种植牙品质监督员。100名监督员包括媒体行业、卫生系统、社区普通居民及社会各界人士，他们深入维尔口腔医院内部，参观和监督了医疗服务细节，对医院运行各环节进行&quot;挑刺&quot;。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　100名质量监督员亲眼见证了种植牙项目的各环节操作，同时对维尔专利技术一日得植牙术进行咨询参观。 &quot;一日得&quot;种植技术是利用四个关键位置的种植体保持牢固半口的所有牙，两颗前牙部位的植体垂直植入牙槽骨，两颗中远部位的植体倾斜角度植入牙槽骨，然后在种植体的基台上安装&quot;拱形连桥&quot;牙冠，这样整个种植牙的受力就呈现出&quot;拱形&quot;的特征，受力会均匀地分布到整体，这在建筑学上是更为稳固的形状。这种稳固的结构也使在种牙的当天，就可安装牙冠恢复美观和咀嚼。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　品质监督员还咨询了解了&quot;种植牙国际八大金标准&quot;，并将维尔口腔医院的种植牙流程按照&quot;八大金标准&quot;一一对照，通过详细检验发现，维尔口腔医院一日得种植牙项目完全符合国际&quot;八大金标准&quot;，值得牙缺失市民放心选择。</span></p>
	</section>
</section>{/dede:field}
{dede:field name='body'}<span style="font-size: 16px;">&nbsp; &nbsp; &nbsp; 为迎接315消费者权益日，3月15日，以&quot;诚信医疗服务，维护患者权益&quot;为主题的北京维尔口腔医院315《诚信医疗承诺书》承诺仪式在京举行，这也标志着医院将诚信医疗、规范办院升级到新的高度。同时北京维尔口腔医院开展了&quot;种植牙品质监督月&quot;活动，邀请百名监督对维尔口腔医疗品质进行挑刺儿，增强市民对种植牙技术的认识和信赖，以进一步提高维尔口腔医疗服务品质。</span><br />
&nbsp;
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size: 16px;"><img alt="" src="/uploads/allimg/c180407/15230A3594P20-15504.jpg" style="width: 600px; height: 397px;" /></span></a></p>
<p>&nbsp;</p>
<section class="xmyeditor cur" id="xmy1489549026349" onmouseup="ajh(this.id);" style="">
	<section style="margin: 5px 0px;">
		<section class="wxqq-borderTopColor wxqq-borderBottomColor" id="uuu0" style="border-top-width: 3px; border-top-style: solid; border-top-color: rgb(30, 155, 232); border-bottom-width: 1px; border-bottom-style: dashed; border-bottom-color: rgb(30, 155, 232); padding: 3px 8px; background-color: rgb(245, 245, 245);">
			<p class="wxqq-Color" id="uuu1" style="font-size: 17px; color: rgb(30, 155, 232);"><strong><span style="font-size: 16px;">坚守如一做诚信医疗的自律者</span></strong></p>
		</section>
		<p><span style="font-size:16px;">　<br />
		&nbsp; &nbsp; 　承诺仪式上，北京维尔口腔医院医疗总院长刘志杰、北京维尔口腔医院医务院长贺彩率全体医护人员宣读了维尔口腔诚信医疗服务的十大承诺，同时共同在承诺书上郑重签字。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　&quot;在维尔，诚信，就是对患者的口腔健康心怀敬畏，我们永远把消费者的口腔健康放在首位。&quot;维尔口腔医院医疗总院长刘志杰对诚信医疗这样解读。作为一家全国连锁的口腔医疗机构，维尔口腔自成立之始，便将诚信作为企业经营之道。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　据了解，维尔口腔的 &quot;医患接触零距离，诊疗操作零差错，医患关系零投诉，顾客隐私零暴露&quot;以及&quot;无痛、无菌、无近远期障碍&quot;的四零要求和三无理念正是对诊疗做出的细化要求，医德、医术两驾马车并驾齐驱是对牙齿问题患者做出的承诺。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　在为患者治疗前，维尔口腔医院都会与患者签订诊疗项目知情协议书，让患者明明白白消费，放心、安心治疗。维尔口腔还与中科创新发展研究院在行业内倡议发起&quot;透明行动&quot;。首先，问询透明化，规范问询流程，确保在缺牙者问诊时给予正确、专业的诊断建议，让缺牙者提前了解治疗的全过程。其次，手术过程透明化，手术所用的药品、材料由缺牙者先检查再拆分，确保来源与质量，并让缺牙者全面了解手术过程，清清楚楚、明明白白的消费。然后，植体质保透明化，维尔口腔提出种植体来源透明化，维尔口腔的每颗种植体均统一采购，都有出厂编码可查，让缺牙者选用指定种植体，签署种植牙质保承诺书，让质保透明化。</span><br />
		&nbsp;</p>
		<p style="text-align: center;"><object height="360" width="760"><param name="quality" value="high" /><param name="wmode" value="transparent" /><param name="movie" value="/uploads/allimg/c180407/15230A36003240-22496.swf" /><param name="allowScriptAccess" value="always" /><embed allowscriptaccess="always" height="360" pluginspage="http://www.macromedia.com/go/getflashplayer" quality="high" src="/uploads/allimg/c180407/15230A36003240-22496.swf" type="application/x-shockwave-flash" width="760" wmode="transparent"></embed></object><br />
		&nbsp;</p>
		<section class="xmyeditor cur" id="xmy1489549026349" onmouseup="ajh(this.id);" style="">
			<section style="margin: 5px 0px;">
				<section class="wxqq-borderTopColor wxqq-borderBottomColor" id="uuu0" style="border-top-width: 3px; border-top-style: solid; border-top-color: rgb(30, 155, 232); border-bottom-width: 1px; border-bottom-style: dashed; border-bottom-color: rgb(30, 155, 232); padding: 3px 8px; background-color: rgb(245, 245, 245);">
					<p class="wxqq-Color" id="uuu1" style="font-size: 17px; color: rgb(30, 155, 232);"><strong><span style="font-size: 16px;">种植牙品质监督月百名监督员来&quot;挑刺&quot;</span></strong></p>
				</section>
			</section>
		</section>
		<p><span style="font-size:16px;">　　<br />
		&nbsp; &nbsp; &nbsp; &nbsp; &quot;不可否认，口腔行业内存在一些急功近利、医生与顾客之间彼此不信任等现象。&quot; 北京维尔口腔医院医疗总院长刘志杰介绍。这种现象的背后是患者与医生之间沟通的欠缺，患者对医疗质量的不满。&quot;因此，在维尔，我们将医疗品质视为 的生命线。&quot;</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　自本月初，维尔口腔医院就发布消息，面向全社会征募评选了100名种植牙品质监督员。100名监督员包括媒体行业、卫生系统、社区普通居民及社会各界人士，他们深入维尔口腔医院内部，参观和监督了医疗服务细节，对医院运行各环节进行&quot;挑刺&quot;。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　100名质量监督员亲眼见证了种植牙项目的各环节操作，同时对维尔专利技术一日得植牙术进行咨询参观。 &quot;一日得&quot;种植技术是利用四个关键位置的种植体保持牢固半口的所有牙，两颗前牙部位的植体垂直植入牙槽骨，两颗中远部位的植体倾斜角度植入牙槽骨，然后在种植体的基台上安装&quot;拱形连桥&quot;牙冠，这样整个种植牙的受力就呈现出&quot;拱形&quot;的特征，受力会均匀地分布到整体，这在建筑学上是更为稳固的形状。这种稳固的结构也使在种牙的当天，就可安装牙冠恢复美观和咀嚼。</span><br />
		&nbsp;</p>
		<p><span style="font-size:16px;">　　品质监督员还咨询了解了&quot;种植牙国际八大金标准&quot;，并将维尔口腔医院的种植牙流程按照&quot;八大金标准&quot;一一对照，通过详细检验发现，维尔口腔医院一日得种植牙项目完全符合国际&quot;八大金标准&quot;，值得牙缺失市民放心选择。</span></p>
	</section>
</section>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180407/15230A3594P20-15504_lit.jpg{/dede:field}
