{dede:field name='keywords'}怎么办{/dede:field}
{dede:field name='description'}引起牙齿痛的情况是很多的，比如说牙髓炎、龋齿、智齿冠周炎和根尖周炎，其中，根尖周炎引起的痛感还比较明显，发作起来让人难以忍受，{/dede:field}
{dede:field name='title'}慢性根尖炎怎么办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size: 16px;">&nbsp; &nbsp; 引起牙齿痛的情况是很多的，比如说牙髓炎、龋齿、智齿冠周炎和根尖周炎，其中，根尖周炎引起的痛感还比较明显，发作起来让人难以忍受，很多人为此很痛苦。慢性根尖炎牙齿自发痛也是常见的一种情况，那么，遇到这些情况我们该怎么办呢?</span><br />
<br />
<div style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="牙疼" src="http://beij.wekq.net/uploadfile/2017/0722/20170722043404878.jpg" style="width: 300px; height: 200px; border-width: 0px; border-style: solid;" /></a></span><br />
&nbsp;</div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">慢性根尖炎的表现剧烈</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 慢性根尖周炎的初期症状不是很明显，因此往往被我们所忽略，事实上，它的危害是很大的。如果置之不理，很可能引起灾难性的后果。根据牙科医院数据显示，严重的根尖周炎导致牙齿蛀牙明显，牙体及内部遭到严重的破坏，外观颜色暗淡无光泽。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="color: rgb(255, 0, 0);">牙痛的原因及治疗</span></strong></a></span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 牙齿自发痛是根尖周炎的一个重要表现，有时候疼痛还比较剧烈，不仅让人无法饮食，而且正常的活动、工作和休息都大受影响，不得不到牙科医院寻求帮助。</span></p>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">慢性根尖炎牙齿自发痛的对策</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 慢性根尖炎牙齿自发痛该如何治疗?一般来说，应该经过牙科医院的综合性检查，确定慢性根尖炎牙齿自发痛的程度如何，如果症状剧烈，牙科医院应及时地根管引流，缓解根尖部压力解除疼痛。根管治疗在多种牙齿病变中都可以发挥巨大的作用，已经成为根尖周炎治疗常备的手段。维尔口腔引进了快速性根管治疗技术，根管预备、根管消毒及根管充填在快速治疗内完成，这在多数牙科医院都是很少见的。</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 慢性根尖周炎一定要引起我们的重视，因为它可能发展为急性根尖周炎。急性根尖周炎是一种常见的口腔疾病，会伴随着一系列典型、剧烈的疼痛，如果发展到这个阶段再到牙科医院进行诊治，那么过程要麻烦得多，付出的代价也更大。</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 引起牙疼的原因很多，除了急性或者慢性的根尖周炎，还有其他的一些原因，这些都会让我们的生活受到影响，严重的话，还会导致牙齿的松动，较后很可能造成被拔除的后果，因此，治疗牙痛，刻不容缓。</span></p>
<p style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0722/20170722043423663.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size: 16px;">&nbsp; &nbsp; 引起牙齿痛的情况是很多的，比如说牙髓炎、龋齿、智齿冠周炎和根尖周炎，其中，根尖周炎引起的痛感还比较明显，发作起来让人难以忍受，很多人为此很痛苦。慢性根尖炎牙齿自发痛也是常见的一种情况，那么，遇到这些情况我们该怎么办呢?</span><br />
<br />
<div style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="牙疼" src="/uploads/allimg/c180322/1521DZ94AX0-15a4.jpg" style="width: 300px; height: 200px; border-width: 0px; border-style: solid;" /></a></span><br />
&nbsp;</div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">慢性根尖炎的表现剧烈</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 慢性根尖周炎的初期症状不是很明显，因此往往被我们所忽略，事实上，它的危害是很大的。如果置之不理，很可能引起灾难性的后果。根据牙科医院数据显示，严重的根尖周炎导致牙齿蛀牙明显，牙体及内部遭到严重的破坏，外观颜色暗淡无光泽。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="color: rgb(255, 0, 0);">牙痛的原因及治疗</span></strong></a></span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 牙齿自发痛是根尖周炎的一个重要表现，有时候疼痛还比较剧烈，不仅让人无法饮食，而且正常的活动、工作和休息都大受影响，不得不到牙科医院寻求帮助。</span></p>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">慢性根尖炎牙齿自发痛的对策</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 慢性根尖炎牙齿自发痛该如何治疗?一般来说，应该经过牙科医院的综合性检查，确定慢性根尖炎牙齿自发痛的程度如何，如果症状剧烈，牙科医院应及时地根管引流，缓解根尖部压力解除疼痛。根管治疗在多种牙齿病变中都可以发挥巨大的作用，已经成为根尖周炎治疗常备的手段。维尔口腔引进了快速性根管治疗技术，根管预备、根管消毒及根管充填在快速治疗内完成，这在多数牙科医院都是很少见的。</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 慢性根尖周炎一定要引起我们的重视，因为它可能发展为急性根尖周炎。急性根尖周炎是一种常见的口腔疾病，会伴随着一系列典型、剧烈的疼痛，如果发展到这个阶段再到牙科医院进行诊治，那么过程要麻烦得多，付出的代价也更大。</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 引起牙疼的原因很多，除了急性或者慢性的根尖周炎，还有其他的一些原因，这些都会让我们的生活受到影响，严重的话，还会导致牙齿的松动，较后很可能造成被拔除的后果，因此，治疗牙痛，刻不容缓。</span></p>
<p style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DZ9523130-23Z4.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DZ94AX0-15a4_lit.jpg{/dede:field}
