{dede:field name='keywords'}牙齿,怎么办{/dede:field}
{dede:field name='description'}牙齿缺损怎么办?维尔口腔医师指出，牙齿缺损是指多种牙体硬组织不同程度的出现质地和生理解剖外形的损坏或异常，它常表现为正常牙体形{/dede:field}
{dede:field name='title'}牙齿缺损怎么办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">&nbsp; &nbsp; 牙齿缺损怎么办?维尔口腔医师指出，牙齿缺损是指多种牙体硬组织不同程度的出现质地和生理解剖外形的损坏或异常，它常表现为正常牙体形态、咬合及邻结关系的破坏。通俗的说，在牙齿萌出后，都具有一定的解剖形态，如果牙齿形态受到不同程度的破坏、缺损或者畸形，在医学上将这些叫做牙齿缺损。出现牙齿缺损，会影响到牙周组织的健康、咀嚼功能和发音功能的发挥以及患者的面容美观。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="门牙缺损修复" src="http://beij.wekq.net/uploadfile/2017/0714/20170714025353901.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 204px;" /></a></span></div>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">一</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">烤瓷牙修复</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 烤瓷牙牙齿缺损修复技术它是先用合金制成金属基底，再在其表面覆盖与天然牙相似的低熔瓷粉，在真空高温烤瓷炉中烧结熔附而成，因而有金属的强度和烤瓷全冠的美观。它疗程短，见效快，但是对牙体有损伤。</span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">二</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">种植牙修复</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 牙齿缺损严重即整颗牙缺失的，可采用种植牙技术进行修复。种植牙义齿是由种植体和种植体支持的上部结构组成的特殊修复体。种植体是人工材料制作，经牙槽外科手术植入颌骨内，起牙根的作用，经过一段时间，种植体与周围骨组织发生骨结合，然后利用种植牙根做支持，在其上方安装人工牙冠，达到恢复缺失牙、恢复咀嚼功能的作用。种植技术是目前成熟的治疗修复牙齿缺失的较先进手段。<a target="_blank"><span style="color: rgb(255, 0, 0);">查询种植牙植骨手术的愈合时间</span></a></span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">三</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">活动义齿</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 它由卡环(老百姓俗称&ldquo;钢丝钩&rdquo;)、基托、人工牙、支托组成，其原理是通过卡环&ldquo;钩住&rdquo;剩余牙齿来稳定假牙，基托连接人工牙来修复牙齿缺损。卡环与基托是多出来的附加结构，影响美观、发音，会有异物感，另外，整个假牙每天必须取下清洁刷洗几次，否则食物会进入假牙与牙龈之间，或粘附于假牙表面上，引发口腔疾病，甚至产生口腔异味。可见，活动义齿缺点较多，麻烦不少。</span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">四</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">固定义齿</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 牙科医生称之为&ldquo;固定桥&rdquo;，老百姓多称其为&ldquo;烤瓷牙&rdquo;。具体做法是把缺失牙两边的健康牙磨小，变成&ldquo;桥墩&rdquo;，然后做牙套套住两边磨小的牙齿，来架住缺失的牙齿(又称桥体)，这种方法不需要每天取下来清洁，咀嚼功能较强，但有一个弱点，即为了修复牙齿，需要磨削两边的健康牙齿。如果恰好邻牙本身就有问题，如龋齿、隐裂或者已经做过根管治疗需要做牙套保护，选择这种方法比较合适。 &nbsp;<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询在线医生</strong></span></a></span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0714/20170714025930978.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">&nbsp; &nbsp; 牙齿缺损怎么办?维尔口腔医师指出，牙齿缺损是指多种牙体硬组织不同程度的出现质地和生理解剖外形的损坏或异常，它常表现为正常牙体形态、咬合及邻结关系的破坏。通俗的说，在牙齿萌出后，都具有一定的解剖形态，如果牙齿形态受到不同程度的破坏、缺损或者畸形，在医学上将这些叫做牙齿缺损。出现牙齿缺损，会影响到牙周组织的健康、咀嚼功能和发音功能的发挥以及患者的面容美观。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="门牙缺损修复" src="/uploads/allimg/c180322/1521D4D44X40-123192.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 204px;" /></a></span></div>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">一</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">烤瓷牙修复</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 烤瓷牙牙齿缺损修复技术它是先用合金制成金属基底，再在其表面覆盖与天然牙相似的低熔瓷粉，在真空高温烤瓷炉中烧结熔附而成，因而有金属的强度和烤瓷全冠的美观。它疗程短，见效快，但是对牙体有损伤。</span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">二</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">种植牙修复</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 牙齿缺损严重即整颗牙缺失的，可采用种植牙技术进行修复。种植牙义齿是由种植体和种植体支持的上部结构组成的特殊修复体。种植体是人工材料制作，经牙槽外科手术植入颌骨内，起牙根的作用，经过一段时间，种植体与周围骨组织发生骨结合，然后利用种植牙根做支持，在其上方安装人工牙冠，达到恢复缺失牙、恢复咀嚼功能的作用。种植技术是目前成熟的治疗修复牙齿缺失的较先进手段。<a target="_blank"><span style="color: rgb(255, 0, 0);">查询种植牙植骨手术的愈合时间</span></a></span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">三</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">活动义齿</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 它由卡环(老百姓俗称&ldquo;钢丝钩&rdquo;)、基托、人工牙、支托组成，其原理是通过卡环&ldquo;钩住&rdquo;剩余牙齿来稳定假牙，基托连接人工牙来修复牙齿缺损。卡环与基托是多出来的附加结构，影响美观、发音，会有异物感，另外，整个假牙每天必须取下清洁刷洗几次，否则食物会进入假牙与牙龈之间，或粘附于假牙表面上，引发口腔疾病，甚至产生口腔异味。可见，活动义齿缺点较多，麻烦不少。</span></p>
<div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">四</span><span style="font-size:18px;"><span style="line-height: 22.3906px;">固定义齿</span></span></h2>
</section>
</div>
</div>
<p><span style="font-size:16px;">&nbsp; &nbsp; 牙科医生称之为&ldquo;固定桥&rdquo;，老百姓多称其为&ldquo;烤瓷牙&rdquo;。具体做法是把缺失牙两边的健康牙磨小，变成&ldquo;桥墩&rdquo;，然后做牙套套住两边磨小的牙齿，来架住缺失的牙齿(又称桥体)，这种方法不需要每天取下来清洁，咀嚼功能较强，但有一个弱点，即为了修复牙齿，需要磨削两边的健康牙齿。如果恰好邻牙本身就有问题，如龋齿、隐裂或者已经做过根管治疗需要做牙套保护，选择这种方法比较合适。 &nbsp;<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询在线医生</strong></span></a></span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D4D500950-131213.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size:16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D4D44X40-123192_lit.jpg{/dede:field}
