<?php
$z[0]=Array("type","<a href=\"/yyjj/881.html\">[field:typename/]</a>",288,368);
$z[0][4]['typeid']="1";
$z[1]=Array("type","[field:typeurl/]\">[field:typename/]</a>",404,477);
$z[1][4]['typeid']="2";
$z[2]=Array("type","[field:typeurl/]\">[field:typename/]</a>",513,586);
$z[2][4]['typeid']="3";
$z[3]=Array("type","[field:typeurl/]\">[field:typename/]</a>",622,695);
$z[3][4]['typeid']="7";
$z[4]=Array("type","[field:typeurl/]\">[field:typename/]</a>",731,804);
$z[4][4]['typeid']="4";

?>