<?php
$z[0]=Array("type","[field:typeurl/]\">[field:typename/]</a>",297,370);
$z[0][4]['typeid']="1";
$z[1]=Array("type","[field:typeurl/]\">[field:typename/]</a>",406,479);
$z[1][4]['typeid']="2";
$z[2]=Array("type","[field:typeurl/]\">[field:typename/]</a>",515,588);
$z[2][4]['typeid']="3";
$z[3]=Array("type","[field:typeurl/]\">[field:typename/]</a>",624,697);
$z[3][4]['typeid']="7";
$z[4]=Array("type","[field:typeurl/]\">[field:typename/]</a>",733,806);
$z[4][4]['typeid']="4";

?>