document.writeln("                <div class=\"imgBox\" id=\"imgBox\">");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\"javascript:openZoosUrl()\" title=\"美团\"><img src=\"/images/pcbanner_meituan.jpg\"/></a></li>");
document.writeln("                        <li><a href=\"javascript:openZoosUrl()\" title=\"补贴\"><img src=\"/images/pcbanner_bt.jpg\"/></a></li>");
document.writeln("                        <li><a href=\"javascript:openZoosUrl()\" title=\"就业保障\"><img src=\"/images/pcbanner_jybz.jpg\"/></a></li>");
document.writeln("                        <li><a href=\"javascript:openZoosUrl()\" title=\"老师\"><img src=\"/images/pcbanner_laoshi.jpg\"/></a></li>");
document.writeln("                        <li><a href=\"http://put.zoosnet.net/LR/Chatpre.aspx?id=PUT57723614&cid=1532826476578326993876&lng=cn\" title=\"证书\"><img src=\"/images/pcbanner_zz.jpg\"/></a></li>");
document.writeln("                        <li><a href=\"javascript:openZoosUrl()\" title=\"10月.2\"><img src=\"/images/pcbanner_4.jpg\"/></a></li>");
document.writeln("                        <li><a href=\"javascript:openZoosUrl()\" title=\"10月.2\"><img src=\"/images/banner.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:openZoosUrl()\" title=\"10月.2\"><img src=\"/images/pcbanner_3.jpg\"/></a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <ol class=\"slideLink\">");
document.writeln("                    <li><a href=\"javascript:openZoosUrl()\"></a></li>");
document.writeln("                    <li><a href=\"javascript:openZoosUrl()\"></a></li>");
document.writeln("                    <li><a href=\"javascript:openZoosUrl()\"></a></li>");
document.writeln("                    <li><a href=\"javascript:openZoosUrl()\"></a></li>");
document.writeln("                    <li><a href=\"javascript:openZoosUrl()\"></a></li>");
document.writeln("                    <li><a href=\"javascript:openZoosUrl()\"></a></li>");
document.writeln("                    <li><a href=\"javascript:openZoosUrl()\"></a></li>");
document.writeln("                    <li><a href=\"javascript:openZoosUrl()\"></a></li>");
document.writeln("                </ol>");