document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\"utf-8\">");
document.writeln("<title>无标题文档</title>");
document.writeln("<style type=\"text/css\">");
document.writeln(".swtCenter {");
document.writeln("    width: 380px;");
document.writeln("    height: 250px;");
document.writeln("    background-color: #FFF;");
document.writeln("    position: fixed;");
document.writeln("    left: 50%;");
document.writeln("    top: 50%;");
document.writeln("    z-index: 99999;");
document.writeln("    margin-left: -190px;");
document.writeln("    margin-top: -130px;");
document.writeln("    -moz-border-radius: 15px;");
document.writeln("    -webkit-border-radius: 15px;");
document.writeln("    border-radius: 15px;");
document.writeln("    -moz-box-shadow: 0 0 20px rgba(10,2,4,0.75);");
document.writeln("    -webkit-box-shadow: 0 0 20px rgba(10,2,4,0.75);");
document.writeln("    box-shadow: 0 0 20px rgba(10,2,4,0.75);");
document.writeln("}");
document.writeln(".closeBtn_swt {");
document.writeln("    right: -5px;");
document.writeln("    top: -5px;");
document.writeln("    width: 44px;");
document.writeln("    height: 44px;");
document.writeln("    background: url(http://www.jingsiedu.com/swt/img/closeBtn_swt.png) no-repeat;");
document.writeln("    -moz-background-size: 100%;");
document.writeln("    -webkit-background-size: 100%;");
document.writeln("    background-size: 100%;");
document.writeln("    cursor: pointer;");
document.writeln("}");
document.writeln(".absolute {");
document.writeln("    position: absolute;");
document.writeln("}");
document.writeln(".swtCenter h3 {");
document.writeln("	margin:0;");
document.writeln("	padding:0;");
document.writeln("    width: 100%;");
document.writeln("    font-size: 20px;");
document.writeln("    text-align: center;");
document.writeln("    color: #b4448c;");
document.writeln("    font-weight: 600;");
document.writeln("    margin-top: 33px;");
document.writeln("	font-family:\"微软雅黑\";");
document.writeln("	");
document.writeln("}");
document.writeln(".swtCenter .fyljg {");
document.writeln("    width: 100%;");
document.writeln("    font-size: 20px;");
document.writeln("    text-align: center;");
document.writeln("    color: #2e3642;");
document.writeln("	font-family:\"微软雅黑\";");
document.writeln("}");
document.writeln(".clear {");
document.writeln("    clear: both;");
document.writeln("}");
document.writeln(".swtCenter p {");
document.writeln("    width:100%;");
document.writeln("    height: 20px;");
document.writeln("    font-size: 13px;");
document.writeln("    color: #6a7380;");
document.writeln("    margin: 0 auto;");
document.writeln("    text-align: center;");
document.writeln("    line-height: 20px;");
document.writeln("	margin-top:20px;");
document.writeln("	font-family:\"微软雅黑\";");
document.writeln("}");
document.writeln(".swt_lists {");
document.writeln("    bottom: 0;");
document.writeln("    left: 0;");
document.writeln("    width:380px;");
document.writeln("    height: 58px;");
document.writeln("    line-height: 58px;");
document.writeln("    -moz-border-radius: 0 0 15px 15px;");
document.writeln("    -webkit-border-radius: 0 0 15px 15px;");
document.writeln("    border-radius: 0 0 15px 15px;");
document.writeln("}");
document.writeln(".swt_lists a {");
document.writeln("    display: block;");
document.writeln("    width: 50%;");
document.writeln("    height: 100%;");
document.writeln("    position: relative;");
document.writeln("    float: left;");
document.writeln("}");
document.writeln(".swt_list1 {");
document.writeln("    background-color: #b4448c;");
document.writeln("    -moz-border-radius: 0 0 15px 0;");
document.writeln("    -webkit-border-radius: 0 0 15px 0;");
document.writeln("    border-radius: 0 0 15px 0;");
document.writeln("}");
document.writeln(".swt_list2 {");
document.writeln("    background-color: #f08315;");
document.writeln("    -moz-border-radius: 0 0 0 15px;");
document.writeln("    -webkit-border-radius: 0 0 0 15px;");
document.writeln("    border-radius: 0 0 0 15px;");
document.writeln("}");
document.writeln(".swt_lists a i,.swt_lists a em{");
document.writeln("    display: block;");
document.writeln("    position: absolute;");
document.writeln("    left: 50%;");
document.writeln("    color: #fff;");
document.writeln("    text-decoration: none;");
document.writeln("	font-family:\"微软雅黑\";");
document.writeln("}");
document.writeln(".swt_lists em {");
document.writeln("    height: 100%;");
document.writeln("    top: 0;");
document.writeln("    margin-left: -16px;");
document.writeln("    font-size: 16px;");
document.writeln("}");
document.writeln(".swt_lists em {");
document.writeln("    font-style: normal;");
document.writeln("}");
document.writeln(".swtCallIcon {");
document.writeln("    top: 50%;");
document.writeln("    margin-left: -50px;");
document.writeln("    margin-top: -13px;");
document.writeln("    width: 27px;");
document.writeln("    height: 24px;");
document.writeln("    background: url(http://www.jingsiedu.com/swt/img/footerLink3.gif) no-repeat;");
document.writeln("    -moz-background-size: 100%;");
document.writeln("    -webkit-background-size: 100%;");
document.writeln("    background-size: 100%;");
document.writeln("}");
document.writeln(".swtLinkIcon {");
document.writeln("    top: 50%;");
document.writeln("    margin-left: -50px;");
document.writeln("    width: 27px;");
document.writeln("    height: 27px;");
document.writeln("    margin-top: -12px;");
document.writeln("    background: url(http://www.jingsiedu.com/swt/img/footerLink2.gif) no-repeat;");
document.writeln("    -moz-background-size: 100%;");
document.writeln("    -webkit-background-size: 100%;");
document.writeln("    background-size: 100%;");
document.writeln("}");
document.writeln(".mfhd {");
document.writeln("  	overflow:hidden;");
document.writeln("	width:100%;	");
document.writeln("    /*width: 140px;");
document.writeln("    height: 32px;");
document.writeln("    -moz-border-radius: 17px;");
document.writeln("    -webkit-border-radius: 17px;");
document.writeln("    border-radius: 17px;");
document.writeln("    margin: 12px auto 5px;");
document.writeln("    line-height: 32px;");
document.writeln("    text-align: center;");
document.writeln("    background: #f08315;");
document.writeln("    color: #fff;");
document.writeln("    font-size: 16px;");
document.writeln("    margin-bottom: 10px;*/");
document.writeln("}");
document.writeln(".clearfix {");
document.writeln("    zoom: 1;");
document.writeln("    display: block;");
document.writeln("}");
document.writeln("/*.mfhd img {");
document.writeln("    width: 23px;");
document.writeln("    height: 23px;");
document.writeln("    margin-left: 2px;");
document.writeln("    display: inline-block;");
document.writeln("	vertical-align: middle;");
document.writeln("}*/");
document.writeln("#tcswt {");
document.writeln("    float: left;");
document.writeln("    margin-top: 19px;");
document.writeln("    margin-left:45px;");
document.writeln("    width: 200px;");
document.writeln("    height: 30px;");
document.writeln("    background-color: #fff;");
document.writeln("}");
document.writeln("#tcswt2 {");
document.writeln("    display: block;");
document.writeln("    height: 34px;");
document.writeln("    width:110px;");
document.writeln("    float: left;");
document.writeln("    background-color: #E45100;");
document.writeln("    margin-top: 19px;");
document.writeln("    margin-left:5px;");
document.writeln("    line-height: 30px;");
document.writeln("    color: #fff;");
document.writeln("	text-align:center;");
document.writeln("	text-decoration:none;");
document.writeln("}");
document.writeln("</style>");

document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<div class=\"swtCenter relative\" id=\"swt_center\"> <span id=\"closeBtn_swt\" class=\"closeBtn_swt absolute\" href=\"javascript:void(0);return false;\" onclick=\"zjClose();\"></span>");
document.writeln("  <h3>竞思教育 咨询预约平台</h3>");
document.writeln("  <div class=\"fyljg\"> <span>注意力训练专家</span> </div>");
document.writeln("  <div class=\"clear\"></div>");
document.writeln("  <!--<a href=\"tel:4006916591\" style=\"text-decoration:none;\">");
document.writeln("  <div class=\"mfhd clearfix\"><img src=\"http://www.jingsiedu.com/swt/img/footerLink4.gif\"> 免费咨询电话 </div>");
document.writeln("  </a>-->");
document.writeln("  <div class=\"mfhd\"> ");
document.writeln("        <input type=\"text\" id=\"tcswt\" value=\"&nbsp;请输入您的电话号码\" onfocus=\"if(this.value==\'&nbsp;请输入您的电话号码\'){this.value=\'\';}\" onblur=\"if(this.value==\'\'){this.value=\'&nbsp;请输入您的电话号码\';}\"><a id=\"tcswt2\" href=\"javascript:;\" onclick=\"lxbfunction(\'swtfc\');\" target=\"_self\">免费咨询电话</a>");
document.writeln("   </div>  ");
document.writeln("  ");
document.writeln("  <p>注意力是孩子成才关键&nbsp;&nbsp;电话直接连线在线老师</p>");
document.writeln("  <div class=\"swt_lists absolute\"> <a href=\"http://www.jingsiedu.com/baoming/\" class=\"swt_list2\"><i class=\"swtLinkIcon\"></i><em>预约课程</em></a> <a href=\"http://mfa.zoosnet.net/LR/Chatpre.aspx?id=MFA54261545&lng=cn\" class=\"swt_list1\" target=\"_blank\"><i class=\"swtCallIcon\"></i><em>在线咨询</em></a> </div>");
document.writeln("</div>");
document.writeln("<script>function zjShow(){");
document.writeln("   document.getElementById(\'swt_center\').style.display = \'block\';");
document.writeln(" }");
document.writeln("  function zjClose(){");
document.writeln("  	var tcswt=document.getElementById(\'tcswt\');");
document.writeln("    document.getElementById(\'swt_center\').style.display = \'none\';");
document.writeln("	setTimeout(\'zjShow()\',25000);");
document.writeln("	tcswt.value=tcswt.defaultValue;");
document.writeln("	");
document.writeln(" }");
document.writeln("	document.getElementById(\"tcswt2\").onclick = function () { ");
document.writeln("		lxb.call(document.getElementById(\"tcswt\"));");
document.writeln("	};  ");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");