{dede:field name='keywords'}弄松,牙齿{/dede:field}
{dede:field name='description'}有很多想要矫牙的朋友们，因为对正畸并不是十分了解，不免存在很多疑问。而矫牙是使牙齿移动，不免有大部分人担心这样会不会使牙齿变松{/dede:field}
{dede:field name='title'}矫正会把牙齿弄松吗?{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">　　有很多想要矫牙的朋友们，因为对正畸并不是十分了解，不免存在很多疑问。而矫牙是使牙齿移动，不免有大部分人担心这样会不会使牙齿变松动。</span>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0915/20170915041510224.jpg" style="width: 300px; height: 200px;" /></span></a></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　矫正会把牙齿弄松吗?</span></span></a></p>
<p><span style="font-size:16px;">　　维尔口腔专家介绍，牙齿矫正后会变松这句话不正确，应该说不正规的牙齿矫正会使牙齿变松，而经过正确设计和矫正后的牙齿是不会变松的。</span></p>
<p><strong><span style="font-size:16px;">　　我们先从牙齿和牙槽骨的结构特点来了解一下牙齿矫正的过程。</span></strong></p>
<p><strong><span style="font-size:16px;">　　牙齿和牙槽骨的结构</span></strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;"> (推荐阅读&mdash;&mdash;牙齿矫正全攻略 )</span></span></a></p>
<p><span style="font-size:16px;">　　牙齿分牙冠和牙根两部分，牙根埋于牙槽骨中，就像大树埋入地下的牙根一样，如果发生水土流失(类比于口腔的牙槽骨吸收)，大树就会摇摇欲坠(牙齿变松)。</span></p>
<p><span style="font-size:16px;">　　了解了牙齿变松的原理，我们接下来就要研究一下为什么会有牙槽骨的吸收。</span></p>
<p><strong><span style="font-size:16px;">　　牙槽骨吸收的原因</span></strong></p>
<p><span style="font-size:16px;">　　牙槽骨吸收的原因主要有两个，一是牙刷不干净导致牙结石形成，刺激牙龈形成牙周炎症。</span></p>
<p><span style="font-size:16px;">　　二是过大的外力刺激，包括过大的咬合力和侧向力。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">【点击咨询】【在线预约】</span></a></span></p>
<p><span style="font-size:16px;">　　换句话，如果牙齿清洁干净，并且避免过大的矫治力，牙槽骨就不会吸收，而这两点都是可以做到的，这也是牙齿矫正得以顺利进行的基础。</span></p>
<p><strong><span style="font-size:16px;">　　矫牙要谨遵医嘱，耐心刷牙</span></strong></p>
<p><span style="font-size:16px;">　　矫正过程中，医生会不厌其烦的提醒患者仔细刷牙，若炎症控制不利还有可能提前终止治疗，就是为了防止牙周炎症导致牙槽骨吸收，所以，朋友们一定要理解医生的良苦用心，认真配合，仔细刷牙，保证治疗顺利进行。另外，拥挤不堪的牙齿常常难以清洁，在矫正前即已形成牙周炎症，待矫正结束后，牙齿变得整齐并易于清洁，反而有助于牙周炎症的控制。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0202/20180202105938729.jpg" style="width: 550px; height: 130px;" /></a></span></p>
<p><span style="font-size:16px;">　　牙齿受适当的力量移动过程中，会有轻微的动度，这是正常的，矫正完成后牙槽骨会自行修复，恢复原有的稳定。未经过正规训练的医生可能不能控制牙齿移动的力量，导致牙齿的过度松动，所以朋友们一定要擦亮双眼，选择正规医院的有正畸资格的医生矫正牙齿。</span><span style="font-size: 16px;">维尔口腔专题提醒：朋友们不要轻信谣言，而应该遵从医生的指导，保护牙齿，保障牙齿健康。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">　　有很多想要矫牙的朋友们，因为对正畸并不是十分了解，不免存在很多疑问。而矫牙是使牙齿移动，不免有大部分人担心这样会不会使牙齿变松动。</span>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0915/20170915041510224.jpg" style="width: 300px; height: 200px;" /></span></a></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　矫正会把牙齿弄松吗?</span></span></a></p>
<p><span style="font-size:16px;">　　维尔口腔专家介绍，牙齿矫正后会变松这句话不正确，应该说不正规的牙齿矫正会使牙齿变松，而经过正确设计和矫正后的牙齿是不会变松的。</span></p>
<p><strong><span style="font-size:16px;">　　我们先从牙齿和牙槽骨的结构特点来了解一下牙齿矫正的过程。</span></strong></p>
<p><strong><span style="font-size:16px;">　　牙齿和牙槽骨的结构</span></strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;"> (推荐阅读&mdash;&mdash;牙齿矫正全攻略 )</span></span></a></p>
<p><span style="font-size:16px;">　　牙齿分牙冠和牙根两部分，牙根埋于牙槽骨中，就像大树埋入地下的牙根一样，如果发生水土流失(类比于口腔的牙槽骨吸收)，大树就会摇摇欲坠(牙齿变松)。</span></p>
<p><span style="font-size:16px;">　　了解了牙齿变松的原理，我们接下来就要研究一下为什么会有牙槽骨的吸收。</span></p>
<p><strong><span style="font-size:16px;">　　牙槽骨吸收的原因</span></strong></p>
<p><span style="font-size:16px;">　　牙槽骨吸收的原因主要有两个，一是牙刷不干净导致牙结石形成，刺激牙龈形成牙周炎症。</span></p>
<p><span style="font-size:16px;">　　二是过大的外力刺激，包括过大的咬合力和侧向力。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">【点击咨询】【在线预约】</span></a></span></p>
<p><span style="font-size:16px;">　　换句话，如果牙齿清洁干净，并且避免过大的矫治力，牙槽骨就不会吸收，而这两点都是可以做到的，这也是牙齿矫正得以顺利进行的基础。</span></p>
<p><strong><span style="font-size:16px;">　　矫牙要谨遵医嘱，耐心刷牙</span></strong></p>
<p><span style="font-size:16px;">　　矫正过程中，医生会不厌其烦的提醒患者仔细刷牙，若炎症控制不利还有可能提前终止治疗，就是为了防止牙周炎症导致牙槽骨吸收，所以，朋友们一定要理解医生的良苦用心，认真配合，仔细刷牙，保证治疗顺利进行。另外，拥挤不堪的牙齿常常难以清洁，在矫正前即已形成牙周炎症，待矫正结束后，牙齿变得整齐并易于清洁，反而有助于牙周炎症的控制。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0202/20180202105938729.jpg" style="width: 550px; height: 130px;" /></a></span></p>
<p><span style="font-size:16px;">　　牙齿受适当的力量移动过程中，会有轻微的动度，这是正常的，矫正完成后牙槽骨会自行修复，恢复原有的稳定。未经过正规训练的医生可能不能控制牙齿移动的力量，导致牙齿的过度松动，所以朋友们一定要擦亮双眼，选择正规医院的有正畸资格的医生矫正牙齿。</span><span style="font-size: 16px;">维尔口腔专题提醒：朋友们不要轻信谣言，而应该遵从医生的指导，保护牙齿，保障牙齿健康。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D54U6240-39643_lit.jpg{/dede:field}
