{dede:field name='keywords'}牙齿美白{/dede:field}
{dede:field name='description'}因为不生活习惯和牙齿病变，出现的烟渍牙、茶渍牙、四环素牙、氟斑牙、遗传性黄牙等，会造成牙齿发黄、发黑甚至缺损。严重的破坏了牙齿{/dede:field}
{dede:field name='title'}牙齿美白多少钱{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p>　　因为不生活习惯和牙齿病变，出现的烟渍牙、茶渍牙、四环素牙、氟斑牙、遗传性黄牙等，会造成牙齿发黄、发黑甚至缺损。严重的破坏了牙齿的美观，牙齿美白应运而生;牙齿美白的价格在几千到几万块钱不等，会受到多个方面因素的影响。<strong>北京维尔口腔医生在线详细的介绍</strong>。</p>
<p style="text-align: center; font-stretch: normal;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427073815665.jpg" style="width: 300px; height: 216px;" /></p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">1</span><strong>影响牙齿美白主要有以下三点因素，</strong></h2>
<p>　　牙齿美白的费用，包含有口腔检查、口腔全景片、CT检查等费用;用于确定患者牙齿变黄的原因、程度等信息，以及是否适合立即做牙齿美白、是否需要进行牙周辅助治疗;根据影像资料，制定牙齿美白方案。<strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#008080;">&lt;&lt;牙齿美白多少钱点击咨询&gt;&gt;</span></a></strong></p>
<p>　　一、辅助治疗费用：补牙之前如果有其它口腔炎症，牙科医师会对患者口腔进行全面的检查，对各种存在的口腔疾病例如牙龈出血，牙周炎，牙周病等进行系统全面的治疗，而治疗期间所产生的费用是不同的。</p>
<p>　　二、造成黑黄牙的原因：造成黑黄牙的原因分为两大类，外源性色素牙和内源性色素牙;外源性色素牙包括长期吸烟、饮用咖啡造成的烟渍牙、咖啡牙等;内源性色素牙有四环素牙、氟斑牙、遗传性黄牙及死髓牙等。不同原因的色素牙，美白的方法不一样，价格也会不同。</p>
<p>　　三、美白牙齿的方法：外源性色素牙通过洗牙、冷光美白的方法清除牙齿外部牙结石、牙菌斑等附作物即可完成牙齿美白;中重度的四环素牙、氟斑牙、死髓牙等内源性色素牙，通过外部美白无法清除牙齿内部的病变，可以通过瓷贴面、美容冠等方法达到美白的效果。</p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">2</span><strong>维尔口腔牙齿美白修复&mdash;&mdash;任蕾美学修复主任推荐</strong></h2>
<div style="text-align: center; padding: 0px; margin: 0px; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0); font-stretch: normal;"><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427070305545.jpg" style="width: 450px; height: 280px;" /></a></div>
<div style="font-stretch: normal;">&nbsp;</div>
<div style="font-stretch: normal;">
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">3</span><strong>维尔口腔</strong><strong>任蕾美学修复主任</strong><strong>&mdash;&mdash;牙齿美白修复真实案例</strong></h2>
<br />
<div style="TEXT-ALIGN: center"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427074215255.jpg" style="width: 300px; height: 159px;" /></a><br />
<span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px"><span style="COLOR: rgb(0,0,0)"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">李女士 &nbsp;年龄：33 牙齿黄</a></span></span><br />
<u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="COLOR: rgb(0,128,128)"><span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px">牙齿美白更多问题击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">4</span><strong>维尔口腔&mdash;&mdash;北京专业美学修复中心</strong></h2>
<div style="padding: 0px; margin: 0px; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0); font-stretch: normal;">
<p>　　维尔口腔是北京较早开展美学修复项目的医疗机构之一。引进的仿生美容冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。由维尔美齿导师刘志杰院长制定出的3-3-4-4美齿黄金法则， 被众多美齿机构广泛借鉴及沿用。</p>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">安全材质</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　具有高度生物兼容性，对口腔无害，并加速种牙冠与口内组织的紧密结合性。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; PADDING-TOP: 5px"><font color="#e36c09"><span style="FONT-SIZE: 14px">专业团队</span></font></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　由院长刘志杰、美学修复主任任蕾等经验丰富的美学修复医生，亲自临床，提高美白修复安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">科学流程</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。</p>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解牙齿美白，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
<div>&nbsp;</div>
</div>
</div>
<br />{/dede:field}
{dede:field name='body'}<p>　　因为不生活习惯和牙齿病变，出现的烟渍牙、茶渍牙、四环素牙、氟斑牙、遗传性黄牙等，会造成牙齿发黄、发黑甚至缺损。严重的破坏了牙齿的美观，牙齿美白应运而生;牙齿美白的价格在几千到几万块钱不等，会受到多个方面因素的影响。<strong>北京维尔口腔医生在线详细的介绍</strong>。</p>
<p style="text-align: center; font-stretch: normal;"><img alt="" src="/uploads/allimg/c180322/1521DBHU220-310C.jpg" style="width: 300px; height: 216px;" /></p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">1</span><strong>影响牙齿美白主要有以下三点因素，</strong></h2>
<p>　　牙齿美白的费用，包含有口腔检查、口腔全景片、CT检查等费用;用于确定患者牙齿变黄的原因、程度等信息，以及是否适合立即做牙齿美白、是否需要进行牙周辅助治疗;根据影像资料，制定牙齿美白方案。<strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#008080;">&lt;&lt;牙齿美白多少钱点击咨询&gt;&gt;</span></a></strong></p>
<p>　　一、辅助治疗费用：补牙之前如果有其它口腔炎症，牙科医师会对患者口腔进行全面的检查，对各种存在的口腔疾病例如牙龈出血，牙周炎，牙周病等进行系统全面的治疗，而治疗期间所产生的费用是不同的。</p>
<p>　　二、造成黑黄牙的原因：造成黑黄牙的原因分为两大类，外源性色素牙和内源性色素牙;外源性色素牙包括长期吸烟、饮用咖啡造成的烟渍牙、咖啡牙等;内源性色素牙有四环素牙、氟斑牙、遗传性黄牙及死髓牙等。不同原因的色素牙，美白的方法不一样，价格也会不同。</p>
<p>　　三、美白牙齿的方法：外源性色素牙通过洗牙、冷光美白的方法清除牙齿外部牙结石、牙菌斑等附作物即可完成牙齿美白;中重度的四环素牙、氟斑牙、死髓牙等内源性色素牙，通过外部美白无法清除牙齿内部的病变，可以通过瓷贴面、美容冠等方法达到美白的效果。</p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">2</span><strong>维尔口腔牙齿美白修复&mdash;&mdash;任蕾美学修复主任推荐</strong></h2>
<div style="text-align: center; padding: 0px; margin: 0px; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0); font-stretch: normal;"><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DBI41960-44115.jpg" style="width: 450px; height: 280px;" /></a></div>
<div style="font-stretch: normal;">&nbsp;</div>
<div style="font-stretch: normal;">
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">3</span><strong>维尔口腔</strong><strong>任蕾美学修复主任</strong><strong>&mdash;&mdash;牙齿美白修复真实案例</strong></h2>
<br />
<div style="TEXT-ALIGN: center"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DBI95T0-53313.jpg" style="width: 300px; height: 159px;" /></a><br />
<span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px"><span style="COLOR: rgb(0,0,0)"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">李女士 &nbsp;年龄：33 牙齿黄</a></span></span><br />
<u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="COLOR: rgb(0,128,128)"><span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px">牙齿美白更多问题击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">4</span><strong>维尔口腔&mdash;&mdash;北京专业美学修复中心</strong></h2>
<div style="padding: 0px; margin: 0px; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0); font-stretch: normal;">
<p>　　维尔口腔是北京较早开展美学修复项目的医疗机构之一。引进的仿生美容冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。由维尔美齿导师刘志杰院长制定出的3-3-4-4美齿黄金法则， 被众多美齿机构广泛借鉴及沿用。</p>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">安全材质</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　具有高度生物兼容性，对口腔无害，并加速种牙冠与口内组织的紧密结合性。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; PADDING-TOP: 5px"><font color="#e36c09"><span style="FONT-SIZE: 14px">专业团队</span></font></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　由院长刘志杰、美学修复主任任蕾等经验丰富的美学修复医生，亲自临床，提高美白修复安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">科学流程</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。</p>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解牙齿美白，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
<div>&nbsp;</div>
</div>
</div>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DBHU220-310C_lit.jpg{/dede:field}
