{dede:field name='keywords'}步骤{/dede:field}
{dede:field name='description'}窝沟封闭又称之为点隙裂沟封闭，是指不去除咬合面牙体组织，在其上涂布一层粘结性树脂，就能保护牙釉质不受细菌及代谢产物侵蚀，增强牙{/dede:field}
{dede:field name='title'}窝沟封闭的治疗步骤是怎样的{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<div><span style="font-size: 16px;">&nbsp; &nbsp; 窝沟封闭又称之为点隙裂沟封闭，是指不去除咬合面牙体组织，在其上涂布一层粘结性树脂，就能保护牙釉质不受细菌及代谢产物侵蚀，增强牙齿抗龋能力，从而达到预防龋病发生的一种有效防龋方法。好像就是给牙齿穿上了一层保护衣，使牙齿免受食物侵蚀。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size: 16px; color: rgb(255, 0, 0);"><strong>接下来我们一起来看看窝沟封闭的治疗步骤具体是怎样的：</strong></span></a></div>
<div>&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0929/20170929050116102.jpg" style="cursor: pointer; border-width: 0px; border-style: solid; width: 300px; height: 200px;" /></span></a></div>
<div style="text-align: center;">&nbsp;</div>
<div><span style="font-size:16px;">　<strong>　一、清洁牙面：</strong>在低速手机上装好锥形小毛刷或橡皮杯，蘸取适量清洁剂于牙面，要对牙面和窝沟来回刷洗约1分钟，同时不断滴水保持毛刷湿润。也可不用清洁剂采用干刷。在刷洗牙面后冲洗漱口，再用尖锐探针清楚残留于窝沟中的清洁剂。清洁剂不能含有油脂或过细磨料，可以用浮石粉或不含氟牙膏；</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　<strong>　第二步、酸蚀：</strong>清洁牙面后通常用棉纱球简易隔湿，用压缩空气将牙面吹干后，再用小棉球或细毛刷蘸取酸蚀剂放在要封闭的牙面上。一般酸蚀剂可为磷酸液或含磷酸的凝胶，一般认为凝胶对保持酸蚀区固定在某一部位较好。而酸蚀面积应为接受封闭的范围，一般为牙尖斜面的2／3。酸蚀时间恒牙为20-30秒，而乳牙为60秒。酸蚀过程中要随时添加酸蚀剂，并应轻轻搅拌，以保证足够酸蚀剂与牙体作用，需要注意的是，不要使酸蚀剂与口腔粘膜及软组织接触。酸蚀过程中，不要擦拭牙面，以免降低酸蚀效果；</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;"><strong>　　第三步、冲洗和干燥：</strong>酸蚀后用水加压彻底的冲洗牙面10-15秒，去除牙釉质表面和反应沉淀物。比如含磷酸的凝胶酸蚀，冲洗时间加倍。冲洗的同时需使用吸唾器随时吸净口内唾液。在冲洗后立即更换隔湿棉卷，切记不能让病自行吐出或漱口。随后用压缩空气吹干牙面约15秒，也可采用挥发性强的溶剂辅助干燥，如：无水酒精、乙醚等；</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;"><strong>　　第四步、涂布封闭剂：</strong>用洗刷笔蘸取适量封闭剂涂布在经酸蚀后的牙面上。注意沿窝沟从远中向近中逐渐涂布，还要使细刷笔上下微微抖动，使封闭剂渗入窝沟，排除窝沟内的空气，防止封闭剂下面出现空隙。通常涂布范围应覆盖全部酸蚀面。在不影响咬合的前提下尽可能涂有一定的厚度。如果涂层太薄就会缺乏足够的抗压强度，容易被咬碎；</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;"><strong>　　第五步、固化：</strong>自凝封闭剂涂布后1-2分钟即可自行固化。光固化封闭剂涂布后，应立即用可见光源照射，引发固化。照射距离约离牙尖1mm，照射时间通常为20-40秒，而具体照射时间要根据可见光源性能与使用的封闭材料类型决定。照射的范围要大于封闭剂涂布的范围；<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询</strong></span></a></span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;"><strong>　　第六步：检查：</strong>封闭剂固化后，用尖锐的探针进行全面检查，观察其固化程度，与牙面的粘接情况，还要确认有无气泡存在，寻找遗漏或未封闭的窝沟并重新封闭，检查咬合是否过高，如果发现问题及时处理。假如封闭剂没有填料，咬合高点可不调和，2-3天后可被磨去；如果使用含有填料的封闭剂，就应调整咬合。封闭后，还应定期（3个月、半年或一年）复查，观察封闭剂保留情况，如脱落应重新封闭。</span><br />
&nbsp;</div>
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0929/20170929050142958.jpg" style="width: 450px; height: 280px;" /></a></span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></div>{/dede:field}
{dede:field name='body'}<div><span style="font-size: 16px;">&nbsp; &nbsp; 窝沟封闭又称之为点隙裂沟封闭，是指不去除咬合面牙体组织，在其上涂布一层粘结性树脂，就能保护牙釉质不受细菌及代谢产物侵蚀，增强牙齿抗龋能力，从而达到预防龋病发生的一种有效防龋方法。好像就是给牙齿穿上了一层保护衣，使牙齿免受食物侵蚀。</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size: 16px; color: rgb(255, 0, 0);"><strong>接下来我们一起来看看窝沟封闭的治疗步骤具体是怎样的：</strong></span></a></div>
<div>&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0929/20170929050116102.jpg" style="cursor: pointer; border-width: 0px; border-style: solid; width: 300px; height: 200px;" /></span></a></div>
<div style="text-align: center;">&nbsp;</div>
<div><span style="font-size:16px;">　<strong>　一、清洁牙面：</strong>在低速手机上装好锥形小毛刷或橡皮杯，蘸取适量清洁剂于牙面，要对牙面和窝沟来回刷洗约1分钟，同时不断滴水保持毛刷湿润。也可不用清洁剂采用干刷。在刷洗牙面后冲洗漱口，再用尖锐探针清楚残留于窝沟中的清洁剂。清洁剂不能含有油脂或过细磨料，可以用浮石粉或不含氟牙膏；</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　<strong>　第二步、酸蚀：</strong>清洁牙面后通常用棉纱球简易隔湿，用压缩空气将牙面吹干后，再用小棉球或细毛刷蘸取酸蚀剂放在要封闭的牙面上。一般酸蚀剂可为磷酸液或含磷酸的凝胶，一般认为凝胶对保持酸蚀区固定在某一部位较好。而酸蚀面积应为接受封闭的范围，一般为牙尖斜面的2／3。酸蚀时间恒牙为20-30秒，而乳牙为60秒。酸蚀过程中要随时添加酸蚀剂，并应轻轻搅拌，以保证足够酸蚀剂与牙体作用，需要注意的是，不要使酸蚀剂与口腔粘膜及软组织接触。酸蚀过程中，不要擦拭牙面，以免降低酸蚀效果；</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;"><strong>　　第三步、冲洗和干燥：</strong>酸蚀后用水加压彻底的冲洗牙面10-15秒，去除牙釉质表面和反应沉淀物。比如含磷酸的凝胶酸蚀，冲洗时间加倍。冲洗的同时需使用吸唾器随时吸净口内唾液。在冲洗后立即更换隔湿棉卷，切记不能让病自行吐出或漱口。随后用压缩空气吹干牙面约15秒，也可采用挥发性强的溶剂辅助干燥，如：无水酒精、乙醚等；</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;"><strong>　　第四步、涂布封闭剂：</strong>用洗刷笔蘸取适量封闭剂涂布在经酸蚀后的牙面上。注意沿窝沟从远中向近中逐渐涂布，还要使细刷笔上下微微抖动，使封闭剂渗入窝沟，排除窝沟内的空气，防止封闭剂下面出现空隙。通常涂布范围应覆盖全部酸蚀面。在不影响咬合的前提下尽可能涂有一定的厚度。如果涂层太薄就会缺乏足够的抗压强度，容易被咬碎；</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;"><strong>　　第五步、固化：</strong>自凝封闭剂涂布后1-2分钟即可自行固化。光固化封闭剂涂布后，应立即用可见光源照射，引发固化。照射距离约离牙尖1mm，照射时间通常为20-40秒，而具体照射时间要根据可见光源性能与使用的封闭材料类型决定。照射的范围要大于封闭剂涂布的范围；<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>点击咨询</strong></span></a></span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;"><strong>　　第六步：检查：</strong>封闭剂固化后，用尖锐的探针进行全面检查，观察其固化程度，与牙面的粘接情况，还要确认有无气泡存在，寻找遗漏或未封闭的窝沟并重新封闭，检查咬合是否过高，如果发现问题及时处理。假如封闭剂没有填料，咬合高点可不调和，2-3天后可被磨去；如果使用含有填料的封闭剂，就应调整咬合。封闭后，还应定期（3个月、半年或一年）复查，观察封闭剂保留情况，如脱落应重新封闭。</span><br />
&nbsp;</div>
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0929/20170929050142958.jpg" style="width: 450px; height: 280px;" /></a></span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></div>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D925B2G0-5V07_lit.jpg{/dede:field}
