{dede:field name='keywords'}龋齿,状况,儿童{/dede:field}
{dede:field name='description'}儿童龋齿的状况有哪几种?儿童呈现龋齿的状况是较为常见的，依照龋坏程度的不一样，又分为几种不一样的状况。那么，儿童龋齿的状况有哪{/dede:field}
{dede:field name='title'}儿童龋齿的状况有哪几种{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">&nbsp; &nbsp; 儿童龋齿的状况有哪几种?儿童呈现龋齿的状况是较为常见的，依照龋坏程度的不一样，又分为几种不一样的状况。那么，<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>儿童龋齿的状况有哪几种?</strong></span></a>针对这个问题，看看下文维尔口腔医师是如何介绍的。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0913/20170913033751723.jpg" style="cursor: pointer; border-width: 0px; border-style: solid; width: 300px; height: 216px;" /></a></span></div>
<p><span style="font-size:16px;">　<span style="color:#ff0000;"><strong>儿童龋齿的状况有哪几种?</strong></span>依据龋齿损坏的程度，龋齿可分为浅、中、深龋。</span></p>
<p><span style="font-size:16px;">　一、浅龋：浅龋的病变只在釉质内，牙齿的颜色本来应该是同个颜色，当表面开始有黑点或是脱钙的白点呈现，或是某处老是塞住食物，表示了此处牙齿的珐琅质已遭到损坏，患儿无不适感。</span></p>
<p><span style="font-size:16px;">　二、中龋：病变已达牙本质，构成浅层龋洞，此刻小儿对冷、酸、热的影响感受显着，简单感到酸痛;或是食物一卡进牙缝，就觉得不舒服，但清掉后，不舒服就解除了。</span></p>
<p><span style="font-size:16px;">　三、深龋：病变已达牙髓腔，痛苦继续一段时间才会不见，如不进行医治，细菌沿着牙根到达牙尖，会导致根尖眼炎，形成慢性病灶，导致牙槽骨、下颌骨炎质、骨髓炎及全身疾病。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0913/20170913034217575.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size:16px;">　<strong><span style="color: rgb(255, 0, 0);">　</span></strong>维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">&nbsp; &nbsp; 儿童龋齿的状况有哪几种?儿童呈现龋齿的状况是较为常见的，依照龋坏程度的不一样，又分为几种不一样的状况。那么，<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>儿童龋齿的状况有哪几种?</strong></span></a>针对这个问题，看看下文维尔口腔医师是如何介绍的。</span><br />
<br />
<div style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0913/20170913033751723.jpg" style="cursor: pointer; border-width: 0px; border-style: solid; width: 300px; height: 216px;" /></a></span></div>
<p><span style="font-size:16px;">　<span style="color:#ff0000;"><strong>儿童龋齿的状况有哪几种?</strong></span>依据龋齿损坏的程度，龋齿可分为浅、中、深龋。</span></p>
<p><span style="font-size:16px;">　一、浅龋：浅龋的病变只在釉质内，牙齿的颜色本来应该是同个颜色，当表面开始有黑点或是脱钙的白点呈现，或是某处老是塞住食物，表示了此处牙齿的珐琅质已遭到损坏，患儿无不适感。</span></p>
<p><span style="font-size:16px;">　二、中龋：病变已达牙本质，构成浅层龋洞，此刻小儿对冷、酸、热的影响感受显着，简单感到酸痛;或是食物一卡进牙缝，就觉得不舒服，但清掉后，不舒服就解除了。</span></p>
<p><span style="font-size:16px;">　三、深龋：病变已达牙髓腔，痛苦继续一段时间才会不见，如不进行医治，细菌沿着牙根到达牙尖，会导致根尖眼炎，形成慢性病灶，导致牙槽骨、下颌骨炎质、骨髓炎及全身疾病。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0913/20170913034217575.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size:16px;">　<strong><span style="color: rgb(255, 0, 0);">　</span></strong>维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DWL0H30-14M2_lit.jpg{/dede:field}
