{dede:field name='keywords'}头条,张辉东{/dede:field}
{dede:field name='description'}很多人想矫正牙齿，但又担心“戴牙套好丑的”“满口托槽会很不舒服”“嘴里放根钢丝还怎么吃饭?”一系列疑虑让大家对牙齿矫正望而却步{/dede:field}
{dede:field name='title'}【今日头条】CENTV健康台对话隐形矫正大咖张辉东{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p><span style="font-size: 16px;">　　随着医学技术的进步，现如今隐形矫治时代已经来临，隐形矫正可以帮你&ldquo;悄悄&rdquo;完成牙齿矫治。隐形矫正尤其受明星的追捧与喜爱。</span></p>
<p><span style="font-size:16px;">　　同样的很多人对此产生了疑问</span></p>
<p><strong><span style="font-size:16px;">　　<img alt="yes" height="20" src="/uploadfile/2017/0921/20170921053251149.gif" title="yes" width="20" /></span><span style="font-size: 16px;">疑</span></strong></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　# 这个看似透明的塑料的牙套真的有那么神奇的矫正效果吗?和传统矫正相比有优势?#</span></span></a></p>
<p><strong><span style="font-size:16px;">　　<img alt="yes" height="20" src="/uploadfile/2017/0921/20170921053251149.gif" title="yes" width="20" />答</span></strong></p>
<p><strong><span style="font-size:16px;">　　本期维尔口腔正畸医生张辉东为大家做一个详细的【隐形矫正】解答</span></strong></p>
<p><span style="font-size:16px;">　　2017/9/15</span></p>
<p><span style="font-size:16px;">　　口腔话题：隐形矫正</span></p>
<p><span style="font-size:16px;">　　解答专家：张辉东</span></p>
<p><strong><span style="font-size:16px;">　　内容提要</span></strong></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　1、什么是隐形矫正?</span></span></a></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　2、隐形矫正的优势</span></span></a></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　3、隐形矫正的适应症</span></span></a></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　4、隐形矫正能否到达传统矫正的效果</span></span></a></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　5、选择隐形矫正需要注意的问题</span></span></a></p>
<p style="text-align: center;">&nbsp;</p>
<p>&nbsp;</p>
<video controls="" height="240px" preload="auto" src="http://video.wekq.net/video/zhd.mp4" style="clear:both;display:block;margin:auto" width="320px">
	您的浏览器不支持video</video>
&nbsp; <span style="font-size:16px;"><strong>　一、隐形矫正</strong></span>
<p style="text-align: center;"><strong><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0921/20170921053251812.jpg" style="width: 500px; height: 246px;" /></a></span></strong></p>
<p><span style="font-size:16px;">　　........</span></p>
<p><span style="font-size:16px;">　　隐形矫治器，通俗地说就是一个透明牙套。矫正器是透明的，不易被人察觉，随着时间的推移，这一系列透明牙套逐渐把牙齿矫正到合适的位置,使你的牙列变得整齐，使你的面型发生改变。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0921/20170921053251669.jpg" style="width: 600px; height: 178px;" /></a></span></p>
<p><span style="font-size:16px;">　　...........</span></p>
<p><span style="font-size:16px;">　　正畸医生通过采集牙齿模型、X光片及牙列/面部照片，获得虚拟的3D数字化模型，经过个性化设计，利用计算机辅助技术将整个治疗过程分成多个步骤，并&ldquo;打印&rdquo;出对应的透明牙套。</span></p>
<p><strong><span style="font-size:16px;">　　二、隐形矫正的优势</span></strong></p>
<p><strong><span style="font-size:16px;">　　1、美观舒适、透明</span></strong></p>
<p><span style="font-size:16px;">　　矫正器由安全的弹性透明高分子材料制成，透明而轻薄，其厚度不到1毫米，几乎完全隐形。解决了许多患者对矫正牙齿的美观顾虑。</span></p>
<p><strong><span style="font-size:16px;">　　2、异物感和疼痛感小</span></strong></p>
<p><span style="font-size:16px;">　　由于没有传统意义上的托槽、钢丝等矫正装置，矫正过程不再痛苦。对牙周组织的刺激及不适感低。</span></p>
<p><strong><span style="font-size:16px;">　　3、可自行摘戴，方便清洁</span></strong></p>
<p><span style="font-size:16px;">　　隐形矫正器可自行摘戴，不影响社交、进食、运动等。同时复诊次数减少，节约您的宝贵时间;口腔卫生容易清洁维护。</span></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#008080;"><span style="font-size:16px;">　　【由于矫正器可自行拆卸，所以很容易清洁，也不必担心牙结石、龋齿、牙釉质脱矿、牙龈出血等牙周问题。】</span></span></a></p>
<p><strong><span style="font-size:16px;">　　三、隐形矫正的适应症</span></strong></p>
<p><span style="font-size:16px;">　　矫治个别牙错位、牙列拥挤、牙齿不整齐、牙间隙、前牙反合(地包天、凹面型)、前牙深覆盖(龅牙、凸面型)、前牙深覆合(或深覆盖)、下颌短缩面型、双颌前突、口唇前突和前牙开合(窄长面型)</span></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#008080;"><span style="font-size:16px;">　　对于一些特殊情况：比如对【金属过敏】【牙釉质发育不良】等不适合传统固定矫正的患者，隐形矫正则是更加理想的选择!</span></span></a></p>
<p><strong><span style="font-size:16px;">　　四、隐形矫正能否到达传统矫正的效果</span></strong></p>
<p><span style="font-size:16px;">　　有很多患者疑问到：隐形矫正像&ldquo;塑料一样的材质&rdquo;，矫正效果真的可以像钢牙矫正一样好吗?</span></p>
<p><span style="font-size:16px;">　　隐形矫正器是由高分子纳米材料制成，外观看起来像塑料一样透明，这些塑料牙套材料都是千挑万选选出来的，具有适合牙齿移动的弹性和刚性。你每戴一个新的塑料牙套，牙套就会挤压牙齿朝向目标移动一小步，累积到就会出现很大的变化!</span></p>
<p><span style="font-size:16px;">　　每一个隐适美牙套都是特制的，只有患者本人才能戴用，而且必须按照一定的顺序，每一步都遵医嘱戴够时间，才能戴的进去，任何条件不符合，这一个甚至后面的所有牙套都只能成为废物。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0921/20170921053252324.jpg" style="width: 600px; height: 230px;" /></a></span></p>
<p><strong><span style="font-size:16px;">　　五、选择隐形矫正时需注意</span></strong></p>
<p><span style="font-size:16px;">　　1、需要到正规医疗机构找专业的正畸医生;</span></p>
<p><span style="font-size:16px;">　　2、遵从医生，定期复查，更换新的矫治器，按时佩戴。</span></p>
<p><strong><span style="font-size:16px;">　　本期重点：</span></strong></p>
<p><span style="font-size:16px;">　　个性化定制的隐形矫正同样可以达到预期矫治效果，甚至可以达到比传统矫正更为理想的效果!</span></p>
<p><span style="font-size:16px;">　　隐形矫正透明隐形，外观上几乎看不出来;</span></p>
<p><span style="font-size:16px;">　　隐形矫正可以在吃饭、刷牙时摘下来;</span></p>
<p><span style="font-size:16px;">　　同时对牙齿和矫正器进行清洁，十分便利;</span></p>
<p><span style="font-size:16px;">　　隐形矫正器是通过定期更换新的矫正器;</span></p>
<p><span style="font-size:16px;">　　遵从医嘱，定期复查，按时佩戴。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0921/20170921053252656.jpg" style="width: 450px; height: 280px;" /></span></a></p>
<p><strong><span style="font-size:16px;">　　个人经历</span></strong></p>
<p><span style="font-size:16px;">　　出生牙医世家，毕业于广州医科大学，曾先后在首都医科大学、广东中山医科大、四川华西医科大系统研修矫正及美学修复，经过长期三甲医院的临床锻炼，积累了丰富的临床经验及扎实的理论基础并多次应邀参加国内外大师口腔修复、口腔矫正的学术交流会。在多年的临床工作和实践中，可以熟练操作各种正畸技术，并不断研究新的方法和技巧，完成很多高难度的错颌畸形。</span></p>
<p><span style="font-size:16px;">　　隐形矫正对于爱美人士或者职场不适合戴钢牙套的人来说无非是一场救赎。</span></p>{/dede:field}
{dede:field name='body'}<p><span style="font-size: 16px;">　　随着医学技术的进步，现如今隐形矫治时代已经来临，隐形矫正可以帮你&ldquo;悄悄&rdquo;完成牙齿矫治。隐形矫正尤其受明星的追捧与喜爱。</span></p>
<p><span style="font-size:16px;">　　同样的很多人对此产生了疑问</span></p>
<p><strong><span style="font-size:16px;">　　<img alt="yes" height="20" src="/uploads/allimg/c180407/15230A32CZZ-12I38.gif" title="yes" width="20" /></span><span style="font-size: 16px;">疑</span></strong></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　# 这个看似透明的塑料的牙套真的有那么神奇的矫正效果吗?和传统矫正相比有优势?#</span></span></a></p>
<p><strong><span style="font-size:16px;">　　<img alt="yes" height="20" src="/uploads/allimg/c180407/15230A32CZZ-12I38.gif" title="yes" width="20" />答</span></strong></p>
<p><strong><span style="font-size:16px;">　　本期维尔口腔正畸医生张辉东为大家做一个详细的【隐形矫正】解答</span></strong></p>
<p><span style="font-size:16px;">　　2017/9/15</span></p>
<p><span style="font-size:16px;">　　口腔话题：隐形矫正</span></p>
<p><span style="font-size:16px;">　　解答专家：张辉东</span></p>
<p><strong><span style="font-size:16px;">　　内容提要</span></strong></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　1、什么是隐形矫正?</span></span></a></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　2、隐形矫正的优势</span></span></a></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　3、隐形矫正的适应症</span></span></a></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　4、隐形矫正能否到达传统矫正的效果</span></span></a></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　5、选择隐形矫正需要注意的问题</span></span></a></p>
<p style="text-align: center;">&nbsp;</p>
<p>&nbsp;</p>
<video controls="" height="240px" preload="auto" src="http://video.wekq.net/video/zhd.mp4" style="clear:both;display:block;margin:auto" width="320px">
	您的浏览器不支持video</video>
&nbsp; <span style="font-size:16px;"><strong>　一、隐形矫正</strong></span>
<p style="text-align: center;"><strong><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0921/20170921053251812.jpg" style="width: 500px; height: 246px;" /></a></span></strong></p>
<p><span style="font-size:16px;">　　........</span></p>
<p><span style="font-size:16px;">　　隐形矫治器，通俗地说就是一个透明牙套。矫正器是透明的，不易被人察觉，随着时间的推移，这一系列透明牙套逐渐把牙齿矫正到合适的位置,使你的牙列变得整齐，使你的面型发生改变。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0921/20170921053251669.jpg" style="width: 600px; height: 178px;" /></a></span></p>
<p><span style="font-size:16px;">　　...........</span></p>
<p><span style="font-size:16px;">　　正畸医生通过采集牙齿模型、X光片及牙列/面部照片，获得虚拟的3D数字化模型，经过个性化设计，利用计算机辅助技术将整个治疗过程分成多个步骤，并&ldquo;打印&rdquo;出对应的透明牙套。</span></p>
<p><strong><span style="font-size:16px;">　　二、隐形矫正的优势</span></strong></p>
<p><strong><span style="font-size:16px;">　　1、美观舒适、透明</span></strong></p>
<p><span style="font-size:16px;">　　矫正器由安全的弹性透明高分子材料制成，透明而轻薄，其厚度不到1毫米，几乎完全隐形。解决了许多患者对矫正牙齿的美观顾虑。</span></p>
<p><strong><span style="font-size:16px;">　　2、异物感和疼痛感小</span></strong></p>
<p><span style="font-size:16px;">　　由于没有传统意义上的托槽、钢丝等矫正装置，矫正过程不再痛苦。对牙周组织的刺激及不适感低。</span></p>
<p><strong><span style="font-size:16px;">　　3、可自行摘戴，方便清洁</span></strong></p>
<p><span style="font-size:16px;">　　隐形矫正器可自行摘戴，不影响社交、进食、运动等。同时复诊次数减少，节约您的宝贵时间;口腔卫生容易清洁维护。</span></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#008080;"><span style="font-size:16px;">　　【由于矫正器可自行拆卸，所以很容易清洁，也不必担心牙结石、龋齿、牙釉质脱矿、牙龈出血等牙周问题。】</span></span></a></p>
<p><strong><span style="font-size:16px;">　　三、隐形矫正的适应症</span></strong></p>
<p><span style="font-size:16px;">　　矫治个别牙错位、牙列拥挤、牙齿不整齐、牙间隙、前牙反合(地包天、凹面型)、前牙深覆盖(龅牙、凸面型)、前牙深覆合(或深覆盖)、下颌短缩面型、双颌前突、口唇前突和前牙开合(窄长面型)</span></p>
<p><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#008080;"><span style="font-size:16px;">　　对于一些特殊情况：比如对【金属过敏】【牙釉质发育不良】等不适合传统固定矫正的患者，隐形矫正则是更加理想的选择!</span></span></a></p>
<p><strong><span style="font-size:16px;">　　四、隐形矫正能否到达传统矫正的效果</span></strong></p>
<p><span style="font-size:16px;">　　有很多患者疑问到：隐形矫正像&ldquo;塑料一样的材质&rdquo;，矫正效果真的可以像钢牙矫正一样好吗?</span></p>
<p><span style="font-size:16px;">　　隐形矫正器是由高分子纳米材料制成，外观看起来像塑料一样透明，这些塑料牙套材料都是千挑万选选出来的，具有适合牙齿移动的弹性和刚性。你每戴一个新的塑料牙套，牙套就会挤压牙齿朝向目标移动一小步，累积到就会出现很大的变化!</span></p>
<p><span style="font-size:16px;">　　每一个隐适美牙套都是特制的，只有患者本人才能戴用，而且必须按照一定的顺序，每一步都遵医嘱戴够时间，才能戴的进去，任何条件不符合，这一个甚至后面的所有牙套都只能成为废物。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0921/20170921053252324.jpg" style="width: 600px; height: 230px;" /></a></span></p>
<p><strong><span style="font-size:16px;">　　五、选择隐形矫正时需注意</span></strong></p>
<p><span style="font-size:16px;">　　1、需要到正规医疗机构找专业的正畸医生;</span></p>
<p><span style="font-size:16px;">　　2、遵从医生，定期复查，更换新的矫治器，按时佩戴。</span></p>
<p><strong><span style="font-size:16px;">　　本期重点：</span></strong></p>
<p><span style="font-size:16px;">　　个性化定制的隐形矫正同样可以达到预期矫治效果，甚至可以达到比传统矫正更为理想的效果!</span></p>
<p><span style="font-size:16px;">　　隐形矫正透明隐形，外观上几乎看不出来;</span></p>
<p><span style="font-size:16px;">　　隐形矫正可以在吃饭、刷牙时摘下来;</span></p>
<p><span style="font-size:16px;">　　同时对牙齿和矫正器进行清洁，十分便利;</span></p>
<p><span style="font-size:16px;">　　隐形矫正器是通过定期更换新的矫正器;</span></p>
<p><span style="font-size:16px;">　　遵从医嘱，定期复查，按时佩戴。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0921/20170921053252656.jpg" style="width: 450px; height: 280px;" /></span></a></p>
<p><strong><span style="font-size:16px;">　　个人经历</span></strong></p>
<p><span style="font-size:16px;">　　出生牙医世家，毕业于广州医科大学，曾先后在首都医科大学、广东中山医科大、四川华西医科大系统研修矫正及美学修复，经过长期三甲医院的临床锻炼，积累了丰富的临床经验及扎实的理论基础并多次应邀参加国内外大师口腔修复、口腔矫正的学术交流会。在多年的临床工作和实践中，可以熟练操作各种正畸技术，并不断研究新的方法和技巧，完成很多高难度的错颌畸形。</span></p>
<p><span style="font-size:16px;">　　隐形矫正对于爱美人士或者职场不适合戴钢牙套的人来说无非是一场救赎。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180407/15230A32CZZ-12I38_lit.gif{/dede:field}
