{dede:field name='keywords'}维尔口腔{/dede:field}
{dede:field name='description'}5分钟种好一颗牙，真的假的? 种植牙不疼?骗人的吧。 到底是真的还是假的?到底疼不疼? 3月24日上午9：00，在维尔口腔三元桥总{/dede:field}
{dede:field name='title'}维尔口腔&quot;见证缺牙重生&quot;种植牙直播惊艳缺牙人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p><span style="font-size:14px;"><span style="color:#000000;">　　5分钟种好一颗牙，真的假的?</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　种植牙不疼?骗人的吧。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　到底是真的还是假的?到底疼不疼?</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　3月24日上午9：00，在维尔口腔三元桥总院举办的&ldquo;见证缺牙重生&rdquo;种植牙直播公益活动，让许多抱着疑问的缺牙人得到了答案。</span></span></p>
<center>
	<span style="font-size:14px;"><span style="color:#000000;"><img alt="" src="/uploadfile/2018/0324/20180324060231883.jpg" style="width: 550px; height: 367px;" /></span></span></center>
<p><span style="font-size:14px;"><span style="color:#000000;"><strong>　　计时5分钟 惊艳缺牙人</strong></span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　3月24日上午，通过网络、报纸报名参加种植牙直播公益活动的缺牙人陆陆续续来自维尔口腔医院。他们中的大多数都是第一次接触种植牙，对种植牙的概念一直都很模糊。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　此次活动的主讲人，维尔口腔医院医务院长、种植牙专家贺彩女士为缺牙人讲解了关于种植牙的知识。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　贺彩指出，种植牙是一种以植入骨组织内的下部结构为基础来支持、固位上部牙修复体的缺牙修复方式。它包括下部的支持种植体和上部的牙修复体两部分。它采用人工材料(如金属、陶瓷等)制成种植体(一般类似牙根形态)，经手术方法植入上下颌，并获得骨组织牢固的固位支持，通过特殊的装置和方式连接支持上部的牙修复体。种植牙可以获得与天然牙功能、结构以及美观效果十分相似的修复效果，已经成为越来越多缺牙患者的首选修复方式。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　&ldquo;种植牙技术发展日新月异，现在临床应用最多的就是即刻种植、即拔即种、ALL-ON-4等种植牙技术。&rdquo;贺彩说，&ldquo;今天直播就是即刻种植技术修复缺牙。&rdquo;</span></span></p>
<center>
	<span style="font-size:14px;"><span style="color:#000000;"><img alt="" src="/uploadfile/2018/0324/20180324060247643.jpg" style="width: 550px; height: 367px;" /></span></span></center>
<p><span style="font-size:14px;"><span style="color:#000000;">　　张女士是这次直播活动中将要种牙的患者，她的口腔缺了1颗牙，通过网络预约了维尔口腔种植院长邱星明的专家号。通过CT片，可以清楚的看到张女士的缺牙部位。邱星明院长熟练的用微创技术在缺牙部位开了一个4mm的创口，然后将一颗种植体植入到张女士的牙骨中，并且完成缝合。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　&ldquo;整个手术时间仅5分钟，实在太神奇了。&rdquo;一名参加直播的缺牙人指着自己的手表说。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;"><strong>　　近距离沟通 原来种植牙这么简单</strong></span></span></p>
<center>
	<span style="font-size:14px;"><span style="color:#000000;"><img alt="" src="/uploadfile/2018/0324/20180324060259557.jpg" style="width: 550px; height: 367px;" /></span></span></center>
<p><span style="font-size:14px;"><span style="color:#000000;">　　短短的5分钟，牙就种完了。张女士来到直播大厅，讲诉了自己的感受：&ldquo;刚躺了一会儿，牙就种好了，我也没想到会这么快。&rdquo;</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　&ldquo;现在疼吗?&rdquo;有缺牙人问。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　&ldquo;一点也不疼，没什么感觉。&rdquo;张女士说，之前不知道种植牙会这么快、而且还不疼，因为到底要不要种植的事，还纠结了好久，&ldquo;早知道这么简单就种好了，我早就来种牙了。&rdquo;</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　贺彩院长告诉大家，这次邱院长使用的是即刻种植技术，其优点就是创伤小，一般只要3-5mm，恢复快，而且无痛苦。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;"><strong>　　抽奖抽到种植牙 幸福要不要这么突然</strong></span></span></p>
<center>
	<span style="font-size:14px;"><span style="color:#000000;"><img alt="" src="/uploadfile/2018/0324/20180324060310818.jpg" style="width: 550px; height: 367px;" /></span></span></center>
<p><span style="font-size:14px;"><span style="color:#000000;">　　直播结束后，现场还进行了抽奖环节。此次直播活动推出的公益大奖让参加活动的缺牙人感觉不虚此行。一等奖价值18000元的瑞士ITI种植体;二等奖价值4500元的全瓷牙冠;三等奖2000元代金券。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　共有6位参加活动的缺牙人抽到大奖。其中，抽到一等奖的缺牙人更是兴奋的难以自已，&ldquo;没想到还能抽到一等奖，幸福来的太突然了。&rdquo;</span></span></p>
<p style="text-align: center;"><img alt="" src="/uploadfile/2018/0324/20180324060436450.jpg" style="width: 550px; height: 367px;" /></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　今年是维尔口腔成立20周年，为了回馈缺牙患者，普及种植牙知识，维尔口腔将种植牙直播公益活动贯彻全年，并且拿出价值百万的进口种植体、全瓷牙等作为奖品，让参加直播活动的缺牙人不仅长见识，更要得实惠。</span></span></p>{/dede:field}
{dede:field name='body'}<p><span style="font-size:14px;"><span style="color:#000000;">　　5分钟种好一颗牙，真的假的?</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　种植牙不疼?骗人的吧。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　到底是真的还是假的?到底疼不疼?</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　3月24日上午9：00，在维尔口腔三元桥总院举办的&ldquo;见证缺牙重生&rdquo;种植牙直播公益活动，让许多抱着疑问的缺牙人得到了答案。</span></span></p>
<center>
	<span style="font-size:14px;"><span style="color:#000000;"><img alt="" src="/uploads/allimg/c180407/15230A335BZ-64Q6.jpg" style="width: 550px; height: 367px;" /></span></span></center>
<p><span style="font-size:14px;"><span style="color:#000000;"><strong>　　计时5分钟 惊艳缺牙人</strong></span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　3月24日上午，通过网络、报纸报名参加种植牙直播公益活动的缺牙人陆陆续续来自维尔口腔医院。他们中的大多数都是第一次接触种植牙，对种植牙的概念一直都很模糊。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　此次活动的主讲人，维尔口腔医院医务院长、种植牙专家贺彩女士为缺牙人讲解了关于种植牙的知识。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　贺彩指出，种植牙是一种以植入骨组织内的下部结构为基础来支持、固位上部牙修复体的缺牙修复方式。它包括下部的支持种植体和上部的牙修复体两部分。它采用人工材料(如金属、陶瓷等)制成种植体(一般类似牙根形态)，经手术方法植入上下颌，并获得骨组织牢固的固位支持，通过特殊的装置和方式连接支持上部的牙修复体。种植牙可以获得与天然牙功能、结构以及美观效果十分相似的修复效果，已经成为越来越多缺牙患者的首选修复方式。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　&ldquo;种植牙技术发展日新月异，现在临床应用最多的就是即刻种植、即拔即种、ALL-ON-4等种植牙技术。&rdquo;贺彩说，&ldquo;今天直播就是即刻种植技术修复缺牙。&rdquo;</span></span></p>
<center>
	<span style="font-size:14px;"><span style="color:#000000;"><img alt="" src="/uploads/allimg/c180407/15230A33631A0-M2V.jpg" style="width: 550px; height: 367px;" /></span></span></center>
<p><span style="font-size:14px;"><span style="color:#000000;">　　张女士是这次直播活动中将要种牙的患者，她的口腔缺了1颗牙，通过网络预约了维尔口腔种植院长邱星明的专家号。通过CT片，可以清楚的看到张女士的缺牙部位。邱星明院长熟练的用微创技术在缺牙部位开了一个4mm的创口，然后将一颗种植体植入到张女士的牙骨中，并且完成缝合。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　&ldquo;整个手术时间仅5分钟，实在太神奇了。&rdquo;一名参加直播的缺牙人指着自己的手表说。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;"><strong>　　近距离沟通 原来种植牙这么简单</strong></span></span></p>
<center>
	<span style="font-size:14px;"><span style="color:#000000;"><img alt="" src="/uploads/allimg/c180407/15230A33E1340-SC1.jpg" style="width: 550px; height: 367px;" /></span></span></center>
<p><span style="font-size:14px;"><span style="color:#000000;">　　短短的5分钟，牙就种完了。张女士来到直播大厅，讲诉了自己的感受：&ldquo;刚躺了一会儿，牙就种好了，我也没想到会这么快。&rdquo;</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　&ldquo;现在疼吗?&rdquo;有缺牙人问。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　&ldquo;一点也不疼，没什么感觉。&rdquo;张女士说，之前不知道种植牙会这么快、而且还不疼，因为到底要不要种植的事，还纠结了好久，&ldquo;早知道这么简单就种好了，我早就来种牙了。&rdquo;</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　贺彩院长告诉大家，这次邱院长使用的是即刻种植技术，其优点就是创伤小，一般只要3-5mm，恢复快，而且无痛苦。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;"><strong>　　抽奖抽到种植牙 幸福要不要这么突然</strong></span></span></p>
<center>
	<span style="font-size:14px;"><span style="color:#000000;"><img alt="" src="/uploads/allimg/c180407/15230A33J3a0-95054.jpg" style="width: 550px; height: 367px;" /></span></span></center>
<p><span style="font-size:14px;"><span style="color:#000000;">　　直播结束后，现场还进行了抽奖环节。此次直播活动推出的公益大奖让参加活动的缺牙人感觉不虚此行。一等奖价值18000元的瑞士ITI种植体;二等奖价值4500元的全瓷牙冠;三等奖2000元代金券。</span></span></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　共有6位参加活动的缺牙人抽到大奖。其中，抽到一等奖的缺牙人更是兴奋的难以自已，&ldquo;没想到还能抽到一等奖，幸福来的太突然了。&rdquo;</span></span></p>
<p style="text-align: center;"><img alt="" src="/uploads/allimg/c180407/15230A33P0450-105B9.jpg" style="width: 550px; height: 367px;" /></p>
<p><span style="font-size:14px;"><span style="color:#000000;">　　今年是维尔口腔成立20周年，为了回馈缺牙患者，普及种植牙知识，维尔口腔将种植牙直播公益活动贯彻全年，并且拿出价值百万的进口种植体、全瓷牙等作为奖品，让参加直播活动的缺牙人不仅长见识，更要得实惠。</span></span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180407/15230A335BZ-64Q6_lit.jpg{/dede:field}
