<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://beij.weierkq.com/zzyjgb/777.html",61,135);
$z[2]=Array("keywordtrim","",137,174);
$z[3]=Array("descriptiontrim","",176,221);
$z[4]=Array("item","\r\n   {dede:match}<div class=\"show_title\">\r\n						<span>[内容]</span>\r\n						<span>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",223,429);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",429,569);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",569,709);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}<div class=\"show_content auto\">[内容]</div>\r\n					<div class=\"zj_input auto\">{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",709,929);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"show_content auto\">[内容]</div>\r\n					<div class=\"zj_input auto\">{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",929,1148);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>