{dede:field name='keywords'}龋齿,儿童{/dede:field}
{dede:field name='description'}儿童龋齿对局部健康的影响，对儿童龋齿对面部发育，口腔卫生都有着很大的影响，局部健康的影响与儿童全身健康影响，更能直接的体现在面{/dede:field}
{dede:field name='title'}儿童龋齿对局部健康的影响{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">&nbsp; &nbsp; 儿童龋齿对局部健康的影响，对儿童龋齿对面部发育，口腔卫生都有着很大的影响，局部健康的影响与儿童全身健康影响，更能直接的体现在面部。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>龋齿是怎么得的？</strong></span></a></span><br />
<br />
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0919/20170919041558390.jpg" style="width: 300px; height: 204px; cursor: pointer; border-width: 0px; border-style: solid;" /></span></a></div>
<p><span style="font-size:16px;">　　1.造成面部发育不对称。龋齿疼痛，造成偏侧咀嚼习惯，久之便造成面部发育不对称。</span></p>
<p><span style="font-size:16px;">　　2.恒牙错牙合和发育不良。龋齿引起乳牙早失，致使相邻牙向缺隙处移位，造成咬合关系紊乱，形成恒牙错牙合；乳牙龋齿如不及时治疗，还可引起恒牙发育不良。</span></p>
<p><span style="font-size:16px;">　　3.颌面部畸形。乳牙列是儿童时期的咀嚼器官，由于咀嚼功能的刺激，才能促进颌骨的正常发育，失去了这种正常生理刺激，颌骨的正常发育受到影响，可造成颌面部轻重不等的畸形。</span></p>
<p><span style="font-size:16px;">　　4.继发其他牙病。龋齿可发展为牙髓炎、根尖周围炎、牙源性囊肿或间隙感染等。乳牙的尖周炎还可波及到恒牙，导致恒牙硬组织发育不全，形成所谓的忒奈氏牙。</span></p>
<p><span style="font-size:16px;">　　5.其他如影响儿童发育，造成偏食和食欲不振等。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>咨询在线医生</strong></span></a></span></p>
<div><span style="color:#ff0000;"><strong><span style="font-size:16px;">维尔口腔医院，专业塑造品牌!</span></strong></span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　1、专业团队 放心诊疗</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　国内知名口腔教授刘志杰领衔的口腔医师团队，让您轻松拥有自然、美观、精细、逼真的牙齿。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　2、即刻手术 节约时长</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔引进先进技术，手术过程仅需5-10分钟，短暂的手术时间降低了手术风险;仅需一次手术，恒久支撑牙冠，咀嚼更给力。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　3、品牌优势 个性修复</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔安全放心，材质安全无害，经久耐用，治疗时会根据顾客牙齿的颜色与形状等实际情况来综合考量，力求整体协调和美观的效果。</span><br />
&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0919/20170919041702979.jpg" style="width: 450px; height: 280px;" /></a></div>
<p><span style="font-size:16px;">　　维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">&nbsp; &nbsp; 儿童龋齿对局部健康的影响，对儿童龋齿对面部发育，口腔卫生都有着很大的影响，局部健康的影响与儿童全身健康影响，更能直接的体现在面部。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>龋齿是怎么得的？</strong></span></a></span><br />
<br />
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/0919/20170919041558390.jpg" style="width: 300px; height: 204px; cursor: pointer; border-width: 0px; border-style: solid;" /></span></a></div>
<p><span style="font-size:16px;">　　1.造成面部发育不对称。龋齿疼痛，造成偏侧咀嚼习惯，久之便造成面部发育不对称。</span></p>
<p><span style="font-size:16px;">　　2.恒牙错牙合和发育不良。龋齿引起乳牙早失，致使相邻牙向缺隙处移位，造成咬合关系紊乱，形成恒牙错牙合；乳牙龋齿如不及时治疗，还可引起恒牙发育不良。</span></p>
<p><span style="font-size:16px;">　　3.颌面部畸形。乳牙列是儿童时期的咀嚼器官，由于咀嚼功能的刺激，才能促进颌骨的正常发育，失去了这种正常生理刺激，颌骨的正常发育受到影响，可造成颌面部轻重不等的畸形。</span></p>
<p><span style="font-size:16px;">　　4.继发其他牙病。龋齿可发展为牙髓炎、根尖周围炎、牙源性囊肿或间隙感染等。乳牙的尖周炎还可波及到恒牙，导致恒牙硬组织发育不全，形成所谓的忒奈氏牙。</span></p>
<p><span style="font-size:16px;">　　5.其他如影响儿童发育，造成偏食和食欲不振等。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>咨询在线医生</strong></span></a></span></p>
<div><span style="color:#ff0000;"><strong><span style="font-size:16px;">维尔口腔医院，专业塑造品牌!</span></strong></span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　1、专业团队 放心诊疗</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　国内知名口腔教授刘志杰领衔的口腔医师团队，让您轻松拥有自然、美观、精细、逼真的牙齿。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　2、即刻手术 节约时长</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔引进先进技术，手术过程仅需5-10分钟，短暂的手术时间降低了手术风险;仅需一次手术，恒久支撑牙冠，咀嚼更给力。</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　3、品牌优势 个性修复</span></div>
<div>&nbsp;</div>
<div><span style="font-size:16px;">　　维尔口腔安全放心，材质安全无害，经久耐用，治疗时会根据顾客牙齿的颜色与形状等实际情况来综合考量，力求整体协调和美观的效果。</span><br />
&nbsp;</div>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploadfile/2017/0919/20170919041702979.jpg" style="width: 450px; height: 280px;" /></a></div>
<p><span style="font-size:16px;">　　维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D9636145P-121612_lit.jpg{/dede:field}
