
    {dede:addurls}http://beij.weierkq.com/etycjzE/5.html
http://beij.weierkq.com/etycjzE/4.html
http://beij.weierkq.com/etycjzE/3.html
http://beij.weierkq.com/etycjzE/2.html
http://beij.weierkq.com/etycjzE/{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="left_center auto">{/dede:areastart}
    {dede:areaend}<div id="pages" class="text-c auto">{/dede:areaend}
