{dede:field name='keywords'}怎么办{/dede:field}
{dede:field name='description'}牙齿变色让我们不再拥有健康美丽的姿态，影响着我们的形象和自信。因此很多人选择美白牙齿来提升自己的气质和自信，对此选择好的牙科医{/dede:field}
{dede:field name='title'}牙齿美白哪里好{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p>　　牙齿变色让我们不再拥有健康美丽的姿态，影响着我们的形象和自信。因此很多人选择美白牙齿来提升自己的气质和自信，对此选择好的牙科医院就是很重要的事。下面北京维尔口腔医生在线为您详细的介绍。</p>
<p style="text-align: center; font-stretch: normal;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427080930668.jpg" style="width: 300px; height: 216px;" /></p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">1</span><strong>维尔口腔院长推荐，冷光美白：</strong></h2>
<p>　　维尔医院专家推荐冷光美白技术。美国皓齿口腔科技公司在冷光美白基础上研究出更新、效率更高，舒适安全的牙齿美白技术&mdash;&mdash;冷光美白技术。冷光美白是通过氧化剂过氧化氢中的小分子，穿过牙釉质和牙本质渗透到牙齿的所有部分，在釉小柱间移动，分解清除牙变色的色素分子。不改变牙齿结构的情况下，能产生美白作用，一小时就拥有洁白的牙齿。</p>
<p>　　专家指出：&ldquo;冷光美白&rdquo;在专用牙龈、牙体防护系统的保护下，使经过特殊光学处理的纳米光催化牙体活化剂上，在牙体表层建立美白作用通道，美白成分直接作用于牙体，通过氧化还原作用将牙体内的浅、中、深层所残留色素彻底清除。同时，通过氟化作用，促使牙釉质新生，封闭牙本质小管和牙釉质微孔。不仅美白高效持久，更带来光亮、坚固，实现真正的健康白--洁白、富光泽、有透明感。该项技术规避了以前所有常规美白方式的弊端，拒绝无光泽、钙化白，是目前新有效的牙齿美白方法。</p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">2</span><strong>维尔口腔牙齿美白修复&mdash;&mdash;任蕾美学修复主任推荐</strong></h2>
<div style="text-align: center; padding: 0px; margin: 0px; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0); font-stretch: normal;"><br />
<img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427070305545.jpg" style="width: 450px; height: 280px;" /></div>
<div style="font-stretch: normal;">&nbsp;</div>
<div style="font-stretch: normal;">
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">3</span><strong>维尔口腔</strong><strong>任蕾美学修复主任</strong><strong>&mdash;&mdash;牙齿美白修复真实案例</strong></h2>
<div style="text-align: center;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427081503348.jpg" style="width: 300px; height: 157px;" /></div>
<div style="text-align: center;"><br />
<span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px"><span style="COLOR: rgb(0,0,0)"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">刘女士 年龄：35 四环素牙</a></span></span></div>
<div style="TEXT-ALIGN: center"><u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="COLOR: rgb(0,128,128)"><span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px">牙齿美白多少钱击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">4</span><strong>维尔口腔&mdash;&mdash;北京牙齿美白修复中心</strong></h2>
<div style="padding: 0px; margin: 0px; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0); font-stretch: normal;">
<p>　　维尔口腔是北京较早开展美学修复项目的医疗机构之一。引进的仿生美容冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。由维尔美齿导师刘志杰院长制定出的3-3-4-4美齿黄金法则， 被众多美齿机构广泛借鉴及沿用。</p>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">安全材质</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　具有高度生物兼容性，对口腔无害，并加速种牙冠与口内组织的紧密结合性。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; PADDING-TOP: 5px"><font color="#e36c09"><span style="FONT-SIZE: 14px">专业团队</span></font></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　由院长刘志杰、美学修复主任任蕾等经验丰富的美学修复医生，亲自临床，提高美白修复安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">科学流程</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。</p>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解牙齿美白，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
</div>
</div>
<br />{/dede:field}
{dede:field name='body'}<p>　　牙齿变色让我们不再拥有健康美丽的姿态，影响着我们的形象和自信。因此很多人选择美白牙齿来提升自己的气质和自信，对此选择好的牙科医院就是很重要的事。下面北京维尔口腔医生在线为您详细的介绍。</p>
<p style="text-align: center; font-stretch: normal;"><img alt="" src="/uploads/allimg/c180322/1521DC62C430-14151.jpg" style="width: 300px; height: 216px;" /></p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">1</span><strong>维尔口腔院长推荐，冷光美白：</strong></h2>
<p>　　维尔医院专家推荐冷光美白技术。美国皓齿口腔科技公司在冷光美白基础上研究出更新、效率更高，舒适安全的牙齿美白技术&mdash;&mdash;冷光美白技术。冷光美白是通过氧化剂过氧化氢中的小分子，穿过牙釉质和牙本质渗透到牙齿的所有部分，在釉小柱间移动，分解清除牙变色的色素分子。不改变牙齿结构的情况下，能产生美白作用，一小时就拥有洁白的牙齿。</p>
<p>　　专家指出：&ldquo;冷光美白&rdquo;在专用牙龈、牙体防护系统的保护下，使经过特殊光学处理的纳米光催化牙体活化剂上，在牙体表层建立美白作用通道，美白成分直接作用于牙体，通过氧化还原作用将牙体内的浅、中、深层所残留色素彻底清除。同时，通过氟化作用，促使牙釉质新生，封闭牙本质小管和牙釉质微孔。不仅美白高效持久，更带来光亮、坚固，实现真正的健康白--洁白、富光泽、有透明感。该项技术规避了以前所有常规美白方式的弊端，拒绝无光泽、钙化白，是目前新有效的牙齿美白方法。</p>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">2</span><strong>维尔口腔牙齿美白修复&mdash;&mdash;任蕾美学修复主任推荐</strong></h2>
<div style="text-align: center; padding: 0px; margin: 0px; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0); font-stretch: normal;"><br />
<img alt="" src="/uploads/allimg/c180322/1521DC631O10-23L7.jpg" style="width: 450px; height: 280px;" /></div>
<div style="font-stretch: normal;">&nbsp;</div>
<div style="font-stretch: normal;">
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">3</span><strong>维尔口腔</strong><strong>任蕾美学修复主任</strong><strong>&mdash;&mdash;牙齿美白修复真实案例</strong></h2>
<div style="text-align: center;"><img alt="" src="/uploads/allimg/c180322/1521DC63BQ0-35513.jpg" style="width: 300px; height: 157px;" /></div>
<div style="text-align: center;"><br />
<span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px"><span style="COLOR: rgb(0,0,0)"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">刘女士 年龄：35 四环素牙</a></span></span></div>
<div style="TEXT-ALIGN: center"><u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="COLOR: rgb(0,128,128)"><span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px">牙齿美白多少钱击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="border-bottom-color: rgb(0, 112, 192); border-bottom-width: 2px; border-bottom-style: solid; text-align: justify; padding: 0px; margin: 8px 0px 0px; min-height: 32px; font-weight: 500; font-size: 16px; line-height: 28px; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); font-stretch: normal;"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">4</span><strong>维尔口腔&mdash;&mdash;北京牙齿美白修复中心</strong></h2>
<div style="padding: 0px; margin: 0px; font-size: 14px; line-height: 21px; font-family: 微软雅黑; color: rgb(0, 0, 0); font-stretch: normal;">
<p>　　维尔口腔是北京较早开展美学修复项目的医疗机构之一。引进的仿生美容冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。由维尔美齿导师刘志杰院长制定出的3-3-4-4美齿黄金法则， 被众多美齿机构广泛借鉴及沿用。</p>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">安全材质</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　具有高度生物兼容性，对口腔无害，并加速种牙冠与口内组织的紧密结合性。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; PADDING-TOP: 5px"><font color="#e36c09"><span style="FONT-SIZE: 14px">专业团队</span></font></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　由院长刘志杰、美学修复主任任蕾等经验丰富的美学修复医生，亲自临床，提高美白修复安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">科学流程</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。</p>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解牙齿美白，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
</div>
</div>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DC62C430-14151_lit.jpg{/dede:field}
