{dede:field name='keywords'}缺失,怎么办{/dede:field}
{dede:field name='description'}家有一老，如有一宝，长寿老人是家庭的财富，更是追求健康的 榜样，但身体的硬朗也没办法改变牙齿的脱落，对饮食再讲究，没有一口好的牙齿，营养没办法通过饮食来获得均衡。牙{/dede:field}
{dede:field name='title'}半口牙缺失怎么办?{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p>　　家有一老，如有一宝，长寿老人是家庭的财富，更是追求健康的好的榜样，但身体的硬朗也没办法改变牙齿的脱落，对饮食再讲究，没有一口好的牙齿，营养没办法通过饮食来获得均衡。牙缺失是我国老年人 常见的问题，其中以半口牙缺失和全口牙缺失为多数。对于老年人半口牙缺失如何修复好呢?<span style="color:#000000;"><strong>北京维尔口腔医生在线解答！</strong></span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0422/20170422091659828.jpg" style="width: 300px; height: 198px;" /></a></p>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">1</span><strong>牙缺失，先看修复方法合不合适</strong></h2>
<p><span style="color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px; line-height: 21px;">　　</span>众所周知，活动假牙和固定假牙及种植牙是我们常见的缺牙修复方法，而面对半口的牙齿修复，并不是这三种方法都合适。首先我们看固定假牙，半口牙缺失无基础牙，而固定假牙需借助相邻牙齿的力量来固位，显然而知不可使用。<strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#008080;">种植牙哪种材料好点击咨询&lt;&lt;&lt;</span></a></strong></p>
<p>　　也许有些人会选择活动假牙，这个是可以的，但时间不长。若采用活动假牙修复，随着年龄增加，上、下牙槽骨严重收缩，可能出现因舌体运动和咀嚼食物时假牙移位或翘动(跳跳牙)，损伤粘膜，造成口腔粘膜溃疡，长期口腔粘膜溃疡可导致口腔粘膜癌变。而种植牙则可避免以上情况发生，让牙齿重获新生。</p>
<p>　　种植牙通过医学方式，将与人体骨质兼容性高的纯钛金属经过精密的设计，制造成类似牙根的圆柱体或其他形状，以外科小手术的方式植入缺牙区的牙槽骨内，经过 1~3 个月后，当人工牙根与牙槽骨密合后，再在人工牙根上制作烤瓷牙冠。</p>
<p>　<strong>　种植牙作为目前较好的牙齿缺失修复体，</strong>经过三十年的临床实践考验，已日趋成为一项成熟的口腔修复治疗手段，与一般传统的修复方法相比更有优势。</p>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">2</span><strong>维尔口腔种植牙&mdash;&mdash;院长推荐</strong></h2>
<div style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px; line-height: 21px; text-align: center;"><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0422/20170422091915131.jpg" style="width: 450px; height: 280px;" /></a></div>
<div>&nbsp;</div>
<div>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">3</span><strong>维尔口腔刘院长&mdash;&mdash;全口一日得种植牙技术真实案例</strong></h2>
<br />
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0423/20170423085132145.jpg" style="width: 300px; height: 165px;" /></a><br />
<span style="font-family: Simsun; font-size: 14px; line-height: 28px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#000000;">刘先生 &nbsp; &nbsp; 年龄：53 &nbsp; &nbsp;牙齿全口缺失</span></a></span><br />
<u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="color:#008080;"><span style="font-family: Simsun; font-size: 14px; line-height: 28px;">治疗方案&ldquo;一日得&rdquo;全口种植技术点击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">4</span><strong>维尔口腔&mdash;&mdash;北京专业安全种植牙中心</strong></h2>
<div style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px; line-height: 21px;">
<p>　　维尔口腔是北京较早开展种植牙医学项目的医疗机构之一，与欧洲、韩国等种植医学机构合作，引进了瑞士一代和第二代ITI种植系统，韩国奥齿泰种植系统、瑞士BIENAIR光纤种植机等国际上较为先进的种植技术和设备</p>
<h2 class="135brush" placeholder="请输入标题" style="margin: 10px 0px; padding: 5px 10px; font-size: 16px; font-weight: 500; border-left-width: 5px; border-left-style: solid; border-left-color: rgb(255, 129, 36); line-height: 32px; color: rgb(102, 102, 102);"><strong><span style="font-size: 14px;"><span style="color: rgb(227, 108, 9);">安全材质</span></span></strong></h2>
<div style="margin: 0px; padding: 0px;">
<p>　　具有高度生物兼容性，对口腔无害，并加速种植体与牙槽骨。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="margin: 10px 0px; padding: 5px 10px; border-left-width: 5px; border-left-style: solid; border-left-color: rgb(255, 129, 36); line-height: 32px;"><font color="#e36c09"><span style="font-size: 14px;">专业团队</span></font></h2>
<div style="margin: 0px; padding: 0px;">
<p>　　由院长刘志杰、董春强等经验丰富的种植学科医生，亲自手术，提高手术安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="margin: 10px 0px; padding: 5px 10px; font-size: 16px; font-weight: 500; border-left-width: 5px; border-left-style: solid; border-left-color: rgb(255, 129, 36); line-height: 32px; color: rgb(102, 102, 102);"><strong><span style="font-size: 14px;"><span style="color: rgb(227, 108, 9);">科学流程</span></span></strong></h2>
<div style="margin: 0px; padding: 0px;">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。<br />
&nbsp;</p>
<div>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解种植牙，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
</div>
</div>
<br />{/dede:field}
{dede:field name='body'}<p>　　家有一老，如有一宝，长寿老人是家庭的财富，更是追求健康的好的榜样，但身体的硬朗也没办法改变牙齿的脱落，对饮食再讲究，没有一口好的牙齿，营养没办法通过饮食来获得均衡。牙缺失是我国老年人 常见的问题，其中以半口牙缺失和全口牙缺失为多数。对于老年人半口牙缺失如何修复好呢?<span style="color:#000000;"><strong>北京维尔口腔医生在线解答！</strong></span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D4CB1950-16239.jpg" style="width: 300px; height: 198px;" /></a></p>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">1</span><strong>牙缺失，先看修复方法合不合适</strong></h2>
<p><span style="color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px; line-height: 21px;">　　</span>众所周知，活动假牙和固定假牙及种植牙是我们常见的缺牙修复方法，而面对半口的牙齿修复，并不是这三种方法都合适。首先我们看固定假牙，半口牙缺失无基础牙，而固定假牙需借助相邻牙齿的力量来固位，显然而知不可使用。<strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#008080;">种植牙哪种材料好点击咨询&lt;&lt;&lt;</span></a></strong></p>
<p>　　也许有些人会选择活动假牙，这个是可以的，但时间不长。若采用活动假牙修复，随着年龄增加，上、下牙槽骨严重收缩，可能出现因舌体运动和咀嚼食物时假牙移位或翘动(跳跳牙)，损伤粘膜，造成口腔粘膜溃疡，长期口腔粘膜溃疡可导致口腔粘膜癌变。而种植牙则可避免以上情况发生，让牙齿重获新生。</p>
<p>　　种植牙通过医学方式，将与人体骨质兼容性高的纯钛金属经过精密的设计，制造成类似牙根的圆柱体或其他形状，以外科小手术的方式植入缺牙区的牙槽骨内，经过 1~3 个月后，当人工牙根与牙槽骨密合后，再在人工牙根上制作烤瓷牙冠。</p>
<p>　<strong>　种植牙作为目前较好的牙齿缺失修复体，</strong>经过三十年的临床实践考验，已日趋成为一项成熟的口腔修复治疗手段，与一般传统的修复方法相比更有优势。</p>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">2</span><strong>维尔口腔种植牙&mdash;&mdash;院长推荐</strong></h2>
<div style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px; line-height: 21px; text-align: center;"><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D4CH2a0-23625.jpg" style="width: 450px; height: 280px;" /></a></div>
<div>&nbsp;</div>
<div>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">3</span><strong>维尔口腔刘院长&mdash;&mdash;全口一日得种植牙技术真实案例</strong></h2>
<br />
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D4CMR30-33045.jpg" style="width: 300px; height: 165px;" /></a><br />
<span style="font-family: Simsun; font-size: 14px; line-height: 28px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#000000;">刘先生 &nbsp; &nbsp; 年龄：53 &nbsp; &nbsp;牙齿全口缺失</span></a></span><br />
<u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="color:#008080;"><span style="font-family: Simsun; font-size: 14px; line-height: 28px;">治疗方案&ldquo;一日得&rdquo;全口种植技术点击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">4</span><strong>维尔口腔&mdash;&mdash;北京专业安全种植牙中心</strong></h2>
<div style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px; line-height: 21px;">
<p>　　维尔口腔是北京较早开展种植牙医学项目的医疗机构之一，与欧洲、韩国等种植医学机构合作，引进了瑞士一代和第二代ITI种植系统，韩国奥齿泰种植系统、瑞士BIENAIR光纤种植机等国际上较为先进的种植技术和设备</p>
<h2 class="135brush" placeholder="请输入标题" style="margin: 10px 0px; padding: 5px 10px; font-size: 16px; font-weight: 500; border-left-width: 5px; border-left-style: solid; border-left-color: rgb(255, 129, 36); line-height: 32px; color: rgb(102, 102, 102);"><strong><span style="font-size: 14px;"><span style="color: rgb(227, 108, 9);">安全材质</span></span></strong></h2>
<div style="margin: 0px; padding: 0px;">
<p>　　具有高度生物兼容性，对口腔无害，并加速种植体与牙槽骨。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="margin: 10px 0px; padding: 5px 10px; border-left-width: 5px; border-left-style: solid; border-left-color: rgb(255, 129, 36); line-height: 32px;"><font color="#e36c09"><span style="font-size: 14px;">专业团队</span></font></h2>
<div style="margin: 0px; padding: 0px;">
<p>　　由院长刘志杰、董春强等经验丰富的种植学科医生，亲自手术，提高手术安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="margin: 10px 0px; padding: 5px 10px; font-size: 16px; font-weight: 500; border-left-width: 5px; border-left-style: solid; border-left-color: rgb(255, 129, 36); line-height: 32px; color: rgb(102, 102, 102);"><strong><span style="font-size: 14px;"><span style="color: rgb(227, 108, 9);">科学流程</span></span></strong></h2>
<div style="margin: 0px; padding: 0px;">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。<br />
&nbsp;</p>
<div>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; line-height: 28px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解种植牙，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
</div>
</div>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D4CB1950-16239_lit.jpg{/dede:field}
