{dede:field name='keywords'}费用{/dede:field}
{dede:field name='description'}维尔的医生指出：种植牙齿由种植体、牙冠和基台叁部分组成，价格在万元 颗左右。具体费用视患者选择的种植体种类、牙冠材料而定。 拜{/dede:field}
{dede:field name='title'}北京种植牙费用{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}　　维尔的医生指出：种植牙齿由种植体、牙冠和基台叁部分组成，价格在万元/颗左右。具体费用视患者选择的种植体种类、牙冠材料而定。
<p style="padding: 0px; margin: 0px; color: rgb(51, 51, 51); font-stretch: normal; font-size: 14px; line-height: 24px; font-family: 宋体;">&nbsp;</p>
<center style="color: rgb(51, 51, 51); padding: 0px; font-stretch: normal; font-size: 14px; line-height: 24px; font-family: 宋体; margin: 0px;">
	<table align="center" border="1" cellpadding="1" cellspacing="1" style="width: 650px; padding: 0px; margin: 0px;">
	<tbody style="padding: 0px; margin: 0px;">
		<tr style="padding: 0px; margin: 0px;">
		<td colspan="4" style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><strong style="padding: 0px; margin: 0px;">维尔种植牙价格表（一）</strong></td>
		</tr>
		<tr style="padding: 0px; margin: 0px;">
		<td colspan="2" style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><strong style="padding: 0px; margin: 0px;">种植系统</strong></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><strong style="padding: 0px; margin: 0px;">优势</strong></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><b style="padding: 0px; margin: 0px;">费用</b></td>
		</tr>
		<tr style="padding: 0px; margin: 0px;">
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><img alt="" src="/uploads/allimg/c180322/1521D3M1W310-1953V.png" style="border: 0px; padding: 0px; margin: 0px; width: 100px; height: 44px;" /></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">瑞典Nobel种植牙系统<br style="padding: 0px; margin: 0px;" />
		<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">[</a><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(0, 0, 205); padding: 0px; margin: 0px;">技术详情</span></a><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">]</a></strong></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;">技术体系较成熟、研发较完善的种植系统。</td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">参考价格</strong></span></a></td>
		</tr>
		<tr style="padding: 0px; margin: 0px;">
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><img alt="" src="/uploads/allimg/c180322/1521D3M320220-20b34.png" style="border: 0px; padding: 0px; margin: 0px; width: 100px; height: 47px;" /></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">德国Camlog种植系统</strong><br style="padding: 0px; margin: 0px;" />
		<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong style="padding: 0px; margin: 0px;">[</strong></a><strong style="padding: 0px; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(0, 0, 205); padding: 0px; margin: 0px;">技术详情</span></a></strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong style="padding: 0px; margin: 0px;">]</strong></a></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;">微痛微创技术，适应性更宽。</td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">参考价格</strong></span></a></td>
		</tr>
		<tr style="padding: 0px; margin: 0px;">
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><img alt="" src="/uploads/allimg/c180322/1521D3M360530-21XQ.png" style="border: 0px; padding: 0px; margin: 0px; height: 48px; width: 100px;" /></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">瑞士ITI种植系统</strong><br style="padding: 0px; margin: 0px;" />
		<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong style="padding: 0px; margin: 0px;">[</strong></a><strong style="padding: 0px; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(0, 0, 205); padding: 0px; margin: 0px;">技术详情</span></a></strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong style="padding: 0px; margin: 0px;">]</strong></a></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;">较稳定的种植系统。</td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">参考价格</strong></span></a></td>
		</tr>
		<tr style="padding: 0px; margin: 0px;">
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><img alt="" src="/uploads/allimg/c180322/1521D3M40E50-224426.png" style="border: 0px; padding: 0px; margin: 0px; width: 100px; height: 47px;" /></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">德国费亚丹Ankylos种植牙系统</strong><br style="padding: 0px; margin: 0px;" />
		<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong style="padding: 0px; margin: 0px;">[</strong></a><strong style="padding: 0px; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(0, 0, 205); padding: 0px; margin: 0px;">技术详情</span></a></strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong style="padding: 0px; margin: 0px;">]</strong></a></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;">安全、适应度高、安全性已获欧美国家齿科<br style="padding: 0px; margin: 0px;" />
		协会的认可。</td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">参考价格</strong></span></a></td>
		</tr>
		<tr style="padding: 0px; margin: 0px;">
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><img alt="" src="/uploads/allimg/c180322/1521D3M449110-231Z0.png" style="border: 0px; padding: 0px; margin: 0px; width: 100px; height: 47px;" /></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">韩国Dentis种植系统</strong><br style="padding: 0px; margin: 0px;" />
		<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong style="padding: 0px; margin: 0px;">[</strong></a><strong style="padding: 0px; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(0, 0, 205); padding: 0px; margin: 0px;">技术详情</span></a></strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong style="padding: 0px; margin: 0px;">]</strong></a></td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; margin: 0px;">实惠耐用，是较适合亚洲人的种植体。</td>
		<td style="font-size: 12px; font-family: 微软雅黑, 宋体; color: rgb(70, 70, 70); padding: 0px; text-align: center; margin: 0px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0); padding: 0px; margin: 0px;"><strong style="padding: 0px; margin: 0px;">参考价格</strong></span></a><br />
		&nbsp;</td>
		</tr>
	</tbody>
	</table>
</center>
<br />
　　种植体是种植牙关键、技术含量很高的部分，只有选择经过长期临床验证的成熟种植系统，由具有丰富经验的专业种植医生植入到牙槽骨内正确合适的位置，才能保证人工牙根能长期稳定的承受咬合力量、支持和固定种植牙。&gt;&gt;哪种种植体较好?哪种种植体较适合我?结合症状咨询医生
<p>　　很多人都觉得种植牙贵，的确乍一看是不便宜。但我们按1万元来计算，1颗种植牙可使用40年(甚至更久) 一年365天，40年约等于14600天。10000元&divide;14600天=0.68元/天，也就是说每天只需0.68元，我们就能告别牙齿缺失，过上吃嘛嘛香的幸福生活。</p>
<div>
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-family: 微软雅黑; max-width: 100%; min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify; line-height: 28px; font-weight: 500; color: rgb(0, 112, 192);"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">一</span><strong>种植牙技术的突破&mdash;&mdash;全口无牙颌种植技术</strong></h2>
</div>
<p>　　全口无牙颌种植技术是生物种植牙史上首次利用四颗种植体或六颗种植体即刻种出整排牙。由于所需种植体的减少，种牙无需植骨，使种植手术操作更简单、微损伤，所需时间更短，成功解决无牙颌种植难题。这项技术避免了痛苦、漫长、昂贵的牙骨移植，非常适合牙骨萎缩的无牙患者。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;[点击] 医生为你详解该技术!</span></a></p>
<p>　　要种牙，先检查!检查牙齿问题症结所在，医生给您估价!维尔开展网络预约或电话预约免口腔检查费活动正在进行中，<span style="color:#ff0000;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">【立即预约】 【在线咨询】</a></span></p>
<div>
<h2 style="line-height: 28px; margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">2</span><strong>维尔口腔种植牙&mdash;&mdash;院长推荐</strong></h2>
<div style="font-size: 14px; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; line-height: 21px; text-align: center;"><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn&amp;r=&amp;rf1=http%3A//beij.wekq&amp;rf2=.net/ycqsf/&amp;p=http%3A//beij.wekq.net/2017/ycqsf_0422/223.html&amp;cid=1492216894929970060446&amp;sid=1494031675098436880077" style="text-decoration: none;" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D3L94LZ-1Ic9.jpg" style="width: 450px; height: 280px;" /></a></div>
<div style="color: rgb(102, 102, 102); font-family: Simsun; font-size: 14px; line-height: 28px;">&nbsp;</div>
<div style="color: rgb(102, 102, 102); font-family: Simsun; font-size: 14px; line-height: 28px;">
<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; font-weight: 500; font-family: 微软雅黑; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; line-height: 20px; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">3</span><strong>维尔口腔刘院长&mdash;&mdash;全口一日得种植牙技术真实案例回放</strong></h2>
<div style="text-align: center;">&nbsp;</div>
</div>
<div style="text-align: center;"><embed allowfullscreen="true" allowscriptaccess="always" bgcolor="#000000" flashvars="autoplay=0&amp;skin=http://beij.wekq.net/statics/js/ckeditor/plugins/flashplayer/player/skin.swf&amp;video=http://video.wekq.net/video/al/2.flv&amp;thumbnail=http://beij.wekq.net/skin/img/news/1.jpg" height="268px" id="f4Player" src="/uploads/allimg/c180322/1521D3L24Z20-VB0.swf" type="application/x-shockwave-flash" width="480px"></embed><br />
<img alt="" src="/uploads/allimg/c180322/1521D3M4WF-24N17.jpg" style="width: 480px; height: 315px;" /><br />
<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn&amp;r=&amp;rf1=http%3A//beij.wekq&amp;rf2=.net/ycqsf/&amp;p=http%3A//beij.wekq.net/2017/ycqsf_0422/223.html&amp;cid=1492216894929970060446&amp;sid=1494031675098436880077" style="font-family: Simsun; font-size: 14px; line-height: 28px; text-decoration: none;" target="_blank"><span style="color: rgb(0, 0, 0);">刘先生 &nbsp; &nbsp; 年龄：53 &nbsp; &nbsp;牙齿全口缺失</span></a></div>
<div style="text-align: center;"><u style="color: rgb(102, 102, 102); font-family: Simsun; font-size: 14px; line-height: 28px; text-align: center;"><strong style="text-decoration: none;"><span style="color: rgb(0, 128, 128);"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn&amp;r=&amp;rf1=http%3A//beij.wekq&amp;rf2=.net/ycqsf/&amp;p=http%3A//beij.wekq.net/2017/ycqsf_0422/223.html&amp;cid=1492216894929970060446&amp;sid=1494031675098436880077" style="text-decoration: none;" target="_blank">治疗方案&ldquo;一日得&rdquo;全口种植技术点击咨询详情</a></span></strong></u></div>
</div>
<p>　　温馨提示：种牙是一项技术含量非常高的手术，对医院的设备技术医生都有着很高的要求，所以不能一味的相信低价种植，一旦出现差错，二次种植不仅会浪费更多的钱，还会更你带来更大的痛苦。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;维尔现开展种植牙活动，网络预约到诊可享巨幅优惠!你还在等什么?马上预约</span></a></p>{/dede:field}
{dede:field name='pubdate'}1521683775{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D3M1W310-1953V_lit.png{/dede:field}
