{dede:field name='keywords'}牙龈,怎么办,宝宝{/dede:field}
{dede:field name='description'}宝宝牙龈发炎了该怎么办?在炎热的夏季里，很多人都容易口腔发炎，维尔口腔医师介绍说，尤其是一些宝宝，抵抗力明显减弱，这个时候家长{/dede:field}
{dede:field name='title'}宝宝牙龈出血怎么办{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size: 16px;">&nbsp; &nbsp; 宝宝牙龈发炎了该怎么办?在炎热的夏季里，很多人都容易口腔发炎，维尔口腔医师介绍说，尤其是一些宝宝，抵抗力明显减弱，这个时候家长就要注意宝宝的口腔保健了，尤其是对以一些牙龈发炎的症状，那么，<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>宝宝牙龈发炎怎么办?</strong></span></a></span><br />
<br />
<div style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="牙龈炎" src="http://beij.wekq.net/uploadfile/2017/0709/20170709041948955.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 216px;" /></a></span></div>
<div>&nbsp;</div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">宝宝牙龈发炎了怎么办？</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 天气很干燥，人体的唾液分泌减少，呼吸道干燥，血管的脆性增强，本来就很容易感染细菌。如果再吃补品或者辛辣刺激的食物，就会加速血液的运行，中医称之为&ldquo;血热妄行&rdquo;，将病菌带到全身，引发牙肉肿痛、流鼻血、干咳、喉咙发炎等症状。</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 宝宝牙龈发炎了该怎么办？医师指出，儿童牙龈炎治疗儿童牙龈炎是儿童牙病中较为常见的病症之一，根据我国流行病学的调查结果显示，儿童牙龈炎的患病率较高，达55%，12岁年龄组的调查报告显示，牙结石的检出率为50%以上，通过调查提示我们，儿童牙龈应引起口腔医务工作者足够的重视，应认真做好口腔卫生宣教工作。　　</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 由于儿童时期牙龈上皮薄，角化差，受细菌感染或外伤刺激及口腔卫生状况较差时，很易引起牙龈炎症，临床表现为牙龈红肿，易出血，牙龈缘处有大量的软垢沉积等。龈缘部的软垢堆积是造成牙龈炎的重要因素。</span></p>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">儿童牙龈炎治疗主要有以下几种：</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 儿童牙龈炎治疗儿童时期牙龈炎与患儿恒牙牙齿萌出，牙列拥挤，不良习惯及长期服用某种药物导致牙龈的炎症，增生有关，儿童牙龈炎治疗主要有以下几种：　　</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 宝宝牙龈发炎了该怎么办？萌出性牙龈炎，恒牙在萌出时出现牙龈肿胀，出血，随着牙齿的全部萌出，症状即可消失；不洁性龈炎，患儿不能掌握正确的刷牙方法，口腔卫生较差，龈缘及龈乳头红肿；严重时可破坏牙槽骨；　&nbsp;</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 牙列拥挤性龈炎,牙齿萌出拥挤，排列不齐，口腔自洁作用差，食物残渣滞留，刺激牙龈组织，造成牙龈的炎症增生和肥厚等，无论何处原因造成的牙龈炎均与口腔卫生不良有关，预防儿童时期牙龈炎，家长应教育指导儿童每天坚持认真正确的刷牙，尤其睡前刷牙较重要。</span></p>
<p style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0709/20170709041949619.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size: 16px;">&nbsp; &nbsp; 宝宝牙龈发炎了该怎么办?在炎热的夏季里，很多人都容易口腔发炎，维尔口腔医师介绍说，尤其是一些宝宝，抵抗力明显减弱，这个时候家长就要注意宝宝的口腔保健了，尤其是对以一些牙龈发炎的症状，那么，<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>宝宝牙龈发炎怎么办?</strong></span></a></span><br />
<br />
<div style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="牙龈炎" src="/uploads/allimg/c180322/1521DYQ64020-19458.jpg" style="border-width: 0px; border-style: solid; width: 300px; height: 216px;" /></a></span></div>
<div>&nbsp;</div>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">宝宝牙龈发炎了怎么办？</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 天气很干燥，人体的唾液分泌减少，呼吸道干燥，血管的脆性增强，本来就很容易感染细菌。如果再吃补品或者辛辣刺激的食物，就会加速血液的运行，中医称之为&ldquo;血热妄行&rdquo;，将病菌带到全身，引发牙肉肿痛、流鼻血、干咳、喉咙发炎等症状。</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 宝宝牙龈发炎了该怎么办？医师指出，儿童牙龈炎治疗儿童牙龈炎是儿童牙病中较为常见的病症之一，根据我国流行病学的调查结果显示，儿童牙龈炎的患病率较高，达55%，12岁年龄组的调查报告显示，牙结石的检出率为50%以上，通过调查提示我们，儿童牙龈应引起口腔医务工作者足够的重视，应认真做好口腔卫生宣教工作。　　</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 由于儿童时期牙龈上皮薄，角化差，受细菌感染或外伤刺激及口腔卫生状况较差时，很易引起牙龈炎症，临床表现为牙龈红肿，易出血，牙龈缘处有大量的软垢沉积等。龈缘部的软垢堆积是造成牙龈炎的重要因素。</span></p>
<div>
<section class="135editor" data-id="33" style="margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: 微软雅黑; font-size: 14px;">
	<h2 style="margin: 8px 0px 0px; padding: 0px; font-size: 16px; max-width: 100%; color: rgb(0, 112, 192); min-height: 32px; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: rgb(0, 112, 192); text-align: justify;"><span class="autonum" data-original-title="" placeholder="1" style="font-weight: 500; line-height: 20px; border-radius: 80% 100% 90% 20%; color: rgb(255, 255, 255); display: block; float: left; margin: 0px 8px 0px 0px; max-width: 100%; padding: 4px 10px; word-wrap: break-word !important; background-color: rgb(0, 112, 192);" title="">☆</span><span style="font-size: 18px;"><span style="line-height: 22.3906px;">儿童牙龈炎治疗主要有以下几种：</span></span></h2>
</section>
</div>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 儿童牙龈炎治疗儿童时期牙龈炎与患儿恒牙牙齿萌出，牙列拥挤，不良习惯及长期服用某种药物导致牙龈的炎症，增生有关，儿童牙龈炎治疗主要有以下几种：　　</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 宝宝牙龈发炎了该怎么办？萌出性牙龈炎，恒牙在萌出时出现牙龈肿胀，出血，随着牙齿的全部萌出，症状即可消失；不洁性龈炎，患儿不能掌握正确的刷牙方法，口腔卫生较差，龈缘及龈乳头红肿；严重时可破坏牙槽骨；　&nbsp;</span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 牙列拥挤性龈炎,牙齿萌出拥挤，排列不齐，口腔自洁作用差，食物残渣滞留，刺激牙龈组织，造成牙龈的炎症增生和肥厚等，无论何处原因造成的牙龈炎均与口腔卫生不良有关，预防儿童时期牙龈炎，家长应教育指导儿童每天坚持认真正确的刷牙，尤其睡前刷牙较重要。</span></p>
<p style="text-align: center;"><span style="font-size: 16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DYR143Z-240P.jpg" style="width: 450px; height: 280px;" /></a></span></p>
<p><span style="font-size: 16px;">&nbsp; &nbsp; 维尔口腔医院成立于1998年，十九年专注口腔医疗，在全国拥有百家口腔医疗连锁机构，其中一线医护人员逾1000多人。已被业界公认为具知名度的口腔品牌连锁机构之一。详情请咨询<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color: rgb(255, 0, 0);"><strong>400-6655-111</strong></span></a>。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DYQ64020-19458_lit.jpg{/dede:field}
