
    {dede:addurls}http://beij.weierkq.com/ycjzffj/5.html
http://beij.weierkq.com/ycjzffj/4.html
http://beij.weierkq.com/ycjzffj/3.html
http://beij.weierkq.com/ycjzffj/2.html
http://beij.weierkq.com/ycjzffj/{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="left_center auto">{/dede:areastart}
    {dede:areaend}<div id="pages" class="text-c auto">{/dede:areaend}
