<?php
$z[0]=Array("addurls","http://beij.weierkq.com/baya5/4.html\r\nhttp://beij.weierkq.com/baya5/3.html\r\nhttp://beij.weierkq.com/baya5/2.html\r\nhttp://beij.weierkq.com/baya5/",6,179);
$z[1]=Array("batchrule","",185,218);
$z[2]=Array("regxrule","",224,255);
$z[3]=Array("areastart","<div class=\"left_center auto\">",261,324);
$z[4]=Array("areaend","<div id=\"pages\" class=\"text-c auto\">",330,395);

?>