{dede:field name='keywords'}为什么要进行根管治疗{/dede:field}
{dede:field name='description'}根管治疗是牙髓病和根尖周病常用的有效治疗方法，它的目的是保留患牙或牙根。根管治疗术是通过机械和化学方法去除根管内的炎症牙髓和坏{/dede:field}
{dede:field name='title'}为什么要进行根管治疗{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">　　根管治疗是牙髓病和根尖周病常用的有效治疗方法，它的目的是保留患牙或牙根。根管治疗术是通过机械和化学方法去除根管内的炎症牙髓和坏死物质，并进行适当消毒、充填根管，以去除根管内容物对根尖周围组织的不良刺激，防止发生根尖周病变。</span>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="http://beij.wekq.net/uploadfile/2017/1110/20171110035335468.jpg" style="width: 500px; height: 196px;" /></span></a></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　&gt;&gt;&gt;你的牙齿为什么要根管治疗?&gt;&gt;&gt;</span></span></a></p>
<p><strong><span style="font-size:16px;">　　为什么要去维尔进行根管治疗</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔采用的根管治疗法的成功率在高，是目前保存患牙较好的治疗方法。一般来讲，对于那些牙髓炎，牙髓坏死，各种类型的根尖周炎都适于作显微根管治疗。尤其对于残冠残根牙修复科需要进行桩冠修复的，根管治疗术是一个可以选择的治疗方法。根管治疗的优点具体如下：</span></p>
<p><span style="font-size:16px;">　　优点1：对于患者有严重的全身性疾病者<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">(例如：先天性心脏病、糖尿病、高血压、梅毒等)</span></a>选用根管治疗可减少危险性。</span></p>
<p><span style="font-size:16px;">　　优点2：节省费用。由于根管治疗可以保持天然牙处于完整及生物学的适当状态，而不用将患牙拔除，减少假牙制作的经费。</span></p>
<p><span style="font-size:16px;">　　优点3：根管治疗可以保持天然牙齿排列的完整性，预防邻接牙齿的移位、蛀牙、牙周病的发生，可防止拔牙后的支持骨质丧失过多。</span></p>
<p><span style="font-size:16px;">　　优点4：避免因牙齿早期拔除所造成的不正咬合，进而免除矫正治疗的麻烦。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/1110/20171110035425301.jpg" style="width: 450px; height: 280px;" /></a></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;在线咨询，根管治疗需要注意哪些?&gt;&gt;&gt;</span></a></span></p>
<p><strong><span style="font-size:16px;">　　维尔连锁口腔，医院正规更放心</span></strong></p>
<p><strong><span style="font-size:16px;">　　一、标准消毒：治疗安全更放心!</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔采用&ldquo;全生态、人性化&rdquo;的环境设计，并率先实现全透明消毒中心，保障消毒更规范，更透明;&ldquo;一人一诊室&rdquo;诊疗环境，更多尊重，更多舒适。</span></p>
<p><strong><span style="font-size:16px;">　　二、贴心服务：给您不一样的体验</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔采用一患一医一诊疗的服务模式，保证了顾客的隐私。始终倡导文明的医德医风，构建和谐稳定的医患关系，为顾客提供卓越的星级服务。气派的装修，典雅高贵的人文环境，让患者享受到先进的口腔医疗服务同时，给您一个不一样的舒适体验。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">【在线咨询】【点击预约】</span></a></span></p>
<p><strong><span style="font-size:16px;">　　三、透明定价：公开透明收费</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔实行&quot;透明定价制&quot;，严格按照卫生部标准和物价局要求，每种药品、每项检查、每项服务、每一笔门诊、住院费用都完全公开，保证每位患者都能真正地明白就医，清楚付费，是您较佳的选择。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0212/20180212101553184.jpg" style="width: 550px; height: 130px;" /></a></span></p>
<p><span style="font-size:16px;">　　维尔温馨提示：提前预约挂号，到院无需挂号(免挂号费)即可实现轻松无障碍就诊!这里不仅给您提供温馨舒适的治疗环境，而且给您免费建立的档案。给牙齿不一样的呵护。医院特别开设在线咨询服务，在线为您解答疾病相关的问题，根据病情给予专业的个性化的指导意见，提供专业治疗方案，如需帮助，请点击咨询或拨打<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">咨询电话：400-6655-111。</span></a></span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">　　根管治疗是牙髓病和根尖周病常用的有效治疗方法，它的目的是保留患牙或牙根。根管治疗术是通过机械和化学方法去除根管内的炎症牙髓和坏死物质，并进行适当消毒、充填根管，以去除根管内容物对根尖周围组织的不良刺激，防止发生根尖周病变。</span>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploads/allimg/c180322/1521DVC552F-13041.jpg" style="width: 500px; height: 196px;" /></span></a></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　&gt;&gt;&gt;你的牙齿为什么要根管治疗?&gt;&gt;&gt;</span></span></a></p>
<p><strong><span style="font-size:16px;">　　为什么要去维尔进行根管治疗</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔采用的根管治疗法的成功率在高，是目前保存患牙较好的治疗方法。一般来讲，对于那些牙髓炎，牙髓坏死，各种类型的根尖周炎都适于作显微根管治疗。尤其对于残冠残根牙修复科需要进行桩冠修复的，根管治疗术是一个可以选择的治疗方法。根管治疗的优点具体如下：</span></p>
<p><span style="font-size:16px;">　　优点1：对于患者有严重的全身性疾病者<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">(例如：先天性心脏病、糖尿病、高血压、梅毒等)</span></a>选用根管治疗可减少危险性。</span></p>
<p><span style="font-size:16px;">　　优点2：节省费用。由于根管治疗可以保持天然牙处于完整及生物学的适当状态，而不用将患牙拔除，减少假牙制作的经费。</span></p>
<p><span style="font-size:16px;">　　优点3：根管治疗可以保持天然牙齿排列的完整性，预防邻接牙齿的移位、蛀牙、牙周病的发生，可防止拔牙后的支持骨质丧失过多。</span></p>
<p><span style="font-size:16px;">　　优点4：避免因牙齿早期拔除所造成的不正咬合，进而免除矫正治疗的麻烦。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521DVE1310-3OJ.jpg" style="width: 450px; height: 280px;" /></a></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">&gt;&gt;&gt;在线咨询，根管治疗需要注意哪些?&gt;&gt;&gt;</span></a></span></p>
<p><strong><span style="font-size:16px;">　　维尔连锁口腔，医院正规更放心</span></strong></p>
<p><strong><span style="font-size:16px;">　　一、标准消毒：治疗安全更放心!</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔采用&ldquo;全生态、人性化&rdquo;的环境设计，并率先实现全透明消毒中心，保障消毒更规范，更透明;&ldquo;一人一诊室&rdquo;诊疗环境，更多尊重，更多舒适。</span></p>
<p><strong><span style="font-size:16px;">　　二、贴心服务：给您不一样的体验</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔采用一患一医一诊疗的服务模式，保证了顾客的隐私。始终倡导文明的医德医风，构建和谐稳定的医患关系，为顾客提供卓越的星级服务。气派的装修，典雅高贵的人文环境，让患者享受到先进的口腔医疗服务同时，给您一个不一样的舒适体验。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">【在线咨询】【点击预约】</span></a></span></p>
<p><strong><span style="font-size:16px;">　　三、透明定价：公开透明收费</span></strong></p>
<p><span style="font-size:16px;">　　维尔口腔实行&quot;透明定价制&quot;，严格按照卫生部标准和物价局要求，每种药品、每项检查、每项服务、每一笔门诊、住院费用都完全公开，保证每位患者都能真正地明白就医，清楚付费，是您较佳的选择。</span></p>
<p style="text-align: center;"><span style="font-size:16px;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><img alt="" src="/uploadfile/2018/0212/20180212101553184.jpg" style="width: 550px; height: 130px;" /></a></span></p>
<p><span style="font-size:16px;">　　维尔温馨提示：提前预约挂号，到院无需挂号(免挂号费)即可实现轻松无障碍就诊!这里不仅给您提供温馨舒适的治疗环境，而且给您免费建立的档案。给牙齿不一样的呵护。医院特别开设在线咨询服务，在线为您解答疾病相关的问题，根据病情给予专业的个性化的指导意见，提供专业治疗方案，如需帮助，请点击咨询或拨打<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&amp;lng=cn" target="_blank"><span style="color:#ff0000;">咨询电话：400-6655-111。</span></a></span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DVC552F-13041_lit.jpg{/dede:field}
