{dede:field name='keywords'}烤瓷牙,寿命{/dede:field}
{dede:field name='description'}烤瓷牙因为其高品质和高度仿真性受到广大爱牙人士的喜欢，是人们做牙齿修复的不错之选，因此有很多人对此表示很感兴趣。烤瓷牙的寿命到{/dede:field}
{dede:field name='title'}烤瓷牙的寿命多长{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<p>　　烤瓷牙因为其高品质和高度仿真性受到广大爱牙人士的喜欢，是人们做牙齿修复的不错之选，因此有很多人对此表示很感兴趣。烤瓷牙的寿命到底有长?这个问题也是我们广大朋友们都比较关心的，<strong>北京维尔口腔医生在线为您解答烤瓷牙的寿命。</strong></p>
<p style="TEXT-ALIGN: center"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427061523381.jpg" style="width: 300px; height: 185px;" /></a></p>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">1</span><strong>烤瓷牙寿命因素主要有以下几点，</strong></h2>
<p><span style="LINE-HEIGHT: 21px; FONT-FAMILY: 微软雅黑; COLOR: rgb(0,0,0); FONT-SIZE: 14px">　　</span>众所周知，烤瓷牙是我们常见的美学修复方法，而影响到烤瓷牙寿命的因素您注意到了吗？<strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="COLOR: #008080">烤瓷牙的寿命点击咨询&lt;&lt;&lt;</span></a></strong></p>
<p>　　1、烤瓷牙的材料。好的材料有好的物理化学性能和稳定性，我们称之为生物相容性。生物相容性好的金属可以和口腔软硬组织&ldquo;和平相处&rdquo;，生物相容性差的金属会对周围组织产生不良刺激，出现过敏、腐蚀、金属离子渗出等现象，从而产生牙龈炎、牙周炎、龈缘黑线、口腔异味等。</p>
<p>　　2、医生的技术。很多人经常忽视这一点，把注意力医院，价格和使用材料上，对医师的技术考虑较少。然而，技术高超的医生才能制作出高品质的烤瓷牙，没有好技术，再好的材料也出不了好效果。这好比同样的原料，好厨师烧的菜肴很美味，技巧拙劣的厨子烧的菜就难以下咽。</p>
<p>　　3、使用和维护。做完烤瓷牙一定要对烤瓷牙进行护理，避免吃坚硬的食物，这样烤瓷牙才能更好为我们服务。</p>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">2</span><strong>维尔口腔烤瓷修复&mdash;&mdash;任蕾美学修复主任推荐</strong></h2>
<div style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; LINE-HEIGHT: 21px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; COLOR: rgb(0,0,0); FONT-SIZE: 14px; PADDING-TOP: 0px"><br />
<img alt="" src="http://beij.wekq.net/uploadfile/2017/0427/20170427064926586.jpg" style="width: 450px; height: 280px;" /></div>
<div>&nbsp;</div>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">3</span><strong>维尔口腔</strong><strong>任蕾美学修复主任</strong><strong>&mdash;&mdash;烤瓷牙修复真实案例</strong></h2>
<br />
<div style="TEXT-ALIGN: center"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="http://beij.wekq.net/uploadfile/2017/0428/20170428060530374.jpg" style="width: 300px; height: 195px;" /></a><br />
<span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px"><span style="COLOR: #000000"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">王女士 年龄：33 门牙烤瓷牙</a></span></span><br />
<u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="COLOR: #008080"><span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px">烤瓷牙的寿命多长？击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">4</span><strong>维尔口腔&mdash;&mdash;北京专业美学修复中心</strong></h2>
<div style="PADDING-BOTTOM: 0px; LINE-HEIGHT: 21px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; COLOR: rgb(0,0,0); FONT-SIZE: 14px; PADDING-TOP: 0px">
<p>　　维尔口腔是北京较早开展美学修复项目的医疗机构之一。引进的仿生美容冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。由维尔美齿导师刘志杰院长制定出的3-3-4-4美齿黄金法则， 被众多美齿机构广泛借鉴及沿用。</p>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">安全材质</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　具有高度生物兼容性，对口腔无害，并加速牙冠与口内组织的紧密结合性。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; PADDING-TOP: 5px"><font color="#e36c09"><span style="FONT-SIZE: 14px">专业团队</span></font></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　由院长刘志杰、美学修复主任任蕾等经验丰富的美学修复医生，亲自临床，提高手术安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">科学流程</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。</p>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解烤瓷牙，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
</div>
</div>
<br />{/dede:field}
{dede:field name='body'}<p>　　烤瓷牙因为其高品质和高度仿真性受到广大爱牙人士的喜欢，是人们做牙齿修复的不错之选，因此有很多人对此表示很感兴趣。烤瓷牙的寿命到底有长?这个问题也是我们广大朋友们都比较关心的，<strong>北京维尔口腔医生在线为您解答烤瓷牙的寿命。</strong></p>
<p style="TEXT-ALIGN: center"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D6232000Z-243b.jpg" style="width: 300px; height: 185px;" /></a></p>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">1</span><strong>烤瓷牙寿命因素主要有以下几点，</strong></h2>
<p><span style="LINE-HEIGHT: 21px; FONT-FAMILY: 微软雅黑; COLOR: rgb(0,0,0); FONT-SIZE: 14px">　　</span>众所周知，烤瓷牙是我们常见的美学修复方法，而影响到烤瓷牙寿命的因素您注意到了吗？<strong><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="COLOR: #008080">烤瓷牙的寿命点击咨询&lt;&lt;&lt;</span></a></strong></p>
<p>　　1、烤瓷牙的材料。好的材料有好的物理化学性能和稳定性，我们称之为生物相容性。生物相容性好的金属可以和口腔软硬组织&ldquo;和平相处&rdquo;，生物相容性差的金属会对周围组织产生不良刺激，出现过敏、腐蚀、金属离子渗出等现象，从而产生牙龈炎、牙周炎、龈缘黑线、口腔异味等。</p>
<p>　　2、医生的技术。很多人经常忽视这一点，把注意力医院，价格和使用材料上，对医师的技术考虑较少。然而，技术高超的医生才能制作出高品质的烤瓷牙，没有好技术，再好的材料也出不了好效果。这好比同样的原料，好厨师烧的菜肴很美味，技巧拙劣的厨子烧的菜就难以下咽。</p>
<p>　　3、使用和维护。做完烤瓷牙一定要对烤瓷牙进行护理，避免吃坚硬的食物，这样烤瓷牙才能更好为我们服务。</p>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">2</span><strong>维尔口腔烤瓷修复&mdash;&mdash;任蕾美学修复主任推荐</strong></h2>
<div style="TEXT-ALIGN: center; PADDING-BOTTOM: 0px; LINE-HEIGHT: 21px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; COLOR: rgb(0,0,0); FONT-SIZE: 14px; PADDING-TOP: 0px"><br />
<img alt="" src="/uploads/allimg/c180322/1521D6232505P-3IX.jpg" style="width: 450px; height: 280px;" /></div>
<div>&nbsp;</div>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">3</span><strong>维尔口腔</strong><strong>任蕾美学修复主任</strong><strong>&mdash;&mdash;烤瓷牙修复真实案例</strong></h2>
<br />
<div style="TEXT-ALIGN: center"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><img alt="" src="/uploads/allimg/c180322/1521D6233041P-44T7.jpg" style="width: 300px; height: 195px;" /></a><br />
<span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px"><span style="COLOR: #000000"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank">王女士 年龄：33 门牙烤瓷牙</a></span></span><br />
<u><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><strong><span style="COLOR: #008080"><span style="LINE-HEIGHT: 28px; FONT-FAMILY: Simsun; FONT-SIZE: 14px">烤瓷牙的寿命多长？击咨询详情</span></span></strong></a></u></div>
</div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">4</span><strong>维尔口腔&mdash;&mdash;北京专业美学修复中心</strong></h2>
<div style="PADDING-BOTTOM: 0px; LINE-HEIGHT: 21px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; FONT-FAMILY: 微软雅黑; COLOR: rgb(0,0,0); FONT-SIZE: 14px; PADDING-TOP: 0px">
<p>　　维尔口腔是北京较早开展美学修复项目的医疗机构之一。引进的仿生美容冠技术在治疗和修复牙齿的同时，强调对牙齿的美容功能，能够满足顾客对形体美观的需求。由维尔美齿导师刘志杰院长制定出的3-3-4-4美齿黄金法则， 被众多美齿机构广泛借鉴及沿用。</p>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">安全材质</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　具有高度生物兼容性，对口腔无害，并加速牙冠与口内组织的紧密结合性。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; PADDING-TOP: 5px"><font color="#e36c09"><span style="FONT-SIZE: 14px">专业团队</span></font></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　由院长刘志杰、美学修复主任任蕾等经验丰富的美学修复医生，亲自临床，提高手术安全系数和成功率。</p>
</div>
<h2 class="135brush" placeholder="请输入标题" style="BORDER-LEFT: rgb(255,129,36) 5px solid; PADDING-BOTTOM: 5px; LINE-HEIGHT: 32px; MARGIN: 10px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; COLOR: rgb(102,102,102); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 5px"><strong><span style="FONT-SIZE: 14px"><span style="COLOR: rgb(227,108,9)">科学流程</span></span></strong></h2>
<div style="PADDING-BOTTOM: 0px; MARGIN: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px">
<p>　　科学筛查口腔疾病和身体疾病，全面分析口腔环境，诊治口腔疾病，术前、术中、术后全程专业指导。</p>
<div>
<h2 style="BORDER-BOTTOM: rgb(0,112,192) 2px solid; TEXT-ALIGN: justify; PADDING-BOTTOM: 0px; LINE-HEIGHT: 28px; MARGIN: 8px 0px 0px; MIN-HEIGHT: 32px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; MAX-WIDTH: 100%; COLOR: rgb(0,112,192); FONT-SIZE: 16px; FONT-WEIGHT: 500; PADDING-TOP: 0px"><span class="autonum" data-original-title="" placeholder="1" style="PADDING-BOTTOM: 4px; LINE-HEIGHT: 20px; BACKGROUND-COLOR: rgb(0,112,192); MARGIN: 0px 8px 0px 0px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; DISPLAY: block; MAX-WIDTH: 100%; WORD-WRAP: break-word !important; FLOAT: left; COLOR: rgb(255,255,255); PADDING-TOP: 4px; border-radius: 80% 100% 90% 20%" title="">5</span><strong>维尔口腔全国品牌连锁&mdash;&mdash;您身边的牙科医院</strong></h2>
</div>
<p>　　温馨提示：为了帮助广大患者朋友更好的了解烤瓷牙，根据病情提供专业的治疗方案，并为您的隐私保密，如需帮助，您可以点击在线咨询，<strong>或者拨打400-6655-111与我们交流。</strong></p>
</div>
</div>
<br />{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521D6232000Z-243b_lit.jpg{/dede:field}
