
    {dede:addurls}http://beij.weierkq.com/zzyjgb/2.html
http://beij.weierkq.com/zzyjgb/3.html
http://beij.weierkq.com/zzyjgb/4.html
http://beij.weierkq.com/zzyjgb/5.html
http://beij.weierkq.com/zzyjgb/6.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="left_center auto">{/dede:areastart}
    {dede:areaend}<div id="pages" class="text-c auto">{/dede:areaend}
