<?php
$z[0]=Array("addurls","http://beij.weierkq.com/zzyjgb/2.html\r\nhttp://beij.weierkq.com/zzyjgb/3.html\r\nhttp://beij.weierkq.com/zzyjgb/4.html\r\nhttp://beij.weierkq.com/zzyjgb/5.html\r\nhttp://beij.weierkq.com/zzyjgb/6.html",6,228);
$z[1]=Array("batchrule","",234,267);
$z[2]=Array("regxrule","",273,304);
$z[3]=Array("areastart","<div class=\"left_center auto\">",310,373);
$z[4]=Array("areaend","<div id=\"pages\" class=\"text-c auto\">",379,444);

?>