{dede:field name='keywords'}牙龈炎{/dede:field}
{dede:field name='description'}在这个充斥这压力和匆忙的环境下，很多人会因此不注意患上了牙周病，而牙龈炎正是牙周病里常见的一种病状，很多人自己得了牙龈炎却还是{/dede:field}
{dede:field name='title'}牙龈炎该如何治疗{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}<span style="font-size:16px;">　　在这个充斥这压力和匆忙的环境下，很多人会因此不注意患上了牙周病，而牙龈炎正是牙周病里常见的一种病状，很多人自己得了牙龈炎却还是全然不知道，那么究竟牙龈炎有什么样的具体症状呢，维尔口腔医生通过牙龈的几个方面来告诉大家一旦出现以下这些情况，就要警惕自己是否是得了牙龈炎：</span>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/1026/20171026055038453.jpg" style="width: 360px; height: 196px;" /></span></a></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　&gt;牙龈出血的症状&lt;</span></span></a></p>
<p><span style="font-size:16px;">　　1、牙龈颜色：正常牙龈呈粉红色，患龈缘炎时游离龈和龈乳头变为深红或暗红色，这是由于牙龈结缔组织内血管充血、增生所致。</span></p>
<p><span style="font-size:16px;">　　2、牙龈出血：健康的牙龈在刷牙或探测龈沟时均不引起出血。患牙龈炎时轻触即出血，探诊也出血。探诊后出血是诊断牙龈有无炎症的重要客观指标。常为牙龈炎患者的主要自觉症状，多在刷牙或咬硬物时发生，偶也可有自发性出血。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">【点击咨询】【在线预约】</span></a></span></p>
<p><span style="font-size:16px;">　　3、牙龈外形：正常牙龈应为菲薄而紧贴牙面，患牙龈炎时，由于组织水肿，使龈缘变厚，不再紧贴牙面，龈乳头变为圆钝肥大，与牙面不再紧贴。在以炎症和渗出为主要病变者，牙龈松软肥大，表面光亮，龈缘有时糜烂渗出;在以纤维增殖为主的病例，牙龈坚韧肥大，有时可呈结节状并盖过部分牙面。</span></p>
<p><span style="font-size:16px;">　　4、牙龈质地：由于结缔组织内炎症浸润及胶原纤维消失，使原来质地致密的牙龈变得松软脆弱，缺乏弹性。有些慢性炎症时牙龈表面上皮增生变厚，胶原纤维增生，使牙龈表面看来坚硬肥厚，但牙周袋内壁有炎症，探诊有出血。有些患者偶而感到牙龈局部痒、胀等不适，并有口臭等</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size: 16px;">&gt;&gt;有了牙龈炎应该怎么治疗呢?&lt;&lt;</span></span></a></p>
<p><span style="font-size:16px;">　　5、牙周袋深度：牙周组织健康时，牙周袋深度一般不超过2-3mm，当牙龈有炎性肿胀或增生时，龈沟可加深达3mm以上，形成假性牙周袋。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/1026/20171026055054956.jpg" style="width: 450px; height: 280px;" /></span></a></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　&gt;有问题?点击咨询在线专家解答&lt;</span></span></a></p>
<p><strong><span style="font-size:16px;">　　维尔口腔牙周病综合治疗能为您做到：</span></strong></p>
<p><span style="font-size:16px;">　　牙周综合治疗：采用显微根管治疗、药物治疗、微创无痛种植牙等技术，解除牙周病患以及修复缺失的牙齿。</span></p>
<p><span style="font-size:16px;">　　轻柔无痛：不需要切开牙龈组织进行开放刮治，采用超声波能量转换，轻松去除生物膜、细菌和牙石沉积物，无震荡或打击，无痛、舒适、轻柔。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&lt;&lt;&lt;想了解更多?点击拨打维尔热线：400-6655-111进行咨询</span></a></span></p>
<p><span style="font-size:16px;">　　不损伤口腔组织：通过空穴效应及微流效应，有效去除龈下菌斑及牙石，阻止牙龈退缩，改善龈下微环境，安全性高，疗效好。</span></p>
<p><span style="font-size:16px;">　　适用范围广：不仅仅适用于各种程度的牙周病患者，对于种植体周围炎症的患者也同样适用，不会对敏感种植体表面造成损害。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;点击查看维尔治疗牙周病方法及价格&lt;</span></a></span></p>
<p><span style="font-size:16px;">　　治牙美牙一举两得：不仅可清除牙周袋内腐败组织和产物，去除生物膜和龈下结石，去除毒素，同时还完成对牙齿的清洁和抛光。</span></p>
<p><span style="font-size:16px;">　　确保卫生：严格遵循一人&quot;一套盘、一手机、一手套、一器械、一空针、一椅套&quot;的&quot;六一&quot;消毒流程，杜绝细菌交叉感染。</span></p>
<p><span style="font-size:16px;">　　北京维尔口腔温馨提示：治疗不仅需要医生用丰富的经验和专业技巧来操作，同时还需要有先进的口腔设备进行配合，所以大家一定要选择正规的机构。如果你有还有很多疑问，欢迎点击在线咨询按钮或拨打我们的<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">服务热线400-6655-111</span></a>进行详细了解。</span></p>{/dede:field}
{dede:field name='body'}<span style="font-size:16px;">　　在这个充斥这压力和匆忙的环境下，很多人会因此不注意患上了牙周病，而牙龈炎正是牙周病里常见的一种病状，很多人自己得了牙龈炎却还是全然不知道，那么究竟牙龈炎有什么样的具体症状呢，维尔口腔医生通过牙龈的几个方面来告诉大家一旦出现以下这些情况，就要警惕自己是否是得了牙龈炎：</span>
<div style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/1026/20171026055038453.jpg" style="width: 360px; height: 196px;" /></span></a></div>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　&gt;牙龈出血的症状&lt;</span></span></a></p>
<p><span style="font-size:16px;">　　1、牙龈颜色：正常牙龈呈粉红色，患龈缘炎时游离龈和龈乳头变为深红或暗红色，这是由于牙龈结缔组织内血管充血、增生所致。</span></p>
<p><span style="font-size:16px;">　　2、牙龈出血：健康的牙龈在刷牙或探测龈沟时均不引起出血。患牙龈炎时轻触即出血，探诊也出血。探诊后出血是诊断牙龈有无炎症的重要客观指标。常为牙龈炎患者的主要自觉症状，多在刷牙或咬硬物时发生，偶也可有自发性出血。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">【点击咨询】【在线预约】</span></a></span></p>
<p><span style="font-size:16px;">　　3、牙龈外形：正常牙龈应为菲薄而紧贴牙面，患牙龈炎时，由于组织水肿，使龈缘变厚，不再紧贴牙面，龈乳头变为圆钝肥大，与牙面不再紧贴。在以炎症和渗出为主要病变者，牙龈松软肥大，表面光亮，龈缘有时糜烂渗出;在以纤维增殖为主的病例，牙龈坚韧肥大，有时可呈结节状并盖过部分牙面。</span></p>
<p><span style="font-size:16px;">　　4、牙龈质地：由于结缔组织内炎症浸润及胶原纤维消失，使原来质地致密的牙龈变得松软脆弱，缺乏弹性。有些慢性炎症时牙龈表面上皮增生变厚，胶原纤维增生，使牙龈表面看来坚硬肥厚，但牙周袋内壁有炎症，探诊有出血。有些患者偶而感到牙龈局部痒、胀等不适，并有口臭等</span><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size: 16px;">&gt;&gt;有了牙龈炎应该怎么治疗呢?&lt;&lt;</span></span></a></p>
<p><span style="font-size:16px;">　　5、牙周袋深度：牙周组织健康时，牙周袋深度一般不超过2-3mm，当牙龈有炎性肿胀或增生时，龈沟可加深达3mm以上，形成假性牙周袋。</span></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="font-size:16px;"><img alt="" src="/uploadfile/2017/1026/20171026055054956.jpg" style="width: 450px; height: 280px;" /></span></a></p>
<p style="text-align: center;"><a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;"><span style="font-size:16px;">　　&gt;有问题?点击咨询在线专家解答&lt;</span></span></a></p>
<p><strong><span style="font-size:16px;">　　维尔口腔牙周病综合治疗能为您做到：</span></strong></p>
<p><span style="font-size:16px;">　　牙周综合治疗：采用显微根管治疗、药物治疗、微创无痛种植牙等技术，解除牙周病患以及修复缺失的牙齿。</span></p>
<p><span style="font-size:16px;">　　轻柔无痛：不需要切开牙龈组织进行开放刮治，采用超声波能量转换，轻松去除生物膜、细菌和牙石沉积物，无震荡或打击，无痛、舒适、轻柔。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&lt;&lt;&lt;想了解更多?点击拨打维尔热线：400-6655-111进行咨询</span></a></span></p>
<p><span style="font-size:16px;">　　不损伤口腔组织：通过空穴效应及微流效应，有效去除龈下菌斑及牙石，阻止牙龈退缩，改善龈下微环境，安全性高，疗效好。</span></p>
<p><span style="font-size:16px;">　　适用范围广：不仅仅适用于各种程度的牙周病患者，对于种植体周围炎症的患者也同样适用，不会对敏感种植体表面造成损害。<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">&gt;点击查看维尔治疗牙周病方法及价格&lt;</span></a></span></p>
<p><span style="font-size:16px;">　　治牙美牙一举两得：不仅可清除牙周袋内腐败组织和产物，去除生物膜和龈下结石，去除毒素，同时还完成对牙齿的清洁和抛光。</span></p>
<p><span style="font-size:16px;">　　确保卫生：严格遵循一人&quot;一套盘、一手机、一手套、一器械、一空针、一椅套&quot;的&quot;六一&quot;消毒流程，杜绝细菌交叉感染。</span></p>
<p><span style="font-size:16px;">　　北京维尔口腔温馨提示：治疗不仅需要医生用丰富的经验和专业技巧来操作，同时还需要有先进的口腔设备进行配合，所以大家一定要选择正规的机构。如果你有还有很多疑问，欢迎点击在线咨询按钮或拨打我们的<a href="http://swt.yakewang.cn/LR/Chatpre.aspx?id=MOP64215664&lng=cn" target="_blank"><span style="color:#ff0000;">服务热线400-6655-111</span></a>进行详细了解。</span></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180322/1521DY954M50-K120_lit.jpg{/dede:field}
