<?php
$z[0]=Array("addurls","http://beij.weierkq.com/crycjzk/9.html\r\nhttp://beij.weierkq.com/crycjzk/8.html\r\nhttp://beij.weierkq.com/crycjzk/7.html\r\nhttp://beij.weierkq.com/crycjzk/6.html\r\nhttp://beij.weierkq.com/crycjzk/5.html\r\nhttp://beij.weierkq.com/crycjzk/4.html\r\nhttp://beij.weierkq.com/crycjzk/3.html\r\nhttp://beij.weierkq.com/crycjzk/2.html\r\nhttp://beij.weierkq.com/crycjzk/",6,387);
$z[1]=Array("batchrule","",393,426);
$z[2]=Array("regxrule","",432,463);
$z[3]=Array("areastart","<div class=\"left_center auto\">",469,532);
$z[4]=Array("areaend","<div id=\"pages\" class=\"text-c auto\">",538,603);

?>