{dede:noteinfo notename="牙齿矫正价格" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area" musthas="ycjzjgi"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://beij.weierkq.com/ycjzjgi/5.html
http://beij.weierkq.com/ycjzjgi/4.html
http://beij.weierkq.com/ycjzjgi/3.html
http://beij.weierkq.com/ycjzjgi/2.html
http://beij.weierkq.com/ycjzjgi/{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="left_center auto">{/dede:areastart}
    {dede:areaend}<div id="pages" class="text-c auto">{/dede:areaend}
{/dede:listrule}
