<?php
$z[0]=Array("channel","\r\n                    <a href='[field:typelink/]'>[field:typename/]</a>\r\n                    ",708,850);
$z[0][4]['typeid']="7";
$z[0][4]['row']="20";
$z[1]=Array("type","<a href=\"[field:typeurl/]\" target=\"_blank\" title=\"[field:typename/]\">[field:typename/]</a>",1023,1147);
$z[1][4]['typeid']="5";
$z[2]=Array("type","<a href=\"[field:typeurl/]\" target=\"_blank\" title=\"[field:typename/]\">[field:typename/]</a>",1170,1294);
$z[2][4]['typeid']="3";
$z[3]=Array("type","<a href=\"[field:typeurl/]\" target=\"_blank\" title=\"[field:typename/]\">[field:typename/]</a>",1317,1441);
$z[3][4]['typeid']="2";
$z[4]=Array("global","",1569,1595);
$z[4][4]['name']="cfg_webname";

?>