<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('408', '/uploads/allimg/150523/1-150523122349129.jpg');
$maNum = 1;
$myaddons[$maNum] = array('409', '/uploads/allimg/150523/1-15052315001U07.jpg');
$maNum = 2;
$myaddons[$maNum] = array('410', '/uploads/allimg/150523/1-150523151340516.jpg');
$maNum = 3;
$myaddons[$maNum] = array('411', '/uploads/allimg/150523/1-150523151Q1B6.jpg');
$maNum = 4;
