<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('268', '/uploads/150504/1-1505041A42C08.jpg');
$maNum = 1;
$myaddons[$maNum] = array('269', '/uploads/150504/1-1505041AAA92.jpg');
$maNum = 2;
$myaddons[$maNum] = array('270', '/uploads/150504/1-1505041AJ3395.png');
$maNum = 3;
$myaddons[$maNum] = array('271', '/uploads/150504/1-1505041AS3T2.png');
$maNum = 4;
$myaddons[$maNum] = array('272', '/uploads/150504/1-1505041F042R4.jpg');
$maNum = 5;
$myaddons[$maNum] = array('273', '/uploads/150504/150504/1-1505041F5563J.jpg');
$maNum = 6;
$myaddons[$maNum] = array('274', '/uploads/150504/1-1505041FINN.jpg');
$maNum = 7;
