<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('367', '/uploads/allimg/150520/1-15052011592M34.jpg');
$maNum = 1;
$myaddons[$maNum] = array('368', '/uploads/allimg/150520/1-150520122152327.jpg');
$maNum = 2;
$myaddons[$maNum] = array('369', '/uploads/allimg/150520/1-150520122219349.jpg');
$maNum = 3;
$myaddons[$maNum] = array('373', '/uploads/allimg/150520/1-1505201F959121.jpg');
$maNum = 4;
$myaddons[$maNum] = array('374', '/uploads/allimg/150520/1-1505201J232450.jpg');
$maNum = 5;
$myaddons[$maNum] = array('375', '/uploads/allimg/150520/1-1505201JTC62.jpg');
$maNum = 6;
